COURSES=[
dict(id='nail-technician',summary='Provide safe nail services: nail anatomy, hygiene, manicure and pedicure, nail art, gel and acrylic systems, product safety, problem solving, pricing and client care.',icon='Spark',tool='notebook',tools=['notebook','board','budget'],
nodes=['Consult','Prepare','Apply','Care'],modules=['Nail science & hygiene','Manicure & pedicure','Nail art & design','Enhancement systems','Studio practice'],
src=dict(page='diploma-in-nail-technician',code='DNT/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to nail technology','Manicure and pedicure techniques','Nail art and design','Gel and acrylic nail extensions','Advanced nail enhancement techniques','Nail care products and chemistry']),
rows='''Name the parts of the nail and healthy nail signs|The nail plate, bed, matrix, folds and cuticle each have a role. Knowing healthy nails helps you notice changes that need medical attention.|Draw and label a fictional nail diagram and write a short guide that separates normal ridges from signs such as swelling, pus, deep colour change or painful separation that need a doctor.|parts labelled;normal versus concern;referral line|A throbbing, swollen nail fold with pus is not treated in the salon, and the client is advised to see a doctor.
Set up a sanitary nail station|Tools touch skin that can bleed, so cleaning, disinfecting and single-use items prevent infection.|Create a fictional station checklist that separates single-use files from metal tools, shows cleaning and disinfectant contact time, and states how used items are stored and disposed of.|single-use separated;contact time;storage|Files and buffers are thrown away after one client, and metal pushers go through cleaning, the disinfectant soak for the stated time and a covered box.
Consult and screen the client|A consultation records health, allergies, nail condition, lifestyle and goals. It can stop a service that would cause harm.|Write a fictional consultation form and role-play a client with a skin rash on one hand who wants gel polish. Record what you ask, observe, decide and tell the client.|health questions;observation;decision explained|The technician postpones services on the irritated hand, explains the reason and offers a plain manicure on the other hand only.
Shape, file and care for the cuticle safely|Shape and length should suit the client and nail strength. Cuticle care softens and pushes back dead skin but does not cut living tissue.|Plan a fictional basic manicure with nail shapes, filing direction, cuticle softening, tools and a response if a client bleeds slightly.|shape chosen;cuticle care;bleeding response|If minor bleeding occurs, the technician applies pressure with clean gauze, covers the spot, discards the used tool and records the incident.
Deliver a manicure and pedicure sequence|A service is delivered in a logical order with timing for soak, scrub, massage and polish. Foot care needs extra attention to hygiene and diabetes.|Plan a fictional 60-minute pedicure with timing for each step and the checks needed for a client who says they have diabetes. State what you will not do.|logical order;timing totals 60;diabetes care|For a client with diabetes, the technician avoids cutting and sharp tools, uses gentle care and suggests a podiatrist for foot problems.
Create nail art with design principles|Colour, balance and spacing make nail art attractive and wearable. A design must suit the length and the client's work.|Design three fictional looks, one for an office, one for a wedding and one for a festival, with colour palette, technique and estimated time. Include one design that is easy to maintain.|looks distinct;palette chosen;time estimated|The office look uses a soft nude base with a thin gold line and takes about 20 minutes.
Apply gel polish and cure correctly|Gel products harden under a matching lamp. Thin coats, correct curing and cap-the-edge technique reduce lifting and skin reactions.|Write a fictional gel polish procedure with preparation, base coat, colour coats, top coat, curing time per coat, avoiding skin contact and removal without damage.|prep done;thin coats;safe removal|Each coat is cured for the time given on the product instruction, and the product is kept off the skin to reduce allergy risk.
Apply and maintain extensions and troubleshoot problems|Extension systems need careful preparation, product ratio and structure. Lifting, breakage and allergies must be handled calmly.|For a fictional client whose acrylic nails keep lifting, list possible causes, a plan to check them, a refill procedure and how you tell the client when to stop the service.|causes listed;refill plan;stop rule|Oil left on the nail plate and a bead placed too close to the cuticle are common causes, so the technician checks preparation and bead placement before the refill.
Respond to an allergic reaction or injury|Nail products can cause skin reactions and tools can cause injury. A technician stops work, protects the client and records what happened.|Write a fictional incident procedure for a client who develops itching and swelling after a gel service. Include stopping the service, removal, advice, record keeping and when to call emergency help.|stop service;advice given;record kept|The technician removes the product, rinses the area, advises seeing a doctor and logs the product name and batch, and calls emergency help if breathing is affected.
Price services and build a studio plan|Prices must cover product, time, rent, tax and profit. A studio plan supports growth and consistent quality.|Build a fictional menu of six services and price a gel manicure from product 90, time 60 minutes at 300 per hour, and 120 for rent and overhead. Add a 25 percent margin on cost.|menu complete;cost calculated;margin applied|Cost is 90 plus 300 plus 120, which is 510, and a 25 percent margin on cost gives a price of about 638.'''),
dict(id='tailoring',summary='Cut, stitch and fit garments: measurements, fabric knowledge, pattern drafting, seams and construction, women and men wear, alterations, quality, pricing and a small tailoring business.',icon='Pen',tool='notebook',tools=['notebook','budget','sheets','board'],
nodes=['Measure','Cut','Stitch','Fit'],modules=['Tools & fabric','Measurement & drafting','Garment construction','Women & men wear','Tailoring business'],
src=dict(page='diploma-in-tailoring',code='DIT/Q1001',duration='Six Months',eligibility='No formal qualification required',modules=['Introduction to tailoring','Fabric knowledge and selection','Body measurements and pattern drafting','Garment construction techniques','Women wear construction','Men wear construction']),
rows='''Use the sewing machine and tools safely|Machine safety, thread tension and correct tools prevent injury and poor stitches. Good habits start with setup.|Write a fictional machine setup and safety checklist covering needle choice, threading, bobbin, tension test, foot pedal position, scissors, pins and finger safety.|setup steps;safety rules;tension test|Before sewing a garment, the tailor stitches a scrap of the same fabric to test tension and stitch length.
Choose fabric and understand grain|Fabric grain, shrinkage and fibre affect how a garment hangs and lasts. Wrong grain causes twisting and puckers.|For a fictional shirt, a lining and a kurta, choose fabrics, explain grain direction and describe a shrinkage test before cutting.|fabrics matched;grain explained;shrinkage test|The cotton is washed and pressed before cutting so the finished shirt does not shrink after the first wash.
Take accurate body measurements|Good measurements are taken the same way each time and recorded clearly. Posture and ease change the fit.|Create a fictional measurement card for a trousers and blouse order, with chest, waist, hip, length and shoulder, how to take each and what ease to add.|card complete;method stated;ease added|A blouse with a 90 centimetre bust gets 6 centimetres ease, so the pattern is drafted for 96 around.
Draft a basic bodice, skirt or trouser pattern|Drafting converts measurements into flat pattern pieces. Seam allowance, grainline and notches make cutting reliable.|Draft a fictional skirt pattern from waist 72 and hip 96 centimetres with length 60, marking seam allowance, darts, grainline and notches.|pattern drafted;allowances marked;grainline|For a skirt with a hip of 96, ease of 4 gives 100 around, so each of four panels is drawn at 25 centimetres at the hip line.
Lay out, cut and mark fabric economically|A good layout saves cloth and keeps pieces on grain. Careful marking transfers darts and notches.|Plan a fictional layout for a shirt in 2.2 metres of 110 centimetre wide fabric, and note what you check before cutting, including nap and pattern matching.|layout efficient;grain checked;marks transferred|The tailor checks that the fabric has no one-way print before laying the sleeves in opposite directions to save cloth.
Stitch seams, darts, pleats and gathers|Different seams and finishes serve different garments. Pressing as you sew gives a clean result.|Create a fictional sample board of a plain seam, French seam, dart, pleat and gathered edge with the use of each and the problem it prevents.|samples made;use stated;finish noted|A French seam is used on sheer cotton because it encloses raw edges and prevents fraying.
Attach collars, sleeves, plackets and closures|Set-in parts must match in size and ease. Closures must be strong and placed accurately.|Write a fictional step sequence for a shirt with collar, sleeves, placket, buttons and a pocket, noting where each is checked for balance and reinforcement.|order correct;checks stated;reinforcement|Buttons are marked on the placket with the garment worn on a form so spacing is even.
Construct a women's and a men's garment|Salwar, kurti, blouse, trousers and shirts have standard construction steps. Fit and comfort matter more than speed.|Plan the construction order for a fictional kurti and a pair of formal trousers, listing seams, closures, fitting stages and finishing for each.|two orders;fitting stages;finishing|The trousers receive a first fitting after the side seams and crotch seam are basted and before the waistband is attached.
Alter a garment and solve a fit problem|Alterations rescue garments and keep customers. A tailor diagnoses the cause of a fit problem before cutting or restitching.|For a fictional shirt that pulls across the back and a trouser that is too long, diagnose each problem, plan the alteration, estimate the time and state what cannot be altered.|diagnosis stated;plan clear;limit explained|The shirt is let out along the side seams by 2 centimetres, while a seam allowance of only 1 centimetre limits any further change.
Fit, alter, price and run orders|Fitting reveals problems that can be corrected. Pricing and delivery rules keep a tailoring business healthy.|Calculate a fictional order price for a blouse with fabric 150, lining 40, thread and hooks 20, labour 6 hours at 80 and 10 percent profit. Write fitting steps and a delivery policy.|price correct;fitting steps;policy written|Cost is 150 plus 40 plus 20 plus 480, which is 690, and adding 10 percent profit gives 759.'''),
dict(id='hand-embroidery',summary='Create hand-embroidered textiles: fabrics and threads, design transfer, basic and traditional stitches, colour, finishing, care and a sellable small product line.',icon='Pen',tool='design',tools=['design','canva','notebook','budget'],
nodes=['Plan','Stitch','Finish','Present'],modules=['Tools & fabric','Basic stitches','Traditional techniques','Design & colour','Product line'],
src=dict(page='hand-embroiderer',code='CHE/Q1001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Introduction to hand embroidery','Fabric selection and preparation','Basic embroidery stitches and techniques','Advanced embroidery techniques','Design development and pattern making','Colour combinations and embellishments']),
rows='''Prepare tools, thread and work area|Needles, threads, hoops and light affect comfort and finish. A good setup prevents eye strain and damaged cloth.|Create a fictional tool kit and workspace plan with needle sizes, thread types, hoop, scissors, thimble, lighting and posture breaks.|tools matched;lighting planned;breaks set|The kit uses a fine needle for cotton lawn and a sharper needle for heavier cloth, with a break every 30 minutes.
Select and prepare fabric|Fabric weight and weave decide which stitches and threads work. Preparation prevents puckering and bleeding colour.|Compare cotton, silk, linen and net for a fictional cushion cover and a dupatta border. Choose a fabric, stabiliser and pre-wash plan for each.|fabrics compared;stabiliser chosen;pre-wash plan|The cotton is pre-washed and pressed, then mounted taut in the hoop before stitching.
Transfer a design accurately|A clean transfer keeps the design centred and the cloth unmarked. The method should suit the fabric.|Plan how to transfer a fictional floral border onto dark cotton and sheer fabric, comparing tracing, tailor's chalk and a washable pen, and state how marks are removed.|method suited;centred layout;marks removed|Dark cotton uses white chalk, while sheer fabric uses a light-box tracing with a washable marker.
Stitch outlines: running, back and stem stitch|Even tension and stitch length make clean lines. Practice samples show where control is missing.|Stitch a fictional sampler of running, back and stem stitch on a curve and a straight line, and write what you adjusted to keep stitch length even.|sampler complete;even length;adjustments noted|On the curve, the stitch length is shortened to 2 millimetres so the line stays smooth.
Fill areas with satin, long-short and chain stitch|Filling stitches cover areas smoothly when thread direction and tension are controlled. Padding adds height.|Plan the fill of a fictional leaf shape in satin stitch and a petal in long-short stitch, including stitch direction, padding and edge control.|direction planned;edge controlled;padding decided|Satin stitches run across the leaf at a consistent angle so the light catches evenly.
Work knots, flowers and decorative stitches|Knots and decorative stitches add texture. Thread twists and tension decide how they sit.|Create a fictional small motif using French knots, lazy daisy and feather stitch, then list two common faults and how to fix them.|motif made;faults named;fixes|Loose French knots are corrected by holding the thread taut while the needle is pulled through.
Explore traditional techniques with respect|Techniques such as chikankari, kantha, aari or mirror work belong to craft communities. Respectful practice credits sources and understands the technique.|Prepare a fictional study note on one traditional technique with origin, materials, main stitches, a sample plan and how you credit the tradition in a product description.|origin noted;sample planned;credit given|The product tag credits the regional tradition of the technique and states that the maker is a learner using it respectfully.
Develop colour and embellishment choices|Colour combinations, thread sheen and beads change a design's mood and durability. Embellishments must be secure and comfortable.|Design a fictional colour scheme and embellishment plan for a bridal border with thread colours, beads, spacing and a way to test washing and abrasion.|palette coherent;secure attachment;test planned|Beads are secured with double knots, and a test swatch is washed gently to check colour and attachment.
Recover from a stitching mistake without ruining the work|Mistakes happen in hand work. A careful embroiderer unpicks cleanly, repairs fabric damage and plans to prevent repeats.|Plan how to fix a fictional motif that was stitched in the wrong colour and has puckered the cloth. Include unpicking, steam pressing, patching, restitching and one habit to prevent a repeat.|unpick safely;repair plan;prevention habit|The stitcher cuts the thread on the back with small scissors, lifts it out gently and presses the area from the wrong side before restitching.
Finish, price and present products|Finishing, framing and care instructions protect work. Pricing must include time and materials.|Price a fictional embroidered cushion cover from fabric 180, thread and beads 220 and 14 hours at 100 an hour, add a 20 percent margin and write a care label.|finish described;price calculated;care label|Cost is 180 plus 220 plus 1400, which is 1800, and a 20 percent margin gives a price of 2160.'''),
dict(id='interior-design',summary='Plan functional interiors: design principles, space planning, materials, lighting, furniture, colour, sustainability, drawings and visualisation, budgets and client projects.',icon='Cube',tool='design',tools=['design','figma','canva','notebook','budget'],
nodes=['Brief','Plan','Specify','Present'],modules=['Design foundations','Space planning','Materials & lighting','Digital presentation','Client project'],
src=dict(page='diploma-in-interior-designing',code='DID/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to interior design','Interior space planning and layouts','Furniture design and placement','Decorative arts and lighting','Digital tools and software for interior design','Sustainable and commercial interior design']),
rows='''Take a client brief and survey a room|A design begins with the client's needs, budget and room facts. Measurements, light and services shape what is possible.|Write a fictional brief for a small living room and record measurements, windows, doors, sockets and the client's needs, budget and time limit.|needs recorded;measurements;constraints|The room is 4.2 by 3.6 metres, has one window on the east wall and must seat four people within a budget of 150000.
Apply principles of design|Balance, proportion, rhythm, emphasis and harmony make a room feel ordered. A designer can explain each choice.|Review three fictional rooms and name the principle used or missing, then propose one change for each to improve balance or proportion.|principles named;change proposed;reason given|A very large sofa against small tables looks unbalanced, so a larger side table is proposed.
Choose colour and understand its effects|Colour changes mood, light and size of a room. Light direction and finishes alter how colour looks.|Create a fictional colour scheme for a north-facing bedroom with walls, soft furnishings and accent, and test two samples at different times of day.|scheme coherent;light considered;testing done|A warm neutral wall colour is chosen for the north-facing room because cool light can make grey look dull.
Draw a plan to scale|A scaled plan shows walls, openings and furniture so ideas can be tested. Accuracy prevents expensive errors.|Draw a fictional floor plan of a one-bedroom flat at 1 to 50 scale, marking dimensions, doors and a furniture layout. Convert 4.2 metres to drawing length.|scale correct;dimensions marked;layout clear|At 1 to 50, a 4.2 metre wall is 4200 millimetres, so it is drawn as 84 millimetres, which is 8.4 centimetres on the sheet.
Plan circulation, zoning and ergonomics|People need clear walkways, reachable storage and comfortable furniture. Standard dimensions guide layouts.|Evaluate a fictional kitchen layout for a work triangle, walkway width and storage reach. Redraw it to fix two problems and list the standard dimensions used.|circulation checked;problems fixed;dimensions cited|A walkway narrower than 900 millimetres is widened so two people can pass safely.
Select materials and finishes|Flooring, wall finishes and ceiling choices affect cost, cleaning, safety and look. Moisture and traffic matter.|Choose materials for a fictional bathroom floor, living room floor and kitchen wall, with reasons based on slip resistance, cost, cleaning and durability.|choices justified;safety considered;cost noted|Matte anti-slip tiles are chosen for the bathroom floor because they reduce the risk of falls.
Design lighting in layers|Ambient, task and accent lighting meet different needs. Light levels, colour temperature and energy use are all considered.|Create a fictional lighting plan for a living room and a study corner with fixtures, positions, switching and warm or cool light choices.|layers used;positions marked;energy considered|A study corner gets a task light at 4000 kelvin and the living area uses warm 2700 kelvin lamps.
Prepare a mood board and 3D or digital presentation|Presentation tools explain a design to a client. Clear images, material samples and a layout make approval easier.|Build a fictional presentation with a mood board, plan, material board and two views of one room using any digital tool. Add a short script for the client meeting.|boards complete;views included;script written|The presentation opens with the client's needs and then shows the plan, finish samples and two views.
Manage a change request and a design problem on site|Clients change their minds and sites reveal surprises. A designer records change requests, prices them and protects the schedule.|Respond to a fictional client who asks to move a wall unit after the cabinets are ordered and a pipe is found where a socket was planned. Write the change record, cost impact and revised plan.|change recorded;cost shown;plan revised|The change record shows an extra cost of 8000 and a delay of three days, and the client signs approval before work resumes.
Budget, schedule and run a client project|Budgets, timelines and contracts keep a project on track. Contingency and approval steps protect both sides.|Prepare a fictional project budget for a 150000 living room with furniture 70000, lighting 15000, paint and finishes 25000, labour 25000 and contingency. Check the total and write a schedule.|budget total correct;contingency;schedule written|The items add to 135000, leaving 15000 as contingency, which is 10 percent of the budget.'''),
]
