COURSES=[
dict(id='beauty-care',summary='Deliver safe, professional beauty services: client consultation, hygiene, skin analysis, facials, hair removal, manicure and pedicure, contraindications, aftercare and salon business basics.',icon='Spark',tool='notebook',tools=['notebook','board','budget'],
nodes=['Consult','Prepare','Treat','Advise'],modules=['Professional foundations','Skin & body science','Facial & body services','Hands, feet & hair removal','Salon service portfolio'],
src=dict(page='advanced-diploma-in-beauty-care',code='ADBC/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to beauty therapy','Nail care and nail art','Skin care and treatments','Hair removal techniques','Anatomy and physiology','Business skills for beauty therapists']),
rows='''Prepare a clean, safe treatment area|A beauty treatment starts with a clean room, clean tools and clean hands. Hygiene protects clients and the therapist from infection.|Create a fictional opening and closing checklist for a small salon room covering surfaces, linen, tool cleaning, hand washing, waste and ventilation. Add who checks it and when.|checklist complete;tools handled safely;responsibility set|Used metal tools are washed, soaked in the approved disinfectant for the stated time and stored in a closed box, and the checklist is signed at 9 am and 7 pm.
Greet the client and carry out a consultation|A consultation records health, allergies, skin concerns and goals before any service. It is where unsafe treatments are caught.|Prepare a fictional consultation form and role-play a five-minute interview with a client who has sensitive skin and takes a daily medicine. Note what you ask, record and decide.|health questions;allergies recorded;decision explained|The therapist asks about allergies, recent sun exposure and medicines, records them, and chooses a gentle facial rather than a strong peel.
Identify skin type and common skin conditions|Skin can be dry, oily, combination, normal or sensitive. A therapist can describe skin type but must not diagnose disease.|Analyse three fictional clients from descriptions of shine, tightness and breakouts. Name the skin type, a suitable routine and the signs that mean a referral to a doctor.|skin types matched;routines suitable;referral signs|A client with painful widespread red lumps is referred to a doctor instead of being given a facial.
Explain the structure of skin and why it matters|Skin has layers that protect the body, sense touch and manage water loss. Knowing them explains why products and treatments behave as they do.|Draw and label a fictional diagram of the three skin layers and write one sentence about how each layer affects a facial, a wax and sun protection.|layers labelled;function explained;link to treatment|Because the outer layer is the barrier, over-exfoliating weakens it, so the plan limits exfoliation to once a week.
Perform a basic facial in the right order|A facial follows a logical order: cleanse, analyse, exfoliate, massage, mask, tone and protect. The order and timing protect the skin.|Plan a fictional 45-minute basic facial for combination skin with each step, time and product type. State one step you would shorten for sensitive skin.|steps in order;timing totals 45;sensitive skin adjusted|Cleansing takes 8 minutes, massage 10, mask 12, and the remaining time covers analysis, toning and sun protection; for sensitive skin the massage is shortened.
Plan safe hair removal|Waxing, threading and bleaching can irritate the skin. A patch test, correct temperature and contraindication check reduce harm.|Write a fictional step-by-step plan for waxing the lower leg and threading the eyebrows, with a patch test, skin check, aftercare and a list of conditions that mean you do not proceed.|patch test;contraindications;aftercare|The therapist does not wax over a rash, sunburn or varicose veins and explains to the client why.
Give a manicure and pedicure with infection control|Nail services involve sharp tools and close contact. Careful hygiene and no cutting of live skin prevent infection.|Write a fictional manicure and pedicure procedure with tool sets, order of steps, how to treat a minor cut and when to refuse service for a suspected nail infection.|ordered steps;tool hygiene;refusal rule|If a client has a swollen painful nail fold, the therapist politely declines and suggests seeing a doctor.
Choose products and give aftercare advice|Products have purposes and ingredients that suit some skin types. Aftercare tells clients what to do and avoid after a service.|For a fictional client after a facial and a wax, write an aftercare sheet with product suggestions, what to avoid for 24 hours and signs to contact the salon. Do not make cure claims.|suitable advice;avoid list;no cure claims|The sheet advises sunscreen, no hot baths or saunas for 24 hours, and calling the salon if redness lasts beyond a day.
Handle an adverse reaction and a complaint|Even careful services can cause redness, burning or dissatisfaction. A calm response protects the client, records facts and prevents repeat harm.|Write a fictional incident procedure for a client who develops a rash after a wax and then complains. Include immediate care, referral signs, record keeping, apology and review.|immediate care;facts recorded;review step|The therapist removes the product, cools the area, advises a doctor if swelling spreads, records the time and product in the file, and phones the client the next day.
Plan and price a beauty service menu|A menu lists services, time and price so that the salon covers its costs and clients know what to expect.|Create a fictional menu of eight services with duration, product cost and price. Calculate the profit on a facial priced at 900 with 220 product and 150 room cost, then set a package discount.|menu complete;profit correct;discount sensible|The facial earns 900 minus 220 minus 150, which is a profit of 530 per client, and a package of three keeps a margin above 400 each.'''),
dict(id='makeup-artistry',summary='Plan and apply makeup professionally: hygiene, colour theory, skin preparation, base, eyes, lips, bridal and editorial looks, kit management, portfolio and client communication.',icon='Pen',tool='design',tools=['design','canva','notebook'],
nodes=['Consult','Prepare','Create','Finish'],modules=['Makeup foundations','Base & skin preparation','Eyes, lips & cheeks','Bridal & fashion looks','Professional portfolio'],
src=dict(page='diploma-in-professional-makeup',code='DPMA/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to professional makeup artistry','Skin preparation and foundation techniques','Eye makeup techniques','Lip makeup and cheek enhancement','Bridal and traditional makeup','Fashion and editorial makeup']),
rows='''Keep a hygienic kit and workspace|Makeup is applied near eyes and mouth, so clean brushes, single-use applicators and sanitised products protect clients from infection.|Build a fictional hygiene routine for a freelance kit: brush cleaning schedule, single-use items, decanting products with a spatula and rules for a client with an eye infection.|schedule set;single-use items;refusal rule|Brushes used on eyes are cleaned after each client, and lipsticks are scooped with a clean spatula rather than applied directly.
Read face shape, skin tone and undertone|Face shape guides placement, while skin tone and undertone guide colour choice. These are guides, not strict rules.|Describe three fictional clients by face shape, depth of tone and undertone, then choose a foundation family, blush and lip colour for each with one reason.|features described;colour choice;reason given|A client with golden undertone and medium depth suits a warm peach blush rather than a cool pink.
Apply colour theory in makeup|Complementary colours cancel or intensify each other, and colour correctors neutralise discolouration. Light and shadow shape the face.|Create a fictional colour-correction chart for dark circles, redness and dullness, with the corrector colour, placement and a note on how much product to use.|corrector matched;placement stated;light amount|Peach or orange tones neutralise blue-brown under-eye shadow, applied thinly before concealer.
Prepare the skin and apply a flawless base|A good base depends on skin preparation, correct shade matching and light layers. Heavy product shows texture.|Plan a fictional base routine for oily skin and dry skin, with cleansing, moisturiser, primer, foundation, concealer, setting and a test of shade match at the jaw in daylight.|prep differs by skin;shade test;setting|On oily skin, powder is pressed on the centre of the face only, and on dry skin a hydrating primer is used.
Shape eyes and brows|Eye shape affects shadow placement and liner. Brows frame the face and are shaped to the person, not to a trend only.|Write a fictional step list for a natural eye look and a smoky eye for hooded eyes, including brow shaping, shadow placement, liner, mascara and false lash safety.|placement for eye shape;brow guide;lash safety|For hooded eyes the shadow is placed slightly higher so it stays visible when the eye is open.
Create lips and cheek colour|Lip shape, colour and finish change the look. Blush position depends on the face and the desired lift.|Design three fictional lip and cheek combinations for day, evening and photographs, listing shade, finish, liner use and the reason for each choice.|three looks;finish chosen;reason|For photographs, a matte lip with a defined liner prevents feathering under bright lights.
Plan a bridal makeup trial and day schedule|Bridal makeup must last for hours, photograph well and match the outfit. A trial reduces risk, and a timeline keeps the day calm.|Write a fictional plan for a bridal trial and wedding morning with allergy check, look decision, product list, timing for the bride and two relatives and a touch-up kit.|trial done;timeline realistic;touch-up kit|The artist allows 90 minutes for the bride and 30 each for two relatives, and finishes 45 minutes before photographs.
Design a fashion or editorial look|Editorial work serves a concept, a photographer and a brand brief. The makeup must work under lighting and movement.|Create a fictional face chart and mood summary for a magazine shoot titled Monsoon Glass, with colours, textures, products, time and a safety note for any glitter near the eyes.|concept clear;face chart;safety note|The look uses a dewy base, clear gloss and silver liner, and loose glitter is replaced with a gel to avoid it falling into the eyes.
Manage an allergy scare and an urgent change|Makeup work happens under time pressure and an allergic reaction can appear without warning. A prepared artist stops, protects the client and adapts the schedule.|Plan a fictional response to a bride whose eyes begin to swell during the trial, covering when you stop, what you remove, who you call and how you change the wedding-day plan.|stop and remove;seek help;plan adjusted|The artist removes the eye products with a clean cleanser, advises the bride to see a doctor, and agrees a hypoallergenic palette for the wedding day only after medical advice.
Price services and present a professional portfolio|Pricing covers time, products, travel and skill. A portfolio shows range and consistency, and permission is needed for client images.|Calculate a fictional bridal package price from kit cost 600, travel 400, 3 hours at 700 per hour and an assistant at 500. Outline a portfolio of eight looks and a consent line for photographs.|price calculated;portfolio range;consent line|The package costs 600 plus 400 plus 2100 plus 500, which is 3600, and the artist adds a consent form before posting any client photograph.'''),
dict(id='hair-salon',summary='Work safely as a hair professional: hair and scalp science, consultation, cutting, colouring, chemical treatments, styling, scalp care, salon hygiene and client management.',icon='People',tool='notebook',tools=['notebook','board','budget'],
nodes=['Consult','Prepare','Style','Care'],modules=['Hair science & consultation','Cutting & finishing','Colour & chemical services','Styling & treatments','Salon practice'],
src=dict(page='diploma-in-hair-stylist',code='DHS/Q0001',duration='Six Months',eligibility='8th Grade or equivalent',modules=['Hair styling and hair science','Hair cutting techniques','Hair colouring and chemical treatments','Hair styling techniques','Hair and scalp treatments','Salon management and client handling']),
rows='''Understand hair structure and growth|Hair has a fibre structure, a growth cycle and different textures. Porosity and elasticity change how it reacts to products and heat.|Explain in a fictional guide for new staff how to judge hair texture, porosity and elasticity with simple tests, and how each result changes product and heat choices.|structure described;tests clear;choices linked|Hair that absorbs water quickly and dries fast is treated as high porosity, so a lighter heat setting and a sealing conditioner are chosen.
Consult the client and inspect the scalp|A consultation covers history, goals, allergies and scalp condition. A scalp problem can stop a service.|Write a fictional consultation card and role-play a client who wants a colour change but reports an itchy scalp. State what you check, what you decide and how you explain it.|history recorded;scalp inspected;decision explained|The stylist postpones colouring on an irritated scalp and suggests seeing a doctor first.
Keep tools and station hygienic|Combs, scissors and capes pass between clients, so cleaning and disinfecting prevent infection.|Create a fictional hygiene schedule for a station, covering combs, scissors, brushes, capes, clippers, floors and hand washing, with who does each task and when.|tasks listed;timing stated;owner named|Clippers are brushed and disinfected after every client and capes are replaced with fresh ones.
Cut basic shapes by sectioning and guides|A cut starts with sections, a guide length and consistent tension. Face shape and growth patterns affect the final shape.|Plan a fictional one-length bob and a layered cut, with sectioning diagram, guide, cutting lines, checks and the wet-to-dry length change.|sections shown;guide set;length allowance|Curly hair shrinks as it dries, so the stylist cuts it longer than the target.
Select colour with theory and safety|Colour depends on the starting level, tone and developer strength. A patch test and strand test reduce unpleasant surprises.|For a fictional client with dark brown hair who wants light brown, write the level, tone, developer choice, patch test, strand test, timing and aftercare.|level reasoned;tests included;aftercare|A patch test is done 48 hours before colouring, and the stylist records the result on the card.
Plan chemical straightening or perm safely|Chemical services alter the hair structure and can damage it. Condition, previous treatments and instructions matter.|Create a fictional decision sheet for chemical smoothing that checks hair condition, past bleaching, scalp health, test strand and when to refuse, plus aftercare for the first week.|checks listed;refusal rule;aftercare|The stylist refuses a smoothing service on hair that snaps in a strand test and recommends conditioning first.
Style hair for an occasion|Occasion styling must last, suit the outfit and be comfortable. Heat tools need temperature control and protection.|Plan a fictional bridal updo and a casual wavy blow-dry with products, tools, temperature, timing and a plan for a bride with fine hair.|steps sequenced;heat protection;fine hair adapted|For fine hair, the stylist adds texture spray before pinning and uses a lower heat.
Provide scalp and hair treatments responsibly|Conditioning, oil and scalp massage can help comfort and appearance, but a stylist does not diagnose or promise to regrow hair.|Write a fictional treatment menu with three services, steps, duration and an honest client statement. Add what you say to a client who asks you to stop hair loss.|treatment steps;honest claims;referral line|The stylist explains that a salon treatment can improve condition but sudden hair loss should be checked by a doctor.
Correct a hair colour problem professionally|Colour mistakes happen when history is unclear or timing is wrong. A professional finds the cause, tells the client honestly and corrects in stages to protect the hair.|Analyse a fictional case where a client has orange tones after lightening. Identify the likely cause, choose a corrective plan across two visits, price it and write what you tell the client.|cause identified;staged plan;honest message|The stylist explains that the hair was not lightened enough, plans a toner this visit and a gentler lightening in two weeks, and warns that the second visit has its own fee.
Price and run salon appointments|A salon earns from service time, product costs and repeat clients. Scheduling and clear policies reduce waiting and conflict.|Build a fictional price list and day schedule for a stylist with eight appointments, then calculate the income if the average ticket is 650 and product cost is 15 percent.|schedule realistic;income correct;policies stated|Eight clients at 650 give 5200 and product cost of 780 leaves 4420 before rent and tax.'''),
dict(id='fashion-design',summary='Design and develop garments: fashion basics, textiles, sketching, pattern drafting, draping, construction, CAD, merchandising and building a small collection.',icon='Pen',tool='design',tools=['design','canva','figma','notebook'],
nodes=['Research','Design','Construct','Present'],modules=['Fashion foundations','Textiles & materials','Pattern & construction','Illustration & CAD','Collection & marketing'],
src=dict(page='certificate-in-advanced-fashion-designing',code='CAFD/Q1001',duration='Three Months',eligibility='10+2 or equivalent',modules=['Fundamentals of fashion designing','Textile science and fabric selection','Pattern making and draping techniques','Garment construction and sewing techniques','Fashion illustration and computer-aided design','Fashion merchandising and marketing']),
rows='''Use design elements and principles|Line, shape, colour, texture, balance and proportion shape how a garment looks. A designer chooses them for a reason.|Analyse three fictional garments and name the elements and principles each uses. Explain how one change in line or proportion would alter the look.|elements named;principles linked;change explained|A vertical panel creates a longer line, while a wide horizontal band makes a garment appear shorter.
Build a mood board and colour story|A mood board turns research into direction. A colour story keeps a collection consistent.|Create a fictional mood board for a summer collection with theme, five colours, textures, silhouettes and the customer the collection serves.|theme clear;palette coherent;customer named|The collection Monsoon Market uses teal, ochre, cream, rust and charcoal, with light cotton and linen for young professionals.
Identify fibres and fabrics|Fibres behave differently in drape, warmth, care and cost. A designer matches fabric to the garment.|Compare cotton, silk, wool, polyester and viscose for a fictional shirt, a coat and a dress. Choose a fabric for each and justify with drape, care and cost.|properties compared;choices justified;care noted|Cotton poplin is chosen for the shirt because it is breathable and easy to wash.
Draw fashion figures and flat sketches|A fashion figure shows mood, while a flat technical drawing shows construction. Both are needed for production.|Draw a fictional dress as a fashion sketch and a front and back flat with seams, darts and closure labelled. List five details a tailor needs.|figure sketch;flat with seams;details listed|The flat shows a side zip, bust darts and a 2 centimetre hem so the tailor can cost and cut it.
Take measurements and draft a basic block|Accurate body measurements and a block are the base for patterns. Ease allows movement and comfort.|Using fictional measurements of bust 88, waist 70 and hip 94 centimetres, plan the ease, draft a basic bodice block on paper and list the checks before cutting.|measurements used;ease allowed;checks listed|With 6 centimetres of ease at the bust, the block is drafted for 94 centimetres around.
Drape and manipulate a pattern|Draping on a form tests drape and fit, and manipulation turns a block into a new style by moving darts and adding fullness.|Plan how a fictional A-line dress is made from a block by moving a dart and adding flare. Show the cutting lines and how you would test the fit in muslin.|dart moved;flare added;fit test planned|The bust dart is rotated to the side seam, and a muslin is pinned on a form before cutting the final fabric.
Plan garment construction and quality checks|Construction order, stitch type, seam finish and pressing decide durability and finish. Quality checks catch errors early.|Write a fictional construction order for a lined jacket or a shirt, with stitch types, seam finishes, pressing points and a quality checklist.|order logical;finishes chosen;checklist|Shoulder seams are stitched and pressed flat before collars are attached.
Use CAD and tech packs|A technical pack tells a factory how to make a style: drawings, measurements, materials, trims and sizing.|Create a fictional tech pack outline for a kurta with flat, measurement table, fabric, trims, stitching notes and tolerance. Use a digital tool of your choice.|flat included;measurements tabled;materials listed|The table lists chest 100, length 90 and sleeve 58 centimetres with a tolerance of 1 centimetre.
Plan sustainable and ethical production|Fashion uses materials, water and labour. Responsible designers choose fabrics, suppliers and quantities with waste, fair work and care in mind.|Compare two fictional production plans for a shirt, one with a cheap polyester and one with organic cotton. Include cost, waste, care life and a statement about a fair labour check.|options compared;waste reduced;labour check|Cutting the pattern pieces to reduce waste saves 0.2 metres a shirt, which is 20 metres over a batch of 100.
Cost, brand and show a mini collection|A collection is costed and positioned for a target customer. Pricing covers materials, labour, overheads and profit.|Cost a fictional five-piece collection and price one dress: fabric 3 metres at 280, trims 120, stitching 450 and overhead 150, with a 40 percent margin on selling price.|costs added;price calculated;collection plan|The dress costs 840 plus 120 plus 450 plus 150, which is 1560, and a 40 percent margin on price gives a selling price of 2600.'''),
dict(id='drawing-painting',summary='Develop drawing and painting skills: line, tone, perspective, colour, figure, landscape, abstract and mixed media, presentation, exhibition and ethical professional practice.',icon='Pen',tool='design',tools=['design','canva','notebook'],
nodes=['Observe','Compose','Create','Present'],modules=['Drawing foundations','Colour & painting','Figure & portrait','Landscape & mixed media','Art practice & portfolio'],
src=dict(page='advanced-diploma-in-drawing-and-painting',code='ADD&P/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Foundations of drawing','Fundamentals of painting','Human figure and portrait drawing','Nature, landscape and outdoor painting','Modern art, abstract and mixed media','Art presentation and professional practices']),
rows='''Draw with line, shape and form|Observation turns objects into simple shapes and then forms. Good drawing begins with looking carefully, not copying symbols.|Make a fictional set of three still-life drawings of a bottle, a bowl and a cloth, first as outline shapes, then with form. Write what you noticed about proportion.|shapes observed;proportion checked;form shown|The bottle is first measured as three stacked shapes so its height is about twice the width of the bowl.
Use tone and shading|Tone shows light on a form. Value steps from light to dark create depth and a believable surface.|Create a fictional value scale of seven steps and shade a sphere and a cylinder with a clear light source. Label highlight, core shadow and cast shadow.|value scale;light source;shadow labelled|The sphere has a highlight at the upper left, a core shadow opposite and a cast shadow on the table.
Apply one-point and two-point perspective|Perspective gives depth with a horizon line and vanishing points. Parallel lines meet at the vanishing point.|Draw a fictional corridor in one-point perspective and a building corner in two-point perspective, marking the horizon and vanishing points.|horizon marked;vanishing points;consistent lines|All receding lines of the corridor floor meet at one point on the horizon.
Mix colour and understand paint behaviour|Paints differ in transparency, drying time and mixing. A colour wheel guides mixing but real pigments vary.|Make a fictional colour mixing chart with primaries, secondaries, tertiaries and tints and shades. Record which paint you used and how each behaved.|mixing chart;paint noted;behaviour recorded|Watercolour tints are made by adding water, while acrylic tints use white and dry darker.
Compose a picture with focus and balance|Composition arranges shapes so the eye moves to a focal point. Balance, contrast and rhythm support the idea.|Plan three thumbnails for a fictional market scene and choose one, explaining the focal point, balance and path of the eye.|three thumbnails;focal point;eye path|The chosen thumbnail places the fruit seller at a third from the left with a strong light behind her.
Draw the figure and portrait with proportion|Human proportion is a guide, and each person varies. Gesture captures movement before details.|Do a fictional series of five gesture sketches in one minute each and one portrait using proportion guides. Note what you adjusted after checking.|gesture series;proportion guide;corrections|The eyes are placed halfway down the head, and the portrait is corrected after noticing the ears were too high.
Paint a landscape with depth and light|Atmospheric perspective makes distant areas lighter and cooler. Time of day changes colour and shadow direction.|Plan and paint a fictional landscape with foreground, middle ground and background, using colour temperature and edge control to create depth.|three planes;temperature shift;light consistent|The distant hills use pale blue-grey and soft edges, while the foreground uses saturated green and sharp edges.
Explore abstract and mixed media|Abstraction simplifies or changes appearance to express an idea. Mixed media combines materials in a controlled way.|Create a fictional series of three small abstract works on one theme using collage, ink and texture paste. Write the concept and why you chose each material.|concept stated;materials chosen;series unity|The series on monsoon uses blue layered papers, thin ink runs and textured paste for rain on stone.
Develop a series with a clear concept|A series connects works through theme, method and development. It shows that the artist has an idea, not only a set of pictures.|Plan a fictional series of six works on the theme Water in the City. Define the concept, the visual rules, the sequence of development, the materials and how the final display will read as one body of work.|concept clear;rules set;sequence planned|The series uses a limited palette of grey, blue and ochre and moves from sketch studies to two large final paintings.
Present, price and protect your art|Presentation, pricing and copyright make art a professional practice. Credit and permission matter when using reference images.|Prepare a fictional artist statement, portfolio of six works, a price list and a copyright note. Price a work from materials 1200, 20 hours at 150 and gallery commission of 30 percent.|statement written;price calculated;copyright note|The work costs 1200 plus 3000, which is 4200, and the listed price is set at 6000 so the artist keeps 4200 after the 30 percent commission.'''),
dict(id='carpentry-furniture',summary='Build and design simple furniture safely: wood selection, tools, workshop safety, measuring, joinery, finishing, ergonomics, cost estimates and a small furniture project.',icon='Cube',tool='design',tools=['design','notebook','budget','sheets'],
nodes=['Plan','Cut','Join','Finish'],modules=['Wood & tools','Joinery & construction','Furniture design','Finishing & assembly','Workshop project'],
src=dict(page='diploma-in-carpenter-furniture-design',code='DCFD/Q9703',duration='Six Months',eligibility='8th Grade or equivalent',modules=['Introduction to carpentry and furniture design','Woodworking materials and tools','Wood joinery techniques','Furniture design principles','Carpentry techniques and furniture construction','Surface finishing and wood coatings']),
rows='''Work safely in a carpentry workshop|Sharp tools, dust and noise cause injuries. Personal protective equipment, guards and tidy habits prevent most accidents.|Write a fictional workshop safety plan covering eye and ear protection, dust control, guard use, clamping, fire safety, first aid and rules for loose clothing.|ppe listed;hazards controlled;first aid|Safety glasses and ear defenders are worn when a router is used, and the dust extractor is checked before work begins.
Identify wood and board materials|Hardwood, softwood, plywood, MDF and veneer have different strength, cost and uses. Moisture and grain direction matter.|Compare teak, pine, plywood and MDF for a fictional bookshelf and a kitchen cabinet. Choose materials and justify them with strength, moisture and cost.|materials compared;moisture considered;choice justified|Plywood is chosen for shelves because it resists sagging better than MDF in humid weather.
Measure, mark and cut accurately|Accurate measurement and marking prevent waste. A saw cuts on the waste side of the line.|Prepare a fictional cutting list for a small stool with leg, seat and rail lengths, add kerf allowance and mark where each cut will be made.|cutting list;allowance;marking method|With a 3 millimetre kerf and four cuts, the plan adds 12 millimetres of waste to the board length.
Maintain and sharpen hand tools|A dull tool needs more force and is more dangerous. Maintenance keeps tools accurate and safe.|Create a fictional maintenance schedule for chisels, planes and saws with cleaning, sharpening angles, storage and checks before use.|schedule clear;sharpening angle;storage|The chisel is sharpened at about 25 degrees and stored with an edge guard.
Make basic joints|Joints connect pieces. Butt, lap and dado joints are simple, and glue surface and clamping pressure decide strength.|Plan how to make a fictional box using butt, lap and dado joints, with marking, cutting, gluing and clamping steps. State which joint is best for the shelf.|joint steps;glue and clamp;best joint reasoned|A dado joint supports the shelf better than a butt joint because the board sits in a groove.
Make strong frame and carcass joints|Mortise and tenon, dovetail and finger joints resist stress. Wood movement must be allowed for.|Select joints for a fictional table frame, a drawer and a cabinet corner, explaining strength, difficulty and what wood movement does in each.|joints chosen;movement considered;difficulty noted|A drawer front is joined with dovetails because they resist being pulled apart.
Design a comfortable, proportionate piece|Furniture must fit the body and the room. Ergonomic dimensions, proportion and style guide design.|Design a fictional study desk and chair with height, depth, legroom and storage dimensions, a sketch and a note on who uses it.|dimensions suitable;sketch;user considered|A desk is drawn at 750 millimetres high with a chair seat height of 450 millimetres.
Sand, finish and protect the surface|Surface preparation decides the finish. Stains, varnish, oil and paint protect wood in different ways.|Plan a fictional finishing schedule for a teak table and a pine shelf, with sanding grits, stain or oil, coats, drying time and ventilation precautions.|sanding sequence;coats and drying;ventilation|The table is sanded through 120, 180 and 240 grit before the first coat of oil.
Solve a design and fabrication problem|Real orders bring constraints such as small rooms, limited budgets and awkward walls. A carpenter adjusts the design while keeping strength and safety.|Redesign a fictional wardrobe for a room with a sloping ceiling and a 4500 budget. Compare two designs, change the dimensions, choose materials and explain how you keep the doors and shelves safe and stable.|constraints stated;design adjusted;stability checked|The wardrobe is lowered on the slope side, uses plywood shelves and a fixed back panel, and is anchored to the wall for stability.
Estimate cost and build a simple piece|A project plan lists materials, tools, time and cost. Estimating avoids loss on the job.|Create a fictional estimate for a bedside table: wood 1800, hardware 250, finish 300, labour 12 hours at 200 and 15 percent profit. Add the build sequence and quality checks.|estimate calculated;sequence;quality checks|The table costs 1800 plus 250 plus 300 plus 2400, which is 4750, and a 15 percent profit makes the quote about 5463.'''),
]
