COURSES=[
dict(id='office-administration',summary='Run an office reliably: records, scheduling, correspondence, visitors, supplies, petty cash, travel, confidentiality and a written operations manual.',icon='Briefcase',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Receive','Organise','Support','Control'],modules=['Office organisation','Communication & records','Supplies & small finance','Executive support & events','Operations manual'],
src=dict(page='advanced-diploma-in-office-administration-and-management',code='ADOAM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to office administration','Business communication and correspondence','Office technology and digital tools','Financial administration and budgeting','HR in office administration','Office operations and facility management']),
rows='''Plan the daily work of an office|An office runs on routines. Listing recurring tasks with owners and times shows gaps and prevents work from depending on memory.|Create a daily and weekly task schedule for a fictional 6-person office covering opening, post, calls, visitors, filing, supplies and closing. Name an owner and a backup for each task.|task list;owner and backup;time slots|The opening checklist is done by Ravi at 9:00 and by Meena if Ravi is absent, so the office never opens late for lack of a key holder.
Handle incoming calls, visitors and post|Every contact is a chance to help or to lose information. A simple log and a clear greeting protect the office and the visitor.|Write a script and log format for a fictional receptionist handling a call, a visitor without an appointment and a courier parcel. Include what is recorded and what is never said.|greeting script;log fields;confidentiality|The log records name, purpose, time in, host and badge issued. The receptionist does not say where the manager is, only that they will check availability.
Set up a filing and records system|A filing system lets anyone find a document in under a minute. Naming, indexing and retention rules keep it working.|Design a filing plan for a fictional office with paper and digital folders, a naming rule, an index, a retention period and a disposal rule for confidential papers.|folder structure;naming rule;retention and disposal|Digital file names follow YYYY-MM-DD-type-party, so 2026-09-18-invoice-sharma sorts by date and can be found by party name.
Draft correspondence and keep copies|Official letters follow a layout and are recorded when sent. A reference number and file copy provide evidence later.|Draft a fictional letter of approval for a leave request and a reply to a vendor query. Add a reference number and describe where the copy and the dispatch record go.|correct layout;reference number;copy kept|Letter ref OFF/2026/114 is entered in the outward register with date and method, and the copy is filed under the employee.
Manage supplies and compare quotes|Buying should balance price, quality, delivery and reliability. Comparing written quotes reduces cost and risk.|Compare quotes from three fictional suppliers for stationery for a year, with unit prices, delivery time and payment terms. Recommend one and explain why the cheapest may not win.|quotes compared;recommendation;risks|Supplier B is 4 percent dearer but delivers in two days and takes returns, so the office avoids stock-outs and recommends B.
Run petty cash with an imprest|An imprest is a fixed float refilled by the amount spent. Every payment needs a voucher so the cash plus vouchers always equals the float.|A fictional petty cash float is 10,000. Record six payments with vouchers and calculate the amount to refill. Explain what you do when the cash and vouchers do not add up.|voucher record;refill amount;difference handling|Vouchers of 7,850 and cash of 2,140 total 9,990, a shortage of 10 that is reported and investigated rather than hidden.
Schedule meetings and travel for an executive|An assistant protects an executive's time by checking diaries, confirming details and preparing papers. Travel plans need buffers.|Plan a fictional two-day business trip: flights or trains, hotel, local transport, meeting schedule, papers and contacts. Include a buffer and a contingency for a delay.|itinerary;buffers;contingency|The plan leaves 90 minutes between landing and the first meeting, and lists a backup train if the flight is cancelled.
Protect confidential information in the office|Confidential papers and screens are exposed by habit, not malice. Simple rules prevent most leaks.|Write a clean-desk and confidentiality policy for a fictional office covering screens, printing, bins, visitors, conversations and sharing files. Describe what to do if a document is left in the printer.|practical rules;visitor control;incident step|Sensitive print jobs require a code at the printer. A paper left behind is handed to the supervisor and logged, not read.
Prepare for emergencies and basic facility checks|Offices need exits, extinguishers, first aid and contact lists that are checked, not only installed. People should know what to do.|Create an emergency card and a monthly checklist for a fictional office with exits, extinguishers, first-aid box, contact numbers and a drill record.|emergency actions;monthly checks;drill record|The checklist records the extinguisher inspection date and that the first-aid box has unexpired items, with initials and date.
Write an office operations manual|A manual lets a replacement keep the office running. It documents routines, contacts, systems and how to deal with exceptions.|Compile a fictional office manual with schedule, call and visitor procedures, filing plan, supply process, petty cash rules, travel checklist, confidentiality rules and emergency plan.|complete sections;usable by a newcomer;exceptions covered|A new assistant follows the manual's page for a courier delivery without asking anyone and records it correctly in the log.'''),

dict(id='supply-chain-logistics',summary='Plan and run supply chains and logistics: demand, inventory, transport, warehousing, performance measures, risk, technology and sustainability.',icon='Workflow',tool='board',tools=['board','data','budget','sheets'],
nodes=['Plan','Source','Move','Measure'],modules=['Supply chain basics','Demand & inventory','Transport & distribution','Risk, technology & sustainability','Supply chain improvement'],
src=dict(page='diploma-in-supply-chain-management',code='DSCM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Supply chain management','Inventory and warehouse management','Logistics and distribution management','Demand planning and supply chain risk','Digital supply chain and emerging technologies','Sustainability and strategy']),
rows='''Map a supply chain from source to customer|A supply chain links suppliers, makers, distributors, retailers and customers. Mapping shows where products, money and information flow and where delays occur.|Map the supply chain for a fictional packaged-rice brand from farm to household. Mark product, money and information flows and identify the longest delay.|stages mapped;three flows;delay identified|Rice moves from farms to a mill, to a distributor and to shops, while payment moves backwards and orders move upstream. The longest delay is waiting for truck loads.
Define customer service measures|Service is measured by delivery on time and in full, accuracy and speed. Averages hide failures that customers feel.|From a fictional table of 200 orders, calculate on-time delivery, in-full delivery and OTIF. Explain why OTIF is lower than either alone.|three measures;OTIF logic;interpretation|If 90 percent arrive on time and 92 percent are complete, OTIF is lower than both because an order must be both to count.
Forecast demand with a simple method|A forecast uses past demand and known events. Its error should be measured so the method can be improved.|Using fictional sales for 6 months, forecast month 7 with a 3-month moving average, then compare with the actual figure given and calculate the forecast error.|forecast calculated;error measured;method comment|Average of 120, 130 and 140 gives 130. If the actual is 150, the error is 20 units, which suggests a rising trend the method misses.
Calculate order quantity and reorder point|Order quantity balances ordering cost with holding cost. The reorder point covers demand during lead time plus a safety buffer.|For a fictional item with annual demand 2,400, order cost 500 and holding cost 12 per unit per year, calculate the economic order quantity. With lead time of 10 days and daily use of 8, find a reorder point with safety stock of 40.|EOQ calculated;reorder point;safety stock|EOQ is the square root of 2 times 2,400 times 500 divided by 12, which is about 447. Reorder point is 80 plus 40, which is 120 units.
Choose transport mode and route|Mode choice trades cost, speed, reliability and damage risk. The best choice depends on the product and the deadline.|Compare road, rail and air for three fictional consignments, fresh flowers, steel coils and urgent spare parts. Choose a mode for each and justify with cost and time.|three options compared;justification;trade-off|Fresh flowers need speed and cold handling, which justifies air despite the high cost, while steel coils favour rail or road for low cost.
Design a distribution network|A network decides where stock is held and how orders are delivered. More locations reduce delivery time but increase inventory and cost.|For a fictional company serving four cities, compare one central warehouse with two regional warehouses on delivery time, inventory, transport cost and risk. Recommend one.|options compared;trade-offs;recommendation|Two regional warehouses cut delivery from three days to one but raise stock holding, so they are chosen only if next-day service is a priority.
Identify and respond to supply risks|Risks come from suppliers, transport, demand and external events. A response plan reduces damage before an event occurs.|Build a risk table for a fictional food manufacturer with eight risks, likelihood, impact, early warning signs and a response for the top three.|risk table;early warning;response|Dependence on one packaging supplier is a high risk. The response is to qualify a second source and hold two weeks of buffer stock.
Use data to find a bottleneck|Technology only helps if it measures the right things. Data shows where time is lost, not only where people feel pressure.|From fictional timestamps for order received, packed, dispatched and delivered, find the stage with the longest average delay and propose one change with an expected effect.|time per stage;bottleneck found;proposal|Packing takes 1 hour on average but waiting for dispatch takes 8, so adding a second dispatch slot has more effect than speeding up packing.
Reduce waste and emissions in a chain|Sustainability can lower cost and risk. Fuller loads, shorter routes, reusable packaging and fewer returns reduce waste.|For a fictional delivery business, propose four changes that cut waste or emissions, estimate effect on cost and service, and say how you would measure the result.|four changes;cost and service effect;measure|Combining deliveries to the same area on one route reduces kilometres driven and fuel cost while keeping the same delivery day.
Present a supply chain improvement plan|An improvement plan states the problem, evidence, options, chosen action, measures and review.|Package a fictional improvement plan for a distributor with a map, service measures, inventory settings, transport choices, risks, a target, owner and a 90-day review.|evidence to action;targets;owners|The plan targets raising OTIF from 84 to 92 percent in 90 days by resetting reorder points, with weekly reporting by the warehouse supervisor.'''),

dict(id='courier-delivery',summary='Run courier and delivery operations: booking, sorting, route planning, tracking, parcel safety, last-mile delivery, returns, service levels and customer care.',icon='Briefcase',tool='board',tools=['board','budget','sheets'],
nodes=['Book','Sort','Deliver','Close'],modules=['Courier basics & booking','Parcel handling & packaging','Routes & last mile','Returns, SLAs & customers','Delivery operations'],
src=dict(page='diploma-in-courier-and-logistics-management',code='DCLM/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to the courier and logistics industry','Transportation management','Warehousing and inventory management','Courier operations and parcel management','Supply chain management in logistics','Customs clearance and international logistics']),
rows='''Take a correct booking|A booking records sender, receiver, contents, weight and service. Errors at booking become failed deliveries later.|Write the booking checklist for a fictional courier counter and process three sample bookings, including one with an incomplete address and one with a restricted item.|complete fields;restricted item;address check|A parcel with a liquid battery is refused or routed to an approved service. An address without a pin code is completed before the receipt is printed.
Calculate chargeable weight|Carriers charge by the greater of actual weight and volume-based weight. Using the wrong figure causes disputes or losses.|For a fictional parcel measuring 40 by 30 by 25 cm and weighing 4 kg, calculate volumetric weight using a divisor of 5000 and state the chargeable weight.|volume calculated;greater weight used;divisor stated|40 times 30 times 25 is 30,000 cubic cm, which divided by 5000 is 6 kg. Because 6 is greater than 4, the chargeable weight is 6 kg.
Pack fragile and valuable items|Packaging protects the item and limits claims. It should resist drops, pressure and moisture.|Specify packaging for a fictional glass vase and a laptop: inner cushioning, outer box strength, labels, sealing and photos at pack time. Explain what the photos protect against.|protection layers;labelling;evidence photos|Photos taken at packing show the item and box condition, which settles a later damage claim fairly for both sides.
Sort parcels without mix-ups|Sorting sends parcels to the correct route. Clear labels, scans and exception handling keep parcels from being lost.|Design a sorting flow for a fictional hub with scan in, destination check, bin allocation, scan out and a table for unreadable labels. Describe how a mis-sort is detected.|scan points;exception table;mis-sort detection|A parcel scanned into the wrong bin triggers an alert at manifest scan, so it is corrected before the vehicle leaves.
Plan a delivery route|A good route groups stops by area and time window, respects vehicle capacity and leaves time for problems.|Plan a fictional route of 30 parcels for one rider, grouping by locality, ordering stops, setting time windows and estimating total time with a 15 percent buffer.|grouped stops;time estimate;buffer|With a 6-hour driving and stopping estimate and a 15 percent buffer the plan allows about 7 hours, so the rider is not given a 9-hour route.
Handle a failed delivery attempt|A failed attempt costs money and annoys customers. Clear reasons, notifications and the next step reduce repeat failures.|Write the procedure for a fictional customer who is not available: contact attempt, reason code, notification, reattempt rule and return rule. Calculate the first-attempt success rate for 1,000 parcels and 850 delivered.|reason codes;reattempt rule;success rate|Delivered first time is 850 of 1,000, or 85 percent. The remaining 150 receive a message with a reattempt slot.
Process returns and reverse logistics|Returns need inspection, a decision and a record. A clear process protects the seller and the customer.|Create a returns process for a fictional online seller: request, pickup, inspection, decision, refund or restock, and record. Include handling of a parcel with a missing item.|steps defined;inspection rules;record kept|The returned parcel is opened on video, the missing item is noted, and the decision is recorded before any refund is made.
Set and measure service levels|A service level agreement defines what will be delivered and how it is measured. Missing targets should trigger action.|Write five service measures for a fictional city courier service, with targets, how each is measured and the action when missed.|measurable targets;measurement source;action trigger|Delivered within 24 hours for 95 percent of local parcels is measured weekly, and a drop below 90 percent triggers a review of routes.
Handle damage, loss and complaints|A claim process should be fair, quick and based on evidence. Customers need clear updates.|Plan how a fictional courier handles a damage claim: report, evidence, investigation, decision, communication and prevention. Include a response to an angry customer.|evidence list;timeline;prevention|The courier acknowledges the claim within a day, reviews packing photos and scan history, and tells the customer the decision date.
Deliver a courier operations plan|An operations plan joins booking, sorting, routing, tracking, service levels and claims into one routine that others can follow.|Package a fictional small courier operation: booking checklist, packing rules, sort flow, route plan, tracking messages, service levels, returns and claims procedures.|complete process;measures;exceptions|The plan shows a parcel from booking to delivery with a scan at every handover, so any customer query is answered from the tracking record.'''),

dict(id='inventory-warehouse',summary='Receive, store, count, pick and ship stock accurately: classification, order quantities, layouts, equipment, technology, safety and security.',icon='Cube',tool='data',tools=['data','board','budget','sheets'],
nodes=['Receive','Store','Pick','Count'],modules=['Stock basics','Control techniques','Warehouse operations','Systems & forecasting','Safety, security & delivery'],
src=dict(page='diploma-in-inventory-and-warehouse-management',code='DI&WM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to inventory and warehouse management','Inventory classification and control techniques','Warehouse operations and storage systems','Inventory systems and technology','Demand forecasting and supply chain integration','Safety, security and compliance']),
rows='''Receive goods against the order|Receiving checks that what arrived matches the purchase order and delivery note, in quantity and condition, before stock is booked in.|Write a goods receiving procedure and process a fictional delivery of 100 cartons where 4 are damaged and 6 are missing. State what is booked into stock and what is recorded as a claim.|three-way match;damage record;stock booked correctly|Only 90 sound cartons are booked in. The 4 damaged and 6 missing are noted on the delivery receipt and reported to the supplier the same day.
Classify stock by value with ABC|A few items often make most of the value. ABC classification focuses control where it matters.|Rank 10 fictional items by annual usage value, calculate cumulative percentages and assign classes A, B and C. State a different control rule for each class.|ranked values;cumulative percent;class rules|Two items together account for 70 percent of value and are class A, so they are counted monthly while class C items are counted yearly.
Calculate reorder level and safety stock|Reorder level triggers an order early enough to cover usage during delivery time. Safety stock covers variation.|A fictional item has daily use of 20, lead time of 6 days, and a worst case use of 28 per day for 6 days. Calculate the reorder level using safety stock.|lead-time demand;safety stock;reorder level|Average use during lead time is 120. Worst case is 168, so safety stock is 48 and the reorder level is 168.
Value stock using FIFO and average cost|The valuation method changes reported cost and profit. Consistency and records matter more than the choice itself.|For a fictional item, receive 100 units at 50 and 100 at 55, then issue 120. Calculate closing stock value by FIFO and weighted average and explain the difference.|FIFO value;average value;difference|FIFO leaves 80 units at 55, worth 4,400. Weighted average cost is 52.5, so 80 units are worth 4,200.
Measure turnover and days of stock|Turnover shows how many times stock is sold and replaced. Low turnover ties up cash and may signal slow items.|Using fictional cost of goods sold of 12,00,000 and average inventory of 2,00,000, calculate stock turnover and days of stock. Suggest two actions.|turnover;days of stock;actions|Turnover is 6 times a year, which is about 61 days of stock. Clearing slow items and reducing order sizes can lower it.
Design a layout and slotting plan|Fast-moving items should be easy to reach. A good layout reduces walking, errors and injuries.|Design a fictional small warehouse layout with receiving, storage, picking and dispatch zones. Slot 12 items by speed and weight and explain the picking path.|zones defined;slotting logic;path|Heavy items go on low shelves and the fastest-moving items sit at waist height near the dispatch area to shorten each pick.
Choose picking methods and measure accuracy|Picking can be by order, batch or zone. Accuracy matters because errors cost returns and trust.|Compare order, batch and zone picking for a fictional e-commerce store with 200 small orders a day. Choose one and define how pick accuracy is measured.|methods compared;choice;accuracy measure|Batch picking suits many small orders with overlapping items. Accuracy is measured as correct lines picked divided by total lines.
Run a cycle count and find the cause|Counting finds differences between records and shelves. Resolving the cause matters more than fixing the number.|Perform a fictional count of 20 items with 3 differences. Recount, check recent movements, find a likely cause for each and decide what to adjust and what to investigate.|recount;cause analysis;adjustment control|A difference of 10 units is traced to a delivery booked twice. The duplicate entry is reversed and the receiving check is strengthened.
Maintain safety and security|Warehouses involve lifting, vehicles and high-value goods. Rules, training and access control reduce harm and loss.|Write a one-page safety and security routine for a fictional warehouse: manual handling, forklift rules, fire exits, hazardous goods, key control, visitors and theft checks.|safe handling;access control;theft prevention|Only trained staff drive the forklift. Visitors wear passes and are escorted, and high-value stock is kept in a locked cage with a log.
Deliver a warehouse control pack|A control pack shows stock rules, counts and corrective actions so owners trust the numbers.|Package a fictional warehouse pack: receiving log, ABC list, reorder levels, valuation, turnover, layout, count results, safety checks and a corrective action list.|numbers consistent;counts reconciled;actions assigned|The pack reconciles the system quantity to the physical count after investigating differences, and shows two items moved to a faster-pick location.'''),

dict(id='cold-storage',summary='Manage temperature-controlled storage safely: cold chain principles, refrigeration basics, hygiene, monitoring, stock rotation, energy and emergency response.',icon='Shield',tool='board',tools=['board','budget','notebook'],
nodes=['Receive','Hold','Monitor','Respond'],modules=['Cold chain basics','Refrigeration & facilities','Hygiene & safety','Operations & supervision','Cold store management'],
src=dict(page='diploma-in-cold-storage-manager',code='DCSM/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to cold storage','Refrigeration techniques','Safety, hygiene and sanitation','Supervising workers','Maintaining infrastructure','Health and safety at cold storage premises']),
rows='''Explain why the cold chain must not break|Perishable products spoil faster when they warm. Every handover between storage, vehicle and shop must keep the right temperature.|For a fictional shipment of milk, vaccines and frozen fish, state the required storage ranges from the product labels given, and describe what happens to quality if each warms for two hours.|ranges stated from labels;handover risks;quality effect|Vaccines are normally kept between 2 and 8 degrees Celsius. Leaving them on a loading dock in the sun can reduce their effectiveness even if they look unchanged.
Receive a cold load and accept or reject it|Receiving checks temperature, packaging, dates and documents before cold goods enter the store. A failed check is a decision, not an inconvenience.|Write a receiving checklist for a fictional chilled delivery with probe temperature, vehicle condition, seals, expiry dates and paperwork. Decide whether to accept a pallet measured above the limit.|probe reading;accept or reject rule;record|A pallet measured above the product limit is rejected or held and reported to the quality manager rather than accepted to avoid a dispute.
Organise stock rotation with FEFO|First expired first out ensures products leave before they expire. Layout and labels must make the rule easy to follow.|Design a rotation system for a fictional cold store with 20 batches, expiry labels, a colour code and a daily check. Explain what to do with a batch within three days of expiry.|rotation rule;labelling;near-expiry action|Batches expiring soonest are placed at the front and marked with a red label, and the manager decides on discount or disposal for those near expiry.
Understand the main parts of a refrigeration system|A system moves heat out of the store using a compressor, condenser, expansion device and evaporator. Knowing the parts helps with reporting faults.|Draw in words the flow of refrigerant through a fictional cold room and describe what each of the four parts does. List three signs that suggest a fault.|four parts explained;flow order;fault signs|Ice build-up on the evaporator, a compressor that runs without stopping and a rising room temperature all suggest the system needs a technician.
Understand insulation and heat load|Heat enters through walls, doors, lights, people and warm products. Good insulation and discipline reduce the work the plant has to do.|List ten sources of heat gain for a fictional cold room and propose a practical control for each. Explain why an open door is costly.|ten sources;controls;door impact|Strip curtains and a closed door policy reduce warm air entering, which lowers energy use and keeps product temperature steady.
Monitor and record temperature|Continuous monitoring with alarms and a written log shows that product stayed safe. Records are evidence for regulators and customers.|Design a temperature monitoring plan for a fictional cold store: sensor locations, check times, alarm limits, who is called, and how data is kept. Include calibration.|sensor placement;alarm response;calibration|A sensor sits at the warmest point near the door and the alarm calls the duty supervisor if temperature stays above the limit for 15 minutes.
Apply hygiene and food safety controls|Clean premises, clean people and controlled processes reduce contamination. Hazard analysis identifies the points that must be controlled.|Create a hygiene routine and a simple hazard analysis for a fictional cold store handling raw and cooked foods, covering handwashing, cleaning, pests, separation and records.|hygiene routine;hazards identified;control points|Raw and cooked foods are stored on separate racks, with raw items below, so juices cannot drip onto food that will be eaten without cooking.
Protect workers in cold and confined areas|Cold stress, slippery floors and trapped workers are real risks. Protective clothing, buddy rules and emergency release prevent harm.|Write a worker safety plan for a fictional freezer room: clothing, time limits, breaks, floor safety, emergency door release, alarm and training.|protective clothing;time limits;emergency release|A worker in a freezer room must have a way to open the door from inside and a regular check by a colleague.
Respond to a power failure or temperature breach|Emergencies need a rehearsed plan: act, protect stock, decide on product safety and learn. Guessing leads to loss or unsafe products.|Write a response plan for a fictional four-hour power failure with steps for alerting, keeping doors shut, checking temperatures, deciding on stock and recording. Include who decides to discard stock.|ordered actions;stock decision;record|After power returns, products above their safe limit for too long are held for quality review and not released on assumption.
Deliver a cold storage management file|A management file brings together procedures, records, maintenance and training so audits and customers can see control.|Assemble a fictional cold store file with receiving checks, rotation rules, temperature logs, cleaning schedule, maintenance plan, emergency plan and a training record.|records consistent;maintenance planned;training evidence|The file shows a temperature excursion on one night, the alarm response, the stock decision and the repair that prevented it recurring.'''),

dict(id='export-import',summary='Learn how goods cross borders: registration, documents, Incoterms, customs, pricing, payment methods, finance, compliance and market entry.',icon='Briefcase',tool='budget',tools=['budget','sheets','notebook'],
nodes=['Register','Price','Ship','Get paid'],modules=['Trade basics & registration','Documents & terms','Shipping & customs','Finance & payment','Export/import plan'],
src=dict(page='advanced-diploma-in-export-import-management',code='ADEIM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to export-import management','Documentation and procedures','Foreign trade policy and regulatory framework','International marketing and market entry','Export finance and payment mechanisms','Import management and procedures']),
rows='''Decide if a product can be exported|Export depends on the product, destination rules and your ability to supply. Some goods need permits or are restricted.|For three fictional products, a spice blend, a cotton shirt and a medicine, list what you must check before export, such as permits, quality standards and destination rules, and state which needs the most care.|checks listed;restricted item;destination rules|A medicine needs strict licences and quality records in both countries, while a cotton shirt mainly needs labelling and destination customs rules.
Prepare to register as an exporter or importer|A business must hold the registrations required by law before it ships. Details must match across documents.|Prepare a fictional checklist of business and trade registrations for a new exporter, with the purpose of each and how a mismatch in names or addresses can delay a shipment. Confirm current rules with the official portal.|registrations listed;purpose;mismatch risk|The business name on the invoice must match the registration. A spelling difference can stop customs clearance until corrected.
Choose and apply Incoterms|Incoterms set who arranges and pays for transport, insurance and risk at each point. A vague term causes costly disputes.|For a fictional sale of machinery, compare ex works, free on board and cost insurance and freight. State who pays for each leg and where risk passes.|three terms compared;cost allocation;risk transfer|Under free on board, the seller loads the goods onto the ship and the risk passes to the buyer once they are loaded.
Build a landed cost and export price|The price must cover cost, packing, transport, charges and margin. Leaving out a charge reduces profit.|For a fictional product costing 500 per unit, add packing 20, inland transport 15, port charges 10, and a 10 percent margin to quote a price. Then add freight 80 and insurance 10 to show a cost and freight price.|cost build-up;margin;price per term|Cost to the port is 545, margin makes about 600 as the free-on-board price, and adding freight and insurance gives about 690.
Prepare a correct commercial invoice and packing list|Shipping documents must agree on description, quantity, weight and value. Customs and banks check them line by line.|Prepare a fictional commercial invoice and packing list for two items. Cross-check goods description, quantities, weights, value, terms and marks against each other and fix one planted mismatch.|documents agree;mismatch found;correction|The invoice shows 500 units but the packing list shows 480, so the shipment would be delayed until the correct quantity is confirmed and both are corrected.
Classify goods and estimate duty|A product code decides the rate of duty and the rules that apply. The wrong code can mean the wrong duty or penalty.|Use the code and rates given in the case to compute import duty and tax for a fictional shipment worth 5,00,000. Explain why you check the product description against the code.|rate applied;duty total;classification check|With a duty rate of 10 percent stated in the case, duty is 50,000. A different code with a different rate would change the cost and risk a penalty.
Compare payment methods by risk|Payment terms shift risk between buyer and seller. The safest for the seller is advance payment and the riskiest is open account.|Rank advance payment, letter of credit, documentary collection and open account by seller risk and buyer risk. Choose terms for a new buyer in a fictional country with unknown credit.|ranking;choice;reason|For an unknown buyer, a letter of credit or advance payment protects the seller, while open account gives the buyer the most time but the seller the most risk.
Understand a letter of credit and avoid discrepancies|A bank pays under a letter of credit only if documents match its terms exactly. A small mismatch can cause refusal or delay.|Given a fictional credit asking for 500 units of Blue Shirt, review five documents and find three discrepancies, such as a different description and a late shipment date. State what the seller does next.|discrepancies found;effect;action|The invoice says Navy Shirt but the credit says Blue Shirt. The seller asks the buyer to amend the credit or corrects the document before presenting it.
Manage currency and finance risk|Exporters face exchange rate changes and need finance before payment arrives. Both can be planned.|A fictional exporter will receive 40,000 dollars in 90 days and needs working capital now. Describe how the currency risk could be fixed and how pre-shipment finance might help, with costs and limits.|currency exposure;hedge option;finance option|The exporter agrees a forward rate to know the rupee amount, and uses short-term finance against the order to buy materials.
Deliver an export or import plan|A plan shows the market, product, price, documents, shipment, payment, risks and compliance steps needed to make a first shipment.|Package a fictional first-export plan: product and market, registrations, price by Incoterm, documents, shipping route, payment terms, risks, compliance checks and a dummy shipment file.|price to documents link;payment risk handled;compliance steps|The dummy file contains a consistent invoice, packing list, certificate of origin draft and shipping instructions that all show the same quantities and values.'''),

dict(id='retail-vehicle-sales',summary='Run retail and sales operations: store layout, merchandising, buying, pricing, stock, customer service, e-commerce and honest pre-owned vehicle sales.',icon='Cart',tool='budget',tools=['budget','data','notebook','sheets'],
nodes=['Buy','Display','Sell','Review'],modules=['Retail basics','Merchandise & margin','Store operations','Digital & vehicle sales','Retail plan'],
src=dict(page='advanced-diploma-in-retail-management',code='ADRM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Fundamentals of retailing','Retail consumer behaviour and CRM','Retail marketing and visual merchandising','Merchandise planning and buying','Store operations and supply chain','Digital retailing and leadership']),
rows='''Choose a store location with evidence|Location decides customers and costs. Footfall, rent, competition and access should be compared, not guessed.|Compare three fictional locations for a stationery shop on footfall, rent, nearby competitors and access. Score each and recommend one, stating what you counted and when.|criteria scored;evidence collected;choice|A location with lower rent but little footfall loses to a busier one if the shop depends on walk-in customers.
Understand how shoppers decide|Customers move from need to search, comparison, purchase and after-sale feelings. Retail actions should help at each step.|Describe how a fictional customer buys a pair of shoes, noting two points where the shop can help the decision and one where it can lose the sale.|steps described;helpful actions;lost-sale point|Allowing the customer to try sizes quickly helps the decision. A confusing price tag at the shelf can lose the sale.
Calculate margin and markup correctly|Markup is a percentage of cost and margin is a percentage of the selling price. Mixing them leads to wrong prices.|A fictional item costs 60 and sells at 100. Calculate markup and margin, and the price needed for a 40 percent margin on a cost of 90. Explain the common mix-up.|markup;margin;price for target margin|Markup is 66.7 percent of cost while margin is 40 percent of price. A 40 percent margin on cost 90 needs a price of 150.
Plan open-to-buy for a season|Open-to-buy shows how much stock can still be bought without overstocking. It links sales plans to purchases.|Using fictional planned sales of 6,00,000, planned closing stock of 2,00,000, opening stock of 1,50,000 and 1,00,000 on order, calculate the open-to-buy at retail value.|formula used;result;caution|Required stock is sales plus closing stock less opening stock, which is 6,50,000. Less 1,00,000 on order leaves 5,50,000 still to buy.
Create a display that sells|Visual merchandising uses layout, lighting and grouping to guide attention. A display should be clean, easy to shop and honest about price.|Plan a fictional festival display with a focal point, product groups, signage and price tickets. Describe how you will refresh it and how you will judge whether it worked.|focal point;grouping;evaluation|A table of gift sets at the entrance with clear price signs is checked by counting how many sets are sold per day before and after the display.
Prevent stock loss and handle returns|Stock is lost through theft, error and damage. Controls and clear return rules protect profit without upsetting honest customers.|Create a loss-prevention routine and a returns policy for a fictional store, covering counts, receipts, tags, cash handling and what to do when a customer returns an item without a receipt.|controls described;returns policy;fair treatment|Items without a receipt may be exchanged for store credit after checking the system, so honest customers are served without opening the shop to fraud.
Run a daily sales and cash close|A daily close balances sales records with cash and cards so mistakes are caught the same day.|For a fictional shop, reconcile a day's sales of 48,500 against cash 22,000, cards 24,000 and UPI 2,000. Find the difference and describe how you would investigate it.|totals compared;difference found;investigation|Cash plus card plus UPI is 48,000, which is 500 less than the sales record. The cashier checks voided bills and refunds before reporting the shortage.
Sell online and across channels|Omnichannel retail lets customers browse in one place and buy or collect in another. Stock must be accurate across channels.|Plan how a fictional shop adds online ordering with store pickup: product list, stock sync rule, packing, pickup process and a rule when an item is out of stock.|stock sync;pickup process;out-of-stock rule|If an item sells in store, the online listing drops the quantity at once so the shop does not sell the last unit twice.
Sell pre-owned vehicles honestly|A used vehicle sale depends on a clear inspection, correct papers and truthful statements. Hiding faults or odometer changes harms buyers and is unlawful.|Create a fictional pre-owned vehicle checklist with inspection, documents, ownership transfer, pricing basis and an honest description. State what you do if a car shows signs of flood or accident damage.|inspection done;documents verified;honest disclosure|A car with signs of previous flood damage is disclosed or declined, never sold as perfect, because the buyer's safety and the shop's reputation are at stake.
Deliver a retail operating plan|A plan combines location, range, price, display, stock, staffing, cash control and a sales target so others can run and review the store.|Package a fictional store plan: customer profile, range and margin targets, open-to-buy, display plan, staffing roster, daily close process, loss controls and monthly review measures.|numbers consistent;controls included;review measures|The plan sets a 38 percent margin target, checks it weekly against actual sales, and shows how a markdown on slow items protects cash.'''),

dict(id='healthcare-administration',summary='Support healthcare organisations: patient flow, records and privacy, front desk, billing and insurance, quality and infection control, hospital operations and strategy.',icon='Shield',tool='board',tools=['board','notebook','sheets'],
nodes=['Register','Coordinate','Bill','Improve'],modules=['Patient access & front desk','Records & privacy','Operations & quality','Finance, staffing & strategy','Hospital administration plan'],
src=dict(page='diploma-in-strategic-management-for-hospital',code='DSMH/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to hospital strategic management','Hospital operations and administration','Healthcare marketing and branding','Financial management in hospitals','HR management in healthcare','Quality management and accreditation']),
rows='''Register a patient accurately and kindly|Correct identity and contact details link a patient to the right record. Errors can lead to the wrong results reaching the wrong person.|Write a fictional front desk registration process with identity checks, duplicate search, consent forms, emergency contact and handling of a patient who cannot give details.|identity check;duplicate search;consent|Searching by name and date of birth before creating a record prevents two files for the same patient, which could split their medical history.
Triage and direct patient flow|Triage decides who needs care first. Front desk staff direct patients using clear rules and escalate danger signs to clinical staff.|Create a simple fictional queue and escalation guide for a clinic reception, with red-flag signs that require immediate clinical attention and a calm script for waiting patients.|escalation signs;queue rule;communication|A patient reporting chest pain or difficulty breathing is brought to a nurse immediately, regardless of their place in the queue.
Keep health records accurate and confidential|Health information is highly sensitive. Records must be accurate, accessible to authorised staff only and stored safely.|Design a fictional records policy covering who may see records, how they are corrected, retention, release to patients and sharing with insurers. State how a breach is reported.|access rules;correction process;breach report|Staff view only the records needed for their work. A record corrected after an error shows who changed it, when, and why.
Schedule appointments and reduce waiting|Good scheduling matches doctor time to demand, with buffers for delays and room for urgent cases.|Plan a fictional doctor's morning clinic of four hours with consultation lengths, buffers, urgent slots and a no-show approach. Calculate how many patients fit.|slot plan;urgent capacity;no-show handling|With 15-minute consultations, 15 minutes of buffer per hour and 2 reserved urgent slots, the clinic has 12 fifteen-minute slots in four hours, 10 for booked patients and 2 held for urgent cases.
Calculate occupancy and length of stay|Occupancy and length of stay show how beds are used. They guide staffing and admissions but do not measure quality of care.|A fictional ward has 30 beds and averaged 22 occupied beds over a 30-day month. Calculate bed occupancy rate and describe what a very high rate could mean for patient safety.|occupancy calculated;interpretation;caution|22 divided by 30 is 73.3 percent. A sustained rate above the ward's planned range can reduce capacity for emergencies and raise infection risk.
Bill accurately and process insurance claims|Billing links services delivered to charges and payers. Incomplete or inaccurate documents cause claim rejection and delay.|Prepare a fictional bill for a day-care procedure and a claim checklist with authorisation, discharge summary, itemised bill and policy details. Explain a rejection and your response.|itemised bill;claim documents;rejection response|A claim is rejected because the discharge summary lacks the diagnosis. The administrator requests the corrected summary and resubmits within the insurer's time limit.
Apply infection control routines|Simple routines such as hand hygiene, cleaning, waste segregation and isolation protect patients and staff. Administration makes these routines easy to follow.|Create a fictional infection control checklist for an outpatient department covering hand hygiene stations, cleaning schedule, waste bins, masks, sharps and a reporting step. Measure compliance.|routine defined;waste segregation;compliance measure|A weekly audit counts how many staff are seen cleaning hands between patients, which makes the habit visible and improves it.
Use quality indicators and prepare for accreditation|Quality indicators track safety and service. Accreditation checks that standards and records exist and are followed.|Define six quality indicators for a fictional small hospital, such as medication errors and patient waiting time, with data source, target and review frequency. List documents an assessor would ask for.|six indicators;data source;documents|Waiting time for outpatient registration is recorded daily with a target of 15 minutes, and the review meeting looks at the weekly average and the longest wait.
Communicate and market a hospital ethically|Healthcare marketing must be honest and respectful. It should inform patients, not exaggerate results or promise cures.|Review five fictional hospital advertisements and rewrite any that promise outcomes or compare unfairly. Add a referral process and a crisis communication step for a service incident.|claims reviewed;honest rewrite;crisis step|The line best doctors guarantee cure is replaced by a factual description of services and qualifications, with no guarantee of results.
Deliver a hospital administration plan|An administration plan brings flow, records, billing, quality, staffing and communication together with owners and measures.|Package a fictional small hospital administration plan: front desk process, records policy, scheduling model, billing workflow, infection control audit, six indicators, staffing outline and a 90-day improvement target.|owners and measures;patient safety covered;improvement target|The plan targets cutting outpatient registration waiting time from 25 to 15 minutes within 90 days by adding a second desk at peak hours.'''),
]
