COURSES=[
dict(id='human-resource-management',summary='Plan, hire, onboard, appraise, pay and support people fairly: job analysis, recruitment, performance, pay, employee relations, law and HR audit.',icon='People',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Plan','Hire','Develop','Comply'],modules=['People planning & hiring','Onboarding & performance','Pay & engagement','Relations & workplace law','HR operations & audit'],
src=dict(page='diploma-in-human-resource-management',code='DHRM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Principles of HRM and organisational behaviour','Talent acquisition and employee relations','Performance management and training','Compensation, motivation and engagement','Labour laws and workplace diversity','Strategic HRM, wellbeing and HR audit']),
rows='''Write a job description from a job analysis|A job analysis records what the work involves and what a person needs to do it. A clear description attracts suitable candidates and sets fair expectations.|For a fictional shop supervisor role, write a job description with purpose, five duties, required skills, reporting line and measures of success. Mark which requirements are essential and which are desirable.|clear duties;essential versus desirable;success measures|A requirement of ability to count cash and reconcile daily takings is essential. Experience with a particular software is desirable because it can be taught.
Plan how many people the business needs|Workforce planning compares the work expected with the people available, so hiring follows demand rather than panic.|A fictional call centre expects 1,200 calls a day and each agent handles 60 calls a day. Calculate the agents needed, allow 15 percent for leave and absence, and state the assumption you would revisit.|demand estimate;absence allowance;assumption noted|1,200 calls at 60 per agent needs 20 agents. Adding 15 percent for absence gives 23 agents, rounded up from 23.
Screen candidates fairly and consistently|Fair selection compares every candidate against the same job-related criteria. Personal bias and irrelevant details should not decide.|Build a scoring grid for a fictional receptionist role with five criteria, a rating scale and rules for ties. Explain which questions you must not ask and why.|job-related criteria;same scale for all;questions avoided|Asking about marital status or religion is not related to the job and risks discrimination, so interviewers use only the scored criteria.
Run a structured interview|A structured interview asks every candidate the same questions and scores answers against agreed examples. It predicts performance better than a casual chat.|Write six interview questions for a fictional sales executive with a good, average and weak answer example for two of them. Include a closing question that candidates can ask you.|consistent questions;scored examples;candidate questions|Tell me about a time you lost a customer and what you changed. A good answer names the cause, an action and a result.
Design a first-week onboarding plan|The first days shape whether a new employee stays. A plan covers paperwork, access, introductions, training and early feedback.|Create a five-day onboarding plan for a fictional accounts assistant with documents, equipment, people to meet, training and a check-in on day five. Name who is responsible for each step.|day-by-day plan;owners named;day-five check|On day one the manager walks through the work and the buddy shows the systems. On day five a short check asks what is unclear.
Set goals and measures for performance|A good goal states the result, the measure and the date. Performance measures should be within the employee's control.|Write four goals for a fictional customer support agent with measures and dates. Replace one vague goal such as be better with a measurable version, and explain how you would review progress.|specific goals;measures and dates;review method|Resolve 85 percent of email queries within 24 hours by the end of the quarter is measurable. Improve customer happiness is not.
Give an appraisal conversation that works|An appraisal talks about evidence, strengths and next steps. The employee should leave knowing where they stand and what happens next.|Prepare notes for a fictional 30-minute appraisal: opening, three evidence-based points, one development goal and agreed actions. Include a reply to an employee who disagrees with the rating.|evidence used;development goal;calm response|If the employee disagrees, the manager asks for their evidence, notes it, and agrees a date to review it, without arguing during the meeting.
Build a pay structure and calculate net pay|A pay structure splits total pay into parts. Deductions required by law are taken from gross pay, and the rates must come from current official rules.|For a fictional employee with a monthly gross pay of 30,000 made of basic, allowance and bonus, calculate net pay using the deduction rates and limits stated in the case. List where you would verify current rates.|pay components;deductions applied;rate source|The case states a provident deduction of 12 percent of basic pay. Net pay is gross less that deduction and any tax deducted at source stated in the case.
Handle a grievance and a workplace harassment complaint|Complaints must be taken seriously, handled promptly and kept confidential. Law requires an appropriate committee for harassment complaints in many workplaces.|Write the steps for a fictional employee complaint, including recording it, informing the right committee, protecting the complainant from retaliation and keeping records. State that the current law should be checked.|confidential recording;correct route;no retaliation|The manager does not investigate alone. The complaint goes to the committee set up under the workplace harassment law and the complainant is told the process.
Run an HR audit and compliance review|An audit checks records against policy and law, finds gaps, ranks risk and assigns owners to fix them.|Audit a fictional small company with ten employees using a 12-point checklist covering contracts, attendance, pay records, leave, deductions, policies and training. Report three gaps and a corrective plan.|checklist applied;gaps ranked;corrective plan|The audit finds three employees without signed contracts. The corrective plan names who prepares the contracts and the date they must be signed.'''),

dict(id='sales-marketing-management',summary='Plan and run sales and marketing: segmentation, research, the marketing mix, pricing, pipeline, forecasting, B2B selling and honest promotion.',icon='Cart',tool='notebook',tools=['notebook','budget','sheets'],
nodes=['Research','Position','Sell','Measure'],modules=['Markets & customers','Marketing mix & pricing','Selling & pipeline','Digital & B2B growth','Go-to-market delivery'],
src=dict(page='advanced-diploma-in-sales-and-marketing-management',code='ADSMM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Fundamentals of sales and marketing','Market research and consumer insights','Sales planning and management','Marketing strategies and brand management','Digital marketing and e-commerce','Business development and B2B sales']),
rows='''Segment a market and choose a target|A market is made of different groups with different needs. Choosing a clear target lets a business serve one group well instead of everyone poorly.|For a fictional neighbourhood bakery, describe three customer segments by need and behaviour, score them on size and fit, and choose one target with a reason.|segments by need;scoring;target chosen|Office workers who want a quick breakfast score highest because they buy daily within a short walking distance, so the bakery targets them first.
Design a short customer survey|Good questions are neutral and answerable. Leading or double questions give results that look clear but mean nothing.|Write eight survey questions for a fictional tea stall, fix two flawed questions you are given, and state the sample you would ask and how you would avoid bias.|neutral wording;sample plan;flawed questions fixed|Do you agree our excellent tea is good value? leads the answer. Rewrite it as How would you rate the value of the tea?
Build a marketing mix for one product|Product, price, place and promotion must support each other. A premium product with a bargain-shop display sends a mixed message.|Describe a fictional packaged snack using the four marketing mix elements for a defined student customer. Show one consistency check between price and place.|four elements;customer defined;consistency check|A low price and sale at campus shops fit a student buyer. Selling the same snack in an expensive hotel shop would not.
Set a price and test it|A price should cover cost, reflect value and fit the market. Testing shows what customers actually accept.|A fictional item costs 40 to make. Calculate the selling price for a 30 percent margin on the price, compare with two competitors at 60 and 75, and design a small price test.|margin calculation;competitor comparison;test design|A 30 percent margin on price means price = cost divided by 0.7, which is about 57. This sits just under the cheaper competitor.
Forecast sales and plan the funnel|A sales forecast works backwards from a target through the stages of the funnel. Each stage has a conversion rate.|A fictional team needs 12 sales this month. With 20 percent of proposals won and 40 percent of leads reaching proposal, calculate leads needed and a weekly activity target.|funnel arithmetic;weekly target;assumptions|12 sales at 20 percent need 60 proposals, and at 40 percent that needs 150 leads, or about 38 leads a week.
Prepare for a sales negotiation|A negotiation is planned by knowing your goals, limits and alternatives. Giving a discount without getting something is a loss.|Prepare a negotiation for a fictional supplier contract: target price, walk-away point, alternatives, three trades you can offer and your opening statement.|target and limit;alternative;trade offers|If the buyer asks for 10 percent off, the seller offers it only in exchange for a larger order or faster payment.
Keep a pipeline clean and honest|A pipeline lists opportunities by stage. If stages are inflated, the forecast is wrong and managers make poor decisions.|Review a fictional pipeline of 12 opportunities, define clear entry rules for each stage and remove or move three stale ones with a reason. Recalculate the forecast.|stage rules;stale items handled;forecast corrected|A deal in Proposal Sent with no reply for 60 days moves back to Follow-up, which reduces the forecast but makes it believable.
Respond to a business proposal request|A proposal answers the buyer's stated needs, not the seller's preferences. Evidence, scope and price should be easy to compare.|Write the outline of a response to a fictional request from a school for stationery supply, including needs summary, offer, price table, delivery terms, references and assumptions.|needs mirrored;price table;assumptions stated|The response quotes per-item prices, a delivery schedule and a clear statement that prices are valid for 30 days.
Promote ethically and avoid misleading claims|Marketing must be truthful. Exaggeration, hidden charges and fake reviews damage trust and can break advertising standards.|Review six fictional promotional claims for a skin product and mark any that are misleading. Rewrite them honestly and say what proof you would hold.|claims reviewed;honest rewrites;proof listed|Fairness guaranteed in seven days is replaced by a statement of the ingredient and its tested effect, with no promise about results.
Deliver a go-to-market plan|A plan joins customer, offer, price, channels, sales targets, budget and measures into one logic that can be tested.|Package a fictional product launch plan for a local service: target segment, positioning, price, channels, 90-day sales target, budget, risks and three measures with review dates.|logic connects;targets measurable;risks included|The plan targets 40 bookings in 90 days, spends 15,000 on local ads, and tracks cost per booking weekly with a stop rule if it exceeds the target.'''),

dict(id='brand-product-management',summary='Understand customers, shape products and brands: insight, positioning, identity, development, launch, pricing perception and measurement.',icon='Pen',tool='notebook',tools=['notebook','canva','sheets'],
nodes=['Insight','Position','Build','Launch'],modules=['Product & customer insight','Positioning & identity','Product development','Launch & growth','Brand measurement'],
src=dict(page='diploma-in-product-and-brand-management',code='DPBM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Fundamentals of product and brand management','Market research and consumer insights','Product development and innovation','Brand strategy and positioning','Marketing strategies for growth','Advertising and promotion strategies']),
rows='''Place a product on its life cycle|Products move through introduction, growth, maturity and decline. The right action depends on the stage.|For three fictional products, place each on the life cycle with evidence from sales and competitors, and suggest one action suited to its stage.|stage identified;evidence;stage-appropriate action|A product whose sales growth is slowing and prices are falling is mature, so the action is to improve efficiency and loyalty rather than spend heavily to attract new buyers.
Interview customers to find a real need|A customer interview asks about past behaviour and problems, not opinions about your idea. It uncovers the job the customer wants done.|Write an interview guide of eight open questions for a fictional lunchbox brand and an observation sheet. Explain why you do not pitch your idea during the interview.|open questions;past behaviour;no pitching|Instead of asking Would you buy a smart lunchbox, ask When did you last forget or spill your lunch, and what did you do?
Write a positioning statement|A positioning statement says who the product is for, what it is, the key benefit and why it is believable. It guides every other choice.|Write a one-sentence positioning statement for a fictional herbal tea and a reason to believe, then test it with three imagined customers and record the likely doubt.|target and benefit;reason to believe;doubt recorded|For tired office workers, Calm Leaf is a caffeine-free evening tea that helps you unwind, made from three single-origin herbs.
Define a brand identity and tone|A brand identity includes the name, look, voice and values. Consistency makes a brand recognisable and trusted.|For a fictional organic oil brand, define its promise, three personality words, colour and tone rules, one example of on-brand copy and one of off-brand copy.|promise;consistent tone;examples|On-brand copy is warm and plain: Pressed this week from seeds grown nearby. Off-brand copy is shouting words such as Mega Super Sale.
Move an idea through stages of development|Product development reduces risk by testing the idea early with small, cheap steps before large investment.|Plan stages for a fictional new snack: idea screen, concept test, prototype, small trial and launch decision. Define the pass criterion and the cost at each stage.|stage gates;pass criteria;cost discipline|After a taste test, the snack must score at least 4 out of 5 from 40 tasters before any money is spent on packaging.
Check name, packaging and claims|Names and packs must be understandable, distinct and legally safe. Claims on a pack must be true and supported.|Evaluate three fictional product names on clarity, memorability and possible meaning problems. Review a draft pack front for claims that need proof.|name criteria;claims checked;risks noted|A name that sounds like a competitor can cause confusion. A pack saying 100 percent natural needs a clear basis for the claim.
Set price in line with brand value|Price tells customers what to expect. A price that is too low can damage a premium brand, while a price too high for the value invites rejection.|For a fictional premium notebook, compare cost-based pricing with value-based pricing against two competitors, recommend a price and state what proof of quality supports it.|methods compared;price reasoned;quality proof|If the notebook paper is clearly better and lasts longer, a price above the average is supported by a visible sample and customer proof.
Plan a launch and its first 90 days|A launch plan sets goals, timing, channels and a way to learn. Early data shows what to change.|Create a 90-day launch plan for a fictional product with pre-launch, launch week and review checkpoints, measures and a decision rule for continuing or adjusting.|timeline;measures;decision rule|If repeat purchases are below 20 percent after 60 days, the team reviews the product and the price before spending more on promotion.
Measure brand health|Brand health combines awareness, perception and behaviour. A single sales number does not explain why customers choose a brand.|Design a fictional quarterly brand check with five measures such as awareness, consideration, preference, repeat purchase and recommendation, and a method for collecting each.|five measures;collection method;interpretation|Awareness may be high while consideration is low, which suggests people know the brand but do not trust or want it.
Deliver a brand and product plan|A brand and product plan connects customer insight, positioning, product, price, communication and measures in one consistent story.|Package a fictional product and brand plan: insight summary, positioning, identity guide, product roadmap, price logic, launch plan and brand health measures with owners.|insight to positioning;consistent identity;measured plan|The plan shows the customer insight about forgotten lunches linking directly to the leak-proof design, the price and the message on the pack.'''),

dict(id='business-strategy',summary='Analyse a business and its environment, choose a strategy, set measures, manage operations, risk, governance and change, including cooperative organisations.',icon='Briefcase',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Analyse','Choose','Align','Review'],modules=['Environment & competition','Strategy & business model','Operations & quality','Governance & cooperatives','Strategic plan'],
src=dict(page='advanced-certification-in-corporate-management-operations',code='ACCMO/Q1001',duration='Three Months',eligibility='10+2 or equivalent',modules=['Principles and practices of management','Human resources and organisational behaviour','Operations and supply chain management','Business strategy and entrepreneurship','IT and business analytics','Leadership and corporate governance']),
rows='''Scan the external environment|A business is affected by politics, economy, society, technology, law and environment. A scan separates what it can influence from what it must adapt to.|Complete a PESTLE scan for a fictional rural cold-drink shop, rank the three most important factors and say how each changes decisions.|factors ranked;impact stated;response|A rise in electricity tariffs is an economic factor the shop cannot control, so it plans a more energy-efficient cooler and fewer hours at low-demand times.
Assess competition with five forces|Profit depends on competitor rivalry, new entrants, substitutes, and the power of buyers and suppliers. Each force can be strong or weak.|Analyse the five forces for a fictional local tuition centre and state which force matters most and one action that reduces its effect.|five forces rated;main pressure;action|If many free online lessons are available, the substitutes force is strong, so the centre competes on personal attention and exam results.
Find strengths and weaknesses honestly|A SWOT lists internal strengths and weaknesses and external opportunities and threats. It is useful only when each item is backed by evidence.|Write a SWOT for a fictional tailoring business with at least one evidence point for each item. Turn two items into strategic options.|evidence for items;options created;no vague items|A strength is that 60 percent of orders are repeat customers. An option is a loyalty offer that uses this strength for a new service.
Describe a business model on one page|A business model shows who the customers are, what value is offered, how it is delivered and how money is made. Weak links show up when written plainly.|Complete a business model canvas for a fictional mobile laundry service and mark the assumption you are least sure about and how you would test it.|key blocks completed;riskiest assumption;test method|The riskiest assumption is that offices will pay a delivery fee, so the owner tests with ten offices for two weeks before buying a van.
Turn strategy into measures|A strategy is clear when it has a few measures across finance, customers, processes and learning. Measures must be owned and reviewed.|Create a balanced scorecard with two measures in each of four perspectives for a fictional bakery, with targets, owners and review dates.|four perspectives;targets;owners|On-time order delivery of 95 percent is a customer measure owned by the dispatch lead and reviewed weekly.
Map a process and remove waste|A process map shows each step, handover and delay. Waste, such as waiting or repeated checking, becomes visible.|Map a fictional order-to-delivery process with at least eight steps, mark waiting and rework, and propose two improvements with an expected saving.|steps mapped;waste identified;improvements|Orders wait for one person to approve. Allowing small orders to proceed without approval removes a two-hour delay for most customers.
Maintain a risk register|A risk register lists what could go wrong, how likely and how serious it is, who owns it and what is being done.|Create a register of eight risks for a fictional small manufacturer with likelihood, impact, owner and response. Highlight the top two.|likelihood and impact;owner;response|A single supplier for a key part is a high risk. The response is to qualify a second supplier and keep a month of stock.
Apply cooperative principles|A cooperative is owned and controlled by its members. Each member usually has an equal vote and surplus is shared by use or reinvested.|Describe how a fictional dairy cooperative handles membership, voting, surplus, member education and election of the committee, and name one risk to good governance.|member control;surplus use;governance risk|Each member has one vote regardless of milk supplied. The risk is a few large members dominating meetings, which the bylaws address with attendance rules.
Lead a change without losing people|People accept change when they understand why, see their role and get support. Resistance is information, not only an obstacle.|Plan a fictional change of switching a shop to a new billing system: reasons, stakeholders, training, a pilot, feedback loop and a way to deal with resistance.|reasons explained;pilot;feedback loop|One counter runs the new system for a week while others use the old one, so problems are found before everyone switches.
Deliver a strategic plan|A strategic plan states the situation, choices, actions, measures and review dates. It can be understood and challenged by others.|Package a fictional one-year strategy for a small business: analysis summary, strategic choices, action plan, scorecard, risks, governance and review cycle.|analysis to action;measures;review dates|The plan commits to two priorities rather than six and states what the business will stop doing to free time for them.'''),

dict(id='project-quality-management',summary='Plan, schedule, budget, control and close projects, and improve processes with quality tools and Six Sigma thinking.',icon='Workflow',tool='board',tools=['board','budget','sheets'],
nodes=['Define','Plan','Control','Close'],modules=['Initiation & scope','Schedule & cost','Quality tools','Risk, people & communication','Project delivery'],
src=dict(page='diploma-in-project-management',code='CPM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Project initiation and governance','Scope management and work breakdown','Scheduling and network analysis','Cost estimation, budgeting and earned value','Quality, resources and communication','Risk, procurement and closure']),
rows='''Write a project charter|A charter states why the project exists, what it must achieve, its limits, who sponsors it and who decides. It is the shared agreement.|Write a one-page charter for a fictional school library renovation with objectives, scope in and out, budget, deadline, sponsor and main risks.|objectives measurable;scope boundaries;sponsor and risks|In scope are new shelves and lighting. Out of scope is replacing books, so the budget and date cannot be silently stretched.
Identify stakeholders and plan engagement|Stakeholders are people affected by or able to affect the project. Different groups need different engagement.|List eight stakeholders for a fictional community hall project, rate influence and interest, and plan how to involve the top three.|stakeholders rated;engagement plan;owner|The nearby residents have high interest and some influence, so a short meeting before work begins prevents noise complaints later.
Break the work into a work breakdown structure|A work breakdown structure divides the project into deliverables and work packages small enough to estimate and assign.|Create a three-level work breakdown structure for a fictional wedding hall decoration project with at least 12 work packages and one owner per package.|three levels;work packages;owners|Under Stage design, packages include flower order, lighting rig and backdrop construction, each with one responsible person and a due date.
Estimate duration and find the critical path|The critical path is the longest chain of dependent tasks. Delays on it delay the project, while other tasks have float.|For a fictional project with tasks A 3 days, B 4 days after A, C 6 days after A and D 2 days after B and C, calculate the critical path, project length and float on B.|dependencies drawn;critical path;float calculated|Path A-C-D is 11 days and A-B-D is 9 days. The project takes 11 days and task B has 2 days of float.
Use three-point estimates|A single estimate hides uncertainty. A three-point estimate uses optimistic, likely and pessimistic values.|A fictional task has estimates of 4, 6 and 14 days. Calculate the weighted expected duration, explain why it is higher than the likely value and say how you would use it in the plan.|formula applied;skew explained;planning use|The weighted estimate is 4 plus 4 times 6 plus 14, divided by 6, which is 7 days. The long tail of what could go wrong raises it above 6.
Track cost and schedule with earned value|Earned value compares work done with work planned and money spent. It shows early whether a project is behind or over budget.|A fictional project has a planned value of 100, earned value of 80 and actual cost of 90. Calculate cost and schedule variance and indices, and forecast completion if the budget is 500.|variances;performance indices;forecast|Cost variance is minus 10 and schedule variance minus 20. The cost index is 0.89, so the forecast at completion is about 562 if performance continues.
Apply quality tools to a problem|Quality tools turn a complaint into causes and actions. Counting problems first shows where effort will matter most.|Use a fictional list of 100 defects in a printing job. Build a Pareto table, find the top two causes and draw a cause-and-effect list for the largest.|Pareto table;top causes;cause list|Misaligned pages cause 45 of 100 defects and smudges 25, so the first two causes account for 70 percent and receive attention first.
Measure defects with DMAIC thinking|DMAIC stands for define, measure, analyse, improve and control. It gives an improvement project a disciplined order and a baseline.|A fictional factory finds 15 defects in 500 units with 4 chances per unit. Calculate defects per million opportunities and outline a DMAIC plan to halve them.|DPMO calculated;five phases;control method|15 defects over 2,000 opportunities is 0.75 percent, which is 7,500 defects per million. Control uses a daily check chart so the gain stays.
Manage risks, communication and a change request|A project stays healthy when risks are tracked, status is shared and changes are decided deliberately.|Create a fictional risk log of six items, a communication plan for three audiences and a change request form. Process a request to add a feature midway through.|risk log;communication plan;change decision|A request to add a second room is assessed for time and cost, and approved only by the sponsor, with the baseline updated.
Deliver and close a project|Closing confirms what was delivered, hands it over, settles accounts and records lessons for the next project.|Package a fictional project closure: deliverables accepted, final budget compared with plan, open issues, handover notes and a lessons-learned review with three actions.|acceptance recorded;budget compared;lessons actioned|The closure shows the project finished 4 percent over budget, explains the cause, and turns the lesson into a checklist for the next project.'''),

dict(id='entrepreneurship',summary='Find a real problem, test a business idea cheaply, model unit economics and cash, choose a structure, understand funding and pitch with evidence.',icon='Spark',tool='budget',tools=['budget','notebook','sheets','canva'],
nodes=['Discover','Test','Model','Pitch'],modules=['Opportunity & customers','Validation','Money & cash','Structure & funding','Business plan & pitch'],
src=dict(page='advanced-diploma-in-entrepreneurship-development',code='ADED/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to entrepreneurship','Idea generation and innovation','Business planning and feasibility','Financial management for entrepreneurs','Marketing and sales strategies','Business operations and management']),
rows='''Find a problem worth solving|A good business starts with a problem people already feel and pay to solve. Interesting ideas without a clear customer often fail.|List five fictional problems seen in a local market, rate each on frequency, pain and willingness to pay, and choose one to investigate with reasons.|problems scored;evidence used;choice reasoned|Daily lunch delivery for small offices scores high on frequency and pain, and customers already pay delivery apps for similar convenience.
Screen business ideas with a scorecard|A scorecard compares ideas against the same criteria so a favourite does not win by default.|Score three fictional ideas on market size, skills, startup cost, competition and speed to first sale. Weight the criteria and recommend one with the first test to run.|weighted criteria;comparison;first test|The idea with the lowest startup cost and fastest first sale wins even if the market is smaller, because it can be tested in a month.
Describe the customer, value and revenue on one page|A business model canvas shows how the idea creates, delivers and captures value in a few lines, so gaps are obvious.|Complete a business model canvas for a fictional home tiffin service and mark the three weakest assumptions.|blocks completed;weak assumptions;next evidence|The weakest assumption is that 30 homes will subscribe within a month, so a pre-order list is the first test.
Run a cheap validation test|A validation test checks whether customers act, such as pay or pre-order, rather than only saying they like the idea.|Design a fictional two-week test for a new service with the action you want, the number needed to count it a success and what you will do if it fails.|real customer action;success threshold;failure plan|If 20 of 100 people contacted pay a small advance, the idea passes. If fewer than 5 do, the owner changes the offer or the idea.
Calculate unit economics and break-even|Each sale should earn more than it costs. Contribution after variable costs pays fixed costs and then becomes profit.|A fictional item sells for 500 with variable cost 300 and monthly fixed cost 60,000. Calculate contribution, break-even units and profit at 400 units a month.|contribution;break-even;profit check|Contribution is 200 per unit, so break-even is 300 units. At 400 units profit is 20,000 a month.
Plan cash for the first six months|A business can be profitable and still run out of cash. A cash plan shows when money arrives and leaves.|Prepare a fictional six-month cash plan for a small shop with startup spending, rent, stock and slow-paying customers. Find the month cash is lowest and how you would cover it.|monthly cash view;lowest point;cover plan|Stock is bought in month one and sales are on credit for 30 days, so cash is lowest in month two. The owner arranges a small loan or negotiates supplier credit.
Choose a legal structure and register honestly|Structures differ in liability, taxes, cost and compliance. The right choice depends on size, partners and risk, and rules should be checked officially.|Compare sole proprietor, partnership and company for a fictional two-person bakery on liability, cost, tax and control, and recommend one with a note to confirm the current rules.|options compared;recommendation;rule check|Two partners who share risk may choose a registered partnership with a written deed to avoid disputes about profit sharing.
Understand funding options and their cost|Money from savings, loans, grants or investors comes with different obligations. Taking more than needed raises cost and risk.|For a fictional startup needing 5 lakh, compare personal savings, a bank loan, a government scheme and an angel investor on cost, control and conditions. Choose a mix.|four sources compared;cost and control;mix chosen|A loan keeps ownership but needs repayment even in a slow month, while an investor shares risk but takes a share of the business.
Pitch the business with evidence|A pitch tells a short story: problem, solution, customer proof, model, numbers and request. Honest limits build trust.|Write a three-minute pitch outline for a fictional business with the problem, solution, early evidence, price, break-even point, the request and the biggest risk.|story arc;evidence;honest risk|The pitch states that 18 of 60 people paid in the test and openly names that delivery cost is the biggest unknown.
Deliver a validated business plan|A plan is complete when its claims are supported by tests or clearly marked as assumptions.|Package a fictional business plan: customer and problem, offer, test results, unit economics, six-month cash plan, structure, funding request, risks and the next 30 days.|claims supported;assumptions marked;next steps|The plan labels the monthly sales forecast as an assumption and shows a worst case where sales are half, with the cash needed to survive it.'''),

dict(id='business-communication',summary='Communicate clearly at work: emails, letters, meetings, reports, presentations, listening, difficult conversations and digital professionalism.',icon='Pen',tool='notebook',tools=['notebook','canva','sheets'],
nodes=['Audience','Message','Channel','Feedback'],modules=['Audience & writing basics','Speaking & listening','Documents & reports','Digital & difficult conversations','Communication pack'],
src=dict(page='certificate-in-business-communication',code='CBC/Q1001',duration='Two Months',eligibility='10+2 or equivalent',modules=['Introduction to business communication','Verbal communication','Non-verbal communication','Written business communication','Digital communication','Business correspondence and documentation']),
rows='''Match the message to the audience|The same fact must be said differently to a customer, a manager and a colleague. Start with what the reader needs to decide or do.|Rewrite one fictional delay announcement three ways for a customer, a manager and a team member, and state the reader's key question each time.|three audiences;reader question;tone changed|The customer wants to know the new delivery date. The manager wants the cause and the fix. The team wants to know what changes in their tasks.
Write a clear professional email|A good email has a precise subject, a short opening, a clear request and a deadline. People should act without replying for clarification.|Draft an email asking a fictional supplier to confirm a delivery date, with subject, greeting, background, request, deadline and closing. Edit it to remove ten unnecessary words.|specific subject;clear request;deadline|Subject: Please confirm delivery date for order 218 by Friday. The body asks one question and gives the reason it is needed.
Run a meeting with an agenda and minutes|A meeting needs a purpose, an agenda, a time limit and recorded decisions with owners. Without these it wastes time.|Prepare an agenda for a fictional 30-minute team meeting and write minutes that record three decisions, owners and dates. Include one item you would move to email.|agenda timed;decisions recorded;owners and dates|Minutes record Asha will send the revised schedule by Wednesday, so everyone knows who acts and when.
Listen actively and check understanding|Active listening means giving attention, asking open questions and summarising what you heard. It prevents mistakes and builds trust.|Write a short fictional conversation where a customer describes a faulty product. Show your three listening moves: a question, a paraphrase and a next step.|open question;paraphrase;next step|So the charger works for a minute and then stops, is that right? Checking this first stops the wrong part being sent.
Speak clearly in a short presentation|A short talk has one main message, a clear order and examples. Pace, voice and eye contact help the audience follow.|Plan a fictional three-minute update on monthly sales with a main message, three points, one example and a closing request. Add a plan for nervousness.|one main message;logical order;closing request|The main message is that sales rose 8 percent because of repeat orders. The close asks the team to continue follow-up calls.
Write a formal letter or memo|Formal documents use a standard layout and a measured tone. They should be accurate and easy to file and find later.|Draft a fictional formal letter to a customer about a late payment with sender, date, reference, polite request, payment options and a courteous close.|standard layout;polite firmness;reference|The letter refers to invoice 4417 dated 3 September and asks for payment by 30 September, offering to discuss a payment plan.
Write a short report with a recommendation|A report gives the reader what they need to decide: purpose, findings, options and a clear recommendation.|Write a one-page fictional report comparing two suppliers on price, delivery and quality, and recommend one with the reasons and risks.|purpose stated;options compared;recommendation|Supplier A costs 3 percent more but delivers on time in 98 percent of orders, so it is recommended despite the higher price.
Communicate professionally in chat and video|Digital tools make messages fast but easy to misread. Clarity, courtesy and confidentiality matter more online.|Create a short guide for a fictional team on chat etiquette, camera and sound in meetings, sharing screens, confidential information and response times.|clear rules;confidentiality;response expectations|Customer account numbers are never pasted into a group chat. A private message or secure system is used instead.
Handle a complaint or conflict by message|Difficult messages should acknowledge the problem, state facts, propose a next step and avoid blame. Tone is part of the content.|A fictional customer writes an angry email about a wrong delivery. Draft a reply that acknowledges, apologises where appropriate, states facts, offers a solution and gives a timeline.|acknowledgement;facts and solution;timeline|I am sorry the wrong item arrived. We will collect it tomorrow and send the correct one by Friday, and I will update you by phone on Thursday.
Deliver a business communication pack|A communication pack shows consistent writing and speaking skills across several workplace tasks.|Assemble a fictional pack: an email, a meeting agenda with minutes, a formal letter, a one-page report and a three-minute talk outline for the same business situation.|consistent facts;suited to audience;edited|All five documents give the same delivery date and figures, and each is shaped for its reader, which shows careful checking.'''),

dict(id='english-language',summary='Improve English for work and study: grammar, punctuation, paragraphs, comprehension, note-making, letters, email and spoken communication.',icon='Pen',tool='notebook',tools=['notebook','canva'],
nodes=['Read','Write','Edit','Speak'],modules=['Grammar & punctuation','Paragraphs & comprehension','Notes & letters','Email & spoken English','English portfolio'],
src=dict(page='certificate-of-proficiency-in-english',code='CPE/Q1001',duration='Three Months',eligibility='10+2 or equivalent',modules=['Paragraph writing','Comprehension of an unseen passage','Letter writing','Note taking and note making','Punctuation','Grammar and usage']),
rows='''Make subjects and verbs agree|A verb must agree with its subject in number. Words between the subject and the verb can distract you.|Correct ten fictional sentences with subject-verb agreement errors, such as The list of items are on the table, and explain the rule for each correction.|ten corrections;rule named;examples|The list of items is on the table, because the subject is list, not items.
Use punctuation to make meaning clear|Commas, apostrophes and full stops show how ideas connect. A missing mark can change the meaning.|Punctuate five fictional unmarked sentences and explain one where meaning changes, such as Lets eat Grandma versus Lets eat, Grandma.|marks placed;meaning change shown;apostrophe rule|The comma in Lets eat, Grandma shows the writer is speaking to Grandma, not suggesting dinner.
Write a paragraph with one clear idea|A paragraph has a topic sentence, supporting sentences and a conclusion. Linking words show how ideas connect.|Write a fictional 120-word paragraph about why a neighbourhood needs a library, with a topic sentence, three supporting points, linking words and a concluding sentence.|topic sentence;supporting points;linking words|The paragraph begins with A library gives every child a quiet place to learn and then supports it with access, quiet and free resources.
Read a passage and answer questions|Comprehension means finding what the text says, not what you assume. Reading the question first shows what to look for.|Read a fictional 150-word passage you are given and write answers to five questions, quoting a line of evidence for each. Mark one inference.|evidence quoted;literal versus inference;complete answers|The answer to why the shop closed early quotes the sentence about the power cut, rather than guessing a reason.
Make notes from a talk or text|Notes capture main ideas in your own words. A clear structure helps you revise and write later.|Make notes from a fictional 200-word text using headings and keywords, then convert them into a three-sentence summary in your own words.|headings;own words;summary|The notes list three headings with keywords such as cause, effect and remedy, so the summary needs no copying.
Write a formal and an informal letter|The layout and tone of a letter depend on the reader. Formal letters are precise and polite and include a clear request.|Write a fictional formal letter requesting a change of exam date and a friendly letter inviting a friend to a function. Compare greeting, tone and closing.|layout;tone difference;clear purpose|The formal letter begins Dear Sir or Madam and ends Yours faithfully. The friendly letter begins Dear Meena and ends With love.
Write an email that gets a reply|A useful email has a specific subject, a short body and a clear request. A polite tone helps get a quick answer.|Write a fictional email to a training institute asking about course timings and fees, with a subject, greeting, two questions and a polite closing.|specific subject;two clear questions;polite tone|Subject: Query about weekday batch timings and fees. The email asks only the two things needed.
Speak a clear short introduction|Spoken English needs clear structure, steady pace and simple words. A short plan reduces nervousness.|Prepare a fictional 60-second self-introduction for a job interview with opening, background, strengths, goal and closing. Record or rehearse it and note two improvements.|clear structure;simple words;improvement noted|After rehearsal the speaker removes filler words and slows down at numbers, so the introduction sounds calm.
Edit a text for accuracy and style|Editing checks meaning first, then grammar, punctuation and word choice. Reading aloud reveals errors that the eye misses.|Edit a fictional 150-word notice with ten planted errors in tense, agreement, punctuation and word choice. List each error, its correction and the rule behind it.|errors found;rules named;improved version|The notice mixes will open and opened in one sentence. The edit makes the tense consistent and removes a repeated word.
Build and edit an English portfolio|A portfolio shows progress. Editing your own work for errors is a key skill and improves with a checklist.|Assemble a fictional portfolio with a paragraph, a letter, an email and notes. Edit each using a checklist of grammar, punctuation, spelling and clarity, and record changes made.|four pieces;checklist used;changes recorded|The checklist catches a missing apostrophe in the letter and a long sentence in the email that is split into two.'''),

dict(id='customer-relationship',summary='Build lasting customer relationships: lifecycle, service standards, complaints, data and CRM tools, loyalty, measurement and privacy.',icon='People',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Know','Serve','Recover','Retain'],modules=['Customer lifecycle','Service & complaints','CRM data & tools','Loyalty & measures','CRM improvement plan'],
src=dict(page='diploma-in-customer-relationship-management',code='DCRM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to CRM','CRM concepts and customer lifecycle','Planning for CRM','CRM and marketing strategy','CRM implementation','Service quality and customer support']),
rows='''Map the customer lifecycle|A customer moves from awareness to purchase, use, loyalty or loss. Each stage needs a different type of contact.|Map the lifecycle for a fictional gym member and list one customer need and one business action at each stage.|stages mapped;needs named;actions|At the lapsing stage the gym calls members who have not visited in three weeks to ask whether something is wrong.
Group customers by value and behaviour|Not all customers need the same service. Grouping by recency, frequency and value helps decide who to contact and how.|Segment 12 fictional customers by recent purchase, frequency and spend into three groups, and propose a different message for each.|segments defined;rule stated;message per segment|Customers who bought often recently but spent little get an offer to try a larger pack. High spenders who have not returned in three months get a personal call.
Set service standards customers can rely on|A service standard is a promise with a number, such as response time. It must be achievable and measured.|Write five service standards for a fictional repair shop, with how each is measured and what happens when it is missed.|measurable promises;measurement;missed-standard action|Phone calls are answered within 5 rings and logged. If a promise is missed, the supervisor reviews the cause that day.
Handle a complaint step by step|A good complaint response listens, apologises where appropriate, finds the facts, acts and follows up. Customers remember how problems were handled.|Write a script for a fictional customer whose order arrived damaged: greeting, listening, empathy, facts, solution, timeline and follow-up. Include a line you would never say.|listening and empathy;clear solution;follow-up|There is nothing we can do is replaced by Here is what I can do today and when you will hear from me.
Keep customer data accurate and useful|CRM value depends on data quality. Duplicate, outdated or incomplete records waste time and annoy customers.|Review a fictional list of 15 customer records with duplicates, missing phones and wrong formats. Define entry rules, a duplicate check and a monthly cleaning routine.|rules defined;duplicates handled;routine|Two records for the same customer, one with a nickname, are merged into one, keeping the latest phone number and the order history.
Use CRM tools to track follow-ups|A CRM tool is only as good as the habits around it. Tasks, notes and reminders keep promises from being forgotten.|Design a fictional CRM workflow for a small training institute: enquiry, call, visit, follow-up, enrolment or loss reason. Define required fields and who owns each step.|stages defined;required fields;owner|Every enquiry has an owner and a next-contact date. A lost enquiry records the reason, such as fees too high, so patterns are visible.
Calculate retention and customer value|Keeping customers is usually cheaper than finding new ones. Small improvements in retention can raise lifetime value strongly.|A fictional service earns 2,000 profit a year per customer. Compare average lifetime and value at 80 percent versus 90 percent retention, and cost-justify a loyalty programme of 300 per customer.|lifetime estimated;value compared;programme tested|At 80 percent retention the average life is 5 years and value 10,000. At 90 percent it is 10 years and value 20,000, so a programme costing 300 is worthwhile if it achieves this.
Measure satisfaction and recommendation|Customer satisfaction and recommendation scores show how customers feel, but they need questions, a sample and follow-up action.|From fictional survey results of 60 percent promoters, 30 percent passives and 10 percent detractors, calculate a net promoter score and describe two actions.|score calculated;actions;follow-up|The score is 60 minus 10, which is 50. The team contacts detractors within a week to understand and fix their issues.
Protect customer privacy and consent|Customers trust you with personal information. Collect only what is needed, use it for the stated purpose and secure it.|Write a privacy checklist for a fictional store collecting phone numbers for offers: consent wording, purpose, storage, access, deletion on request and sharing limits. Note that law should be checked.|consent;purpose limit;deletion|The customer is told that the phone number will be used for order updates and offers and can ask to be removed at any time.
Deliver a CRM improvement plan|A plan finds the biggest customer problem, sets measures and actions, and shows how success will be checked.|Package a fictional CRM improvement plan for a small business: current problems from data, lifecycle map, three actions, tools, owners, measures and a 90-day review.|problem to action link;owners;review plan|Because 40 percent of enquiries are never followed up, the plan assigns an owner and a two-day follow-up rule, and measures the share followed up each week.'''),
]
