COURSES=[
dict(id='tally-erp',summary='Set up a company in accounting software, record vouchers and inventory, apply GST, TDS and payroll, and produce checked reports for a small business.',icon='Chart',tool='budget',tools=['budget','data','sheets'],
nodes=['Set up','Record','Reconcile','Report'],modules=['Company & ledgers','Vouchers & banking','Inventory & costing','GST, TDS & payroll','Reports & controls'],
src=dict(page='tally',code='TALLY/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Accounting basics and Tally ERP 9.0','Inventory management','Voucher entry and advanced accounting','Taxation and compliance','Payroll and security control','Reports, MIS and final project']),
rows='''Set up a company and a sensible ledger list|Accounts are grouped under assets, liabilities, income and expenses. A clear ledger list set up first prevents wrong postings later.|For a fictional stationery shop, define the financial year start, the base currency, and a ledger list with groups for cash, bank, sales, purchases, rent and capital. Explain where a customer who owes money is placed.|financial year set;ledger groups;debtor placement|A customer who owes the shop is a debtor under current assets. A supplier the shop owes is a creditor under current liabilities.
Choose the right voucher for each transaction|Each transaction type has a voucher that records both sides correctly. A wrong voucher type produces a correct-looking but wrong ledger.|Classify 8 fictional transactions as payment, receipt, contra, journal, sales, purchase, debit note or credit note. For each, name the two accounts affected.|correct voucher type;two accounts per entry;reasoning|Moving cash into the bank is a contra voucher between Cash and Bank. Paying the electricity bill from the bank is a payment voucher.
Reconcile the bank book to the statement|A bank book and a bank statement differ because of timing. Reconciliation explains every difference, it does not force the totals to match.|Using a fictional bank book showing 84,000 and a statement showing 90,500, list a cheque not yet cleared and a bank charge not yet entered, and prove the reconciled balance.|differences listed;reconciled total;entry needed|A cheque for 7,000 issued but not presented, less a bank charge of 500 recorded only by the bank, explains the 6,500 difference.
Record stock with units and godowns|Inventory needs a unit of measure, an opening quantity and a location. Stock quantity and value should be checked together.|Create stock items for a fictional shop with units in pieces and boxes, two godowns and an opening balance. Record a transfer between godowns and show the totals are unchanged.|units defined;godown transfer;total unchanged|Moving 40 notebooks from the main store to the shop counter changes the location balances but not the company's total of notebooks.
Value stock and explain the effect on profit|Closing stock reduces cost of goods sold. A different valuation method gives a different profit from the same facts.|Using fictional purchases of 100 units at 10, then 100 at 12, and a sale of 120 units, calculate cost of goods sold by FIFO and weighted average. Say which gives higher profit and why.|both methods calculated;profit comparison;reason|FIFO issues 100 at 10 and 20 at 12, so cost is 1,240. Weighted average uses 11 per unit and gives 1,320, which means FIFO shows the higher profit in rising prices.
Record GST sales and purchases correctly|GST collected on sales is offset by GST paid on purchases. The net amount owed depends on correct rates, place of supply and invoice records.|Use the rate stated in the case, 18 percent for practice only. Record a fictional intra-state sale of 10,000 and a purchase of 6,000, then calculate the net GST payable and say what must be on the invoice.|tax calculated;net payable;invoice requirements|Output tax is 1,800 and input tax is 1,080, so 720 is payable. Always confirm the current rate and rules from official sources before real filing.
Process a month of payroll with statutory deductions|Payroll turns attendance and pay terms into a net salary after deductions. Statutory rates and limits must come from the current official rules.|For a fictional employee with the case rates given, calculate gross pay, one statutory deduction, one voluntary deduction and net pay. State where you would verify the current rates.|gross to net;deduction logic;rate source named|Gross 25,000 less a deduction of the stated percentage and an advance recovery leaves net pay. The calculation sheet notes the official source for the current rate.
Control user access and protect the company data|Not every user should edit every record. Roles, passwords and backups protect the books from error and misuse.|Design access for a fictional business: owner, accountant, data entry clerk and auditor. Define what each can view or change, a backup routine and how a deleted voucher would be traced.|role permissions;backup routine;audit trail|The data entry clerk can create vouchers but cannot alter closed periods. The auditor can read everything but change nothing.
Prepare and check the final accounts|Final accounts summarise the year. A trial balance, profit and loss and balance sheet should agree with each other and with the source records.|From a fictional trial balance, prepare a profit and loss figure and a balance sheet, then confirm that assets equal liabilities plus capital. Record any adjustment you made.|profit calculated;balance sheet agrees;adjustment recorded|Net profit of 48,000 is added to opening capital. A balance sheet that differs by 500 sends you back to find a missing accrual, not to adjust capital.
Deliver a month-end close pack|A month-end pack lets an owner or auditor see what was recorded, what was reconciled and what is still open.|Assemble a fictional month-end pack with trial balance, bank reconciliation, stock summary, GST computation, payroll summary and a list of open items for the owner.|reports consistent;reconciliations attached;open items listed|The pack shows stock value in the balance sheet agrees with the stock summary, and lists one unmatched supplier invoice awaiting confirmation.'''),

dict(id='graphic-dtp',summary='Learn design principles, colour, type, layout, branding and print preparation, and turn a client brief into a finished, legally safe design.',icon='Pen',tool='design',tools=['design','canva','figma','adobe'],
nodes=['Brief','Compose','Check','Deliver'],modules=['Design foundations','Vector & raster images','Layout & desktop publishing','Branding & advertising','Portfolio & client delivery'],
src=dict(page='diploma-in-graphic-designing',code='DGD/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Design foundations and colour','Vector illustration','Raster image editing','Desktop publishing and pre-flight','Branding, advertising and packaging','UI/UX layout, portfolio and freelance practice']),
rows='''Read a design with the elements and principles|Line, shape, colour, texture and space are the elements. Balance, contrast and emphasis are the principles that arrange them.|Analyse a fictional poster described in words. Name its dominant element, its focal point, one use of contrast, and one change that would improve balance.|elements named;focal point;improvement proposed|The sale price is the largest and darkest element, so it is the focal point. Moving the logo to the opposite corner would balance the weight of the layout.
Choose colour for the medium and the meaning|Screens mix light in RGB and print mixes ink in CMYK, so colours can shift between them. Colour also carries meaning that varies by audience.|Select a three-colour palette for a fictional organic grocer used on a website and a printed label. State the mode for each, and check contrast of text on the background.|mode per medium;palette roles;text contrast|A bright screen green may print duller in CMYK, so the printed label proof is checked before the full print run is ordered.
Set type with a clear hierarchy|Type hierarchy tells readers what to read first. Size, weight and spacing do the work, not many different fonts.|Specify heading, subheading, body and caption styles for a fictional restaurant menu using at most two typefaces. Give sizes, line spacing and a rule for long dish names.|style hierarchy;two-typeface limit;long-text rule|Dish names are 14 points bold, descriptions 10 points regular with 14-point line spacing, and names that wrap are kept to two lines.
Decide between vector and raster artwork|Vector graphics scale without losing sharpness. Raster images are made of pixels and lose quality when enlarged.|For a fictional shop, choose a file type for a logo, a product photo, a shop signboard and a web banner. Justify each by scalability, size and transparency needs.|type per use;scaling reason;export format|The logo is vector so it prints sharply on a small card and a large signboard. A product photo stays raster because it is made of photographic detail.
Prepare an image honestly and non-destructively|Edits on separate layers can be undone. Retouching should not mislead the viewer about what a product really looks like.|Write an editing plan for a fictional product photograph: crop, colour correction, background clean-up and export size. Say what you will not change and keep an original copy.|layered edits;original kept;honest limits|Dust on the background is removed, but a real scratch on the product is not hidden, because the advert must not misrepresent the item.
Build a multi-page layout with styles and a grid|A grid and master pages keep long documents consistent. Paragraph styles make a late text change safe.|Plan a 12-page fictional brochure with a master page, a three-column grid, margins, page numbers, and styles for headings, body and captions. State where images may break the grid.|master page;grid defined;style list|Page numbers sit on the master page so adding a page renumbers automatically, and a full-width image may cross the grid only on feature pages.
Create a brand identity sheet|A brand sheet records the logo rules, colours, type and tone so anyone can use the brand consistently.|Write a one-page brand sheet for a fictional tutoring centre: logo clear space, minimum size, colour values, two typefaces, an incorrect-use example and a short voice note.|logo rules;colour and type values;incorrect-use example|The logo needs clear space equal to the height of its first letter. Stretching it or placing it on a busy photo is shown as incorrect use.
Prepare a file for professional printing|A printer needs bleed, safe margins, correct colour mode and fonts embedded or outlined. A pre-flight check finds problems before they are printed.|Create a pre-flight checklist for a fictional A5 flyer with 3 mm bleed, safe margin, CMYK mode, image resolution and font handling. Describe a failure and how you would fix it.|bleed and margin;colour and resolution;failure fix|An image at 72 pixels per inch would print blurred. A 300 pixels per inch version is requested before the file is sent.
Respect copyright and licences in design|Images, fonts and music belong to someone. A licence states what use is allowed and a project record shows where each asset came from.|For a fictional ad campaign, build an asset register listing each image and font with its source, licence, permitted use and expiry. Mark one asset that cannot be used commercially.|source recorded;licence checked;restricted asset flagged|A font licensed for personal use is replaced by an open-licence font before the poster is sold to a client.
Deliver a client-ready design package|A professional delivery has the brief, the approved design, the export files and a record of changes the client accepted.|Package a fictional campaign: a brief, three layouts shown with rationale, the chosen design, export list with sizes, an asset register and the one change request that was agreed.|brief to design trace;export list;change record|The client asks for a bigger price. The change request is recorded and the revised file is exported in print and web sizes with the updated version number.'''),

dict(id='animation-multimedia',summary='Plan and build animation, video and multimedia projects with storyboards, timing, character design, simple 3D workflows and clean exports.',icon='Spark',tool='design',tools=['design','blender','capcut','adobe'],
nodes=['Story','Design','Animate','Export'],modules=['Animation principles','Story & character','2D motion & editing','3D workflow','Multimedia delivery'],
src=dict(page='2d-3d-animation',code='DIN/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Animation fundamentals','Character design','Graphic design','2D animation and editing','3D modelling and animation','Introduction to Maya']),
rows='''Apply the principles of animation to a bouncing ball|Squash and stretch, timing and easing make movement feel weighty and alive. A ball is a clear test of those ideas.|Describe a fictional 24-frame bouncing ball animation. State the keyframes, where the ball is fastest and slowest, and where squash and stretch occur.|key poses;timing and easing;squash and stretch|The ball is stretched just before impact, squashed on contact, and slower at the top of each bounce where easing makes it appear to hang.
Write a one-minute story and its storyboard|A storyboard shows the shots in order so problems are found before costly animation. Each shot has one purpose.|Write a six-shot fictional story about a lost kite, with a thumbnail description, shot type, action and sound for each shot. State what changes between the first and last shot.|six shots;shot purpose;change over time|Shot 1 is a wide view of the empty field. Shot 6 is a close-up of the kite caught in a tree, with the sound of wind to close the story.
Design a character that works from every angle|A character sheet shows front, side and expression views so different animators draw the same figure.|Sketch in words a fictional shopkeeper character with silhouette, three expressions, a front and side description, a colour palette and a size comparison with a door.|silhouette clarity;turnaround notes;palette and scale|A hat and apron make the silhouette readable even when filled with black, and the character is shown at head-height beside the door to fix scale.
Plan keyframes and in-betweens for a walk cycle|A walk cycle repeats a set of key poses. Frame counts decide the speed of the walk.|Plan an 8-frame fictional walk cycle with contact, down, passing and up poses. Explain how doubling the frames per step changes walking speed and how the loop will be checked.|key poses named;speed effect;loop check|With the same distance covered over more frames the walk looks slower. The last frame should flow into the first one without a visible jump.
Edit a short sequence with a clear cut list|Editing chooses what the audience sees and when. A cut list records each clip, its length and the reason for the cut.|Prepare a cut list for a 30-second fictional product promo using five clips, a title, a transition rule, and a music level so speech remains clear.|cut list;transition rule;audio balance|Cuts happen on movement so they feel natural. Music is lowered under the voice-over and a short fade ends the video without a sudden stop.
Plan a simple 3D object from reference to render|A 3D workflow moves through modelling, materials, lighting, camera and rendering. Each stage has a check.|Write the stages for modelling a fictional wooden stool: reference sizes, basic shapes, material, light, camera angle and render settings. State one check at each stage.|stage order;reference scale;check per stage|The seat height is compared to a reference of 45 cm before materials are added, because a wrong shape cannot be rescued by good lighting.
Light and frame a shot to guide attention|Light shows shape and mood and the camera chooses what matters. A viewer looks first at the brightest, sharpest or most contrasting area.|Describe lighting and camera for a fictional night street scene so the viewer notices a lit shop door first. State key light direction, fill, camera height and lens choice.|key light;camera placement;focus of attention|A warm light at the shop door against a dim blue street makes the door the brightest and warmest area, so the eye goes there first.
Prepare visual effects plates and clean composites|Visual effects combine footage layers. Matching light, colour and motion makes them look like one shot.|Plan a fictional shot adding a flying lantern to a filmed courtyard. List the plates, tracking data, colour matching, shadow handling and a check that the lantern is not floating unnaturally.|layers planned;tracking;colour and shadow match|The lantern is tracked to camera movement and given a soft shadow on the wall, otherwise it looks pasted on top of the footage.
Choose export settings for each platform|The right format, frame rate and size depend on where the video will play. Over-compressing hurts quality and under-compressing creates failures.|For a fictional animation, define exports for a phone social post, a website embed and a classroom projector. Give resolution, frame rate, format and a file-size limit.|settings per platform;frame-rate consistency;size limit|The social version is vertical and shorter, while the projector version keeps full resolution and the same frame rate as the master file.
Deliver a short multimedia project with a showreel|A deliverable includes the final file, the source files, a credits list and notes on what each team member did.|Package a fictional 30-second animated advert: brief, storyboard, character sheet, final export, source folder list, credits and a one-minute breakdown note for a portfolio.|complete package;credits and licences;breakdown note|The credits state that the music is licensed, who modelled the product, and which shots used stock footage so there is no confusion about ownership.'''),

dict(id='autocad',summary='Draw accurately in 2D and 3D, organise layers, blocks and dimensions, and produce checked drawing sets ready to plot and share.',icon='Cube',tool='notebook',tools=['notebook','github'],
nodes=['Set up','Draw','Annotate','Plot'],modules=['Workspace & precision','2D drafting & editing','Annotation & dimensions','Blocks & references','3D & plotting'],
src=dict(page='diploma-in-autocad',code='DIA/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Workspace and drafting basics','Advanced 2D drafting','Annotation, dimensions and hatching','Blocks, external references and design centre','Introduction to 3D modelling','Rendering, plotting and documentation']),
rows='''Plan drawing units and limits before drawing|A drawing is only useful if everyone reads its units the same way. Set units and scale at the start, not after drawing.|For a fictional room plan 5 m by 4 m, decide the drawing unit, the scale at which it will print on A3, and the precision of dimensions. Explain what happens if units are mixed.|unit chosen;print scale;mixed-unit risk|Drawing in millimetres, a 5 m wall is 5000 units long. At 1 to 50 on A3 it prints 100 mm long, so the sheet size and scale are confirmed together.
Enter coordinates three ways|Absolute, relative and polar coordinates describe the same point differently. Choosing the right one saves time and avoids error.|Write the input needed to draw a fictional 4 by 3 rectangle from the origin and a line at 30 degrees, 5 units long, using absolute, relative and polar entry. Say which you use and why.|absolute entry;relative entry;polar entry|From the point 2,2 a relative entry of @5<30 draws a line 5 units long at 30 degrees, without calculating the end point by hand.
Draw precisely with snaps instead of by eye|Object snaps lock the cursor to exact geometry such as endpoints and midpoints. Drawing by eye leaves small gaps that break later work.|Describe how to draw a fictional door centred in a 900 mm opening using midpoint and endpoint snaps. State how you would verify there is no gap or overlap.|snap types;centred placement;gap check|The door line starts at the opening midpoint, and an inquiry of the distance to each jamb shows 450 mm on both sides.
Set up layers and standards for a team|Layers separate drawing content by meaning, colour and line weight. A shared standard lets a team find and change things safely.|Create a fictional layer list for a small house plan with walls, doors, windows, dimensions, furniture, text and hatch. Define colour, linetype and plot weight for each, and a rule for naming.|layer list;line weights;naming rule|Walls print heavier than furniture so structure is clear. A drawing that places everything on layer 0 cannot be filtered or edited safely.
Dimension a plan so it can be built|Dimensions state sizes and positions once, in a consistent style. Missing, duplicated or conflicting dimensions cause errors on site.|Write the dimension style for a fictional one-bedroom plan: text height at print scale, arrow style, units, and a checklist to avoid double or missing dimensions.|dimension style;text height;completeness check|Text 2.5 mm high at print scale is entered as 125 units for a drawing at 1 to 50, so printed text stays readable.
Use blocks and attributes to build a schedule|A block is one definition used many times. Attributes attach data so a schedule can be generated without retyping.|Plan blocks for a fictional door and window set with attributes for type, size and quantity. Explain how changing the block definition updates every use and how a schedule is produced.|block definition;attributes;schedule output|Changing the window block from 1200 to 1500 wide updates every window symbol once, and the schedule counts them automatically.
Organise a project with external references|External references let several people work on one site plan or building layer at once. The master file stays light and always shows the latest version.|Design a file structure for a fictional house with architectural, electrical and plumbing drawings referencing one base plan. Explain version control and how broken paths are avoided.|reference structure;version rule;path handling|Electrical drawings reference the base plan using a relative path inside the project folder, so moving the folder does not break the link.
Model a simple 3D solid and check its dimensions|A 3D solid has volume and is built from primitives with operations such as extrude and subtract. Checking dimensions prevents silent errors.|Plan a fictional concrete step block 1200 by 300 by 150 mm with a rectangular recess. List the steps and calculate its volume before and after the recess to check the model.|primitive and operation order;volume check;dimension record|The block is 54,000,000 cubic mm. A 200 by 100 by 50 mm recess removes 1,000,000, leaving 53,000,000, which should match the software's volume query.
Set up a layout and plot to a true scale|Model space holds the full-size drawing and layout space holds sheets. A viewport scale decides whether a printed measurement is true.|Prepare a fictional A3 layout with title block, one viewport at 1 to 50, plot style and PDF output. Explain how to prove the scale is correct on the printed sheet.|viewport scale;title block data;scale proof|A 5 m wall is measured on the printed sheet as 100 mm using a ruler. If it is not, the viewport scale or paper size is wrong.
Produce a checked drawing set|A drawing set is consistent across sheets, with an index, revision notes and a check that dimensions, labels and references agree.|Package a fictional small-house set: plan, section, schedule and site sheet with a sheet index, revision table, standards checklist and one marked-up correction after peer review.|sheet index;revision record;cross-sheet check|A section shows ceiling height 2.7 m but the plan note says 2.9 m. The check finds the conflict and the corrected sheets both carry revision B.'''),

dict(id='hardware-networking',summary='Identify, assemble and troubleshoot computers, plan small networks and servers, and secure them using safe, documented professional practice.',icon='Workflow',tool='notebook',tools=['notebook','github'],
nodes=['Identify','Build','Connect','Secure'],modules=['Hardware & assembly','Troubleshooting & operating systems','Network design','Servers & services','Security & support practice'],
src=dict(page='diploma-in-computer-hardware-and-networking',code='DCHN/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Computer architecture and hardware','Peripherals, installation and troubleshooting','Networking fundamentals and protocols','Network infrastructure and routing','Server administration and operating systems','Network security and professional practice']),
rows='''Identify components and how they connect|A computer works because the processor, memory, storage, power and board are matched. Knowing each part's role makes faults easier to locate.|Describe how a fictional office desktop starts: power supply, motherboard, processor, memory, storage and display. For each part, name one sign of failure.|part roles;connection order;failure signs|If the machine powers on with no display, a memory seating problem or a graphics fault is checked before the storage drive is blamed.
Assemble safely with static and order control|Static discharge can damage components. A planned assembly order prevents bent pins, loose cables and missing standoffs.|Write the safe assembly procedure for a fictional budget desktop, covering anti-static handling, order of installation, cable routing and a final check before first power-on.|static precautions;assembly order;pre-power check|The processor and memory are installed on the board before it goes in the case, because there is more room to see the alignment marks.
Diagnose a computer that will not start|Fault finding narrows the cause step by step. Change one thing at a time and record what happens.|A fictional PC does not display anything. Write an ordered diagnostic plan using power, cables, memory, beep signals and a known good part, and state the result you expect from each step.|ordered plan;one change at a time;evidence recorded|Reseating the memory and trying a single stick tells you whether one module is faulty, which swapping three parts at once would not.
Plan an operating system installation|An installation needs a verified source, a drive plan, drivers and a way to restore data. Partitioning mistakes can erase files.|Plan installing an operating system on a fictional refurbished laptop: backup, installation media check, partition layout, drivers, updates and a first-login security step.|backup first;partition plan;post-install checks|Customer files are copied to an external drive and the copy is opened before any partition is deleted, because an unchecked backup is not a backup.
Calculate IP addresses and subnets|An IP address has a network part and a host part. A subnet mask decides how many devices fit in a network.|Split the fictional 192.168.10.0/24 range into four equal subnets. Give each network address, usable range, broadcast address and number of hosts, then assign one to a reception area.|subnet size;address ranges;host count|A /26 has 64 addresses, of which 62 can be used for devices. The first subnet runs from 192.168.10.1 to 192.168.10.62.
Design and document a small office network|A network diagram shows devices, cables and addresses. Documentation lets a new technician fix problems without guessing.|Design a fictional 15-person office network with router, switch, access point, printer and server. Draw it in words, label cable types, assign addresses and write a naming rule.|topology described;address plan;cable and label rule|Printers use fixed addresses outside the DHCP pool so their location never changes after a restart.
Configure services for users and shared files|A server gives people accounts, groups and permissions. Least privilege limits damage from mistakes and misuse.|Plan accounts and permissions for a fictional office with accounts, sales and administration groups. Define folders, who can read or edit, and how a leaver's account is disabled.|groups and roles;folder permissions;leaver process|Sales staff can read the price list but only the manager can edit it. A leaver's account is disabled the same day and files are kept for review.
Back up and test recovery|A backup is useful only if it can be restored. Copies should be separate, tested and protected.|Design a backup plan for the fictional office server using the 3-2-1 idea: three copies, two media types, one off-site. Include schedule, retention and a quarterly restore test.|3-2-1 applied;restore test;retention period|A copy kept in the same room as the server is lost in a fire, so one backup is stored off-site or in encrypted cloud storage.
Harden a network against common attacks|Security reduces attack paths. Strong wireless settings, updates, firewalls and least privilege are practical first controls.|Write a hardening checklist for the fictional office: router password, wireless security, firmware updates, firewall rules, guest network, and a monitoring routine. Explain each control in one line.|control list;guest separation;monitoring routine|Visitors use a guest network that cannot reach the file server, so a compromised visitor phone cannot see office files.
Deliver a supportable network handover|A handover turns installed equipment into a supportable service, with diagrams, credentials stored safely and a clear support procedure.|Package a fictional small-office network: diagram, address table, equipment list, device settings, backup plan, support steps and a test sheet that proves every service works.|diagram and addresses;test evidence;support procedure|The test sheet shows that the printer, shared folder and guest Wi-Fi each passed a live check, and that the guest network could not reach the file server.'''),

dict(id='mobile-repair',summary='Diagnose and repair phones with safe, lawful and customer-respecting practice, covering hardware faults, software issues, records and a repair business.',icon='Cube',tool='notebook',tools=['notebook','board'],
nodes=['Receive','Diagnose','Repair','Return'],modules=['Components & safe handling','Hardware faults','Software & data','Chip-level & signal faults','Repair service operations'],
src=dict(page='diploma-in-mobile-phone-repairing',code='DMPR/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to mobile phone repair','Hardware components and functions','Hardware repair and troubleshooting','Software repair and troubleshooting','Advanced chip-level repair','Network and signal issues']),
rows='''Identify phone parts and their jobs|A phone is a set of linked modules: board, battery, display, charging port, cameras and antennas. Knowing each job guides diagnosis.|Describe a fictional smartphone with no charging. List the parts involved, from cable and port to battery and power circuit, and in what order you would inspect them.|part roles;inspection order;likely cause|A loose or dirty charging port and a worn cable are checked before any board work, because they are the cheapest and most common causes.
Work safely with batteries, tools and static|Lithium batteries can ignite if punctured or bent, and static can damage chips. Safe handling protects the technician and the customer.|Write a bench safety routine for a fictional repair shop: anti-static mat, battery handling, swollen battery response, tool storage and fire extinguisher location.|static control;battery rules;emergency response|A swollen battery is not pressed or pierced. It is isolated in a non-flammable container and sent for correct disposal.
Receive a device with a proper job record|A repair record protects the customer and the shop. It notes the device, the reported fault, existing damage, data warnings and agreed price.|Create a fictional repair intake form for a cracked-screen phone with owner details, IMEI check against the box or invoice, condition photos, data backup warning and customer consent.|identity of device;existing damage;consent recorded|The form states the screen is cracked and a back panel scratch already exists, so the customer cannot later claim the scratch was caused during repair.
Replace a display or battery step by step|A repair procedure follows a fixed order: power off, remove, replace, test every function and record results. Skipping tests causes returns.|Write the procedure and the test list for replacing a fictional phone screen: disconnect battery, replace, touch test, brightness, proximity sensor, camera and face or fingerprint check.|ordered steps;full function test;result record|After fitting the new screen, the proximity sensor fails to switch off the display during a call, so the repair is not complete until that is fixed.
Diagnose a power or charging fault with measurements|Measurement beats guessing. A charging fault is traced by testing the cable, the port, the battery and then the power circuit.|A fictional phone charges slowly. Plan a diagnosis using a known good charger, a USB meter reading and inspection of the port, with a decision table of results and next actions.|measurement plan;decision table;escalation|If a known good charger delivers full current but the phone draws very little, the port or battery is suspected before board work.
Reinstall software without losing the customer's data|Reinstalling software can erase customer data. Ask first, back up, confirm, then proceed and verify.|Write a customer-safe procedure for a fictional boot-loop phone: ask about data, attempt a backup where possible, use official firmware, and record what was and was not recovered.|data warning;official firmware;recovery record|If the customer needs photos recovered, the shop explains that a factory reset will erase them and gets agreement before continuing.
Handle locks, accounts and ownership lawfully|A technician must not bypass a lock on a device that may be stolen. Proof of ownership protects everyone, and altering a phone identity is unlawful.|A fictional customer brings a locked phone without a bill. Write the policy: what proof you ask for, when you refuse, and what you tell the customer. Explain why you never alter an IMEI.|ownership proof;refusal rule;lawful boundary|A phone with an account lock and a customer who has no proof is declined politely, with advice to contact the manufacturer or the original seller.
Diagnose weak signal and network faults|Signal faults come from the SIM, settings, antenna, board or the area itself. Rule out the simple causes first.|Plan a diagnosis for a fictional phone that shows no network. Test the SIM in another phone, check network mode and band support, inspect antenna contacts, and decide when to refer a board fault.|simple causes first;SIM test;referral point|The customer's SIM works in a second phone, which points to the faulty phone and its antenna or board rather than the network provider.
Quote, schedule and track repairs|A good quote lists parts, labour, time and warranty. Tracking jobs prevents lost devices and customer disputes.|Create a fictional price list and job board for five repair types. Give a sample quote, expected time, warranty terms, status stages and how you tell a customer about a new fault found during repair.|clear quote;status stages;new-fault approval|When a second fault is found, the shop calls the customer with a new price and waits for approval instead of adding work silently.
Run a repair service with quality and aftercare|A reliable shop checks work before return, tracks returns and learns from them. Aftercare builds trust.|Package a fictional shop operating routine: intake, repair, quality check, handover, warranty claim process, returned-job log and monthly review of the most common faults.|quality check;warranty process;return analysis|Three screen returns in a month are traced to one supplier batch, so the shop changes supplier and records the reason in its monthly review.'''),
]
