# Row format: title|principle|task|criterion;criterion;criterion|worked example[|tool override]
# src: IISDT course code, duration, eligibility and the six module headings from the public course page.
COURSES=[
dict(id='computer-applications',summary='Operate a computer, office software, accounts, databases and web basics, then protect and hand over a small office system.',icon='Compass',tool='notebook',tools=['notebook','sheets','vscode'],
nodes=['Organise','Create','Calculate','Protect'],modules=['Operating systems & files','Documents & spreadsheets','Accounts & databases','Web pages & security','Office systems handover'],
src=dict(page='adca',code='ADCA/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Operating systems, networking and administration','Office automation, macros and data analysis','ERP and computerised accounting','Relational databases and SQL','Web architecture, front-end design and CMS','Desktop publishing, graphics and cyber security']),
rows='''Organise files and folders on a shared computer|An operating system stores work in folders and names. A consistent structure and naming rule lets another person find a file without asking its owner.|A fictional training office keeps 40 mixed files on one desktop. Design a folder tree, a naming rule with date and version, and a backup location. Show where an old draft goes.|folder tree;naming rule;backup location|Fees_2026-10_v2.xlsx sits in Accounts/Monthly. The older v1 moves to Archive, and a weekly copy goes to an external drive kept in the office cabinet.
Diagnose a slow computer in a sensible order|Troubleshooting starts with the cheapest and most reversible check and records each result so no step is repeated.|A fictional reception PC takes six minutes to start. List five ordered checks such as startup programs, free disk space, updates, a malware scan and hardware age. State the evidence each gives and when you would escalate.|ordered checks;evidence per check;escalation point|Only 2 percent free disk space points to clearing space before any reinstall. A long startup list points to disabling items one at a time and restarting after each change.
Prepare a mail-merge letter from a template|Styles make formatting repeatable. A mail merge joins one template to one table so each letter is personal without retyping.|Write a fee-reminder letter template for 6 fictional students with merge fields for name, course and due date. Describe the data table and one check you make before printing.|template styles;merge fields;preview check|Fields Name, Course and DueDate come from table columns of the same names. Previewing record 3 shows a blank DueDate, so you fix the table rather than the letter.
Build a spreadsheet that explains itself|Formulas should point at labelled cells, not typed numbers, so a changed input updates every result and a reviewer can trace it.|Build an exam-marks sheet for 8 fictional students with total, percentage and pass or fail at 40 percent. Put the pass mark in one labelled cell and test a student at exactly 40 percent.|cell-based formulas;single pass-mark cell;boundary test|The formula IF(D2/E2>=0.4,"Pass","Fail") treats exactly 40 percent as a pass. Changing the pass mark in one cell updates all eight rows.
Record a business month in double-entry form|Every transaction has equal debit and credit sides. A balanced trial balance shows the entries agree, not that they are right.|Record 6 fictional transactions: capital introduced, a purchase, a credit sale, rent paid, a customer receipt and a withdrawal. Prepare a trial balance and name one error it would not catch.|balanced entries;trial balance;limitation stated|Posting rent to a wrong expense account leaves debits equal to credits, so the trial balance still agrees. It cannot reveal that kind of error.
Design related tables and test a join|Splitting data into related tables avoids repeating facts. A key connects a row in one table to exactly one row in another.|Design Students, Courses and Enrolments tables with keys for a fictional institute. Write one query listing each student with a course, and test a student who has no enrolment.|tables and keys;join logic;no-enrolment case|An inner join hides a new student with no enrolment. A left join shows that student with an empty course so the gap is visible.
Plan an accessible web page|A page is structure, appearance and behaviour. Headings and labels should make sense before any styling is applied.|Write the HTML outline of a fictional institute page with a heading, a course list and a contact form. Say how the layout changes on a narrow phone screen.|semantic structure;labelled form;narrow-screen plan|Five courses appear in one column on a phone and two columns on a tablet. Every form field has a visible label rather than only placeholder text.
Protect a small office from common threats|Most office security failures are ordinary: reused passwords, unchecked attachments and untested backups. A control should match a likely threat.|Write a one-page routine for a 5-person fictional office covering password rules, an attachment check, update timing, a backup restore test and who is told after an incident.|access control;attachment check;backup and incident owner|An unexpected invoice from a known name is verified by phoning a saved number before anyone opens it. A backup is only trusted after a test restore.
Choose the right tool for each office task|The best tool depends on the shape of the data and how many people change it. A wrong choice creates errors later.|Given five fictional tasks, a letter, a class timetable, a student register, monthly accounts and a brochure, choose a tool for each. Justify each choice and name one risk of the wrong tool.|tool matched to data;justification;risk named|A register edited daily by three staff outgrows a spreadsheet because simultaneous saves overwrite each other. A shared form or database avoids that.
Hand over a small office system|A handover lets a replacement operator continue the work. It lists what exists, where it lives, how it is checked and what is still unresolved.|Package a fictional institute's folder plan, letter template, marks sheet, ledger entries, enrolment tables and security routine. Process one change request and record what changed.|complete inventory;tested change;open issues|The change request moves the fee reminder date from the 5th to the 10th. You update one merge table cell, re-run the preview, and note that the printed June letters still show the old date.'''),

dict(id='computer-basics',summary='Learn the parts of a computer, documents, slides, spreadsheets, the internet and safe digital payments from a standing start.',icon='Compass',tool='notebook',tools=['notebook','sheets','canva'],
nodes=['Learn','Practise','Check','Use safely'],modules=['Computer & desktop basics','Documents & presentations','Spreadsheets & the internet','Digital payments & services','Safe digital life'],
src=dict(page='certificate-in-computer-conceptccc',code='CCC/Q0001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Computer and GUI operating system','Word processing and office automation','Spreadsheet calculations','Presentation software','Internet, WWW and browsers','Digital financial services and cyber security']),
rows='''Name the parts of a computer and their jobs|Hardware is the physical machine and software is the instructions it runs. Input, processing, memory, storage and output each do a different job.|Describe what happens when a fictional shop owner types a bill, saves it and prints it. Name the input device, the processor, the memory, the storage and the output device involved.|five parts named;correct order;memory versus storage|Typing uses the keyboard as input. The bill sits in memory while open and is written to storage when saved. The printer is the output device.
Manage files, folders and settings|A file is stored work and a folder groups files. Settings change how the computer behaves and should be changed on purpose.|Write the steps to create a Reports folder, rename a file, move it, and change the screen text size for a fictional relative. Include how to undo each step.|create and rename;move a file;undo step|Renaming Report.docx to Report-Oct.docx keeps its content. If you move it to the wrong folder, drag it back or use the Undo command straight away.
Write a clean document|Consistent fonts, spacing and alignment make a document easier to read. Formatting should help the reader, not decorate.|Write a one-page notice for a fictional village library with a heading, three short paragraphs, a bulleted list of opening times and a page footer. Check spelling before saving.|heading and body styles;list formatting;spelling check|The heading is larger and bold, body text is one size, and opening times appear as a list so a reader finds Saturday hours at a glance.
Build a short presentation that supports a talk|A slide supports the speaker with one idea, short text and a clear image. Reading paragraphs aloud loses the audience.|Plan five slides introducing a fictional tailoring shop: title, services, prices, location and contact. Keep each slide to one idea and describe the image you would place on each.|one idea per slide;short text;contact slide|The prices slide holds a three-row table only. Detailed fabric choices stay in your spoken explanation instead of crowding the slide.
Calculate with basic spreadsheet formulas|A spreadsheet calculates from cell addresses. Relative addresses move when copied and absolute addresses stay fixed.|Create a fictional weekly grocery sheet with item, quantity, price and line total, a grand total and an average price. Explain why the tax cell uses an absolute address.|line-total formulas;grand total;absolute reference|If tax sits in cell F1, the formula uses $F$1 so copying it down the column keeps pointing at the same tax rate.
Search, send email and handle attachments with care|A search result is a lead, not proof. An email attachment from an unexpected sender should be verified before it is opened.|Write the steps to find the opening time of a fictional government office, then write a polite email with a subject line asking about a form. Describe how you would treat an unexpected attachment.|reliable source check;clear subject and request;attachment caution|Prefer the office's official site over a forum post. A reply that carries an unexpected zip file is checked with the sender by phone before opening.
Compare ways to pay digitally|Each payment method has different speed, cost, limits and recourse. A safe choice depends on the situation, not only on convenience.|For a fictional person paying rent, a shop bill and a school fee, compare card, bank transfer, UPI and cash on four points: speed, record, limits and what happens after a mistake.|four-point comparison;record kept;mistake recovery|A UPI payment to a wrong ID cannot simply be pulled back by the sender. The sender contacts the bank and the receiver, so checking the name before confirming matters.
Use online services without exposing secrets|Official services should be reached through addresses you know. Passwords, one-time codes and card numbers are never shared by message or call.|Write a checklist for a fictional person using a bank app and a government portal: how to confirm the address, what is never shared, and what to do if a code arrives that was not requested.|address check;secrets never shared;unrequested code response|A caller who says they are from the bank and asks for the one-time code is refused. The person hangs up and calls the number printed on the card.
Recognise and respond to a scam message|Scams create urgency and ask for money, codes or links. A calm check against a trusted channel defeats most of them.|Analyse three fictional messages: a prize notice, a courier fee link and a bank block warning. Mark the warning signs in each and write the response you would take and who you would report it to.|warning signs found;safe response;reporting step|The courier message uses a shortened link and a small fee. The safe step is to open the courier's real site yourself and enter the tracking number there.
Deliver a personal digital skills file|Evidence of skill is a small set of finished, checked work with a note of what you can and cannot yet do.|Assemble a one-page file for a fictional job seeker with a formatted document, a tidy spreadsheet, a five-slide plan, a payment safety checklist and a plain list of next skills.|finished items;checked results;honest limits|The file states that the spreadsheet formulas were checked with a boundary test, but advanced lookups and pivots are listed as the next skills to learn.'''),

dict(id='office-suite',summary='Build confident document, slide and spreadsheet skills, then move to lookups, cleaning, pivots, charts and dashboards for real reporting work.',icon='Chart',tool='data',tools=['data','sheets','notebook'],
nodes=['Source','Clean','Calculate','Report'],modules=['Documents & slides','Formulas & lookups','Cleaning & summarising','Charts & dashboards','Analysis & handover'],
src=dict(page='certificate-in-advanced-excel',code='CAE/Q1001',duration='Two Months',eligibility='10th Grade or equivalent',modules=['Excel basics refresher','Advanced formulas and functions','Data tools and data cleaning','Pivot tables and pivot charts','Data visualisation and charting','Advanced data analysis']),
rows='''Style a document so it can be reused|Named styles keep headings, body text and lists consistent. Changing a style once updates every place it is used.|Plan a fictional monthly newsletter template with Heading 1, Heading 2, Body and Caption styles. State the font, size and spacing of each, and how a contents list will be produced.|style set;consistent spacing;automatic contents|If Heading 2 is changed from 14 to 16 points in the style, all 12 subheadings update together without selecting them one by one.
Make a slide deck that supports a talk|A deck should follow the speaker's argument. Slide masters keep layout consistent and make late edits safe.|Outline an 8-slide quarterly sales summary for a fictional shop with a master layout, one chart, one table and speaker notes. State the single decision the audience should make.|master layout;one decision;notes for the speaker|The deck ends by asking the audience to approve stocking a second brand. Each slide supports that request with one fact.
Write formulas that survive copying|A formula must keep the right references when copied. Absolute, relative and mixed references behave differently.|Create a fictional price table with a discount cell. Write formulas for net price and total, copy them down and across, and explain which references are fixed.|correct reference types;copy test;labelled assumptions|With the discount in B1, the net price formula refers to $B$1 so copying it across ten products never shifts the discount cell.
Look up values and handle missing matches|A lookup returns a value by key. If the key is missing, the formula should show a clear message instead of a misleading blank or error.|Given a fictional product table and an order list, write lookups for price by product code. Add handling for a code that does not exist and test with one wrong code.|lookup logic;missing-key message;wrong-code test|Looking up code P-199 which is absent returns "Code not found" rather than an error that spreads into the order total.
Clean a messy import without losing the source|Cleaning should be repeatable. Keep the original, apply documented steps, and record how many rows changed.|A fictional list has duplicate customers, mixed capital letters, extra spaces and text-formatted dates. Keep a raw copy, list your cleaning steps and count rows before and after.|raw copy kept;documented steps;row count reconciled|Trimming spaces turns "Meena " and "Meena" into one name, so 120 rows become 114 after removing 6 true duplicates, and the log says so.
Summarise with a pivot and verify it|A pivot table summarises quickly, but its total must be checked against the source or an error will travel unseen.|Plan a pivot of fictional monthly sales by region and product. State the row, column and value fields, then reconcile the pivot grand total to a direct sum of the data.|field plan;grand-total reconciliation;refresh note|The pivot total of 4,82,500 matches the sum of the source column. After new rows are pasted, the pivot is refreshed before it is trusted.
Choose a chart that matches the question|A chart should answer one question. Pie, line, bar and combination charts each suit different comparisons.|For a fictional shop, choose charts for share of sales by category, monthly trend, and target versus actual. Justify each choice and say what each chart must not be used to show.|chart matches question;labels and units;misuse noted|Monthly trend is a line because order matters. Category share across twelve small categories is a bar chart, since many pie slices are hard to compare.
Design a one-page dashboard|A dashboard shows the few numbers a person needs to decide, with consistent definitions and a visible data date.|Sketch a one-page sales dashboard with three key numbers, two charts and one filter for a fictional manager. Define each number and show the date the data was last updated.|defined measures;data date;filter behaviour|Revenue is defined as invoiced sales excluding tax. The page header states "Data to 30 September" so nobody reads old figures as current.
Test a what-if question|A what-if analysis changes one assumption at a time and records the result, so the effect of each assumption is visible.|Using a fictional budget, test a 10 percent cost rise and a 5 percent price rise separately and together. Record base, each scenario and which assumption matters most.|one change at a time;scenario table;key assumption|Raising the price 5 percent adds more profit than a 10 percent cost rise removes, so the shop's margin is more sensitive to price than cost.
Hand over a reporting workbook|A handover workbook explains inputs, calculations and outputs so the next person can refresh it without guessing.|Package a fictional monthly report workbook with a notes sheet, input sheet, calculations, charts and a refresh checklist. Test it by changing one input and recording every result that changed.|documented inputs;refresh checklist;change test|Changing October sales for one region updates the pivot, two charts and the dashboard total. The notes sheet lists exactly those four places so nothing is missed on refresh.'''),

dict(id='data-entry-typing',summary='Develop accurate keyboard skills in English and Hindi, careful data entry, document preparation and the data protection habits an office relies on.',icon='Pen',tool='notebook',tools=['notebook','sheets'],
nodes=['Type','Enter','Verify','Protect'],modules=['Keyboard & workstation','Accurate data entry','Documents & dictation','Data quality & security','Productive office work'],
src=dict(page='data-entry-operatordeo',code='DEO/Q0001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Computer fundamentals and operating system','Word processing','Spreadsheets','Data entry speed and accuracy','Data management and security','Internet, email and communication']),
rows='''Set up a safe typing workstation|Posture, screen height and hand position protect the body and support accuracy over a long shift.|Describe the ideal setup for a fictional data entry operator: chair, screen height, keyboard position, wrist posture and break rhythm. Add a daily five-minute stretching routine.|workstation setup;wrist posture;break schedule|Elbows rest near a right angle, the top of the screen sits at eye level, and a short break every 30 minutes reduces strain.
Measure speed and accuracy honestly|Speed without accuracy creates rework. Net speed counts correct words only, so errors reduce the score.|Record a fictional 5-minute typing test of 600 typed words with 12 errors. Calculate gross speed, error rate and net speed, and plan the next practice target.|gross and net speed;error rate;practice target|600 words in 5 minutes is 120 words per minute gross. With 12 errors counted against 600 words the accuracy is 98 percent, so the next target is accuracy before speed.
Enter numbers and codes without transposing|Numeric errors are common and costly. Chunking digits and reading back from the source reduces them.|Prepare a method to enter 20 fictional invoice numbers and amounts. Include how you read the source, chunk long numbers, and spot a transposed pair such as 1,38 and 1,83.|chunked entry;read-back check;transposition catch|Invoice 4057218 is entered as 405 7218. A running subtotal compared to the printed batch total reveals a transposition quickly.
Type English and Hindi text with the right tools|Unicode text and a standard keyboard layout keep Hindi documents readable on any device. Fonts and layout choices affect accuracy.|Plan a Hindi and English notice for a fictional school. Choose the input layout and font, note how you will check conjuncts and punctuation, and save in a form others can open.|layout choice;font check;shared-file format|A Unicode font displays the Hindi text on another computer. An old non-Unicode font would show unreadable symbols instead of words.
Transcribe dictated text accurately|Taking dictation needs quick notes and a careful written-out version. Unclear words are flagged, not guessed.|Write a method for transcribing a fictional 3-minute office dictation using short outlines or abbreviations. Include how you mark doubtful words and read the transcript back.|note method;doubt flags;read-back|A name heard as either Mehra or Mehta is highlighted for confirmation rather than silently typed as the likelier one.
Build a clean data entry form and rules|Validation rules stop impossible values at the door. A good form is easier to fill correctly than to fill incorrectly.|Design a fictional customer register sheet with dropdowns, date format, phone length and a duplicate check. Test it with three wrong entries and record what each rule catches.|input rules;duplicate check;wrong-entry tests|A phone number with nine digits is rejected, a date typed 31/02 is refused, and a repeated customer ID is highlighted.
Verify entered data before release|Checking is a separate step from entering. Compare to source, count records and sample for errors.|Describe a verification process for 200 fictional hand-written application forms entered by two operators. Include a double-entry or sampling check, a record count and an error log.|source comparison;record count;error log|The batch has 200 forms and 198 rows, so two forms are missing. The log records which form numbers need re-entry before the file moves on.
Protect personal data you handle|Personal data belongs to the person it describes. Handle only what you need, store it safely and share it only with authority.|A fictional office holds applicants' phone numbers and ID numbers. Write rules for access, screen locking, printing, disposal and what to do after sending a file to the wrong person.|minimum access;disposal rule;incident step|A mis-sent spreadsheet is reported to the supervisor at once, the recipient is asked to delete it, and the event is written down.
Plan a productive working day|Priorities, batches and checkpoints let a data entry role meet deadlines without sacrificing accuracy.|Plan a fictional 8-hour shift with 600 forms to enter. Set batch sizes, check points, a break pattern and a rule for what to do when the source is unreadable.|batch plan;checkpoints;unreadable-source rule|Batches of 50 forms end with a count check. A smudged amount is queried with the sender instead of guessed.
Deliver a verified data entry batch|A finished batch includes the data, the checks performed, the errors found and an honest account of what remains uncertain.|Prepare a delivery pack for a fictional batch of 120 records: the entered file, accuracy and speed log, verification results, exceptions and a short handover note.|entered data;verification record;exceptions listed|The pack reports 120 forms received, 118 entered, 2 unreadable and returned to the sender, with a 99 percent accuracy sample of 20 checked records.'''),
]
