COURSES=[
dict(id='c-cpp-programming',summary='Learn to read, write, trace and debug C and C++ programs: types, control flow, functions, arrays, pointers, structures, files and classes.',icon='Cube',tool='notebook',tools=['notebook','vscode','github'],
nodes=['Plan','Write','Trace','Debug'],modules=['First programs & types','Decisions, loops & debugging','Functions, arrays & strings','Pointers, structures & files','Objects & a finished program'],
src=dict(page='certificate-in-c-programming',code='CCP/Q1001',duration='Two Months',eligibility='10+2 or equivalent',modules=['Introduction to C programming','Operators and expressions','Control flow and decision making','Functions in C','Arrays and strings','Structures and file handling']),
rows='''Trace a first program line by line|A program runs its statements in order. Compiling turns your text into a program and reports syntax errors before anything runs.|Write a short C program for a fictional till that stores two whole numbers and prints their sum with a label. Trace it by hand, then describe the compiler message you would expect if one semicolon is missing.|ordered trace;expected output;error message|With a=4 and b=5 the program prints Total: 9. A missing semicolon is reported at or just after the line where the statement should have ended.
Choose data types and predict the result|Every variable has a type that decides its range and how arithmetic behaves. Whole-number division discards the fraction.|Predict the output of 7/2, 7/2.0, 7%2 and storing 300 in a signed char for a fictional program. Explain each result and when you would choose float, double or int.|integer division;modulus;range limit|7/2 gives 3 because both numbers are integers. 7/2.0 gives 3.5, and 7%2 gives the remainder 1.
Write decisions that handle every boundary|A decision must cover every case, including the edges. Off-by-one boundaries cause most grading bugs.|Write the logic for a fictional marks program with bands 90 and above, 75 to 89, 40 to 74 and below 40. Test the values 39, 40, 74, 75, 89 and 90 and show each output.|all bands covered;boundary tests;no gaps or overlaps|Mark 75 must fall in the 75 to 89 band, not the lower band, so the comparison uses greater than or equal to 75 rather than greater than 75.
Find and fix a loop bug|A loop needs a correct start, a correct stop and a change that reaches the stop. Off-by-one errors read or write past the data.|A fictional loop sums an array of 5 numbers using i from 0 to 5 inclusive. Explain why it is wrong, show what it reads, and write the corrected condition with a test.|bug explained;corrected condition;test case|Indexes run 0 to 4. Using i<=5 reads a sixth item that does not exist, so the loop condition must be i<5.
Split a task into functions|Functions give a job one name, clear inputs and one result. Passing by value copies the data, passing a pointer lets a function change the original.|Design functions for a fictional billing program: calculate_subtotal, apply_discount and print_bill. State parameters and return values, and explain why swap needs pointers.|clear signatures;value versus pointer;single responsibility|A swap function that receives copies of two numbers swaps only the copies. Passing their addresses lets it change the real variables.
Handle strings and the end marker|A C string is a character array ending in a zero character. Forgetting the end marker or room for it corrupts memory.|Explain how to store and reverse the fictional word BOOK in a character array. Say how many bytes are needed, where the end marker goes, and what goes wrong if the array has size 4.|array size;end marker;overflow risk|BOOK needs 5 bytes: four letters and the end marker. A size-4 array overwrites the next memory when the marker is written.
Use pointers and dynamic memory safely|A pointer holds an address. Memory you request must be checked, used within bounds and released exactly once.|Describe how a fictional program asks for memory for 10 integers, checks the request succeeded, fills them, and releases the memory. Name the bugs from using it after release and forgetting to release.|allocation check;bounds respected;release once|If the request returns a null pointer the program stops with a message. Using memory after release is a dangling pointer bug.
Store records in structures and files|A structure groups related fields. File operations can fail, so every open and write needs an error check.|Design a fictional student structure with roll number, name and marks, and describe saving three records to a file and reading them back. Explain what the program does when the file cannot be opened.|structure fields;read-write plan;open failure|If the file opening call returns null, the program prints a clear message and exits instead of reading from a missing file.
Model an object with a class|A class keeps data and the rules for changing it together. Hiding data protects it from invalid states.|Design a fictional C++ bank account class with private balance, deposit and withdraw. Write the rule that stops a negative balance and test a withdrawal larger than the balance.|private data;rule enforced;failed-withdrawal test|With a balance of 500, a withdrawal of 800 is refused and the balance stays 500. A public balance field would allow it to be set to minus 300.
Deliver a tested menu-driven program|A finished program has a clear specification, handles bad input and comes with tests a stranger can repeat.|Plan a fictional menu program to add, list and search student records using a structure and a file. Write the specification, ten test cases including invalid input, and a note of known limits.|specification;ten test cases;known limits|Entering the letter x where a number is expected must not crash the menu. The test case lists the input, the expected message and the observed result.'''),

dict(id='server-web-programming',summary='Understand how server-side web applications handle requests, forms, databases, sessions and security, using PHP and ASP.NET concepts.',icon='Code',tool='api',tools=['api','web','vscode','github'],
nodes=['Request','Validate','Store','Respond'],modules=['Requests & server scripts','Forms & validation','Databases & queries','Sessions & access control','A tested web application'],
src=dict(page='certificate-in-php',code='PHP/Q0001',duration='Two Months',eligibility='10+2 or equivalent',modules=['Introduction to PHP','Control structures and functions','Forms and user input','Arrays and strings','Database connectivity with MySQL','Sessions, cookies and authentication']),
rows='''Follow one request through a server|A browser sends a request, the server runs code and returns a response. What the server decides is separate from what the browser displays.|Describe what happens when a fictional visitor submits a contact form: the method, address, data sent, server script, database step and response. Name where an error could occur.|request path;server work;error point|The browser sends a POST to /contact with name and message. The server saves the message, then returns a confirmation page or an error status.
Write variables and conditions that handle missing input|Server scripts receive input that may be missing or unexpected. Check that a value exists before using it.|Trace a fictional script that reads age from a form and prints a message for adults and minors. Describe what it does when age is missing, text or negative.|existence check;type check;safe default|If age is missing the script shows a form error and does not treat it as zero.
Validate on the server and escape on output|Browser checks help users but can be bypassed. The server must validate, and output must be escaped to prevent injected scripts.|Plan a fictional registration form with name, email and age. List server validation rules and show how the text script alert(1) would be safely displayed instead of executed.|server rules;output escaping;bypass reasoning|A user disables browser checks and posts age -5. The server rejects it, and a name containing script tags is displayed as plain text.
Work with arrays and JSON|Arrays hold related values and JSON is the common format for exchanging them. Parsing can fail, so handle that case.|Given a fictional JSON list of three products with price, write the steps to read it into an array, total the prices and handle invalid JSON. Show the expected total.|parse step;total check;invalid-data handling|Prices 120, 80 and 50 give a total of 250. Text that is not valid JSON produces an error message, not a blank total.
Query a database with prepared statements|User input must never be joined into SQL text. Prepared statements keep data separate from commands.|Show how a fictional login query is attacked with input such as a quote and an always-true condition, and rewrite the design with a prepared statement. Explain why the second is safe.|attack shown;prepared statement;reason it works|Joining the typed name into the query can change its meaning. A prepared statement sends the query shape and values separately, so input is only ever data.
Create, read, update and delete records|CRUD operations need clear rules about who may change what and how conflicts are handled.|Design CRUD for a fictional appointment list: fields, create rules, edit rules, delete rules and a duplicate booking check. Describe a test for two users booking the same slot.|four operations;duplicate rule;conflict test|A unique constraint on date and time stops two people booking the same slot even if both press save at the same moment.
Build login with hashed passwords and sessions|Passwords are stored as slow hashes, never as text. A session identifies a logged-in user between requests and must expire.|Plan a fictional login: registration, hashing, login check, session start, logout and timeout. Explain what an attacker gains from a leaked table of hashes versus plain passwords.|password hashing;session lifecycle;logout and expiry|A leaked table of plain passwords exposes accounts at once. Properly salted slow hashes make each password costly to guess.
Authorise every action on the server|Hiding a button is not security. The server must check who the user is and whether they may act on this specific record.|For a fictional customer portal, write the server check for viewing an invoice and test a logged-in user requesting another customer's invoice number directly.|ownership check;denied request;status response|User 12 requests invoice 9001 that belongs to user 40. The server answers forbidden even though user 12 is logged in.
Accept file uploads safely|Uploaded files can contain harmful content or be disguised. Limit type, size and location, and never run uploaded files.|Design a fictional profile photo upload: allowed types, size limit, renamed storage, location outside executable folders, and how you verify the file is really an image.|type and size limit;safe storage;content verification|A file named photo.jpg.php is renamed to a random name with an image extension, stored outside the web root, and checked as a real image.
Deliver a tested web application plan|A deliverable web application has requirements, security checks, test cases and a deployment checklist that includes error logging.|Package a fictional booking site: pages, database tables, validation rules, login and role rules, eight test cases, error logging, and a release checklist with configuration kept out of public files.|requirements to tests;security checks;release checklist|Test case 6 posts a booking with an empty name and expects a validation message. The release checklist notes that database credentials are read from server settings, not stored in public files.'''),

dict(id='software-development',summary='Build software the professional way: requirements, version control, Python and JavaScript, front end, APIs, databases, testing and release.',icon='Code',tool='notebook',tools=['notebook','vscode','github','replit'],
nodes=['Specify','Build','Test','Release'],modules=['Requirements & version control','Programming fundamentals','Front end & APIs','Data & back end','Full application & release'],
src=dict(page='advanced-diploma-in-software-web-application-development',code='ADSWAD/Q0001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to software and web development','Programming with Python and JavaScript','Front-end web development','Back-end development with Node.js','Databases, SQL and NoSQL','Full-stack development']),
rows='''Turn a request into testable requirements|A requirement states what must be true and how it will be checked. Vague words such as fast or easy cannot be tested.|Rewrite the fictional request that an appointment app should be easy and fast into five testable requirements with a pass condition each. Mark which are must-have for the first release.|testable wording;acceptance condition;priority|The page shows the next free slot within 2 seconds on a typical phone connection is testable. The app should feel quick is not.
Use version control to record a change|Version control stores every change with an author and a reason. Small, clearly named commits make problems easy to find and undo.|Write the sequence for a fictional change: create a branch, edit, commit with a clear message, and merge. Show how you would undo a commit that introduced a bug.|branch used;clear message;recovery path|A commit named Fix rounding of discount total can be reverted alone. A commit named update stuff hides what changed.
Write a function and its tests|A function has defined inputs and outputs. Tests record expected results before you trust the code, including edge cases.|Design a Python function for a fictional shop that returns a discount of 10 percent on orders over 1,000. Write five test cases including exactly 1,000 and a negative value.|spec stated;edge cases;test list|An order of exactly 1,000 gets no discount if the rule says over 1,000. The test documents that decision.
Handle events and asynchronous results in JavaScript|Browser code reacts to events and waits for slow results. The interface must show loading, success and failure states.|Plan a fictional button that fetches a price list. Describe the states the page shows while loading, on success and on a network failure, and how repeated clicks are prevented.|three states;failure message;duplicate click guard|If the fetch fails, the page shows a retry message and keeps the old list, not a blank screen.
Design a small REST API|An API exposes resources with consistent names, methods and status codes. Clients depend on predictable behaviour.|Design endpoints for a fictional library: list books, get one book, borrow a book and return it. State methods, paths, success and error statuses and one validation rule.|resource names;methods and statuses;validation|Borrowing a book that is already out returns a conflict status with a clear message, not a success.
Choose between SQL and document storage|Relational tables suit structured data with relationships and strict rules. Document stores suit flexible, nested records. The choice follows the data and queries.|For a fictional clinic bookings system and a fictional product catalogue with varying attributes, choose a storage type for each and justify with two queries each.|choice justified;query examples;trade-off stated|Appointments link patients, doctors and slots with rules, which suits tables. Products with different attribute sets can suit documents.
Build interface state with components|A component renders from its data. When state changes the display updates, so state should have one clear owner.|Plan a fictional cart component: state, how add and remove change it, where the total is calculated, and what the component shows when the cart is empty.|state owner;update flow;empty state|The total is calculated from the item list each time, not stored separately, so it can never disagree with the items.
Secure authentication and secrets|Tokens identify users and secrets unlock services. Neither belongs in public code, and tokens must expire.|List the steps to add login to a fictional app: password hashing, token expiry, where secrets are stored, and what to do if a secret is committed to the repository by mistake.|hashed passwords;secret storage;leak response|A key committed to a public repository is treated as exposed: it is revoked and replaced, because deleting the commit does not erase copies.
Plan deployment and monitoring|A release moves tested code to users in a repeatable way, with a way to roll back and a way to know it works.|Write a release checklist for a fictional full-stack app: build, tests, environment settings, database migration, smoke test, rollback and one monitored measure after release.|ordered release;rollback plan;post-release check|After release, a smoke test creates and deletes a test booking. If it fails, the previous version is restored before users are affected.
Deliver a full-stack project|A finished project includes working features, tests, documentation and honest notes about what is not done.|Package a fictional booking application: requirements, API list, data model, test results, security checks, deployment notes and a list of known limits and next steps.|requirements traced to tests;security checks;known limits|The package maps the requirement that a slot cannot be double booked to test 4, and lists payments as not built in this release.'''),

dict(id='ai-machine-learning',summary='Understand how machine learning works: framing problems, data splits, evaluation, core algorithms, neural networks, language models and responsible use.',icon='Spark',tool='notebook',tools=['notebook','data','huggingface','ollama'],
nodes=['Frame','Prepare','Train','Evaluate'],modules=['Framing & data','Evaluation & error','Algorithms','Neural networks & language','Responsible delivery'],
src=dict(page='advanced-diploma-in-ai-and-machine-learning',code='ADAIML/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to AI and machine learning','Mathematics and statistics for ML','ML algorithms and techniques','Deep learning and neural networks','Natural language processing','Reinforcement learning and AI agents']),
rows='''Decide whether a problem needs machine learning|Machine learning finds patterns from examples. If a clear rule solves the task, a rule is simpler and easier to explain.|Compare a rule-based approach and a learning approach for three fictional tasks: detecting a GST invoice number format, flagging likely spam and predicting delivery delay. Choose one for each.|rule versus learning;data availability;justification|An invoice number format is a pattern a rule can check exactly. Spam changes over time and has no simple rule, which suits learning from examples.
Split data without leakage|A model must be judged on data it has not seen. Information from the test set leaking into training makes results look better than they are.|Plan the train, validation and test split of 1,000 fictional loan records. Explain one leakage mistake, such as scaling on all data first, and how your plan prevents it.|split sizes;leakage example;prevention|Splitting 700, 150 and 150 and computing averages only from the training part prevents the test set from influencing the model.
Compute precision and recall from a confusion matrix|Accuracy hides important mistakes when classes are uneven. Precision and recall measure different kinds of error.|A fictional fraud model gives 40 true positives, 10 false positives, 20 false negatives and 930 true negatives. Calculate accuracy, precision, recall and F1, and say which matters most for fraud.|four metrics;interpretation;context choice|Accuracy is 97 percent but recall is only 66.7 percent because 20 of 60 real frauds were missed, which is the expensive error.
Fit a straight line and measure its error|A regression line predicts a number. Error measures show how far predictions are from reality.|For fictional data of advertising spend 1, 2, 3, 4 and sales 3, 5, 7, 10, estimate a line by eye, predict spend 5 and compute the mean absolute error of your four predictions.|line stated;prediction;error calculated|If your line predicts 3, 5, 7 and 9 for the four points the errors are 0, 0, 0 and 1, so the mean absolute error is 0.25.
Detect overfitting with validation|A model that memorises training data fails on new data. Comparing training and validation scores reveals this.|A fictional model scores 99 percent on training data and 71 percent on validation data. Explain what this shows, list three actions to try and the evidence that would show improvement.|gap identified;remedies listed;evidence to collect|The large gap suggests memorisation. Simplifying the model, adding data or regularising are tried, and the validation score is rechecked each time.
Group data with clustering by hand|Clustering groups similar items without labels. The result depends on the distance measure and the number of groups chosen.|Take six fictional customers described by monthly spend and visits. Perform one assignment step of K-means with two centres and state how you would choose the number of clusters.|assignment step;distance used;choosing k|Each customer is assigned to the nearest centre, then centres are recalculated as the mean of their members, and the steps repeat until nothing changes.
Walk through a tiny neural network|A neural network multiplies inputs by weights, adds a bias and applies an activation. Training adjusts the weights to reduce loss.|For a fictional neuron with inputs 2 and 3, weights 0.5 and -1 and bias 1, calculate the weighted sum and the output after a ReLU activation. Explain what training would change.|weighted sum;activation applied;what training changes|The sum is 2 times 0.5 plus 3 times minus 1 plus 1, which is minus 1. ReLU turns it into 0, so the neuron is inactive for this input.
Evaluate a text classifier honestly|Language models and classifiers can look fluent while being wrong. Evaluation needs labelled examples, a clear metric and a review of errors.|Design an evaluation of a fictional complaint classifier with three categories. Define 60 test examples, the metric, a check of the worst errors and what you would not claim from the result.|labelled test set;metric chosen;error review|Reading the ten worst mistakes shows that sarcastic complaints are mislabelled, so the report states the model is not reliable for sarcasm.
Audit a model for bias and write a model card|A model can be less accurate for some groups. A model card records purpose, data, limits and monitoring for everyone who uses it.|For a fictional loan screening model, compare error rates across two applicant groups and draft a model card with intended use, training data, known limits and a human review rule.|group comparison;model card sections;human review|If false rejections are 8 percent for one group and 15 percent for another, the model is not approved until the gap is understood and reviewed by a person.
Deliver a machine learning project report|A project report lets another person repeat the work and judge the claims. It includes a baseline, results and limits.|Package a fictional prediction project: problem, data description, split, baseline, chosen model, metrics, error analysis, risks and a plain statement of what the model must not be used for.|baseline compared;error analysis;limits stated|The report shows the model beats a baseline that always predicts no delay, 82 percent accuracy to 74 percent, and states it must not be used to deny orders automatically.'''),

dict(id='data-science',summary='Ask a precise question, clean data, explore it, apply statistics honestly, build simple predictive models and tell a truthful data story.',icon='Chart',tool='data',tools=['data','sheets','notebook'],
nodes=['Question','Clean','Analyse','Explain'],modules=['Questions & data','Cleaning & exploring','Statistics','Modelling & SQL','Story & reproducibility'],
src=dict(page='advanced-diploma-in-data-science',code='ADDS/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to data science','Programming for data science','Data wrangling and preprocessing','Exploratory analysis and visualisation','Statistical analysis and probability','Machine learning fundamentals']),
rows='''Turn a vague wish into an answerable question|A data question names the population, measure, period and decision it will inform. Without these the analysis cannot be checked.|A fictional shop owner asks, are customers happier now? Rewrite it as a precise question with the measure, period, comparison group and the decision the answer would change.|measure defined;period and group;decision linked|Compare the average satisfaction rating of orders in September with August for repeat customers, to decide whether the new delivery process stays.
Describe a dataset before touching it|Know what each column means, its type and its source before analysis. Surprises found later cost more.|For a fictional orders table with eight columns, write a data dictionary with type, meaning, allowed values and one risk for each column.|dictionary complete;types and ranges;risk noted|A column named date may hold the order date or the delivery date. The dictionary records which, because mixing them changes delay calculations.
Clean data and keep a log|Cleaning changes the data. Every change must be recorded so results can be reproduced and challenged.|A fictional customer file has duplicates, inconsistent city names and ages of 0 and 150. Write cleaning steps, decide what to do with each problem and log how many rows were affected.|steps documented;decisions justified;row counts|Ages of 0 and 150 are flagged as impossible and set to missing, not guessed, and the log shows 12 rows changed.
Decide how to treat missing values|Missing data has causes. Deleting, filling or flagging each affects the result in a different way.|In a fictional survey 15 percent of income values are missing. Compare deleting rows, filling with the median and adding a missing flag. Say which risks bias and what you would test.|three options compared;bias risk;sensitivity check|If higher earners skip the question, deleting or median filling changes the average. Running the analysis both ways shows how sensitive the result is.
Explore with summaries and a chart that does not mislead|Summary numbers and charts reveal shape, but axes, outliers and averages can mislead.|For fictional delivery times with a few extreme delays, report mean, median and spread, and describe one chart that shows the distribution honestly instead of hiding the extremes.|summary choice;chart choice;outlier handling|A mean of 3.2 days hides that most orders arrive in 2 days while a few take 14. A histogram and the median show both facts.
Separate correlation from causation|Two measures moving together do not prove one causes the other. A hidden third factor or chance may explain the link.|A fictional table shows ice cream sales and swimming accidents rising together. Explain the likely hidden factor and design a check that could separate the explanations.|link described;hidden factor;test design|Hot weather raises both. Comparing days with similar temperature shows whether the link remains once temperature is held roughly equal.
Read an A/B test without overclaiming|A difference between groups may be chance. Sample size, a pre-set decision rule and the size of the effect all matter.|A fictional website shows 5.0 percent conversion for version A on 2,000 visits and 5.6 percent for version B on 2,000 visits. State what you can and cannot conclude and what to do next.|effect size;chance considered;next step|The 0.6 point gap could easily be chance with 2,000 visits each, so the team collects more data before choosing a winner.
Answer a question with SQL|Queries combine, filter and summarise tables. Each join and filter changes the rows included, so check the counts.|Write the logic for a fictional query giving total sales per month by region from orders and customers tables. Explain how you would confirm the total equals the sum of the raw orders.|join logic;grouping;reconciled total|Joining orders to customers on customer id should not change the number of orders. If the count grows, duplicate customer rows are the likely cause.
Build and judge a simple predictive model|A model should beat a simple baseline on data it has not seen and be explained in plain language.|For fictional house prices, compare a baseline that predicts the average price with a one-feature model using area. Say how you would measure improvement on held-out data.|baseline stated;held-out test;plain explanation|If predicting the average gives an error of 8 lakh and the area model gives 5 lakh on unseen houses, the model adds value. A better training score alone does not.
Deliver a reproducible analysis|A reproducible analysis includes the question, data source, cleaning steps, code or formulas, results and limits so another analyst gets the same answer.|Package a fictional analysis: question, data dictionary, cleaning log, key figures, two charts, conclusion with confidence and a list of what the data cannot show.|reproducible steps;honest conclusion;limits listed|The conclusion says average delivery time fell from 3.4 to 2.9 days after the change, but the data covers only one city and six weeks, so the result is not generalised.'''),

dict(id='digital-marketing-seo',summary='Plan and measure honest digital marketing: search optimisation, paid search, social media, content and email, with budgets, consent and analytics.',icon='Cart',tool='notebook',tools=['notebook','budget','sheets','canva'],
nodes=['Audience','Message','Channel','Measure'],modules=['Goals & audience','Search optimisation','Paid, social & content','Email, consent & analytics','Campaign delivery'],
src=dict(page='advanced-diploma-in-digital-marketing',code='ADDM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to digital marketing','Search engine optimisation','Search engine marketing and pay-per-click','Social media marketing','Content marketing and blogging','Email marketing and automation']),
rows='''Set a marketing goal you can measure|A goal names the result, the number, the audience and the date. Without a number you cannot tell whether the work succeeded.|For a fictional tutoring centre, write one goal with a measure, target, audience and deadline, and name the two numbers you will track weekly to see progress.|measurable goal;audience defined;tracking numbers|Get 40 trial-class bookings from parents within 8 km during October, tracked through the booking form and call log.
Understand search intent|People search for different reasons. Content and pages must match what the searcher wants to do.|Classify ten fictional search phrases about a bakery as informational, navigational or transactional, and match each to a page or content idea.|intent labels;page match;gap found|The phrase eggless cake near me is transactional and needs a location page with ordering. How to bake without eggs is informational and suits a blog post.
Optimise a page for people and search engines|Clear titles, headings, content and image descriptions help both visitors and search engines. Stuffing keywords harms readers.|Write the title, description, main heading, three subheadings and image alt text for a fictional page on yoga classes. Explain why you avoid repeating the keyword in every line.|title and description;heading structure;alt text|The title says Beginner Yoga Classes in Pune and the main heading matches it. Alt text describes the image for a screen reader, such as a group practising at sunrise.
Plan content that earns attention honestly|Useful content answers a real question. A content calendar spreads effort and links each piece to a goal.|Draft a four-week fictional content calendar for a local gym with topic, format, audience question, call to action and measure for each piece.|audience question;call to action;measure per piece|A post on beginner mistakes in squats answers a real question, ends with a free assessment offer, and is measured by sign-ups.
Do the arithmetic of a paid search campaign|Paid ads cost per click. Conversion rate and value decide whether the cost per customer is acceptable.|A fictional ad costs 20 per click, 4 percent of visitors book, and a booking earns 1,500 profit. Calculate cost per booking, return, and the conversion rate needed to break even.|cost per booking;profit comparison;break-even|At 4 percent, 25 clicks give one booking and cost 500, leaving a profit of 1,000. Break-even would be a conversion rate of about 1.3 percent.
Write ads and posts that are truthful|Marketing claims must be accurate and supportable. Exaggerated or unproven claims harm customers and can break advertising rules.|Review five fictional ad lines for a health snack and rewrite any that promise results or compare unfairly. Record the evidence you would need before using each claim.|unsupported claims found;truthful rewrite;evidence list|The line cures stress becomes an honest description such as a source of fibre, supported by the nutrition label rather than a health promise.
Run email marketing with consent|People must agree to receive marketing and be able to leave easily. Respecting this protects trust and legal compliance.|Design a fictional newsletter sign-up and first email: consent wording, what you collect, unsubscribe handling and how to treat an address that unsubscribed. Note that data protection law should be checked.|consent wording;unsubscribe rule;data minimised|The sign-up form says exactly what mail will be sent and how often, and one click removes the address from every list.
Track campaigns with tagged links and a funnel|Tagged links show which channel brought a visitor. A funnel shows where people drop out.|For a fictional launch use three tagged links for email, social and ads. With visits 1,000, sign-ups 120 and paid customers 18, calculate each stage rate and the weakest step.|tagged sources;stage rates;weakest step|12 percent of visitors sign up and 15 percent of sign-ups pay, so the next test focuses on the sign-up to payment step.
Test two versions fairly|An A/B test changes one thing, splits the audience at random and picks the winner by a rule set in advance. Stopping early on a lucky streak misleads.|Plan a test of two fictional email subject lines sent to 1,000 people each. Define the single change, the success measure, the minimum run time and what you will do if the difference is small.|one change;decision rule;small-difference plan|Subject A is opened by 21.0 percent and B by 22.5 percent. With 1,000 per group that gap may be chance, so the team repeats the test before rolling out B.
Deliver a measured campaign plan|A campaign plan connects the audience, message, channels, budget, schedule and measures, and includes a review date.|Package a fictional 30-day campaign: goal, audience, channel plan, budget split, content list, tracking setup, weekly review and a rule for stopping an under-performing ad.|goal to measure;budget split;stop rule|The plan stops any ad that has spent twice its target cost per booking without a single booking, and moves that budget to the best performing ad.'''),

dict(id='computer-trainer',summary='Learn to teach computer skills well: needs analysis, lesson design, demonstration, assessment, feedback, online delivery and starting a training practice.',icon='People',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Assess','Plan','Teach','Review'],modules=['Learners & outcomes','Lesson design','Teaching practice','Assessment & feedback','Training practice'],
src=dict(page='computer-trainer-proficiency-diploma',code='CTPD/Q0001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Basics of computers and IT','MS Office applications','Internet and digital tools','Teaching skills and training methodology','Typing and data entry skills','Professional and career skills']),
rows='''Find out what learners already know|A trainer plans from where learners are. A short, friendly check reveals gaps and prevents lessons that are too hard or too easy.|Write a five-question pre-course check for a fictional adult class learning basic computing. Include one practical task and say how you will group learners afterwards.|practical task;neutral wording;grouping decision|Asking the learner to save a file into a named folder shows real skill. Asking do you know computers? tells you little.
Write learning outcomes you can observe|An outcome uses an action you can see, such as create or identify, not vague words like understand.|Rewrite five vague aims for a fictional spreadsheet lesson as observable outcomes, each with a condition and a standard.|action verbs;condition and standard;observable|By the end the learner can create a sheet that totals five numbers with a formula, without help, in under ten minutes.
Plan a 45-minute lesson|A lesson has a start, demonstration, practice and check. Time is planned, with room for questions.|Plan a 45-minute fictional lesson on creating a table in a word processor with outcome, minute-by-minute steps, materials, practice task and an exit check.|timed stages;practice task;exit check|10 minutes demonstrating, 20 minutes guided practice, 10 minutes independent task and 5 minutes to check each learner has a finished table.
Demonstrate a skill step by step|Learners copy what they see. Showing small steps, naming what you click and letting them repeat the step builds skill.|Write the demonstration script for a fictional lesson on attaching a file to an email. Break it into five steps and add a question to check understanding after step three.|small steps;spoken labels;understanding check|After showing how to browse for the file, ask the learner to say where the file will appear in the message before moving on.
Teach learners who work at different speeds|In real classes some finish early and some need more time. A plan with extensions and support keeps everyone learning.|Design supports for a fictional class where two learners finish in half the time and two struggle with the mouse. Give one extension task and two supports without singling anyone out.|extension task;supports;respectful approach|Fast finishers add a chart to their table. Others use a printed step card and a partner check, available to everyone.
Build a fair assessment and rubric|A rubric describes what good work looks like at each level so marking is consistent and learners know the target.|Create a four-criterion rubric for a fictional practical task, formatting a one-page notice. Give levels and one example of work at each of two levels.|clear criteria;level descriptors;example work|The criterion alignment has three levels: text is mixed, headings are aligned but body is not, or all alignment is consistent and intentional.
Give feedback that helps learners improve|Useful feedback is specific, kind and points to a next step. General praise or criticism teaches little.|Write feedback for three fictional learners: a correct but slow worker, a fast but careless worker and a learner who is anxious. Include one strength and one next step each.|specific strength;next step;respectful tone|You saved in the right folder and named the file clearly. Next time check the spelling in the heading before printing.
Teach safely online|Online sessions need a clear link, rules, privacy and a way to help someone who is lost. Recording or sharing a screen needs permission.|Plan a fictional 60-minute online session: pre-session instructions, tool choice, consent for recording, screen sharing rules, chat and how you support someone who cannot hear.|pre-session info;consent;support method|Learners are told beforehand to close personal tabs before sharing a screen and are asked before any recording starts.
Design a short course outline|A course outline sets the order of skills, the time for each, and how progress will be shown at the end.|Draft a 12-session fictional basic computer course outline with outcomes per session, a mid-course check and a final practical assessment.|logical sequence;mid-course check;final assessment|Files and folders come before documents, so learners know where saved work goes. Internet safety is placed before online forms.
Deliver a taught session and reflect on it|Teaching improves through evidence. A session plan, learner feedback and honest reflection show what to change.|Package a fictional 20-minute session: plan, materials, observation checklist, three learner comments and a reflection naming one thing that worked and one change to make.|plan and materials;learner evidence;specific change|Two of three learners could not find the Save As step, so the reflection changes the plan to demonstrate it again and add a printed step card.'''),

dict(id='office-it-support',summary='Provide dependable office IT support: triage requests, solve common faults, manage accounts and devices, protect data and document everything.',icon='Workflow',tool='board',tools=['board','notebook','bitwarden'],
nodes=['Log','Diagnose','Resolve','Document'],modules=['Helpdesk basics','Troubleshooting','Accounts & security','Systems & recovery','Support operations'],
src=dict(page='professional-diploma-in-office-it-and-tech-support',code='PDOTTS/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Fundamentals of IT and networking','Programming and software development','Operating systems and databases','Web development and cybersecurity','Software engineering and AI','IT support and mobile app development']),
rows='''Log a support request completely|A good ticket records who, what, when, how many are affected and what has been tried, so anyone can continue the work.|Write the ticket for a fictional staff member who cannot print. Include contact, device, exact message, start time, impact and steps already tried.|complete fields;exact symptoms;impact stated|The ticket says Printer shows offline since 10:15 for the accounts team, not just printer broken, so the next person can start at once.
Set priority from impact and urgency|Priority comes from how many people are affected and how serious the effect is, not from who shouts loudest.|Rank five fictional requests: one user needs a password reset, the whole office has no internet, a printer is jammed, an invoice system is down on payroll day and a new laptop is requested. Justify the order.|impact assessed;urgency assessed;ranking logic|The office-wide internet outage and the payroll system failure come first because many people and a deadline are affected.
Verify identity before a password reset|Resetting a password for the wrong person gives them access to someone's data. Verify identity by an independent method.|Write a reset procedure for a fictional office when a caller claims to be the manager but sounds unsure. Include verification, a temporary password rule and a record of the request.|independent verification;temporary credential;record kept|Support calls the manager back on the number held in the staff directory, not the number the caller provides.
Troubleshoot a printing fault in order|Check the simplest causes first and change one thing at a time. Record each result.|A fictional office printer is not printing for one user. List an ordered diagnosis from the user's queue and connection to the printer, driver, network and device, with the finding that would stop each branch.|ordered checks;single change;stop conditions|If other users can print, the problem is with that user's computer or queue, not the printer, so the printer is not reset.
Troubleshoot a network or connection problem|Network faults can be at the device, the cable, the switch, the router or the provider. Testing from the device outward finds the layer.|A fictional PC has no internet. Plan checks in order: cable or Wi-Fi, local address, router reachability, outside address and name resolution, and explain what each result tells you.|layered checks;result meaning;escalation|If the PC can reach the router but not an outside address, the fault is beyond the office network and the provider is contacted.
Set up and remove user accounts correctly|New staff need the right access on day one. Leavers need access removed on time. Both must be recorded.|Write onboarding and offboarding checklists for a fictional office: accounts, email, files, equipment, training and removal of access. Include who approves each step.|joiner steps;leaver steps;approval|On a leaver's last day the account is disabled, the mailbox is forwarded to the manager and the laptop is collected and logged.
Protect devices and data in daily support|Updates, backups, encryption and locked screens prevent most losses. Support makes these routine.|Create a one-page device standard for a fictional office covering updates, antivirus, screen lock, disk encryption for laptops, backup and what to do when a laptop is lost.|updates and backups;lost-device steps;encryption|A lost laptop is reported at once, its access is removed and encryption keeps the files unreadable to the finder.
Plan backup and recovery for office data|A recovery plan states what is protected, how often, where copies are kept and how quickly service must return.|For a fictional accounting office, define backup scope, frequency, retention, recovery time goal, a restore test and who decides when to restore.|scope and frequency;restore test;recovery goal|The accounting file is backed up daily and a restore to a spare computer is tested each month, with the result recorded.
Write a knowledge-base article|A good article lets the next user fix the problem without calling. It states the symptom, cause, steps and when to ask for help.|Write a fictional knowledge-base article titled Wi-Fi connected but no internet with symptom, likely causes, numbered steps, a check that it worked and when to contact support.|symptom and cause;numbered steps;escalation|The article ends with: if these steps do not help, create a ticket and include the time the fault began and your device name.
Deliver a support runbook|A runbook gives a team consistent procedures, service targets and escalation so support does not depend on one person.|Package a fictional office support runbook: ticket process, priority table, five common fixes, account procedures, backup test schedule, escalation contacts and a monthly review measure.|procedures documented;priority and escalation;review measure|The runbook sets a first response target of 30 minutes for office-wide faults and measures the share of tickets reopened each month as a quality signal.'''),

dict(id='cctv-installation',summary='Survey a site, plan cameras and cabling, size storage, configure recording and remote access securely, respect privacy law and commission a system.',icon='Shield',tool='budget',tools=['budget','notebook'],
nodes=['Survey','Design','Install','Commission'],modules=['CCTV basics & survey','Cameras & cabling','Recording & storage','Network & remote access','Handover & maintenance'],
src=dict(page='certificate-in-cctv-installation-technician',code='CCTVIT/Q0001',duration='One Month',eligibility='10th Grade or equivalent',modules=['Introduction to CCTV systems','System components and equipment','Installation tools and techniques','Video recording and storage','Networking and remote access','Security and maintenance']),
rows='''Survey a site and set the purpose of each camera|Each camera should have a job, such as identifying a face at a door or watching a wide yard. The job decides position, lens and lighting.|For a fictional two-room shop with a door, counter and storeroom, write the purpose of each of four cameras, the area it must cover and the lighting issue you will check.|purpose per camera;coverage area;lighting check|The door camera is for identifying people entering, so it is placed at face height and angled to avoid the bright glass behind them.
Choose camera type and resolution for distance|Resolution and lens decide how much detail is captured at a distance. Higher resolution is not always needed, but identification needs enough pixels on the target.|Select camera types for a fictional entrance, a counter and a car park. State resolution, lens field of view, night vision need and weatherproof rating for each.|type per location;detail requirement;weather rating|The outdoor car park camera needs a weatherproof rating and infrared for night. The counter camera needs a narrower view with more detail on hands and cash.
Plan cabling and power with a budget|Cable length, power and connectors determine whether a camera works. Standard Ethernet has a distance limit, and power over Ethernet shares a fixed power budget.|Plan a fictional 8-camera network system with 12 W per camera and a switch with 120 W of power budget. State cable limit, the total load and the margin left.|cable limit;power calculation;margin|8 cameras at 12 W need 96 W, which is within 120 W and leaves 24 W of margin. A run over 100 metres needs a different solution.
Install safely at height and near power|Working at heights and near mains power is dangerous. Plan the task, use proper equipment and leave mains connections to qualified people.|Write a safe-work plan for a fictional exterior camera installation: ladder use, drilling checks for hidden cables and pipes, weather limits, tool safety and when to stop.|ladder safety;drilling check;stop rules|Before drilling the wall the installer checks for hidden pipes and cables with a detector and uses a second person to hold the ladder.
Calculate storage and retention|Storage depends on bit rate, number of cameras and days kept. Under-sizing loses footage you promised to keep.|A fictional shop has 8 cameras at 4 Mbps each recording continuously. Calculate storage per day and for 30 days, then state whether a 8 TB drive is enough.|daily storage;30-day need;drive decision|One camera at 4 Mbps records about 43.2 GB per day, so 8 cameras need about 346 GB per day and 10.4 TB for 30 days. An 8 TB drive is not enough.
Configure recording rules|Motion recording saves space but can miss events if it is badly set. Schedules and sensitivity should match the risk.|Define recording rules for a fictional shop: continuous during opening hours, motion at night, and a pre-record time. Test with a person walking at the edge of the camera view.|schedule set;motion sensitivity;test result|A test walk at the edge of the view is recorded with the first seconds before the trigger, which confirms pre-record is working.
Set up remote viewing without exposing the system|Default passwords and open ports let strangers watch private video. Remote access must use unique credentials, updates and a secure route.|Plan remote viewing for a fictional owner. Change default passwords, set user roles, update firmware and choose a secure access method instead of leaving the recorder open to the internet.|unique passwords;secure access method;role limits|The owner connects through a secure vendor service or a VPN, and the recorder's own login page is not exposed to the public internet.
Respect privacy and the law|Cameras record people. Place them where there is a legitimate need, avoid private areas, tell people and control who can see recordings.|Write a privacy checklist for a fictional office installation: no cameras in toilets or changing areas, visible signs, access list, retention period and the process for a request to view footage. Say that local law must be checked.|no private areas;signage;access control|The camera facing the corridor is angled so it cannot see into the staff changing room, and notices at the entrance say recording is in progress.
Commission and hand over the system|A system is complete when every camera and function has been tested and the owner knows how to use and maintain it.|Prepare a fictional commissioning sheet: camera views, recording, playback, time and date, remote access, storage, alarms and owner training. Add a maintenance schedule.|every function tested;owner trained;maintenance plan|The sheet shows the recorder clock was corrected, because footage with the wrong time is unreliable evidence.
Deliver a small shop CCTV design|A complete design joins purpose, equipment, cabling, storage, access, privacy and maintenance in one record.|Package a fictional 4-camera shop design: site notes, camera list, cable plan, power and storage calculations, security settings, privacy checklist, commissioning sheet and a bill of materials.|calculations consistent;privacy included;commissioning record|The bill of materials lists a 4 TB drive because the storage calculation of 173 GB per day for 4 cameras gives about 5.2 TB for 30 days, so retention is set to 20 days instead.'''),

dict(id='mis-technology-operations',summary='Design information systems that support decisions: information needs, databases, reports, ERP and business intelligence, with access control and change management.',icon='Briefcase',tool='notebook',tools=['notebook','data','sheets'],
nodes=['Need','Model','Report','Govern'],modules=['Information needs','Data & databases','Reports & decisions','ERP & processes','Governance & delivery'],
src=dict(page='diploma-in-management-information-system',code='DMIS/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to MIS','IT fundamentals for MIS','Database management and SQL','Decision support and business intelligence','ERP and supply chain management','E-commerce and digital business']),
rows='''Identify who needs which information|Each role makes different decisions and needs different information, at a different level of detail and frequency.|For a fictional training institute, list what the owner, accounts clerk and course coordinator each need to know, how often, and the decision it supports.|role-based needs;frequency;decision link|The owner needs monthly enrolment and fee collection totals, while the coordinator needs a daily attendance list by batch.
Tell transaction, management and decision systems apart|A transaction system records events, a management system summarises them and a decision system helps analyse choices.|Classify five fictional features of an institute's software as transaction, management or decision support, and explain one report that moves data from one level to the next.|correct classification;data flow;example|Recording a fee payment is transaction processing. A monthly overdue summary is management reporting.
Draw how data flows through a process|A data flow diagram shows where information comes from, what changes it and where it is stored. Gaps show missing controls.|Describe a data flow for fictional admissions: applicant form, verification, fee receipt, record creation and report to the principal. Identify one missing control.|flows described;stores identified;gap found|The diagram shows applicant documents are never checked against the register, so a verification step and a person responsible are added.
Design tables that avoid repeated facts|A database table should describe one kind of thing. Repeating a fact in many rows invites contradictory updates.|Design tables for fictional students, batches, courses and fee payments with keys. Explain how a change of course fee updates once rather than in many rows.|tables identified;keys;update logic|The fee lives in the Courses table. Payments refer to the course, so changing the fee does not require editing hundreds of payment rows.
Query data to answer a management question|A query turns stored records into an answer. Check that the result makes sense against a simple known count.|Write the logic or SQL for the number of unpaid students by batch in a fictional institute, and describe how you would confirm it with a manual count of one batch.|query logic;filter correctness;manual check|If the query says 7 unpaid in Batch A, the cashbook is checked for Batch A to confirm 7 outstanding receipts.
Design a report people will use|A good report answers a question at a glance, has defined measures and shows the date and source of the data.|Design a one-page monthly fictional management report with five measures, a definition for each, a comparison to last month and one action the reader can take.|defined measures;comparison;action prompted|Collection rate is defined as fees received divided by fees due in the month, so two people calculating it will get the same figure.
Map a business process onto ERP modules|ERP systems connect departments through shared data. Understanding the process first prevents buying or configuring the wrong thing.|Map the order-to-cash process of a fictional supplier to sales, inventory and finance modules, and name the data that must pass between them without being typed again.|process mapped;shared data;duplicate entry removed|When a sales order is shipped, the inventory module reduces stock and passes the invoice details to finance automatically.
Build a dashboard around decisions|Dashboards should show a few measures that lead to action. Too many charts hide what matters.|Specify a fictional dashboard for the owner of a small institute with four measures, target values, colour rules and what the owner should do when each target is missed.|decision measures;target and alert rule;action|If attendance drops below 80 percent for a batch, the coordinator contacts absent students that week.
Control access to information|People should see only the information their role requires. Roles, approvals and logs protect privacy and reduce errors.|Create an access matrix for a fictional institute with owner, accounts, coordinator and teacher roles over student records, fee data and exam marks. Include a log requirement.|role matrix;least privilege;activity log|Teachers can enter marks for their own batch but cannot view fee balances, and every mark change is logged with the user and time.
Deliver an information system proposal|A proposal explains the need, design, cost, risks and plan to introduce the system, including training and change.|Package a fictional proposal for a small institute: needs, data model, reports, access rules, cost estimate, risks, training plan and a pilot with a measure of success.|needs to design trace;risks and training;pilot measure|The pilot runs in one batch for a month and succeeds if the coordinator produces the attendance report in under five minutes instead of an hour.'''),
]
