COURSES=[
dict(id='human-rights',summary='Understand human rights principles, law and institutions, document violations safely, analyse civil, economic and gender rights, and plan ethical advocacy.',icon='People',tool='notebook',tools=['notebook','board'],
nodes=['Learn','Document','Advocate','Protect'],modules=['Foundations','Law & institutions','Rights in practice','Equality & advocacy','Rights brief'],
src=dict(page='advanced-diploma-in-human-rights',code='ADHR/Q0001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to human rights','Human rights and international law','Violations and accountability','Civil and political rights','Economic, social and cultural rights','Human rights and gender equality']),
rows='''Explain what makes something a human right|Human rights belong to every person because they are human. They are universal, equal and not granted by a government, though governments must respect and protect them.|Explain in plain words the difference between a right, a privilege and a legal entitlement using three fictional situations, and say which rights from the Universal Declaration apply.|universal idea;clear distinction;examples|The right to be free from torture applies to everyone at all times, while a bus pass for students is a benefit created by a scheme.
Classify rights and spot conflicts|Rights are grouped as civil, political, economic, social and cultural. They are interdependent and sometimes need balancing.|Sort ten fictional situations into the right at stake and name one case where two rights conflict, such as privacy and public safety. Explain how a fair balance is judged.|correct categories;conflict identified;balancing test|A person's right to speak freely may conflict with another person's right to reputation, so limits must be lawful, necessary and proportionate.
Trace how international rules reach national law|International treaties bind states that accept them, and national constitutions and laws give effect to rights inside a country. Courts and commissions apply them.|For a fictional rights treaty, trace the steps from signature and ratification to national law, a court case and a report to a treaty body. Name where individuals can complain.|ratification step;national route;complaint path|After a country ratifies a treaty it must report its progress, and a person may use national courts first before any international complaint route.
Find the right body to complain to|Different bodies deal with different harms. Choosing the right route saves time and protects the complainant.|For four fictional complaints, such as police misconduct and denial of a ration entitlement, choose the proper authority, documents needed and time limits to check. Verify procedures on official sources.|right authority;documents;verification|A complaint of custodial mistreatment goes to the human rights commission and the courts, with medical records and a written account.
Document a violation safely and accurately|Documentation must be truthful, consent-based and protective of witnesses. Wrong or careless records can cause harm and weaken a case.|Create a fictional fact-finding template with date, place, persons, sources, evidence, consent and security risks. Explain why you separate what was seen from what was heard.|facts separated from hearsay;consent;security|The record says the witness reports seeing officers take the phone, rather than stating as proven fact that the phone was stolen.
Analyse freedom of expression and its limits|Free expression can be limited only by law for a legitimate purpose and by measures that are necessary and proportionate. Blanket bans are hard to justify.|Analyse a fictional town order banning all public meetings for a month after a dispute. Apply the three-part test of lawful basis, legitimate aim and proportionality, and suggest a narrower measure.|three-part test;weakness found;narrower alternative|A month-long ban on every meeting goes beyond what is needed. A time- and place-limited order for the tense area is more proportionate.
Apply fair trial and arrest safeguards|People accused of crimes have rights to be informed, to counsel, to be heard and to be treated humanely. Safeguards protect the innocent and the integrity of justice.|List safeguards that should be respected at arrest, detention and trial, and test a fictional arrest account against them. Mark which are missing and what a lawyer or family member should do.|safeguards listed;gaps found;response|The account shows the family was not told where the person was held, which is a gap the family reports to the court and commission.
Analyse economic and social rights|Rights such as education, health and housing are realised progressively, but governments must still prioritise the basics and avoid discrimination.|For a fictional district with a school that lacks toilets and a clinic without staff, identify the rights at stake, who is responsible and a realistic plan to improve with indicators.|rights identified;responsible body;indicators|The school's lack of toilets affects girls' attendance, so the indicator is the percentage of girls attending after toilets are built.
Examine gender equality at work and in society|Equality requires removing barriers as well as ending open discrimination. Policies need practical steps and ways to complain safely.|Review a fictional workplace policy for equal pay, safe complaints and flexible work. Find three gaps and write improvements with measures.|gaps found;improvements;measures|The policy has no named person for complaints, so an independent contact and confidential route are added with a response time.
Plan a rights-based advocacy campaign|Advocacy aims to change a practice or law using evidence and respectful pressure. It must avoid harming the people it wants to help.|Package a fictional campaign to improve access to a village health clinic: problem evidence, target decision-maker, message, allies, risks to participants, actions and measures of success.|evidence to ask;risk to participants;measures|The plan collects clinic opening records and patient testimonies with consent, and asks the district officer to fill the vacant post by a stated date.'''),

dict(id='event-wedding',summary='Plan and deliver events and weddings: concept, budget, venue, vendors, schedule, risk, sponsorship, guest experience and post-event evaluation.',icon='Calendar',tool='budget',tools=['budget','board','canva','sheets'],
nodes=['Brief','Plan','Run','Review'],modules=['Event concept & budget','Venue, vendors & risk','Marketing & sponsorship','Weddings & social events','Delivery & evaluation'],
src=dict(page='advanced-diploma-in-event-management',code='ADEM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to event management','Event marketing and promotion','Event logistics and operations','Types of events and their management','Event financial management and budgeting','Post-event evaluation, legal and ethical considerations']),
rows='''Write a clear event brief|An event brief states the purpose, audience, date, size, budget and measures of success. Without it, every decision becomes an argument.|Write a one-page brief for a fictional annual day of a school with objective, audience, date, expected attendance, budget limit and three success measures.|purpose and audience;budget limit;success measures|The brief says the event should give every class a stage slot, host 600 guests and finish within 90 minutes, with parent feedback as a measure.
Build a budget with a contingency|A budget lists every cost, with a reserve for surprises. Underestimating small items often breaks the plan.|Prepare a fictional budget for a 150-guest family function with venue, catering, decor, sound, photography, transport and a 10 percent contingency. Show total and per-guest cost.|all costs listed;contingency;per-guest cost|Costs of 3,00,000 plus 10 percent contingency make a budget of 3,30,000, or 2,200 per guest for 150 guests.
Choose a venue with a scorecard|Venue choice depends on capacity, location, access, services, rules and cost. A scorecard stops the loudest opinion from winning.|Score three fictional venues on capacity, parking, accessibility, kitchen, power backup, curfew and price. Weight the criteria and recommend one with a site visit checklist.|weighted criteria;comparison;site visit|A venue that is cheaper but has a curfew at 10 pm fails a wedding that must continue after dinner, so it scores poorly on the key need.
Contract and manage vendors|Vendors deliver what is written and agreed. A contract and payment schedule protect both sides.|Outline a fictional vendor agreement for a caterer with menu, headcount, timing, payment stages, cancellation, substitution and responsibilities. List three questions to ask before signing.|scope clear;payment stages;cancellation terms|The caterer receives 30 percent at booking, 50 percent a week before and the balance after service, and the contract states the final head count date.
Create a run of show|A run of show is a minute-by-minute schedule with owners and cues. It lets the team act without asking the planner.|Write a fictional run of show for a two-hour conference with arrival, registration, sessions, breaks, speaker handovers and closing, naming the owner of each cue.|timed cues;owners;buffers|Registration opens at 8:30 with two desks. A five-minute buffer between sessions allows a late speaker to arrive without cutting the next speaker.
Plan for risks and crowd safety|Events face weather, power failure, delays, medical emergencies and crowd issues. A plan assigns who acts and how.|Make a risk table for an outdoor fictional cultural evening with eight risks, early signs, responses and responsible persons. Include crowd entry and exit control.|risk table;responses;crowd control|If rain starts, the covered hall is used and the stage programme is shortened. The announcer, not the singer, tells the audience what to do.
Win sponsors with a useful proposal|Sponsors support events that reach their audience. A proposal shows audience, benefits, packages and proof, not just a request for money.|Write a fictional sponsorship proposal for a local sports tournament with audience profile, three packages, benefits, price, delivery obligations and how results will be reported.|audience;packages;reporting|The gold package shows the sponsor's logo on jerseys and at the entrance, and the organiser promises a photo report within a week.
Plan a wedding with family and rituals in mind|Weddings combine family expectations, rituals, schedules and budgets. A planner listens first and respects the families' traditions.|Prepare a fictional wedding planning file with a family meeting agenda, ritual timeline given by the family, guest list limits, budget split and decision roles. Include a way to settle disagreements.|listening agenda;timeline;decision roles|The family meeting records that the muhurat timing is fixed by the family priest, so the planner builds the whole day around it.
Design the guest experience|Guests remember comfort, clarity and care. Signs, seating, food, accessibility and handling special needs matter as much as decoration.|Plan a fictional guest journey from invitation to departure for 200 guests including elderly relatives, children and out-of-town visitors, with information, welcome, seating, food and transport.|journey mapped;accessibility;information|Elderly guests are given ground-floor seating near the entrance, and out-of-town guests receive a map and transport timetable in advance.
Evaluate an event and report results|Evaluation compares results with the brief. Honest numbers and feedback show what to repeat and what to change.|Compare fictional budget and actual for an event, summarise feedback from 40 responses, calculate cost per attendee and write three lessons. Include how you report an overspend.|budget compared;feedback summarised;lessons|The event went 8 percent over because decor changed late. The lesson is a decor freeze date two weeks before the event.'''),

dict(id='cooking-baking',summary='Cook and bake safely and consistently: food safety, knife and kitchen basics, methods, baking science, cakes and desserts, costing and starting a small food business.',icon='Cart',tool='budget',tools=['budget','notebook','sheets'],
nodes=['Prepare','Cook','Check','Serve'],modules=['Kitchen safety & basics','Cooking methods & scaling','Baking science','Cakes, desserts & allergens','Menu & food business'],
src=dict(page='diploma-in-cooking-and-baking',code='DCB/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Culinary arts and kitchen fundamentals','Baking and pastry fundamentals','Cooking techniques and cuisines','Advanced cake baking and decorating','Desserts and confectionery','Advanced pastry and chocolate work']),
rows='''Set up a clean and safe kitchen routine|Food safety depends on clean hands, clean surfaces, separate raw and cooked foods, and correct temperatures. A routine makes safe habits automatic.|Write a fictional opening and closing checklist for a small kitchen covering handwashing, surface cleaning, raw and cooked separation, fridge temperature checks and waste. Follow your local food safety authority for exact limits.|hygiene steps;separation;temperature check|The checklist records that cold foods are kept at the safe temperature stated by the authority, and raw chicken is stored below cooked food.
Use knives and equipment safely|Most kitchen injuries come from dull knives, wet boards and rushed work. Safe habits protect the cook and make cuts uniform.|Write a fictional practice plan for basic knife work: grip, stable board, guard hand, cuts for onion and carrot, cleaning and storage. Explain why a sharp knife is safer.|safe grip;stable board;cleaning|A damp cloth under the board stops it sliding, and the knife is washed and put away immediately, not left in a sink of water.
Scale a recipe for a different number of portions|Scaling multiplies ingredients by a factor, but cooking times, pan size and seasoning do not always scale in the same way.|Scale a fictional recipe for 4 servings to 25 servings. Calculate the multiplier and new quantities for five ingredients, and say what else changes besides quantity.|multiplier;quantities;non-linear changes|The multiplier is 6.25. Salt is added gradually and tasted, since seasoning does not always scale exactly.
Choose a cooking method for a food|Boiling, steaming, roasting, frying and grilling suit different foods and results. The choice affects taste, texture, nutrition and cost.|For six fictional foods, such as potatoes, fish, greens and paneer, choose a method and explain the expected texture, the risk to avoid and one alternative.|method matched;texture reasoned;risk|Leafy greens are cooked briefly so they stay bright and keep nutrients, while long boiling makes them dull and soft.
Make a basic sauce and understand thickening|A roux of equal weights of fat and flour thickens a liquid. Adding hot liquid gradually avoids lumps.|Describe the method and quantities for a fictional white sauce for 500 ml of milk using a roux of 40 g butter and 40 g flour. Explain how to fix a lumpy sauce and how to store leftovers safely.|roux ratio;method;lump fix|Cook the roux briefly, add warm milk a little at a time while whisking, and strain the sauce if lumps remain.
Use baker's percentages|Bakers write ingredient weights as a percentage of flour weight. This makes recipes easy to scale and compare.|A fictional bread recipe has 1,000 g flour, 650 g water, 20 g salt and 10 g yeast. Convert to baker's percentages and scale to 2,500 g of flour.|percentages;scaled weights;check|Water is 65 percent, salt 2 percent and yeast 1 percent. For 2,500 g of flour the water is 1,625 g, salt 50 g and yeast 25 g.
Explain why bakes succeed or fail|Flour, fat, sugar, eggs and leavening each do a job. Knowing the job explains why a cake sinks or a biscuit spreads.|Diagnose four fictional baking faults, a sunken cake, a dense loaf, spread biscuits and a dry sponge, and name the likely causes and corrections.|causes linked;corrections;ingredient role|A cake that sinks after the oven door was opened early may have collapsed because the structure was not yet set.
Control allergens and label food honestly|Food allergies can be serious. Ingredients must be identified, cross-contact prevented and labels accurate.|Prepare a fictional allergen matrix for five bakery items covering common allergens, a cross-contact control plan and the wording of a label. Say what you do when a customer asks about an ingredient you are unsure of.|matrix complete;cross-contact controls;honest answer|If unsure whether a chocolate contains nuts, the baker says so and does not guess, because a wrong answer could cause serious harm.
Cost a menu item and set a price|A selling price must cover ingredients, labour, packaging, overhead and profit. Costing each item reveals which products earn money.|Cost a fictional cake with ingredients, packaging and labour of 1.5 hours at 150 per hour, add overhead of 15 percent and a 30 percent margin on price, and give the selling price.|all costs;margin method;price|Ingredients 420 plus packaging 40 plus labour 225 is 685. Overhead of 15 percent gives about 788, and a 30 percent margin on price needs about 1,125.
Plan a small food business safely|A small food business needs a menu, safe production, costing, registration and delivery rules. Registration depends on type and turnover and must be verified.|Package a fictional home bakery plan with menu, weekly production schedule, food safety rules, allergen controls, costing, storage and delivery. Include a note listing the registrations to verify with the food authority.|menu and schedule;safety controls;registration note|The plan includes a log of fridge temperature and a rule that orders are baked fresh, with registrations listed for verification before the first sale.'''),

dict(id='montessori',summary='Teach with the Montessori approach: prepared environment, observation, sensitive periods, practical life, sensorial, language, mathematics, culture and parent partnership.',icon='People',tool='notebook',tools=['notebook','board','canva'],
nodes=['Observe','Prepare','Present','Reflect'],modules=['Philosophy & environment','Child development','Materials, language & number','Culture, practical life & observation','Classroom & parents'],
src=dict(page='montessori-teacher-training',code='SBDMEEL/Q001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to Montessori education','Child psychology and development','Language and mathematics','Cultural studies, art, music and creativity','Classroom management and observation','Parental engagement and communication']),
rows='''Describe the Montessori approach in plain words|Montessori education is built on respect for the child, freedom within limits, a prepared environment and hands-on materials. The teacher guides rather than lectures.|Explain to a fictional parent, in 150 words, how a Montessori classroom differs from a traditional one in teacher role, materials, pace and movement.|clear differences;parent-friendly;examples|Children choose work from open shelves and the teacher gives short individual lessons, unlike a class where all do the same task at the same time.
Check a prepared environment|The environment should be orderly, beautiful and sized for children, with materials in sequence. Every item should have a purpose.|Audit a fictional classroom description against a checklist: child-sized furniture, low shelves, order, complete materials, freedom of movement and safety. List five improvements.|checklist applied;improvements;safety|Pouring jugs placed on a high shelf are lowered so children can reach them independently, and a tray holds a cloth to wipe spills.
Observe a child without judging|Observation records what a child does, not what you think of them. Good notes guide the next lesson.|Write a fictional ten-minute observation of a three-year-old at work with date, time, activity, concentration, hands and steps. Remove any judgement words and state one next step.|factual record;no judgement;next step|The note says Aru chose the pouring tray, poured water into a second jug nine times and smiled, rather than saying Aru is a good girl.
Link sensitive periods to activities|Children show strong interest in certain skills at certain ages, such as order, movement and language. Teachers offer matching work at the right time.|For three fictional children aged two, three and five, identify likely sensitive interests from observations and plan one suitable activity for each.|interest identified;matched activity;evidence|A two-year-old who repeatedly lines up objects shows interest in order, so a simple sorting tray is offered.
Present a practical life lesson|A lesson is demonstrated slowly with few words, in steps, so the child can later repeat it independently.|For a fictional lesson, break the activity of pouring water between two jugs into eight steps, write what the teacher says and does, and note the control of error.|steps ordered;slow demonstration;control of error|The teacher shows each step silently and says only the key words. A visible mark on the jug shows when to stop pouring.
Plan a sensorial lesson|Sensorial materials isolate one quality such as size or colour so the child refines their senses. Each has a built-in control of error.|Describe a fictional lesson using a graded set of cylinders or blocks: the quality isolated, presentation steps, extension and how the child can self-correct.|quality isolated;self-correction;extension|If a cylinder does not fit its socket, the child sees at once that a mistake was made and tries again without adult help.
Teach early reading through sounds|Children learn the sounds of letters before the names, and build words from sounds. Writing readiness develops through hands-on preparation.|Plan a four-week fictional sequence for sound introduction with three sounds per week, matching objects and word building. Explain why sounds come before letter names.|sound sequence;objects;word building|After learning s, a and t the child builds words like sat and at with a movable alphabet before learning other sounds.
Teach the decimal system with concrete materials|Children understand place value when they handle units, tens, hundreds and thousands before using symbols.|Show how a fictional child builds the number 1,342 with concrete bead quantities and number cards. Describe the exchange of 10 units for 1 ten.|concrete build;exchange idea;symbol link|The child collects 1 thousand bar, 3 hundred squares, 4 ten bars and 2 unit beads, then matches each to a card showing its value.
Run a work cycle and mixed-age classroom|A long uninterrupted work cycle allows deep concentration. Mixed ages let younger children learn from older ones and older ones lead.|Plan a fictional morning for a mixed-age class of 20 children with a three-hour work cycle, lesson times, group time, outdoor time and teacher observation slots. Explain how interruptions are limited.|work cycle protected;lessons planned;observation time|Group songs are scheduled after the work cycle so children are not pulled away from concentrated work.
Partner with parents and keep records|Parents need clear information about what their child does and how to support independence at home. Records show progress and guide conversations.|Prepare a fictional parent meeting outline and a child progress record using observations, with photos only with permission. Include how to answer a parent who asks why children are not taught alphabet writing early.|parent communication;records;consent|The teacher explains that hand preparation through practical life makes writing easier later, and shares observation notes showing the child's growing control.'''),

dict(id='nursery-preprimary',summary='Teach nursery and pre-primary children well: development, play-based methods, planning, routines, safety, positive guidance, inclusion and parent partnership.',icon='People',tool='notebook',tools=['notebook','board','canva'],
nodes=['Observe','Plan','Teach','Reflect'],modules=['Early childhood foundations','Play-based teaching','Planning & classroom','Guidance & inclusion','Term plan & partnership'],
src=dict(page='nursery-teacher-training-ntt',code='DPNECT/Q001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Foundations of early childhood education','Child growth and development','Teaching methodologies and strategies','Curriculum planning and classroom management','Child psychology and special needs','Evaluation, communication and professional development']),
rows='''State the aims of early childhood education|Early education builds a love of learning, language, social skills and confidence. It prepares children for school through play, not pressure.|Write a short fictional aims statement for a nursery school and give two examples each of a healthy activity and an inappropriate pressure, such as hours of writing practice.|aims clear;healthy activities;pressure example|Learning to share blocks and tell a short story builds skills that a three-year-old can use, while copying a full page of letters does not.
Use development milestones as a guide|Milestones describe typical ranges for movement, language, thinking and social behaviour. Children develop at different rates, and a teacher notes concerns without diagnosing.|Match fictional behaviours of children aged two, three and four to domains of development. Identify one that suggests the teacher should talk to the parent, and how to say it kindly.|domains matched;ranges respected;kind message|A four-year-old whose speech is very hard for others to understand is mentioned respectfully to the parents with a suggestion to consult a specialist.
Plan a circle time|Circle time gathers children for greetings, songs, talk and stories. It should be short, active and welcoming for all.|Write a fictional 20-minute circle time plan for three-year-olds with a greeting, a song with actions, a short story and a calming ending. Include what you do when a child cannot sit still.|short and active;story plan;flexible response|A child who needs to move is given a quiet job such as holding the story book, rather than being told to sit still.
Tell a story and teach a rhyme|Stories and rhymes build language, memory and imagination. Voice, pictures and actions keep young children engaged.|Prepare a fictional storytelling session with a short story, props, questions to ask children and a related rhyme. Plan how to repeat it for children who need more time.|age-suitable story;questions;repetition|After the story, the teacher asks what the little bird did first, giving every child time to answer with words or actions.
Plan safe creative activities|Art and craft should use safe materials and suit the children's age. Small parts and sharp tools can be dangerous for young children.|Choose three fictional art activities for three-year-olds, list materials, safety checks and what children learn. Explain why small beads are removed for children under three.|safe materials;learning aim;small parts hazard|Finger painting with non-toxic paint develops sensory and motor skills. Beads small enough to swallow are replaced with large pieces or removed.
Arrange a child-friendly, safe classroom|A room should be safe, clear and inviting, with learning areas, low furniture and visible routines. Safety checks are regular.|Draw a plan in words for a fictional nursery room with play areas, storage, display, cloakroom and toilet access. Add a weekly safety checklist with five items.|learning areas;low and safe;checklist|The block corner is on a carpet away from the door, and the checklist includes loose wires, sharp edges, locked cupboards and clean toilets.
Build a daily routine|A predictable routine gives young children security. Quiet and active times alternate and transitions are planned.|Write a fictional half-day nursery timetable with arrival, free play, snack, circle time, outdoor play, story and departure. Explain how you manage transitions.|balanced timetable;transition method;flexibility|A short song signals tidy-up time, so children move to snack without confusion or fuss.
Guide behaviour positively|Young children learn behaviour by example and guidance. Clear expectations, praise for effort and calm responses work better than punishment.|For three fictional incidents, a child biting, a child refusing to share and a child crying at drop-off, write what you do, say and avoid, and how you inform the parent.|calm response;positive language;parent communication|For a child who bites, the teacher protects both children, stays calm, names the feeling and watches for the trigger, without humiliating the child.
Include every child|Inclusion means every child belongs and gets the support they need. Teachers adapt activities and work with families and specialists.|Adapt a fictional circle time activity for a child with hearing difficulty and a child who speaks a different home language, listing changes and how you check understanding.|adaptations;respect;checking understanding|The teacher faces the child, uses clear gestures and picture cards, and pairs the child with a friendly partner.
Plan a term and communicate with parents|A term plan connects themes, activities and observation. Parents should hear regularly what their child is learning and how to help.|Package a fictional 12-week term plan with themes, weekly aims, sample activities, observation method, a parent newsletter and a parent meeting agenda.|themes and aims;observation plan;parent communication|The week-four theme is My Family, with an activity where children bring a photo, and the newsletter suggests talking about family jobs at home.'''),

dict(id='early-childhood-care',summary='Care for young children safely: health, nutrition, hygiene, first-aid planning, safe environments, emotional care, safeguarding and running a daycare routine.',icon='Shield',tool='notebook',tools=['notebook','board'],
nodes=['Welcome','Care','Protect','Communicate'],modules=['Care foundations','Health & nutrition','Safety & first-aid planning','Emotional care & safeguarding','Daycare operations'],
src=dict(page='advance-certificate-in-early-childhood-care-and-education',code='ACECE/Q1001',duration='Three Months',eligibility='10+2 or equivalent',modules=['Foundations of early childhood education','Child growth and development','Curriculum and pedagogical approaches','Classroom management and environments','Health, nutrition and safety','Psychological and emotional development']),
rows='''Plan responsive daily care|Babies and young children need care that follows their signals for feeding, sleep, comfort and play. Records help carers share information.|Create a fictional daily care sheet for toddlers covering arrival, meals, nappy or toilet times, sleep, play and notes for parents. Explain how you respond when a child is distressed.|care sheet;responsive approach;handover|The sheet records the child's last meal and nap so the next carer and parent know when the child may be hungry or tired.
Teach and practise hygiene|Handwashing, clean toys and safe handling of food prevent infections spreading in groups of children.|Prepare a fictional hygiene routine for a daycare covering handwashing times, nappy changing, toy cleaning, toilet cleaning and illness spread. Include a child-friendly handwashing song or steps.|key handwashing times;cleaning schedule;child steps|Hands are washed on arrival, before food, after toilet or nappy changes and after outdoor play.
Plan age-appropriate meals|Young children need frequent small meals with a range of nutrients and safe textures. Allergies and cultural food preferences must be respected.|Plan a fictional one-day menu for toddlers with meals and snacks, texture and choking safety, allergy record and a way to introduce new foods gently.|balanced day;safe textures;allergy record|Whole nuts and hard raw pieces are avoided for young children, and fruit is cut into appropriate sizes to reduce choking risk.
Monitor growth and refer concerns|Growth charts help spot problems early. Carers record measurements accurately and refer concerns to health professionals, they do not diagnose.|Record fictional weights for a child over four months, plot them against an expected range given in the case, and decide when and how to speak to parents and the health worker.|measurements recorded;trend read;referral|If a child's weight stops rising for several months, the carer tells the parents kindly and suggests a check with the health worker.
Recognise illness and decide on exclusion|Carers notice signs of illness and follow health guidance on exclusion, medicines and notifying parents. Sick children need rest and care at home.|Create a fictional illness policy with signs that need immediate parent contact, rules about returning after illness, medicine consent and how to record what was given.|signs listed;exclusion rule;medicine record|Medicine is given only with written parent permission, the dose and time are recorded, and a second staff member checks.
Childproof the environment|Young children explore with hands and mouths. A safe space prevents falls, burns, poisoning and choking.|Audit a fictional daycare room using a checklist for sockets, furniture, windows, cleaning products, small objects and hot items. List five fixes with owners.|hazards found;fixes;owners|Cleaning liquids are moved to a locked high cupboard, and sockets are covered with safe caps.
Plan first-aid readiness|First-aid skill must be learned from a certified trainer. A daycare keeps a stocked kit, clear procedures and trained staff, and knows how to call for help.|Prepare a fictional first-aid readiness plan: kit contents, trained staff list, emergency numbers, parent contact process and an incident record form. State that hands-on skills require certified training.|kit and training;emergency numbers;incident record|The incident form records what happened, what was done, who was told and the time, and parents sign to confirm they have been informed.
Support attachment and emotional security|Secure relationships help children feel safe to learn. Carers respond warmly and consistently and help children name feelings.|Plan how a fictional carer eases a two-year-old's separation at drop-off, including a goodbye routine, comfort object, parent guidance and what you do when crying continues.|goodbye routine;comfort;parent guidance|The parent says a short goodbye and does not slip away, which builds trust that the parent will return.
Safeguard children from harm|Child protection depends on safe recruitment, supervision, clear conduct rules and knowing how to report concerns.|Write a fictional safeguarding policy for a daycare with staff checks, supervision rules, visitor control, photo rules, what to do about a concern and who to inform. Note that current law applies.|safe recruitment;supervision;reporting|Visitors sign in and are never left alone with children, and phones are not used to photograph children without parent permission.
Write a daycare operations manual|An operations manual ensures consistent care, safety and communication, even when staff change.|Compile a fictional operations manual with daily schedule, ratios stated by local rules, health policy, meal plan, safety checklist, incident process, parent communication and staff training plan.|complete manual;safety;communication|The manual says how parents are told about an injury the same day and includes a monthly review of incident records to find patterns.'''),

dict(id='teaching-methods',summary='Plan and teach primary lessons well: development, objectives, literacy and numeracy, methods, assessment, remedial support, inclusion and family partnership.',icon='People',tool='notebook',tools=['notebook','board','canva'],
nodes=['Plan','Teach','Assess','Support'],modules=['Learners & objectives','Teaching methods','Assessment & feedback','Inclusion & support','Unit plan'],
src=dict(page='diploma-in-primary-education',code='IODPEP/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Child psychology','Child health care','Principles of primary education','Modern methods of teaching','Working with parents and community','Educational psychology']),
rows='''Use learner development to shape teaching|Children think and learn differently at different ages. Concrete examples and hands-on tasks suit younger primary learners.|For fictional children aged six and eleven, describe how their thinking differs and plan how to teach the idea of fractions to each with an appropriate activity.|age differences;concrete activity;adjustment|For a six-year-old, fractions are shown by folding paper into halves and quarters. An eleven-year-old can compare fractions on a number line.
Write learning objectives that can be checked|An objective states what the child will be able to do by the end of the lesson. It is observable and linked to the activity and the check.|Rewrite five vague aims for a fictional Grade 3 science lesson into measurable objectives and match each with an activity and a quick check.|measurable verbs;activity link;check|By the end of the lesson children can sort six objects into things that float and things that sink, and explain one reason.
Plan a complete lesson|A lesson has an opening, main activity, practice and closing. Timing and materials are prepared in advance.|Create a fictional 40-minute lesson plan on a reading comprehension passage with objective, materials, steps, questions, time for each part and a plan for early finishers.|timed steps;questions;early finishers|Ten minutes are used for a pre-reading discussion, fifteen for reading and questions and ten for pair work, with five minutes for a closing check.
Teach early reading with phonics|Phonics teaches the link between sounds and letters in a clear order. Practice with real words and short texts builds fluency.|Plan a fictional two-week phonics sequence for Grade 1, with sounds, blending practice, sight words and a short decodable text. Describe a quick daily check.|sequence;blending practice;daily check|After teaching s, a, t and p, children blend sat and tap, and read a short sentence made only of those sounds.
Teach number sense with concrete materials|Numbers are understood through objects, pictures and then symbols. Skipping the concrete step leaves gaps.|Plan a fictional lesson on place value for Grade 2 with counters, tens frames or bundles of sticks, pictorial drawings and written numbers. Include a task that reveals misunderstanding.|concrete to symbol;misconception check;materials|Children make 23 with two bundles of ten sticks and three single sticks, and a child who writes 5 for twenty-three shows a place value misconception.
Manage a lively classroom|Routines, clear instructions and positive attention reduce disruption. Problems are solved by understanding causes.|For three fictional classroom situations, noise during group work, a child refusing to start and frequent interruptions, write routines and calm responses you use and what you avoid.|routines;calm responses;avoided actions|A signal such as raised hand and silence gets attention without shouting, and the teacher practices it in the first week.
Use projects and role play|Project work and role play help children apply learning, speak and cooperate. They need clear goals, roles and assessment.|Design a fictional two-week project on a local market for Grade 4 combining maths, language and social studies, with roles, products, a rubric and a plan for fair group contribution.|clear goals;roles;rubric|Children price items in a mock market, write signs and present to the class, with a rubric for accuracy, teamwork and clear speaking.
Assess often and give feedback that helps|Formative assessment finds what children understand during teaching. Feedback should tell the child what to do next.|Create a fictional short quiz, an exit ticket and a feedback comment for a Grade 5 fractions lesson. Show how results change the next day's teaching.|quick checks;useful feedback;next-day change|If six of thirty children miss equivalent fractions, the teacher regroups them for a short reteach while others extend.
Support children who are behind and those who are ahead|Learners need different supports. A teacher plans small-group help and extensions without labelling children.|Plan a fictional remedial and extension plan for a class where five children cannot read fluently and four read well above grade. Include grouping, tasks, time and monitoring.|differentiated tasks;grouping;monitoring|Struggling readers practise with short texts three times a week, while advanced readers write a summary or question for a longer story.
Deliver a primary unit plan|A unit plan sequences lessons toward larger goals, with assessments, resources and a plan to involve families.|Package a fictional four-week Grade 3 unit with objectives, lesson sequence, assessments, differentiation, resources, home activities and a reflection plan.|sequence;assessment;family involvement|The unit ends with a poster presentation on plants, and families are asked to help find leaves for a collection.'''),

dict(id='school-management',summary='Lead and administer a school: governance, policy and law, curriculum, operations, finance, staff, safety, communication and development planning.',icon='Briefcase',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Lead','Plan','Operate','Review'],modules=['Leadership & policy','Curriculum & operations','Staff & finance','Safety & community','School development plan'],
src=dict(page='advanced-diploma-in-school-management',code='ADSM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['School management and leadership','Educational policies and regulatory framework','Curriculum planning and development','School operations and administration','Human resource management in schools','School marketing and public relations']),
rows='''Set a vision and measurable goals|A vision describes the school's purpose. Goals turn it into measurable aims that staff can work toward.|Write a vision statement and four measurable goals for a fictional primary school, with a baseline, target and date for each.|vision;measurable goals;baselines|The goal of raising the reading level means 60 percent of Grade 3 children read a grade-level passage fluently by March, from a baseline of 42 percent.
Understand the legal framework for schools|Schools must follow education law, board rules, child protection law and safety standards. Leaders keep records that show compliance.|List the main legal and regulatory duties of a fictional private school covering admissions, child protection, safety, staff qualifications and records, and name a document for each. Check current rules.|duties listed;documents;verification|The school keeps a register of staff qualifications and police verification so that it can show compliance during an inspection.
Handle admissions fairly|Admissions should follow published criteria and legal requirements. Transparent procedures reduce disputes.|Design a fictional admissions process with notice, application, selection method, document check, reserved places according to the law and record keeping. Describe how a rejection is communicated.|published criteria;legal obligations;records|The school publishes the number of seats and the selection method, and uses a lottery record signed by two staff members.
Build a timetable that works|A timetable balances subjects, teacher availability, rooms and rest. A clash means lost learning.|Create a fictional weekly timetable framework for classes 1 to 5 with periods per day, subject allocations, teacher constraints and how a substitute is arranged. Count weekly periods.|periods counted;clash check;substitute plan|With 7 periods a day and 5 days, each class has 35 periods, shared among languages, maths, environment, arts, games and library.
Prepare the school budget|A school budget plans income from fees and grants and spending on salaries, materials, maintenance and development. Salaries are usually the largest cost.|Prepare a fictional annual budget for a school of 300 students with fee income, salaries, utilities, learning materials, maintenance and a reserve. Calculate surplus and fee per student.|income and costs;reserve;per student|Fee income of 90 lakh against costs of 82 lakh and a reserve of 5 lakh leaves a surplus of 3 lakh. The fee per student is 30,000.
Recruit, support and appraise teachers|Good teachers are hired through fair processes, supported with training and appraised with clear feedback.|Plan a fictional cycle for one teacher: recruitment criteria, induction, classroom observation, feedback and a development plan. Include a respectful way to address poor practice.|selection criteria;observation;support plan|After an observation, the principal gives specific feedback, agrees one improvement target and arranges a visit to a colleague's classroom.
Keep children safe and prepared for emergencies|A school must protect children from harm, hazards and emergencies. Policies, drills and staff training make safety real.|Write a fictional school safety plan covering child protection policy, visitor control, fire and evacuation drills, first aid, transport safety and reporting incidents.|policy elements;drill schedule;reporting|Fire drills are held each term, and every class teacher knows the exit route and the assembly point for taking a headcount.
Use records and data for improvement|Attendance, results and incident data show patterns. Leaders use them to decide where to help.|From fictional attendance and test data for three classes, identify a pattern and propose an action with an owner and measure. Explain how you protect student privacy.|pattern found;action;privacy|Class 4B has lower attendance on Mondays. The class teacher phones absent families, and the target is a 3 point rise in a month.
Communicate with parents and the community|Clear communication builds trust. Parents want to know how their child is doing and what the school is doing about problems.|Plan a fictional parent communication calendar with a newsletter, parent meetings, a complaint route and a crisis message template. Include a response to an angry parent.|calendar;complaint route;crisis template|The crisis message states what happened, what is being done and when the next update comes, avoiding speculation.
Write a school development plan|A development plan sets priorities for the year, actions, owners, resources and measures, and is reviewed regularly.|Package a fictional one-year school development plan with three priorities, actions, owners, budget, timeline, risks and review dates.|priorities;owners and budget;review|The plan limits itself to reading, student attendance and teacher training, and states what the school will not take on this year.'''),

dict(id='counselling',summary='Guide students and clients ethically: listening skills, career assessment, education pathways, decision making, session records, referral and professional practice.',icon='People',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Listen','Assess','Plan','Review'],modules=['Counselling foundations','Assessment & pathways','Decision making & families','Sessions & records','Counselling practice file'],
src=dict(page='diploma-in-career-and-education-counseling',code='DCEC/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to career and education counselling','Student psychology and development','Career assessment tools and techniques','Educational pathways and career opportunities','Counselling techniques and session management','Professional practice and career advancement']),
rows='''Explain the counsellor's role and limits|A career counsellor helps people explore choices. A counsellor does not make decisions for them, diagnose illness or promise outcomes.|Write a short fictional explanation to a parent of what a career counselling session will and will not do, including confidentiality and its limits.|role clear;limits stated;confidentiality|The counsellor tells the parent that the student decides, the counsellor offers information and options, and a serious safety concern would have to be shared.
Listen and reflect before advising|Understanding comes before advice. Open questions and reflection show the person that they are heard.|Role-play a fictional student who says they have no idea what to do after school. Write six open questions and three reflecting statements that could follow, and one advising mistake to avoid.|open questions;reflection;advice delayed|You sound worried about choosing the wrong stream. What have you enjoyed learning so far? invites the student to speak without being pushed.
Recognise when to refer|Counsellors notice signs of distress that need professional help. A calm, caring referral protects the person.|Describe warning signs in a fictional student who is withdrawn and talking about hopelessness. Write what you say, what you record and who you inform, respecting local procedures and confidentiality limits.|warning signs;caring response;referral|The counsellor does not try to treat the problem but arranges for a qualified professional, informing a parent or guardian according to school policy.
Use career assessments carefully|Interest, aptitude and personality tools can start a conversation but cannot decide a future. Results depend on the quality of the tool and how it is used.|Review a fictional interest inventory result with three top codes. Explain what it suggests, what it cannot show and three questions you ask to test whether the results fit the student.|results explained;limits;follow-up questions|The result suggests an interest in helping and investigating, so the counsellor asks the student which activities they have actually enjoyed and in what situations.
Map education pathways|Students need to understand streams, courses, entrance routes, costs and timelines. Information must be accurate and current.|Create a fictional pathway map for a student after Grade 10 with streams, courses, entrance routes and decision dates, and note which details must be verified with official sources.|pathway options;dates;verification|The map shows that a stream choice affects later entrance options and tells the student to confirm eligibility rules on the official site.
Build a decision with a balance sheet|A decision tool lists benefits, costs, risks and values for each option so the person can compare them honestly.|Help a fictional student compare two course options using criteria such as interest, cost, future scope and family support. Create a weighted decision table and a next-step plan.|criteria weighted;options compared;next steps|The student gives interest a high weight, so the course with a slightly higher fee but stronger fit scores best, and the next step is a visit to the college.
Talk with parents about differing views|Parents and students may disagree. A counsellor helps each side listen and find shared concerns, without taking sides.|Plan a fictional joint meeting where a student wants design and parents want engineering. Write the opening, ground rules, questions for each and a compromise next step.|neutral opening;both heard;next step|The counsellor asks parents what they fear about design, and the student what they fear about engineering, then suggests exploring both before the deadline.
Plan and run a counselling session|A session has an opening, exploration, goals and a close. Time boundaries and notes keep it professional.|Create a fictional 45-minute session plan with rapport, issue exploration, goal setting, action plan and closing. Include how you handle a long silence.|session structure;goals;action plan|The counsellor lets the silence last a few seconds and then says Take your time. What is going through your mind?
Keep session notes and respect privacy|Notes record facts, agreed actions and follow-up, and are stored securely. They are shared only as allowed.|Write fictional session notes in SOAP-like order of issue, observations, plan and next date, and set rules for storage, sharing and disposal.|factual notes;secure storage;sharing rules|Notes record the student said they feel pressured by marks, not that the student is lazy, and are stored in a locked file accessible only to the counsellor.
Compile a counselling practice file|A practice file shows ethical, structured counselling work with reflections and supervision.|Assemble a fictional file with a case summary, assessment, pathway map, decision table, action plan, session notes, ethical issues and a reflection on what you would do differently. Remove any real data.|full cycle;ethics noted;reflection|The reflection records that the first session talked too much and the revised plan leaves more time for the student to speak.'''),
]
