COURSES=[
dict(id='financial-accounting',summary='Record transactions, balance the books, prepare financial statements, apply costing and budgeting, and understand tax, audit and controls for a small business.',icon='Chart',tool='budget',tools=['budget','data','sheets'],
nodes=['Record','Balance','Report','Control'],modules=['Accounting records','Adjustments & statements','Cost & budgets','Tax & compliance basics','Controls & year-end'],
src=dict(page='advanced-diploma-in-finance-and-accounts',code='ADFA/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Fundamentals of finance and accounting','Corporate accounting and financial reporting','Cost and management accounting','Taxation and GST','Financial management and banking operations','Auditing, compliance and financial technology']),
rows='''Classify transactions with the accounting equation|Assets equal liabilities plus capital. Every transaction changes at least two items and keeps the equation balanced.|For six fictional transactions of a new shop, state which items change, whether each rises or falls, and show that assets still equal liabilities plus capital after each one.|two sides identified;equation balanced;correct classification|The owner introduces 50,000 cash. Cash, an asset, rises by 50,000 and capital rises by 50,000, so the equation still balances.
Journalise, post and take out a trial balance|A journal records each transaction with its debit and credit. Posting to ledgers and listing balances checks that debits equal credits.|Journalise 10 fictional transactions for one week, post them to ledger accounts and prepare a trial balance. Say what a difference of 900 would tell you to check first.|journal entries;ledger posting;trial balance agrees|If debits exceed credits by 900 you check for a transposed figure or a half-posted entry, since a difference divisible by nine often means transposed digits.
Prepare a bank reconciliation statement|A cash book and a bank statement differ because of timing and unrecorded items. Reconciliation explains each difference.|The fictional cash book shows 52,300. Cheques issued but not presented are 9,000, a deposit not yet credited is 4,000, bank charges of 300 and a direct customer deposit of 2,000 are not in the cash book. Reconcile to the statement balance.|adjusted cash book;timing items;statement agrees|Adjusted cash book is 54,000 after charges and the direct deposit. Adding 9,000 and deducting 4,000 gives 59,000, which should equal the bank statement.
Calculate depreciation by two methods|Depreciation spreads the cost of an asset over its useful life. The method chosen changes the profit of each year.|A fictional machine costs 100,000, has a life of 5 years and a scrap value of 10,000. Calculate straight-line depreciation and the first two years at 20 percent on written-down value. Compare the profit effect.|straight-line figure;reducing balance;comparison|Straight-line is 18,000 each year. At 20 percent reducing balance it is 20,000 in year one and 16,000 in year two, which front-loads the expense.
Prepare final accounts with adjustments|Adjustments for accruals and prepayments make profit match the period it belongs to, not the period cash moved.|From a fictional trial balance with outstanding rent of 2,000 and prepaid insurance of 1,200, prepare a profit and loss figure and show where each adjustment appears on the balance sheet.|adjustments applied;profit calculated;balance sheet placement|Outstanding rent is added to expense and shown as a liability. Prepaid insurance is deducted from expense and shown as a current asset.
Build a simple cash flow statement|Profit is not cash. A cash flow statement explains why cash moved, starting from profit and adjusting for non-cash items and working capital.|Using fictional profit of 80,000, depreciation of 10,000, receivables up by 15,000 and payables up by 5,000, calculate cash from operating activities and explain why it differs from profit.|reconciled figure;adjustments explained;reasoning|The cash from operations is 80,000 plus 10,000 minus 15,000 plus 5,000, which is 80,000. The business was profitable but customers owe it money.
Use break-even and contribution analysis|Contribution is selling price minus variable cost. Break-even is the point where total contribution covers fixed cost.|A fictional product sells at 50 with variable cost 30 and fixed costs of 40,000. Find the break-even quantity and the margin of safety at 2,600 units. Say what happens if fixed costs rise.|contribution per unit;break-even quantity;margin of safety|Contribution is 20, so break-even is 2,000 units. At 2,600 units the margin of safety is 600 units, about 23 percent of sales.
Compare budget and actual and explain variances|A variance is the difference between plan and result. Its value is in the explanation and the action, not the subtraction.|Prepare a fictional monthly budget versus actual for sales, materials and wages. Mark each variance favourable or adverse and write one cause and one action for the largest.|variances calculated;favourable or adverse;cause and action|Materials cost 6,000 over budget. The cause is a price rise from the supplier, so the action is to request quotes from two other suppliers.
Design controls that reduce fraud and error|Controls separate duties, require approvals and record evidence. The person who prepares a payment should not approve it.|Design controls for a fictional payments process: supplier set-up, invoice matching, approval, payment and bank reconciliation. Identify two fraud risks and the control that addresses each.|segregation of duties;approval limits;fraud risks addressed|A supplier bank account change is confirmed by calling a known number before any payment, because a fake change request is a common fraud.
Deliver a year-end accounts and controls pack|A year-end pack shows the records, adjustments, statements and checks, and lists what remains uncertain for the owner or auditor.|Package a fictional business year-end: trial balance, adjustments list, financial statements, bank and ledger reconciliations, depreciation schedule, key ratios and a list of unresolved items.|statements agree;reconciliations attached;open items listed|The pack shows that the balance sheet balances and lists one unreconciled customer receipt of 3,200 that is still being traced.'''),

dict(id='gst-taxation',summary='Apply GST and basic income tax principles to invoices, credits, returns and records, and learn compliant tax practice for small businesses.',icon='Chart',tool='budget',tools=['budget','data','sheets'],
nodes=['Classify','Calculate','Reconcile','File'],modules=['Tax concepts & registration','Supply & invoicing','Input credit & returns','Income tax & deductions','Compliance practice'],
src=dict(page='gst',code='GST/Q0101',duration='Two Months',eligibility='12th Grade or equivalent',modules=['Introduction to GST','Registration and documentation','Supply under GST','Input tax credit','Returns and payment','Assessment, audit and legal provisions']),
rows='''Tell direct and indirect taxes apart|A direct tax is paid by the person on whom it is levied. An indirect tax is collected from the buyer and paid to the government by the seller.|Classify five fictional taxes as direct or indirect and explain who bears the burden and who pays the government in each case.|correct classification;burden and payer;examples|GST is charged to the customer on the bill but the seller deposits it, so the seller collects and the customer bears it.
Decide whether registration is needed|Registration depends on turnover thresholds, the type of supply and the place of business. The rules are official and change, so check the current rule.|For three fictional businesses, use the threshold stated in the case to decide if registration is required, list documents needed and name the portal where the application is made.|threshold applied;documents listed;official source|A small trader below the stated threshold with only local supply may not need registration. An online seller selling across states may need it regardless of turnover.
Split tax correctly between CGST SGST and IGST|Tax within a state is shared as central and state GST. Tax on a supply between states is charged as integrated GST. The place of supply decides which applies.|Use 18 percent for practice only. Calculate tax on a fictional supply of 10,000 within one state and the same supply to another state, and show the tax lines on each invoice.|intra-state split;inter-state tax;correct invoice lines|Within a state 9 percent central and 9 percent state tax gives 900 plus 900. To another state it is 1,800 of integrated tax. The total is the same.
Prepare a complete tax invoice|An invoice must show the details that let the buyer claim credit and the department verify the supply. Missing details can block the credit.|List the mandatory elements of a fictional tax invoice and prepare one for a sale of two items with different rates, showing taxable value, tax per line and total in figures.|mandatory fields;line-wise tax;total check|The invoice shows supplier and buyer tax numbers, invoice number and date, item codes, quantity, taxable value, rate, tax amount and place of supply.
Claim input tax credit only when conditions are met|Credit is allowed only if the purchase is for business, supported by a valid document, goods or services are received and the supplier has paid the tax.|Review eight fictional purchases and decide which credit is claimable. Give the condition each failed case did not meet, such as a personal use item or a supplier who did not file.|conditions applied;blocked cases;documentation|A purchase for the owner's family holiday is not business use, so its credit is not claimed even if the invoice is valid.
Handle reverse charge and exempt supplies|In some cases the buyer, not the seller, pays the tax. Exempt and nil-rated supplies do not carry output tax and affect credit.|Given the case rules, record a fictional purchase under reverse charge and one exempt sale. Show the tax liability, whether credit arises and the entry in the books.|reverse charge entry;exempt treatment;credit effect|Under reverse charge the buyer records the tax as payable and, if conditions are met, as credit in the same period, so the net cost is zero.
Reconcile books to returns|Returns must agree with the books and with what suppliers reported. Differences are investigated, not forced.|A fictional trader's sales register totals 5,00,000 but the summary return shows 4,80,000. Reconcile the 20,000 difference, decide whether to amend and describe the evidence to keep.|difference explained;amendment decision;evidence kept|A sale of 20,000 was entered in the books but omitted from the return. The next return corrects it with interest if the rules require.
Compute simple income tax and TDS|Taxable income is receipts minus allowed deductions. Tax deducted at source is an advance payment credited against final tax.|Using slabs and rates given in the case, compute tax for a fictional freelancer with 8,00,000 of receipts and 1,50,000 of eligible deductions. Show TDS already deducted and the balance payable.|taxable income;tax computed;TDS credit|Receipts less deductions give 6,50,000. Tax from the stated slabs is reduced by the 30,000 already deducted at source, leaving the balance to pay.
Separate legitimate planning from evasion|Planning uses reliefs the law provides. Evasion hides income or invents expenses. A professional refuses the second and records advice.|Review five fictional client requests, such as claiming personal expenses as business or issuing bills without sale, and mark each lawful planning or evasion. Write the response to one.|correct judgment;lawful alternative;written refusal|A request to issue an invoice for goods never supplied to claim credit is fraud. The professional refuses and explains the penalty risk to the client.
Deliver a monthly compliance file|A compliance file shows what was sold, bought, taxed and filed, with checks and open items, so any reviewer can follow the trail.|Package a fictional trader's month: sales and purchase registers, tax calculation, credit summary, reconciliation to books, return summary, payment record and a notice-response log.|registers agree;credit supported;open items|The file shows tax payable of 14,800 after credit, the payment reference, and one pending supplier invoice whose credit is deferred until the supplier files.'''),

dict(id='financial-management',summary='Make sound financial decisions with time value of money, ratios, capital budgeting, working capital, financing, valuation and risk analysis.',icon='Briefcase',tool='budget',tools=['budget','data','sheets'],
nodes=['Measure','Compare','Decide','Monitor'],modules=['Time value & statements','Ratios & working capital','Investment decisions','Financing & valuation','Risk & recommendation'],
src=dict(page='advanced-diploma-in-finance-management',code='ADFM/Q1001',duration='Six Months',eligibility="Bachelor's degree or equivalent",modules=['Principles of financial management','Financial accounting and reporting','Corporate finance and investment decisions','Financial markets and institutions','Investment and portfolio management','Financial risk management']),
rows='''Calculate future and present value|Money received sooner is worth more because it can earn a return. Comparing amounts at different times requires moving them to the same date.|For a fictional investor, calculate the future value of 1,00,000 invested for 3 years at 8 percent, and the present value of 1,00,000 due in 3 years at the same rate. Explain the difference.|future value;present value;interpretation|One lakh at 8 percent for 3 years grows to about 1,25,971. The present value of one lakh received in 3 years is about 79,383.
Read a balance sheet and cash position|Financial statements show what a business owns, owes and earns. Reading them together reveals whether it is healthy.|From a fictional balance sheet and profit statement, list three strengths and three concerns, citing the figures that support each.|figures cited;balanced view;question for management|Profit is rising but cash fell and receivables doubled, so management is asked how quickly customers pay.
Calculate and interpret ratios|A ratio compares two figures. It is only meaningful against the business's past and its peers.|Calculate current ratio, debt to equity and return on equity from fictional statements. Compare them with last year and a stated industry average and write a two-sentence conclusion.|three ratios;comparison;conclusion|A current ratio falling from 1.8 to 1.1 means short-term assets cover short-term debts much less comfortably than a year ago.
Manage working capital and the cash cycle|Working capital connects stock, receivables and payables. A longer cash cycle ties up money and forces borrowing.|Calculate inventory days, receivable days and payable days for a fictional trader and find the cash cycle. Propose two actions to shorten it and the risk of each.|three day-counts;cash cycle;actions and risks|With 45 inventory days, 30 receivable days and 40 payable days the cash cycle is 35 days. Pressing suppliers for longer terms can damage relationships.
Evaluate a project with payback and NPV|Payback ignores value after recovery and the time value of money. Net present value discounts all cash flows at the required return.|A fictional project costs 1,00,000 and returns 40,000 each year for 3 years. Use a 10 percent rate to find payback and NPV and decide whether to proceed.|payback period;NPV calculated;decision|Payback is 2.5 years. The present value of inflows is about 99,474, so NPV is about minus 526, a marginal reject at 10 percent.
Estimate a sensible cost of capital|Debt and equity cost different amounts and the average weighted by their share is the cost of capital. Cheaper debt raises financial risk.|A fictional firm has 40 percent debt at 9 percent before tax and 60 percent equity at 15 percent. With 25 percent tax on interest, calculate the weighted average cost of capital and comment on more debt.|after-tax debt cost;weights applied;risk comment|Debt after tax is 6.75 percent. The weighted cost is 0.4 times 6.75 plus 0.6 times 15, which is 11.7 percent.
Choose between ways to finance growth|Each source of finance has cost, control and risk. The choice should match the use of funds and the firm's cash flow.|For a fictional firm needing 20 lakh for equipment, compare a bank loan, owner equity, leasing and supplier credit on cost, control, repayment risk and speed. Recommend one.|four options compared;repayment risk;recommendation|A loan with fixed instalments suits equipment that earns steady cash. If sales are seasonal, the repayment schedule may need to follow the cash cycle.
Value a bond or share with explicit assumptions|A value is an estimate based on assumptions. Showing them lets others test and challenge your answer.|Value a fictional bond paying 80 yearly with 3 years left at a required yield of 10 percent, and a share expected to pay 5 growing 4 percent at a required return of 12 percent. State what each assumption drives.|bond value;dividend growth value;assumptions stated|The bond is worth about 950.3 and the share about 65.0. A small change in the required return moves the share value sharply.
Identify and respond to financial risks|Market, credit, liquidity and operational risks differ. Responding well starts with naming the risk and measuring its size.|For a fictional exporter with 2 crore of foreign receivables, list four risks, size one by scenario and propose a mitigation with its cost.|risks named;scenario sized;mitigation costed|If the foreign currency falls 5 percent before payment, the exporter loses about 10 lakh. A forward contract fixes the rate for a known cost.
Deliver an investment recommendation|A recommendation states the options, the numbers, the risks and the decision rule, and shows what would change the advice.|Prepare a fictional board paper recommending whether to buy a 25 lakh machine: cash flows, NPV, payback, financing, key risks, sensitivity to a 10 percent lower sales assumption and a clear decision.|numbers consistent;sensitivity tested;clear recommendation|The paper shows the project stays positive if sales fall 10 percent but turns negative at 20 percent lower sales, so the board sets a sales review point.'''),

dict(id='financial-planning',summary='Plan personal and family finances: budgets, goals, inflation, investments, tax, insurance, retirement and estate basics, with ethics and suitability.',icon='Briefcase',tool='budget',tools=['budget','sheets','notebook'],
nodes=['Goals','Cash flow','Protect','Grow'],modules=['Goals & budgeting','Risk & protection','Investing for goals','Tax & retirement','Estate & advice ethics'],
src=dict(page='diploma-in-financial-planning',code='DFP/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to financial planning','Investment planning','Tax planning and optimisation','Retirement planning','Risk management and insurance planning','Estate planning and wealth transfer']),
rows='''Turn life goals into costed financial goals|A financial goal has an amount, a date and a priority. Without these it cannot be planned or measured.|For a fictional family, convert three wishes into goals with a cost, deadline and priority: a child's college fund, a house deposit and an emergency reserve.|amount and date;priority order;assumptions|House deposit of 6,00,000 in five years needs about 10,000 each month with no growth assumed, which the plan states so it can be tested.
Build a budget and an emergency fund|A budget compares income and spending so surplus can be directed. An emergency fund covers unexpected costs without borrowing.|Prepare a fictional monthly budget for a household earning 60,000. Set a target emergency fund of 3 to 6 months of essential expenses and a savings rate.|income and expenses;fund target;savings rate|Essential costs of 35,000 a month make a 6-month emergency fund 2,10,000, kept in an easily accessible account.
Show the effect of inflation on a goal|Prices rise over time, so a future cost is higher than today's. A goal planned in today's money will be underfunded.|A fictional course costs 10 lakh today. Estimate its cost in 10 years at 6 percent inflation and the monthly savings needed if the money earns 7 percent, stating the assumptions.|inflated cost;monthly saving;assumptions|At 6 percent for 10 years the cost is about 17.9 lakh. The plan is rechecked each year because both rates are only assumptions.
Work out how much life cover a family needs|Life cover replaces the income a family would lose and clears debts. The need comes from the family's situation, not from a sales target.|For a fictional earner with 8 lakh income, a 20 lakh loan and two children, estimate cover using the income-replacement method. Subtract existing assets and cover.|income multiple;debts included;existing cover deducted|Ten years of income plus the loan, less existing savings and cover, gives the gap the policy should fill.
Understand health cover terms|Health policies differ in waiting periods, exclusions, limits and co-payment. A cheap premium can hide limited cover.|Compare two fictional health policies by sum insured, waiting period, room rent limit, co-payment and exclusions. Choose one for a 55-year-old and explain the trade-off.|terms compared;trade-off;suitable choice|A policy with a 10 percent co-payment has a lower premium but the family pays a tenth of every claim, which matters at older ages.
Match investment risk to goal and time|A goal due soon should not depend on assets that can fall sharply. Longer goals can accept more variation.|Allocate fictional savings between safer and growth assets for three goals of 1, 5 and 15 years. Explain the logic and what a 20 percent fall would do to each goal.|time horizon logic;allocation;fall impact|Money needed within a year stays in low-risk deposits. A 15-year goal can hold more growth assets because there is time to recover from a fall.
Plan tax-efficient saving without breaking the rules|Tax rules reward certain savings, but a tax saving is only worth having if the product also suits the goal. Use the rules stated in the case.|Using the deduction limits given in the case, plan a fictional person's yearly tax-saving choices. Check each for lock-in, risk and fit with goals before choosing.|limit respected;lock-in checked;goal fit|A product that locks money for 15 years is a poor fit for a goal due in three years, even if it saves tax.
Estimate a retirement corpus|A retirement plan estimates yearly expenses, years in retirement, inflation and returns. Small assumption changes make large differences.|For a fictional 35-year-old planning to retire at 60 with 6 lakh of yearly expenses in today's money, estimate expenses at retirement, a corpus using a stated withdrawal rate and monthly saving needed. Test a lower return.|inflated expenses;corpus target;sensitivity test|At 6 percent inflation, 6 lakh becomes about 25.8 lakh in 25 years. With a 4 percent withdrawal rate the corpus needed is about 6.4 crore.
Prepare the basics of estate planning|Nomination, joint holding and a will each do something different. A plan lists assets, wishes and documents so family can act.|For a fictional family, list assets, nominees, a will outline and where documents are kept. Explain the difference between a nominee and a legal heir and why both matter.|asset list;nominee versus heir;document location|A nominee receives the money to hold, but the legal heirs may still have a claim, so a will makes the owner's wishes clear.
Deliver a suitable plan with honest limits|A written plan lists facts, goals, assumptions, recommendations and risks. It must be suitable for the client and state that an authorised adviser is needed for regulated advice.|Package a fictional household plan: facts, goals, cash flow, protection gap, investment approach, tax notes, retirement estimate, assumptions, risks and a plain statement that this is education, not regulated advice.|assumptions visible;suitability reasoned;scope statement|The plan lists that returns are not guaranteed, shows two scenarios, and notes that a registered adviser must be consulted before buying any product.'''),

dict(id='stock-market',summary='Understand how securities markets work, read company information, assess risk and practise disciplined, paper-based decision making without real money.',icon='Chart',tool='budget',tools=['budget','sheets','notebook'],
nodes=['Understand','Analyse','Size risk','Review'],modules=['Market structure','Company analysis','Charts & derivatives','Risk & behaviour','Journal & review'],
src=dict(page='advanced-diploma-in-indian-stock-market',code='ADISM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to stock markets','Fundamental analysis','Technical analysis','Derivatives and options','Investment strategies and portfolio management','Intraday and swing trading']),
rows='''Explain how a share trade happens|A trade passes from a broker to an exchange, is matched, cleared and settled into a depository account. Each party has a role.|Trace a fictional purchase of 10 shares from order to settlement. Name the broker, exchange, clearing body, depository and regulator, and what each does.|roles named;order of steps;regulator role|The broker sends the order to the exchange, the clearing body guarantees settlement, and the shares appear in the buyer's depository account.
Tell primary and secondary markets apart|New securities are sold in the primary market. Later buying and selling between investors happens in the secondary market.|Classify five fictional events as primary or secondary and explain who receives the money in each. Include an initial offer and a trade on an exchange.|correct classification;money recipient;examples|In a public offer the company receives the money. When one investor sells to another on the exchange, the money goes to the seller.
Read company results with a few ratios|Earnings, price and debt together describe a company. A single ratio can mislead.|From fictional results, calculate earnings per share, price to earnings and debt to equity for two companies and say what each ratio suggests and does not prove.|three ratios;comparison;limits of ratios|A lower price to earnings may mean a bargain or may reflect expected decline. The ratio is a question to investigate, not an answer.
Estimate a value with stated assumptions|A valuation is a range from assumptions. Showing them lets you see which ones the value depends on.|Estimate the value of a fictional share using expected earnings and a range of three price to earnings multiples. Show which assumption changes the answer most.|value range;assumption sensitivity;margin of safety|With earnings of 20 per share, multiples of 12, 15 and 18 give 240, 300 and 360. The multiple matters more than small changes in earnings.
Read a price chart without over-reading it|Charts show past prices and volume. Patterns suggest possibilities but do not guarantee outcomes.|Describe a fictional chart with a rising trend, a moving average and a volume spike. State what the chart shows, what it does not show, and how you would test a pattern on past data.|observations separated;limits;back-test idea|A price above its 50-day average describes the past trend. It does not promise the next day's move.
Calculate an option payoff and its risk|An option gives a right, not an obligation, and its buyer's loss is limited to the premium. Sellers can face much larger losses.|For a fictional call option with strike 100 and premium 6, show profit or loss at expiry for prices 90, 100, 106 and 120. State the maximum loss for the buyer and the risk to the seller.|payoff table;break-even;seller risk|At expiry the buyer breaks even at 106. Below 100 the buyer loses the 6 premium. The seller's loss grows as the price rises.
Size positions and set exits before entering|A trade plan decides in advance how much to risk and where to exit. Risking too much on one trade can end the account.|With a fictional paper account of 5,00,000, risk 1 percent per trade. For an entry at 200 and a stop at 190, calculate the number of shares and the maximum loss if the stop works.|risk amount;position size;exit rule|Risk is 5,000. With a 10-point stop, 500 shares can be bought, so the planned loss is 5,000. Slippage or gaps can make the real loss larger.
Spot behavioural traps and scams|Fear, greed and overconfidence push people to poor decisions. Scammers use tips, guaranteed returns and urgency.|Analyse three fictional messages: a guaranteed return tip group, a request to deposit into a personal account and a fake trading app. Mark the warning signs and the safe response.|warning signs;safe response;verification step|No legitimate adviser guarantees returns. The safe step is to check the registration of any adviser or broker on the regulator's official website.
Keep a paper-trading journal and review it|A journal records the reason, plan and result of every decision. Reviewing it separates skill from luck.|Prepare a journal for 10 fictional paper trades with thesis, entry, stop, exit, result and lesson. Calculate win rate, average gain, average loss and what they imply together.|complete entries;statistics;lesson|Winning 4 of 10 trades can still be profitable if average wins are much larger than average losses, which the journal shows by calculation.
Deliver a risk-aware investment study|A study states the question, evidence, assumptions, risks and the exact conditions under which you would change your mind.|Package a fictional study of one company and a small paper portfolio: thesis, key numbers, valuation range, risks, position sizes, review dates and a statement that no real money or advice is involved.|thesis to numbers;risk limits;change-of-mind rule|The study states it will sell if debt to equity rises above the stated limit or if earnings fall two quarters in a row.'''),

dict(id='banking-lending',summary='Learn bank accounts, payments, KYC, credit appraisal, loan processing, mutual fund basics and customer-safe practice for banking and finance roles.',icon='Briefcase',tool='budget',tools=['budget','sheets','notebook'],
nodes=['Verify','Appraise','Decide','Serve'],modules=['Banking basics','Payments & customers','Credit appraisal','Loans & recovery','Funds & compliance'],
src=dict(page='certificate-in-banking-and-mutual-fund',code='CBMF/Q1001',duration='Three Months',eligibility='10+2 or equivalent',modules=['Introduction to the banking and financial system','Banking operations and services','Principles of mutual funds','Investment and portfolio management','Banking and mutual fund regulations','Credit and loan management']),
rows='''Match the right account to the customer|Accounts differ in purpose, cost and rules. A good recommendation fits how the customer actually uses money.|Recommend an account type for four fictional customers: a salaried worker, a shop owner, a student and a retiree. Give two reasons and one limit or charge to explain.|fit to customer;reasons given;charges disclosed|The shop owner has frequent deposits and cheques and needs a current account, accepting minimum balance rules that the salaried worker does not need.
Complete customer verification properly|Know-your-customer checks confirm identity and address before an account opens. They protect the customer, the bank and the public.|Create a verification checklist for a fictional new account: identity proof, address proof, photo, risk questions, record keeping and what to do if documents do not match.|documents checked;mismatch action;record kept|If the name on the address proof differs from the identity proof, the staff member asks for a supporting document rather than overriding the system.
Choose the right payment channel|Each channel has speed, limit, cost and reversibility. Advising correctly prevents failed or risky payments.|For four fictional payments, rent, a large property payment, a small shop bill and an urgent family transfer, choose a channel, state limits as given in the case and explain the risk if the wrong one is used.|channel chosen;limit respected;risk explained|A very large urgent payment suits a real-time gross channel. A small shop bill suits an instant mobile payment.
Respond safely to a suspected fraud|Speed matters in fraud. The customer is helped to block access, report it and keep evidence, and staff never ask for secrets.|A fictional customer reports an unauthorised transfer after sharing a one-time code. Write the steps: block the channel, record the facts, report, advise on evidence and explain what you will not ask.|immediate containment;evidence kept;secrets never requested|Staff never ask for a PIN or code. They block the card or app access and record the time of the transaction and the caller number.
Calculate a loan instalment and total interest|An equated monthly instalment combines principal and interest over the term. A longer term lowers the instalment but raises total interest.|For a fictional loan of 5,00,000 at 10 percent a year for 5 years, state the approximate monthly instalment and total paid, then compare with 3 years.|instalment;total interest;term comparison|At 5 years the instalment is about 10,624, so total paid is about 6,37,000. At 3 years the instalment is higher but total interest is lower.
Appraise a borrower with the five Cs|Credit appraisal asks about character, capacity, capital, collateral and conditions. A decision rests on evidence, not impressions.|Appraise a fictional small trader for a 3 lakh working capital loan using income evidence, existing loans, stock, collateral and market conditions. Recommend approve, modify or decline.|five Cs addressed;evidence cited;recommendation|Declared monthly income of 80,000 is supported by only 55,000 of bank credits, so the appraisal bases capacity on the lower proven figure.
Review a loan file before approval|A file must be complete, consistent and compliant. Missing documents and unexplained differences are resolved before money moves.|Check a fictional loan file with five planted problems, such as mismatched names, an expired document and an unsigned form. List each, its risk and the action required.|problems found;risk stated;corrective action|The applicant name differs between the application and the bank statement. The file is returned for clarification and not approved until it is explained.
Manage overdue accounts fairly|Early contact and honest options help customers repay. Recovery must follow policy and law, and respect the customer.|Plan the stages for a fictional account overdue by 30, 60 and 90 days, including reminders, a restructuring option and the point at which it is classed as non-performing. Describe respectful conduct.|stage plan;customer options;conduct rules|At 30 days a friendly reminder and call are made. After 90 days overdue the loan is classed as non-performing under the usual rule and special handling begins.
Explain mutual fund basics honestly|A mutual fund pools money in units whose value is the net asset value. Returns are not guaranteed and charges reduce them.|Explain to a fictional customer the NAV of a fund with net assets of 120 crore and 6 crore units, the effect of a monthly investment plan and the main risks. Avoid promises.|NAV calculated;SIP effect;risks stated|NAV is 120 crore divided by 6 crore units, which is 20 per unit. A monthly plan buys more units when the price is low and fewer when high.
Deliver a loan decision memo with compliance checks|A decision memo records the facts, the analysis, the policy checks and the reasons so another officer can audit the decision.|Package a fictional small business loan file: verification summary, income analysis, instalment affordability, collateral note, policy checklist, risk points and a recommendation with conditions.|facts to decision trace;policy checks;conditions set|The memo approves a reduced amount because the proven income supports an instalment of 12,000 rather than 18,000, and sets a condition to register the collateral before release.'''),

dict(id='insurance-advisory',summary='Advise on life and health insurance responsibly: needs analysis, product types, disclosure, claims, grievances and ethical selling.',icon='Shield',tool='notebook',tools=['notebook','budget','sheets'],
nodes=['Listen','Analyse','Explain','Follow up'],modules=['Insurance principles','Needs & products','Disclosure & suitability','Claims & service','Ethics & compliance'],
src=dict(page='certificate-in-life-insurance-advisor',code='CLIA/Q0101',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Introduction to insurance','Classification of insurance','Documents to apply for a policy','Protection of policyholders','AML and KYC guidelines','Premiums and claims']),
rows='''Explain what insurance is for|Insurance transfers a financial risk to a pooled fund in return for a premium. It protects against a loss, it is not an investment guarantee.|Explain insurance in plain words to a fictional first-time customer using one example for life, one for health and one for a motor vehicle. Say what each does and does not cover.|plain explanation;three examples;limits stated|A term life policy pays the family if the policyholder dies in the term. It does not pay anything if the policyholder lives, which is why it is cheap.
Apply the core insurance principles|Utmost good faith, insurable interest and indemnity shape every policy. Understanding them explains why claims are paid or refused.|Match each principle to a fictional claim scenario, including a person insuring a stranger's property, and explain the outcome of each case.|principle matched;scenario outcome;reasoning|A person has no insurable interest in a neighbour's house, so a policy on it would not be valid.
Find a customer's real protection need|A needs analysis asks about income, debts, dependants and existing cover. A product is recommended only after the gap is known.|Interview a fictional customer by writing ten questions. Then calculate a basic life cover gap from income, loan, dependants and savings, and say what other information you still need.|needs questions;gap calculated;missing information|Two dependants, a 15 lakh loan and ten years of income needed, less 10 lakh savings, leave a gap that the policy amount should be sized to cover.
Compare product types fairly|Term, endowment and unit-linked plans serve different purposes, with different costs, risks and benefits. Fair comparison shows all of them.|Compare a term plan, a savings plan and a market-linked plan on purpose, premium, maturity benefit, charges and risk for a fictional customer. State which fits the customer's stated goal.|purpose compared;charges disclosed;fit stated|A customer wanting pure protection at low cost is shown the term plan first, with a clear note that it has no maturity benefit.
Complete a proposal form with full disclosure|A policy rests on honest answers. Hiding a health condition or habit can lead to a claim being rejected later.|Review a fictional proposal form with three answers that look incomplete, such as smoking, a past surgery and income. Explain how you help the customer disclose accurately and why.|disclosure advice;risk of non-disclosure;customer helped|A customer who omits a past heart procedure risks a rejected claim. The advisor explains this and records the correct answer on the form.
Explain health policy exclusions and waiting periods|Many policies delay cover for existing conditions and exclude some treatments. Customers must understand this before buying.|Prepare a one-page explanation for a fictional family of waiting periods, exclusions, co-payment and sub-limits, with two examples of a claim that is paid and one that is reduced.|terms explained;example claims;reduction case|A hospital room above the policy's rent limit can reduce the whole claim proportionally, not only the room charge, so the limit is explained before purchase.
Guide a claim from first notice to settlement|Claims go smoothly when the customer reports promptly and gives the right documents. The advisor supports but does not promise the outcome.|Write the steps and document list for a fictional hospital claim: intimation, cashless request, discharge papers, bills, reports and follow-up. Explain what you say if the insurer queries a document.|claim steps;document checklist;honest follow-up|If the insurer asks for earlier treatment records, the advisor helps gather them and tells the customer the claim is under review, not approved.
Handle complaints and grievance routes|Customers have routes to complain. Good service resolves the issue early and explains escalation honestly.|A fictional customer says a claim was wrongly refused. Write your response, the steps in the insurer's grievance process, the next escalation and what you must not promise.|empathy and facts;escalation path;no false promise|The advisor records the complaint, gives the reference number and timeline, and explains the escalation route without predicting that the claim will be paid.
Sell ethically and protect customer data|Ethical selling means recommending what fits, disclosing costs, not misleading and keeping personal data safe.|Review five fictional sales lines, such as guaranteed double returns or limited time offer, and rewrite each into an honest statement. Add the data-protection steps for a customer's health documents.|misleading lines found;honest rewrites;data protection|Guaranteed double returns is false for a market-linked plan. The honest line explains that returns depend on markets and charges apply.
Deliver a complete advice file|An advice file proves the customer was heard, the need was analysed, the product was explained and the disclosures were made.|Package a fictional customer file: fact find, needs calculation, products compared, recommendation and reasons, signed disclosures, claims guidance and a service follow-up date.|need to product trace;disclosures recorded;follow-up planned|The file shows why a term plan was recommended, records that the customer was told it pays no maturity benefit, and sets a policy review for twelve months later.'''),

dict(id='international-economy',summary='Understand global trade, exchange rates, financial markets, international institutions and banking, and write evidence-based economic briefs.',icon='Briefcase',tool='notebook',tools=['notebook','sheets','budget'],
nodes=['Observe','Compare','Explain','Advise'],modules=['Trade foundations','Policy & institutions','Exchange rates','Global finance','Economic briefing'],
src=dict(page='diploma-in-international-economy-and-finance',code='DIEF/Q1001',duration='Six Months',eligibility="Bachelor's degree or equivalent",modules=['Fundamentals of international economics','International trade and policy','Global financial markets and institutions','Foreign exchange and currency markets','International monetary systems and policies','Global banking and financial services']),
rows='''Show why countries trade with comparative advantage|A country gains from specialising in what it produces at the lowest opportunity cost, even if another country is better at everything.|Using fictional output of cloth and grain per worker in two countries, calculate the opportunity cost for each and show a trade that leaves both better off.|opportunity costs;gain shown;assumptions|If one country gives up less grain to produce each unit of cloth, it specialises in cloth and trades, even though the other country may be more productive overall.
Read a balance of payments table|The balance of payments records a country's transactions with the world. Its parts show how a deficit is financed.|Interpret a fictional table with exports, imports, remittances, investment inflows and reserves change. Say whether the current account is in deficit and how it is financed.|current account;financing;interpretation|Imports exceed exports by 30 billion and remittances reduce the gap, leaving a deficit financed by investment inflows and a fall in reserves.
Predict who gains and loses from a tariff|A tariff raises the price of imports. It helps domestic producers and the government but costs consumers and can invite retaliation.|Analyse a fictional 20 percent tariff on imported steel. Identify gainers, losers, the effect on a steel-using manufacturer and one possible retaliation.|gainers and losers;downstream effect;retaliation|Domestic steel makers gain, but a pipe manufacturer buying steel faces higher costs and may raise prices or sell less.
Explain what trade agreements and institutions do|Trade agreements lower barriers between members and international bodies set rules and settle disputes. They also create obligations.|Describe a fictional free trade agreement between two countries: what is liberalised, what is excluded, rules of origin and a dispute step. Explain one benefit and one concern.|scope described;rules of origin;benefit and concern|Rules of origin stop a third country from sending goods through a member to avoid tariffs by requiring a minimum local content.
Calculate the effect of an exchange rate change|An exchange rate sets the home price of foreign goods and the foreign price of home goods. A change shifts costs and competitiveness.|If a fictional importer buys 1,00,000 dollars of goods when the rate is 83 and later 85, calculate the extra cost. Explain the effect on an exporter paid in dollars.|rupee cost before and after;exporter effect;risk|The same goods cost 83,00,000 at 83 and 85,00,000 at 85, an extra 2,00,000 for the importer. The exporter receives more rupees.
Hedge a currency exposure and know its cost|A forward contract fixes a future rate. It removes uncertainty but also removes the chance of a better rate.|A fictional exporter expects 50,000 dollars in 3 months. Compare leaving the exposure open with a forward at a quoted rate, and describe a scenario where the hedge looks costly afterwards.|exposure identified;hedge compared;regret scenario|If the dollar later rises, the unhedged exporter would have earned more, but the hedged exporter knew the price in advance and could plan.
Explain inflation and interest rate effects|Central banks use interest rates to influence inflation and growth. A rate change spreads through borrowing, saving and exchange rates.|Trace the effects of a fictional interest rate rise on a household loan, business investment, the currency and inflation. Mention one delay and one side effect.|transmission steps;delay;side effect|A rate rise makes loans costlier, which slows spending, but the effect on prices takes months to appear.
Separate direct investment from portfolio flows|Direct investment builds long-term assets. Portfolio flows move quickly and can leave in a crisis, which makes them riskier for stability.|Compare a fictional foreign factory investment and a foreign purchase of shares. Describe permanence, benefits to the country and the risk of a sudden outflow.|both flow types;permanence;stability risk|A factory is hard to move, so it stays through a shock. Shares can be sold in a day, which can strain the currency.
Learn from a financial crisis case|Crises usually grow from borrowing, confidence and exposure to sudden outflows. A timeline separates the trigger from the underlying weakness.|Build a timeline for a fictional country crisis: rising short-term foreign debt, a falling currency, reserve loss and policy response. Identify the weakness, the trigger and one lesson.|timeline built;weakness versus trigger;lesson|The trigger was an investor withdrawal, but the weakness was short-term debt that exceeded reserves, so the lesson is to watch that ratio.
Write a country trade and finance brief|A brief tells a decision-maker what happened, why it matters and what to watch, using sourced data and honest limits.|Prepare a fictional two-page brief on one country's trade position with three indicators, a trend, two risks, a currency note and sources to verify. State what the data cannot show.|indicators with sources;risks;limits stated|The brief cites the official release for each figure, flags that the latest quarter is provisional, and says the data cannot show how the trade deficit will respond to the next policy change.'''),

dict(id='quantitative-techniques',summary='Use statistics, probability, forecasting and optimisation to support business decisions, with careful interpretation and honest limits.',icon='Chart',tool='data',tools=['data','sheets','notebook'],
nodes=['Describe','Model','Optimise','Decide'],modules=['Describing data','Probability & sampling','Relationships & forecasting','Optimisation & decisions','Decision report'],
src=dict(page='diploma-in-quantitative-techniques-in-business',code='DQTB/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to quantitative techniques','Correlation and regression','Probability and probability distributions','Time series and index numbers','Sampling','Univariate data analysis']),
rows='''Summarise data with the right measures|Mean, median and mode describe the centre of data. Spread tells how far values vary. The best measure depends on the shape.|For fictional monthly sales of 20, 22, 21, 23, 20, 95, calculate the mean, median and range. Say which centre measure better describes a typical month and why.|three measures;outlier effect;choice justified|The mean is 33.5 but the median is 21.5. The one large month pulls the mean up, so the median describes a typical month better.
Choose and read a distribution chart|A histogram shows how often values fall in ranges. Its shape signals skew, outliers and whether averages are reliable.|Group 30 fictional delivery times into five bins and describe the shape. Say whether the average or the median should be reported and what a manager should ask.|bins chosen;shape described;measure choice|Most deliveries fall in 2 to 3 days with a long tail to 9 days, so the report shows the median and asks about the late tail.
Calculate simple and conditional probability|Probability is the share of favourable outcomes. Conditional probability changes when new information is known.|In a fictional batch, 60 percent of items come from machine A with 2 percent faults and 40 percent from machine B with 5 percent faults. Find the probability a random item is faulty, and that a faulty item came from A.|total probability;conditional probability;check|Faulty chance is 0.6 times 0.02 plus 0.4 times 0.05, which is 0.032. Given a fault, the chance it came from A is 0.012 divided by 0.032, about 37.5 percent.
Judge a sample before trusting it|A sample is only useful if it represents the population. Bias in how people are chosen cannot be fixed by making the sample larger.|Review three fictional surveys, an online poll, a street survey in one area and a random draw from customer records. Identify bias and design a better sampling plan.|bias identified;population defined;better plan|Asking only customers who come to the shop on weekends misses weekday customers, so a random sample from all invoices is used instead.
Fit a line and interpret the relationship|Regression estimates how one measure changes with another. A strong fit does not prove causation, and predictions beyond the data are unsafe.|For fictional data on advertising spend and sales, calculate a correlation by tool or by hand, fit a line and predict one value inside the range. Say why a prediction far outside the range is risky.|relationship measured;prediction in range;extrapolation risk|A line fitted to spend of 1 to 5 thousand should not be used to promise sales at 50 thousand, where behaviour may be completely different.
Forecast a series and measure the error|A forecast should be compared with what actually happened. A simple method that is checked beats a complex one that is not.|Using fictional monthly demand for 12 months, forecast the next 3 months with a 3-month moving average and calculate the error for the last 3 known months. State one risk of the method.|forecast made;error measured;method risk|A moving average lags behind a steady rise, so the error is consistently negative and the method is replaced if demand is trending.
Build an index to compare prices over time|An index compares a basket of goods with a base period. Weights decide which price changes matter most.|Construct a simple weighted price index for three fictional goods with base and current prices and quantities. Interpret a value of 112 and name one limitation.|weighted calculation;interpretation;limitation|An index of 112 means the basket costs 12 percent more than in the base period, but the basket may not match every household's spending.
Solve a two-variable optimisation problem|Linear programming finds the best result within limits. The optimum lies at a corner of the feasible region.|A fictional workshop makes chairs with profit 30 and tables with profit 50 under 120 machine hours (2 and 3 hours) and 70 wood units (1 and 2). Find the best mix at the corners.|constraints written;corner points;best mix|The corners give profits of 1,800, 1,750 and 1,900. The best mix is 30 chairs and 20 tables for a profit of 1,900.
Choose under uncertainty with expected value|Expected monetary value weights outcomes by their chance. It guides a decision but ignores a person's tolerance for loss.|For two fictional options, Option A pays 1,00,000 with 60 percent chance and loses 20,000 with 40 percent chance. Option B pays a sure 40,000. Compute expected values and discuss when the decision might change.|expected value;comparison;risk attitude|Option A has an expected value of 52,000, which beats the sure 40,000. A business that cannot survive a 20,000 loss might still choose B.
Deliver a decision report built on numbers|A decision report presents the question, the method, the result, the sensitivity and the recommendation in plain language.|Package a fictional report recommending the product mix for a workshop: data, assumptions, calculations, sensitivity to a 10 percent change in profit, recommendation and limits.|method visible;sensitivity checked;clear recommendation|The report states that the mix changes if table profit falls below 45, so the owner reviews pricing before changing production.'''),
]
