COURSES=[
dict(id='construction-supervision',summary='Supervise building work: roles, materials, drawings, quantities, planning and critical path, safety, quality inspection, cost control, sustainability and site communication.',icon='Cube',tool='data',tools=['data','sheets','budget','notebook','board'],
nodes=['Plan','Coordinate','Inspect','Control'],modules=['Supervision foundations','Drawings & quantities','Planning & scheduling','Quality & safety','Cost & site leadership'],
src=dict(page='diploma-in-construction-supervisor',code='DCS/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to construction supervision','Building materials and construction techniques','Construction safety and site supervision','Construction drawings and equipment','Structural engineering and project planning','Quality control, inspection and cost estimation']),
rows='''Define the supervisor's role and chain of command|A supervisor turns plans into daily work, coordinating labour, materials and inspections. Clear authority and communication prevent confusion and rework.|Write a fictional role description and daily routine for a site supervisor on a four-storey residential block, including reporting lines, decisions they may make alone and decisions they must refer.|role clear;limits stated;routine listed|The supervisor may stop unsafe work immediately but must refer a change in structural steel to the engineer.
Choose and check common materials|Cement, sand, aggregate, bricks and steel must meet quality needs before use. Storage and testing protect strength and cost.|Create a fictional material inspection checklist for cement, sand, bricks and reinforcement bars, with what to check on delivery, how to store each and what to do with rejected material.|checks listed;storage rules;rejection step|Cement bags are stacked off the floor in a dry store, and damp or lumpy bags are rejected and recorded.
Read drawings and specifications|Plans, sections and schedules tell the team what to build. The specification adds quality requirements, and conflicts must be clarified before work.|Using a fictional plan and a column schedule, list ten items a supervisor checks before a column pour, including dimensions, bar sizes, cover and levels. Mark one conflict and how you raise it.|ten checks;conflict identified;escalation|The plan shows a 230 millimetre wall but the schedule shows a 300 millimetre column, so the supervisor queries the engineer before shuttering.
Measure and estimate quantities|Quantities of concrete, bricks and plaster drive cost and orders. Careful measurement avoids shortages and waste.|Calculate the concrete volume for a fictional slab 6 by 4 metres and 150 millimetres thick, and the cement bags needed for a 1:2:4 mix using a dry volume factor of 1.54 and 0.035 cubic metres per bag.|volume computed;dry volume;bags rounded up|Volume is 3.6 cubic metres, dry volume 5.544, cement share one seventh gives 0.792, and 0.792 divided by 0.035 is about 23 bags.
Plan work and find the critical path|A schedule shows the order and duration of tasks. The critical path is the longest chain, so delays there delay the project.|Draw a fictional network where task A takes 3 days, B takes 4 after A, C takes 6 after A and D takes 2 after both B and C. Find the critical path and the float on B.|network drawn;critical path found;float computed|The path A, C, D takes 11 days, B has path A, B, D of 9 days, so B has 2 days of float.
Coordinate trades and manage site meetings|Many trades work in the same space, and poor coordination causes clashes and delay. A short regular meeting with a clear record keeps everyone aligned.|Prepare a fictional weekly coordination meeting agenda and a one-page action record for masonry, plumbing, electrical and plastering teams working on one floor.|agenda clear;actions owned;dates set|The record assigns the plumber to complete pipe chasing by Wednesday before plastering begins on Thursday.
Control quality with inspections and hold points|Hold points stop work until an inspection passes. Records show what was checked and by whom.|Create a fictional inspection and test plan for reinforcement, shuttering, concrete pour and curing, including hold points, accept criteria and records.|hold points;criteria stated;records|Concrete is not poured until the engineer signs the reinforcement checklist, and curing starts within the specified time.
Supervise safety, equipment and waste|Safety, machine use and waste are daily duties. A supervisor leads by checking, not only by instruction.|Write a fictional morning safety talk and equipment check for a mixer, a hoist and scaffolding, and a plan to separate site waste into reusable, recyclable and disposal streams.|talk written;equipment checked;waste separated|Bricks broken in cutting are reused for fill and metal offcuts are collected for recycling.
Handle a design change, delay or dispute|Sites change. A supervisor records instructions, assesses time and cost effects, and keeps the paper trail that settles disputes.|Manage a fictional case where the owner asks to move a door after the brickwork is up and rain delays plastering by 4 days. Write the change record, the revised programme and the message to the client.|change recorded;impact stated;message professional|The record shows 3 days of rework and 6000 of extra cost, and work proceeds only after the client signs approval.
Track cost and productivity|Actual progress and cost are compared with plan. Variances show problems early.|Compare fictional planned and actual figures: a wall planned at 120 square metres per day for 5 days at 18000 daily labour, but only 450 square metres done in 5 days at the same cost. Compute the productivity and cost variance.|productivity computed;variance found;cause noted|Planned output was 600 square metres, actual 450 is 75 percent, so the cost per square metre rose from 150 to 200.'''),
dict(id='electrical-safety',summary='Understand and reduce electrical risk: shock, arc flash and fire hazards, standards, earthing, protection devices, lockout, testing, first aid awareness and safe maintenance planning.',icon='Shield',tool='notebook',tools=['notebook','sheets','data','board'],
nodes=['Identify','Isolate','Test','Verify'],modules=['Electrical safety foundations','Hazards & risk assessment','Installations & practice','Fire, shock & emergencies','Maintenance & testing'],
src=dict(page='diploma-in-electrical-safety',code='DES/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Fundamentals of electrical safety','Electrical hazards and risk assessment','Electrical installations and safe work practices','Fire and explosion hazards in electrical systems','Electrical shock prevention and first aid','Safety in electrical maintenance and testing']),
rows='''Apply basic electrical laws to understand danger|Voltage, current and resistance explain why shock can be harmless or deadly. Wet skin has much lower resistance than dry skin.|Using the formula current equals voltage divided by resistance, calculate the fictional current through a body at 230 volts if resistance is 100000 ohms dry and 1000 ohms wet, and explain the safety lesson.|formula applied;two values;lesson stated|Dry skin gives 2.3 milliamps and wet skin gives 230 milliamps, which is why wet areas need extra protection.
Describe the effects of electric current on the body|Current level and duration decide injury. Even small currents can cause involuntary muscle contraction, and a severe shock needs urgent medical care.|Prepare a fictional awareness chart of effects from tingling to cardiac arrest with approximate current ranges from a recognised source, and state that every shock must be reported and checked.|effects ordered;source cited;report rule|A chart notes that a person who cannot let go of a conductor may be held by muscle contraction, so isolation comes first.
Identify shock, arc flash and fire hazards|Electrical work may involve contact shock, arc flash and fire. Each hazard has different controls, and the worst case is considered.|Walk through a fictional switch room and list ten hazards grouped as shock, arc flash, fire and mechanical, each with a likely cause.|ten hazards;groups used;causes named|A missing panel cover is a shock hazard and an overloaded cable is a fire hazard.
Carry out a risk assessment for electrical tasks|A risk assessment rates likelihood and consequence and decides controls. De-energised work is preferred over live work.|Assess five fictional tasks, such as replacing a socket, testing a panel and cable trenching, with a 5 by 5 matrix and controls, and decide which must be done only when de-energised.|tasks scored;controls chosen;de-energise rule|Testing a live panel scores high and requires a qualified person, correct PPE and a second person present.
Use earthing, RCDs and protective devices|Earthing and residual current devices limit shock risk, and fuses and breakers protect against overload. They need testing to remain reliable.|Explain with a fictional home circuit how an earth connection, a 30 milliamp RCD and a 16 amp breaker each protect and list the monthly tests an owner should do.|three devices explained;tests listed;limits stated|A 30 milliamp RCD trips when leakage current reaches that level, but it does not replace safe behaviour.
Plan lockout-tagout and safe isolation|Isolation proves a circuit is dead before work. Lock, tag, test and verify prevent accidental energising.|Write a fictional safe isolation procedure with the steps of identify, switch off, lock, tag, test the tester, test the circuit and test the tester again, plus who may remove the lock.|steps in order;proving unit used;lock owner|Each worker places a personal lock, and only that worker removes it at the end of the job.
Prevent electrical fires|Fires start with overload, loose connections, damaged insulation and poor ventilation. Inspection and load control reduce them.|Calculate the load on a fictional 16 amp circuit at 230 volts when three appliances of 2000, 1500 and 800 watts run together, and say what action is needed.|load computed;limit compared;action given|The total is 4300 watts, which is 18.7 amps, over the 16 amp rating, so the loads are spread across circuits.
Respond to shock and burn emergencies|The first priority is to make the area safe before touching a casualty. Call for help, check breathing and start CPR if trained.|Prepare a fictional emergency card for a person who is still in contact with a live conductor, with steps in order, who to call, and what not to do. Note that first aid needs hands-on training.|safe first;call help;training note|The card says to switch off at the isolator or use dry non-conductive material only if switching off is impossible, and to call emergency services.
Run an electrical safety audit and rank the findings|An audit samples installations against a standard. Findings are ranked so urgent risks are fixed first.|Audit a fictional workshop with twelve items including damaged leads, missing covers, unlabelled isolators and blocked panels. Rank findings by risk and set owners and due dates.|twelve items;risk ranked;owners assigned|A panel with a missing cover is ranked critical and fixed the same day, while missing labels are scheduled for the week.
Maintain, test and document equipment|Testing finds faults before they injure people. Records show test dates, results and corrective actions.|Create a fictional test schedule and result record for insulation resistance on motors, thermal checks on panels and battery room checks, with pass limits and actions on failure.|schedule set;limits stated;actions|A motor with insulation resistance below the minimum limit is taken out of service until repaired.'''),
dict(id='disaster-management',summary='Plan for and respond to disasters: hazard types, risk and vulnerability, early warning, shelter and relief planning, incident command, psychosocial support, recovery and community resilience.',icon='Compass',tool='data',tools=['data','notebook','board','sheets','budget'],
nodes=['Assess','Prepare','Respond','Recover'],modules=['Disaster foundations','Hazards & risk','Response & logistics','Health, command & climate','Recovery & community'],
src=dict(page='diploma-in-disaster-management',code='DDM/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to disaster management','Natural and man-made disasters','Disaster risk assessment and emergency response','Medical and psychological aspects of disaster management','Climate change and environmental hazards','Post-disaster recovery and rehabilitation']),
rows='''Describe the disaster management cycle|Disaster management has phases of mitigation, preparedness, response and recovery. Each phase has its own actions, and good work in earlier phases reduces harm later.|Place twelve fictional actions, such as building embankments, running drills, opening shelters and rebuilding schools, into the correct phase and explain each placement.|twelve actions;phases correct;explanations|Running a community drill is preparedness, and rebuilding a school with safer design is recovery.
Distinguish hazard, exposure, vulnerability and capacity|A hazard becomes a disaster when it meets exposed, vulnerable people with limited capacity. This explains why the same flood harms some communities more.|Compare two fictional villages facing the same flood, one with raised houses and an alarm and one without, and rate hazard, exposure, vulnerability and capacity from 1 to 5.|four factors rated;comparison made;conclusion drawn|The village with raised houses and an alarm rates vulnerability 2 and capacity 4, so the expected harm is lower.
Prepare a hazard and vulnerability map|Maps show where hazards and vulnerable people are. They guide planning and are most useful when the community helps make them.|Plan a fictional participatory mapping session for a coastal ward with layers for flood zones, elderly residents, shelters and roads, and list how you will keep personal data safe.|layers planned;community involved;data protected|The ward map marks elderly residents by block rather than by name to protect privacy.
Design an early warning and communication chain|An early warning system works only if warnings reach people in time and in a form they trust. Roles, channels and messages must be clear.|Write a fictional cyclone warning chain from the weather office to households with channels, languages, message wording and times, and check that a household receives it at least 12 hours ahead.|chain mapped;message plain;lead time checked|The district office sends the alert at 18 hours, the sirens and local volunteers pass it on within 2 hours, and households have 16 hours.
Plan shelters, water and sanitation|Shelters need space, water, toilets and safety. Minimum standards guide planning, and special needs are planned early.|Calculate for a fictional camp of 600 people the covered space at 3.5 square metres each, water at 15 litres each per day and toilets at 1 per 20 people, and add a plan for disabled and elderly residents.|space computed;water computed;toilets computed|The camp needs 2100 square metres, 9000 litres of water a day and 30 toilets, with accessible toilets near the entrance.
Organise search, rescue and first response safely|Rescue is dangerous, so untrained people avoid unsafe entry. Teams use roles, equipment and communication to protect rescuers.|Create a fictional first-response guide for a flood that says what community volunteers can do safely, what must be left to trained teams and how to hand over to the authorities.|safe actions;limits;handover|Volunteers check on neighbours from safe ground and call trained teams instead of entering fast water.
Use incident command and coordinate agencies|An incident command system defines roles for command, operations, planning, logistics and finance. It prevents duplication and gaps.|Draw a fictional command structure for a landslide response and write a one-page situation report format with needs, resources and next actions.|roles shown;report format;needs listed|The situation report lists affected households, road status, shelter occupancy and urgent supply needs.
Support psychological recovery and public health|Disasters affect mental and physical health. Psychological first aid offers comfort and practical help, and disease risk rises when water and sanitation fail.|Plan a fictional psychological first aid session for survivors, with listening principles, what to say, what to avoid and when to refer for specialist care.|principles stated;avoid list;referral|The volunteer does not press for details and refers a person with severe distress to a health worker.
Evaluate a community preparedness drill|A drill tests plans and exposes gaps. A good evaluation records times and decisions and leads to changes in the plan.|Evaluate a fictional earthquake drill in a school of 450 students with a target of evacuating in 4 minutes. Record 5 minutes 20 seconds, list problems and set three improvements.|timing compared;problems listed;improvements set|The drill took 80 seconds longer than target because one stair was blocked, so the stair is cleared and signed.
Plan recovery, rehabilitation and lessons learned|Recovery rebuilds in safer ways. Lessons from the event feed future plans.|Prepare a fictional recovery plan for a flooded village with housing, livelihoods, school and health actions, a budget table of 5000000, and a method for community feedback.|actions listed;budget allocated;feedback method|Housing receives 2000000, livelihoods 1200000, school repair 1000000, health 500000 and monitoring 300000, which totals 5000000.'''),
dict(id='food-quality',summary='Check and control food safety and quality: hazards, microbiology, hygiene, HACCP, standards, preservation, temperature control, labelling, audits and corrective action.',icon='Shield',tool='data',tools=['data','notebook','sheets','board'],
nodes=['Identify','Control','Verify','Correct'],modules=['Food safety foundations','Microbiology & hygiene','HACCP & systems','Processing & packaging','Audit & public health'],
src=dict(page='certificate-in-food-quality-control-inspection',code='CFQCI/Q1001',duration='Three Months',eligibility='10+2 or equivalent',modules=['Introduction to food safety','Microbiology and foodborne pathogens','Food hygiene and sanitation practices','Food safety management systems','Food processing and preservation techniques','Foodborne disease prevention and public health']),
rows='''Classify food hazards|Food can be unsafe because of biological, chemical, physical or allergen hazards. Naming the hazard is the first step in controlling it.|List fictional hazards for a small bakery and a dairy counter and group them as biological, chemical, physical and allergen, with a likely source for each.|hazards grouped;sources named;allergens included|A piece of metal from a damaged sieve is a physical hazard, and undeclared nuts are an allergen hazard.
Understand how microbes grow in food|Microbes need nutrients, moisture, warmth and time. The temperature danger zone is where many bacteria grow fastest.|Using the fictional rule that a bacterium doubles every 20 minutes, calculate the number after 3 hours from a starting count of 100 and explain why chilling and hot holding matter.|doubling computed;result explained;control linked|Three hours is nine doublings, which gives 100 times 512, or 51200, so food is kept cold or hot rather than left at room temperature.
Practise personal hygiene and cleaning|Hands and surfaces spread contamination. Cleaning removes dirt and sanitising reduces microbes, in that order.|Write a fictional hygiene procedure for handwashing, protective clothing, cleaning and sanitising a slicer, including contact time and who verifies.|steps ordered;contact time;verification|The slicer is cleaned with detergent, rinsed and then sanitised for the stated contact time before reuse.
Prevent cross-contamination|Raw and ready-to-eat foods must stay apart. Colour coding, separate tools and storage order reduce risk.|Design a fictional kitchen layout and fridge storage order for raw meat, dairy, cooked food and vegetables, with colour-coded boards and a rule for allergen foods.|layout clear;storage order;colour coding|Raw meat is stored on the lowest shelf so juices cannot drip onto cooked food.
Apply HACCP principles|HACCP finds hazards, sets critical control points, limits, monitoring and corrective actions. It is a system of prevention.|Build a fictional HACCP plan for cooked chicken, with process steps, hazards, a critical control point, critical limit, monitoring and corrective action.|steps listed;limit set;action defined|The critical limit is a core temperature of at least 75 degrees Celsius, monitored by probe, and undercooked batches are cooked again.
Monitor temperature and cold chain|Temperature records prove control. Cooling, freezing and transport must keep food within safe limits.|Review a fictional log of chilled storage readings of 4, 5, 6, 9, 5 and 4 degrees Celsius against a 5 degree limit, and decide actions for out-of-limit readings.|readings checked;actions chosen;records kept|The reading of 9 degrees is investigated, product held and its time out of range assessed before release.
Test and interpret microbial counts|Plate counts estimate bacteria per gram. Dilution factors convert plate numbers to the original sample.|A fictional plate from a 10 to the power minus 3 dilution shows 150 colonies from 1 millilitre. Calculate the colony forming units per gram and compare with a limit of 10 to the power 5.|dilution used;count computed;limit compared|The count is 150 times 1000, which is 150000 or 1.5 times 10 to the power 5, so the sample exceeds the limit.
Read labels, additives and allergen controls|Labels must state ingredients, allergens, dates and storage. Wrong labels are a major cause of recalls.|Check a fictional pack label against a recipe, find three errors including an allergen, and write a corrected label and a recall decision.|errors found;label corrected;recall decision|The label omits milk although the recipe contains butter, so the batch is held and relabelled.
Manage a recall and communicate with customers|A recall removes unsafe food from the market. Speed, traceability and clear messages protect people.|Plan a fictional recall of 2400 packs after an allergen labelling error, with traceability, who is notified, how customers are told, disposal and prevention. Calculate how many packs are still unsold if 1500 have been sold.|traceability;message clear;count computed|Of 2400 packs, 1500 sold leaves 900 to retrieve from stock, and customers are told what to do with the 1500 sold.
Audit a food business and close corrective actions|An audit compares practice with a standard. Corrective actions fix the problem and prevent a repeat.|Audit a fictional restaurant kitchen against a 15 point checklist, write six findings with severity, and plan corrective and preventive actions with dates.|checklist used;findings rated;actions dated|Dirty drains are rated major, cleaned the same day and added to a weekly cleaning schedule.'''),
dict(id='security-services',summary='Prepare for professional private security work: duties, legal limits, observation, access control, emergencies, communication, de-escalation, reporting and ethical conduct.',icon='Shield',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Observe','Control','Respond','Report'],modules=['Security foundations','Surveillance & risk','Crisis & emergency','Law & conduct','Communication & practice'],
src=dict(page='diploma-in-security-officer-skills-and-crisis-management',code='SSOSCM/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to security services','Surveillance and risk assessment','Crisis and emergency management','Legal framework and security laws','Soft skills and professional communication','Practical training and scenario-based learning']),
rows='''Describe the security officer's role and limits|A security officer protects people and property by prevention, observation and reporting. The role does not give police powers, and the law sets strict limits.|Write a fictional duty statement for a residential complex guard that lists duties, what the guard may not do and when to call the police.|duties listed;limits clear;call rule|The statement says that the guard observes and reports and does not search residents or use force except as the law allows in self-defence.
Control access and manage visitors|Access control limits who enters. Fair, consistent procedures protect safety and respect people.|Design a fictional visitor procedure for an office with identification, a log, visitor pass, host confirmation and an exit check, including how to handle a visitor without ID.|steps ordered;log kept;exception handled|A visitor with no ID waits while the host comes to the gate, and the guard does not search bags unless the policy allows it.
Patrol, observe and notice changes|Good patrols are varied and watchful. Noticing what is out of place prevents incidents.|Plan a fictional night patrol route for a warehouse with checkpoints, timings, what to look for and how to record observations without relying on a fixed pattern.|route planned;checkpoints;variation|The route varies its start point each night and records any unlocked door at the time found.
Use CCTV and alarm systems responsibly|Cameras and alarms help, but they raise privacy duties. Footage must be kept secure and used only for the stated purpose.|Write a fictional CCTV control-room procedure covering monitoring, logging, alarm response, privacy and who may request footage.|procedure clear;privacy;access control|Footage is released only to authorised persons with a written request and is logged.
Assess risk and vulnerability|A risk assessment looks at threats, vulnerabilities and consequences. Controls are chosen to reduce the highest risks first.|Assess a fictional small shopping centre by listing five threats, scoring likelihood and impact, and proposing physical, procedural and staffing controls.|threats listed;scores multiplied;controls proposed|Theft from the car park scores 4 times 3, which is 12, and a lighting upgrade and patrols are recommended.
Respond to emergencies: fire, bomb threat and first aid|Emergency response follows set procedures. Safety of people comes before property, and the right authorities are called quickly.|Create a fictional response card for a fire alarm, a suspicious package and a medical collapse, with the first three actions, who to call and what the guard must not do.|three actions each;call list;do-not rules|For a suspicious package, the guard keeps people away, does not touch it and calls the police.
Manage crowds and conflict without escalation|Calm communication prevents most conflicts. De-escalation uses listening, space and clear options, and force is the last resort.|Write a fictional de-escalation script for an angry visitor refused entry, using respectful tone, explanation, options and when to call a supervisor or the police.|calm tone;options offered;escalation point|The guard says, I understand you are upset; I cannot let you in without a pass, but I can call your host now.
Know laws, rights and evidence handling|Security staff must respect rights, privacy and licensing rules. Evidence must be protected and handed over properly.|Prepare a fictional one-page legal awareness sheet that lists topics to confirm in current local law, such as licensing, use of force, detention and data protection, and a chain of custody form for a found item.|topics listed;law confirmed;custody form|The sheet tells the guard to confirm the local rules with the employer and records who found, handed over and received the item.
Review an incident and improve procedures|After an incident, the team looks at what worked, what failed and what to change. The aim is better protection, not blame.|Review a fictional incident in which a visitor entered without a pass during a shift change. Identify gaps, rewrite two procedures and plan a short refresher.|gaps found;procedures rewritten;refresher planned|The review finds that the gate was unattended for 10 minutes during handover and sets an overlap of 15 minutes.
Write incident reports and brief a shift|A clear report states facts in time order without opinion. A shift handover keeps the next team informed.|Write a fictional incident report of a minor theft and a handover note covering open issues, equipment and risks for the next shift.|facts only;time order;handover complete|The report says that at 21:40 the guard saw the door open and does not claim to know who did it.'''),
dict(id='electrician',summary='Learn the foundations of electrical work: circuits, wiring design, loads, protection, machines, measurement, panels, solar basics and fault finding, always under qualified supervision and local rules.',icon='Workflow',tool='notebook',tools=['notebook','sheets','data','board'],
nodes=['Calculate','Install','Test','Maintain'],modules=['Electrical basics','Wiring & installation','Machines & measurement','Panels & power systems','Renewables & practice'],
src=dict(page='electrician-technician-program',code='ETP/Q0001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Basics of electrical engineering','Electrical wiring and installation','Electrical machines and transformers','Electrical measurements and instrumentation','Power systems and electrical panels','Renewable energy and practical applications']),
rows='''Use Ohm's law and power formulas|Voltage, current, resistance and power are linked by simple formulas. Correct calculation is the base of safe design.|Calculate for a fictional 2300 watt heater on 230 volts the current, the resistance and the energy used in 4 hours. State which cable size must be checked.|current computed;resistance computed;energy computed|Current is 2300 divided by 230, which is 10 amps, resistance is 23 ohms and 4 hours uses 9.2 kilowatt hours.
Analyse series and parallel circuits|Series circuits share current, while parallel circuits share voltage. Household loads are normally in parallel.|For fictional resistors of 10, 20 and 30 ohms, compute the total resistance when in series and the parallel value, and explain why a house is wired in parallel.|series total;parallel total;reason|Series gives 60 ohms and the parallel value is 1 divided by 0.1833, which is about 5.45 ohms.
Plan a domestic wiring layout|A layout shows circuits, switches, sockets and protection. Separate lighting and power circuits reduce risk.|Draw a fictional wiring plan for a two-room flat with lighting, power, an air conditioner circuit and an earth connection, and label the protective devices.|circuits separated;devices labelled;earth shown|The air conditioner has its own circuit with a suitably rated breaker, separate from sockets.
Select cables and calculate voltage drop|Cable size depends on current, length, installation and allowed voltage drop. Undersized cable overheats.|For a fictional 10 amp load on a 20 metre run with a copper conductor of about 7.4 milliohm per metre, calculate the loop resistance and voltage drop, then compare with 3 percent of 230 volts.|loop doubled;drop computed;limit compared|The loop is 40 metres, resistance about 0.296 ohms, drop about 3 volts, which is 1.3 percent and within the 3 percent limit.
Calculate load and balance phases|Loads are summed and spread across phases. Unbalanced loads overheat and waste capacity.|Distribute a fictional set of single-phase loads of 3, 2.5, 4, 1.5, 3.5 and 2 kilowatts across three phases and calculate each phase total and the imbalance.|loads allocated;totals computed;imbalance|Allocating 4 plus 2 to one phase and 3.5 plus 2.5 and 3 plus 1.5 to the others gives 6, 6 and 4.5 kilowatts.
Test circuits and use instruments|Testing proves a circuit is safe. Instruments must be used correctly and checked on a known source.|Write a fictional test sequence for a new circuit with continuity, insulation resistance, polarity and earth checks, with the limits to check in the local code.|sequence ordered;limits cited;test the tester|Insulation resistance is measured with the circuit isolated, and the result is compared with the minimum required by the code.
Understand motors, starters and protection|Motors draw high starting current. Starters reduce stress, and protection prevents damage.|Explain direct-on-line and star-delta starting for a fictional three-phase motor and calculate the star starting current if direct-on-line starting current is 60 amps.|methods explained;value computed;protection named|Star-delta starting reduces starting current to about one third, so the star current is about 20 amps.
Read panel diagrams and locate faults|Panel drawings show power and control paths. A methodical approach avoids guesswork.|Use a fictional control diagram for a pump with stop, start, overload and contactor, and list a fault-finding sequence for a pump that will not start.|diagram read;sequence logical;isolation first|The sequence checks supply, isolation, overload trip, control fuse, contactor coil and the start button, one at a time.
Diagnose a fault and plan a safe repair|Fault finding combines symptoms, measurements and logic. A safe repair isolates, tests, repairs and verifies before reconnecting.|Diagnose a fictional case where a bedroom circuit trips every evening. List causes, measurements, the order of checks, the safe repair and the verification before the circuit is reenergised.|causes listed;order logical;verification|The technician isolates the circuit, finds low insulation resistance in a damaged cable and replaces it before retesting.
Plan a small solar system and an energy saving|Solar systems depend on load, sunshine, panel rating and battery size. Energy saving reduces size and cost.|Size a fictional home system with a daily load of 3 kilowatt hours, 5 peak sun hours and system efficiency of 75 percent, and estimate the panel capacity.|load known;formula used;capacity stated|Required array capacity is 3 divided by (5 times 0.75), which is 0.8 kilowatts, so a 1 kilowatt array is chosen with margin.'''),
]
