COURSES=[
dict(id='fire-technician',summary='Learn the knowledge side of fire prevention and response: fire science, risk checks, equipment, safe evacuation, first aid awareness and emergency planning, leaving hands-on drills to qualified instructors.',icon='Shield',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Assess','Prevent','Respond','Review'],modules=['Fire science','Prevention & inspection','Equipment & systems','Response planning','Emergency drill file'],
src=dict(page='certificate-in-fireman',code='CIF/Q1001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Introduction to fire science','Fire prevention and safety measures','Firefighting equipment and tools','Firefighting tactics and strategies','Emergency medical response and first aid','Disaster management and response']),
rows='''Explain the fire triangle and why fires spread|Fire needs fuel, heat and oxygen, and spreads by conduction, convection and radiation. Removing one element stops the fire, and smoke is often the first danger.|Write a fictional briefing for new office staff that explains the fire triangle, the three ways heat spreads, and why smoke can be more dangerous than flames. Use one office example for each.|elements explained;spread modes;smoke danger|A rubbish bin fire next to a curtain shows how radiant heat ignites nearby fuel, and the briefing tells staff to leave rather than fight a spreading fire.
Classify fires and choose the right extinguisher|The wrong extinguisher can make a fire worse. Classes depend on fuel, such as ordinary solids, liquids, gases, metals, electrical equipment and cooking oils.|Create a fictional chart that matches six imaginary fire situations to a fire class and a suitable extinguisher type, and mark which must never be fought with water.|six matches;water warnings;class named|A cooking oil fire is not fought with water, and the chart says to cover with a fire blanket only if it is safe and call for help.
Inspect a building for fire hazards|A hazard inspection finds ignition sources, fuel and blocked exits before a fire. Inspection notes must be specific so someone can fix them.|Inspect a fictional two-storey shop using a checklist covering exits, wiring, storage, cooking, extinguishers and alarms. List five findings with location, risk and a fix.|five findings;risks stated;fixes assigned|Cartons stacked against a distribution board are recorded as a high risk and ordered to be moved one metre away.
Know alarms, detectors and suppression systems|Detectors sense smoke, heat or gas, and sprinklers and other systems control fires. Systems work only if tested and maintained.|Prepare a fictional table of smoke, heat and gas detectors and sprinkler types with where each is used and a monthly test routine. Explain what a false alarm record shows.|types matched;test routine;false alarm record|Heat detectors are used in a kitchen because steam and cooking smoke would set off smoke detectors.
Plan evacuation routes and timing|People need time to notice, decide and move. Clear routes, signs and drills reduce the time needed to reach safety.|For a fictional office with 80 people, 30 metres to the nearest stair and a walking speed of 1 metre per second, estimate the travel time and add 60 seconds for pre-movement. Mark the route on a plan.|travel time computed;pre-movement added;route marked|Walking takes 30 seconds, and with 60 seconds of pre-movement the estimate is 90 seconds before queuing at the stair.
Understand protective equipment and safe distance|Protective equipment lets trained personnel work near heat and smoke. Untrained people must not enter smoke-filled areas.|Write a fictional awareness sheet that describes helmets, gloves, fire-resistant clothing and breathing apparatus, and states clearly who may use them and why untrained staff must evacuate.|equipment described;training limit stated;evacuate rule|The sheet says that breathing apparatus needs training and fit checks, so ordinary staff leave and wait at the assembly point.
Recognise hazards: electrical, chemical and cooking fires|Different hazards need different responses. Cutting power, shutting gas and keeping people away are first steps for trained responders.|Create fictional response notes for an overloaded socket fire, a small spill of solvent and an oil pan fire, listing what staff do first and when to call the fire service.|three notes;first actions;call rule|For the socket fire, staff isolate power if safe, evacuate and call the fire service rather than use water.
Provide first-aid awareness for burns and smoke|First aid reduces harm until professionals arrive. Burns need cooling, and smoke inhalation needs fresh air and medical help.|Prepare a fictional first-aid card for minor burns, smoke inhalation and a person who has collapsed, with simple steps and the time to call emergency services. Note that first aid training is hands-on.|steps clear;call time;training noted|The card says to cool a burn with running cool water for the recommended period and to seek medical help for large or facial burns.
Know the limits of a non-firefighter's role|Many deaths happen when untrained people try to fight a fire or rescue others. Knowing when to leave is itself a skill.|Write a fictional decision guide for a shop worker who finds a growing fire: when a small first attempt with an extinguisher is reasonable, when to leave at once and what to tell the fire service on arrival.|decision points;leave rule;information for crews|The guide says to leave if the fire is larger than a waste bin, if smoke is rising or if the exit is at risk, and to tell crews where people may still be inside.
Plan a drill, record results and report|A drill tests plans and trains people. Records show time, problems and corrections.|Plan and score a fictional evening drill for a hostel of 120 residents with start time, alarm, headcount at the assembly point and a target of 5 minutes. Record 6 minutes 30 seconds and set actions.|plan written;result compared;actions set|The headcount completed in 6 minutes 30 seconds, which is 90 seconds over target, so the blocked second stair is cleared and marked.'''),
dict(id='fire-safety-management',summary='Manage fire safety systems and compliance: risk assessment, fire load, protection systems, audits, hazardous materials, documentation, emergency plans, training and incident learning.',icon='Shield',tool='notebook',tools=['notebook','board','sheets','data'],
nodes=['Assess','Protect','Audit','Improve'],modules=['Management foundations','Systems & equipment','Risk & audit','Chemical & environmental fire safety','Fire safety management file'],
src=dict(page='certificate-in-fire-safety-management',code='CFSM/Q1001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Introduction to fire and safety management','Fire protection systems and equipment','Fire risk assessment and hazard control','Firefighting techniques and emergency response','Environmental and chemical safety in fire management','First aid and medical response in fire incidents']),
rows='''Define roles and legal duties for fire safety|Owners, managers and staff each have duties. Rules differ by place, so a manager checks the current local code and keeps records.|Create a fictional responsibility chart for a small hotel that lists the owner, manager, fire warden and staff duties and the records each keeps. State that local rules must be confirmed.|roles listed;records named;local rules noted|The chart assigns weekly alarm tests to the fire warden and annual review to the owner.
Assess fire risk with a structured method|A risk assessment identifies hazards, people at risk, existing controls and extra actions. It must be reviewed after changes.|Carry out a fictional risk assessment of a small workshop using steps of identify, evaluate, control, record and review. Score likelihood and severity from 1 to 5 and rank the top three risks.|steps followed;scores multiplied;ranked|A solvent store scoring likelihood 3 and severity 5 has a risk score of 15 and is ranked first.
Calculate fire load and interpret it|Fire load estimates the heat released by combustibles per floor area. It helps judge risk and protection needs.|Calculate the fictional fire load of a storeroom of 40 square metres with 600 kg of wood at 17 megajoules per kilogram and 200 kg of paper at 16 megajoules per kilogram.|energy summed;divided by area;result interpreted|Wood gives 10200 and paper 3200, total 13400 megajoules, so the load is 335 megajoules per square metre.
Select and place extinguishers and hydrants|Extinguishers are chosen by class and placed along escape routes. Travel distance and signage make them usable.|Plan extinguisher placement for a fictional 2000 square metre warehouse with a maximum travel distance of 15 metres. Estimate the minimum number of units and state the class needed.|class chosen;distance rule used;count estimated|If each unit serves a square of 21 metres a side, which keeps every point within about 15 metres of the unit, it covers 441 square metres, so 2000 divided by 441 rounds up to at least 5 units placed near exits.
Understand detection and suppression design|Detectors and suppression systems must match the hazard. Designers use density, coverage and water supply calculations.|For a fictional sprinkler zone of 100 square metres and a design density of 5 litres per minute per square metre, calculate the required flow and the water needed for a 60 minute supply.|flow computed;volume computed;units stated|The flow is 500 litres per minute, so a 60 minute supply needs 30000 litres.
Manage hazardous materials and storage|Flammable materials need segregation, ventilation, labels and limits. Safety data sheets guide storage and response.|Create a fictional storage plan for solvents, gas cylinders and oxidisers in one yard, with separation, signs, spill control and a check on safety data sheets.|segregation shown;spill control;sds used|Oxidisers are stored in a separate bay away from solvents and gas cylinders are chained upright.
Audit a facility and write findings|An audit compares what exists with a standard. Findings should be specific, ranked and tracked until closed.|Audit a fictional factory against a ten-point checklist and write eight findings with evidence, risk rating, owner and due date.|ten points used;evidence cited;owners assigned|A locked fire exit is rated high, assigned to the plant manager and due within one day.
Prepare an emergency plan and train people|An emergency plan sets roles, contacts, procedures and training. People remember what they practise.|Write a fictional emergency plan for a 150-bed hospital wing, including evacuation phases, wardens, contacts, patient priorities and a training schedule.|roles assigned;phases defined;training scheduled|The plan moves patients from the fire zone first and schedules a drill each quarter.
Evaluate a fire protection upgrade by cost and risk|Safety money is limited, so managers compare risk reduction with cost. The aim is a defensible choice rather than the cheapest option.|Compare two fictional upgrades for a 20 year old warehouse, a sprinkler system costing 1800000 and improved detection with compartmentation costing 900000. Estimate risk reduction and give a recommendation.|options compared;risk reduction;recommendation reasoned|If the sprinklers cut expected annual loss from 600000 to 150000, the saving is 450000 a year, so payback on 1800000 is 4 years.
Investigate an incident and drive improvement|After an incident, the goal is learning and prevention rather than blame. Root causes lead to action.|Investigate a fictional storage fire using timeline, causes, contributing factors and corrective actions, and set owners and dates for each action.|timeline built;root cause stated;actions owned|The investigation finds that overloaded extension boards and no inspection routine caused the fire and sets a monthly electrical check.'''),
dict(id='industrial-safety',summary='Run practical industrial safety: hazard identification, risk assessment, PPE, machine and electrical safety, chemicals, confined spaces, emergency plans, incident investigation and audits.',icon='Shield',tool='data',tools=['data','notebook','sheets','board'],
nodes=['Identify','Control','Verify','Learn'],modules=['Safety foundations','Fire & health','Machine & electrical','Chemical & construction hazards','Emergency & compliance'],
src=dict(page='certificate-in-industrial-safety',code='CIS/Q0001',duration='Three Months',eligibility='10+2 or equivalent',modules=['Introduction to industrial safety','Fire prevention and occupational health safety management','Electrical and mechanical safety','Chemical and hazardous material safety','Construction and workplace safety','Emergency preparedness and legal and regulatory compliance']),
rows='''Identify hazards by walking the work|Hazards come from energy, materials, tasks and people. A walk through the work with the people doing it finds more than a desk review.|Perform a fictional walk-through of a packaging line and list ten hazards grouped as physical, chemical, biological, ergonomic and psychological, with the task where each occurs.|ten hazards;groups used;task linked|A forklift crossing a walkway is a physical hazard at the loading task, and repetitive packing is an ergonomic hazard.
Rate risk with likelihood and severity|A matrix helps compare risks. Multiplying likelihood and severity gives a score that sets priority.|Score eight fictional hazards on a 1 to 5 matrix and rank them. Show the calculation and recommend action times for high, medium and low scores.|scores computed;ranking justified;action times|A press with an unguarded nip point scores likelihood 4 times severity 5, which is 20, and is rated high.
Apply the hierarchy of controls|Elimination and substitution are stronger than guards, training or PPE. Choosing a higher level is usually more reliable.|For three fictional hazards of noise, dust and manual lifting, propose one control at each level of the hierarchy and say which you would implement first and why.|hierarchy used;three hazards;first choice reasoned|For dust, substituting a wet cutting method removes much of the hazard before masks are considered.
Select and manage PPE|PPE is the last line of defence. It must fit, suit the hazard, be maintained and be worn correctly.|Prepare a fictional PPE matrix for welding, spray painting and warehouse work with items, standards to check, replacement rules and a fit check for respirators.|matrix complete;fit check;replacement rule|A respirator is fit-tested to the wearer and filters are replaced on a set schedule.
Control noise and ergonomic exposure|Noise exposure depends on level and time. Ergonomic risk comes from force, repetition and posture.|If an 85 decibel limit applies for 8 hours with a 3 decibel exchange rate, calculate the allowed time at 91 decibels and suggest controls for a fictional grinding station.|allowed time computed;controls proposed;units correct|At 91 decibels the allowed time is 8 divided by 2 squared, which is 2 hours, so enclosures and rotation are proposed.
Apply lockout-tagout and machine guarding|Machines must be isolated and energy released before maintenance. Guards prevent contact with moving parts.|Write a fictional lockout-tagout procedure for a conveyor motor, from notice to verification and restart, and list three guarding principles for a nip point.|steps in order;energy verified;guard principles|The procedure requires the isolating switch to be locked and the start button tested before work begins.
Handle chemicals using labels and data sheets|Labels and safety data sheets tell workers about hazards, handling, first aid and spill response.|Create a fictional chemical register for five products, with hazard class, storage, PPE and spill response, and describe how a worker uses the data sheet in an emergency.|register complete;data sheet used;spill response|A corrosive cleaner is stored low on a tray and the spill response uses neutralising material and eye wash.
Control confined space and height work|Confined spaces and heights kill through a lack of oxygen or falls. A permit, testing and rescue plan are required.|Prepare a fictional permit checklist for a tank entry and a roof job, covering isolation, gas testing, standby person, rescue, fall protection and communication.|permit items;rescue plan;standby role|The tank entry requires gas testing before and during entry, a standby person outside and a rescue plan that does not send a second person in unprepared.
Verify that controls actually work|A control on paper is not a control in practice. Verification uses observation, testing and worker feedback.|Design a fictional verification plan for three controls, a machine guard, a ventilation hood and a permit system, with the evidence you collect, how often, and what triggers action.|evidence defined;frequency set;trigger action|The hood is tested with a smoke tube each month, and a result below the design capture speed triggers repair.
Investigate an accident and calculate incident rates|Investigation looks for root causes. Rates such as injuries per 200000 hours allow comparison over time.|Calculate the incident rate for a fictional plant with 6 recordable injuries and 400000 hours worked using the 200000 hour basis, and write root cause findings for one injury.|rate computed;root cause;action|Six injuries multiplied by 200000 and divided by 400000 gives a rate of 3.0, and the investigation finds a missing guard.'''),
dict(id='health-safety-environment',summary='Build a combined health, safety and environment system: culture, hygiene, hazard analysis, permits, fire and electrical safety, construction hazards, environmental controls and audit.',icon='Shield',tool='data',tools=['data','notebook','sheets','board'],
nodes=['Assess','Control','Monitor','Improve'],modules=['HSE foundations','Health & hygiene','Safety systems','Site hazards','Environmental management'],
src=dict(page='certificate-in-health-safety-environment',code='CHSE/Q1001',duration='Three Months',eligibility='10+2 or equivalent',modules=['Introduction to health, safety and environment','Occupational health and hygiene','Safety management systems','Fire and electrical safety','Construction and industrial safety','Environmental management']),
rows='''Explain the purpose of an HSE management system|An HSE system sets policy, roles, risk control, monitoring and improvement. It works when leaders and workers both take part.|Draft a fictional HSE policy statement and a plan-do-check-act cycle for a small factory, with roles and measures for each stage.|policy clear;cycle used;roles assigned|The policy commits the factory to reduce injuries and waste, and the cycle schedules monthly inspections and quarterly review.
Describe occupational health hazards and monitoring|Workers may be exposed to noise, dust, heat and chemicals. Monitoring and health checks show whether controls work.|Plan a fictional health surveillance programme for a foundry covering noise, heat and dust, including measurements, medical checks and records.|hazards listed;monitoring planned;records kept|The programme measures noise each year and offers hearing tests, and records are kept confidential.
Use job safety analysis|A job safety analysis breaks a task into steps, finds hazards and sets controls. It is most useful when workers help prepare it.|Prepare a fictional job safety analysis for replacing a forklift battery, with steps, hazards, controls and responsible persons.|steps broken down;hazards linked;controls set|The step of lifting the battery lists a crush hazard and sets use of a hoist and a clear exclusion area.
Apply permit-to-work systems|High-risk work needs a permit that defines scope, controls, authorisation and closure. A permit is a safety check, not paperwork.|Design a fictional hot-work permit with fields for location, fire watch, gas test, equipment, duration, authorisers and closure, and explain how it prevents conflicts with other jobs.|fields complete;fire watch;closure step|The permit expires at the end of the shift and requires a fire watch for 30 minutes after the work.
Check electrical and fire safety basics|Electrical faults and fire are common causes of loss. Inspection, correct equipment and clear escape routes reduce risk.|Complete a fictional inspection of a workshop for sockets, cables, earthing, extinguishers and exits, and list eight findings with rankings.|eight findings;ranked;actions|A damaged extension lead is removed from service immediately and a replacement is issued.
Control construction and lifting hazards|Excavation, scaffold, lifting and heights need planning and competent supervision. Many incidents come from missing basics.|Create a fictional site safety briefing for a 12 metre building with scaffold, lifting and trench works, listing the checks needed each day and who signs them.|checks listed;sign-off;hazards covered|The scaffold inspection tag is checked each morning and no one climbs without it.
Assess environmental aspects and impacts|An environmental aspect is an activity that can affect the environment. An impact is the change it causes. Significance sets priority.|Build a fictional aspects and impacts register of eight activities with impact, significance score and control, and rank the top two.|register complete;significance scored;ranked|Diesel storage with weak bunding scores high and is controlled by adding a bund and spill kit.
Manage waste and resource efficiency|The waste hierarchy prefers prevention, reuse and recycling over disposal. Measurements show progress.|Calculate recycling rate for a fictional site that produced 12 tonnes of waste, recycled 4.8 tonnes and sent the rest to landfill, then propose three actions to reach 60 percent.|rate computed;actions proposed;target linked|Recycling is 4.8 divided by 12, which is 40 percent, so separating cardboard at source is proposed to reach 60 percent.
Handle a serious incident and communicate with regulators|After a serious incident, the first duty is care of people, then preserving evidence, notifying the authorities and learning. Honest reporting is required.|Prepare a fictional incident response and reporting plan for a fall that causes a fracture, including first response, scene control, notification timing, interviews and lessons shared with workers.|care first;notification;lessons shared|The plan secures the scene, reports within the legal time limit, interviews witnesses separately and shares the lessons in a toolbox talk.
Audit a system and report improvements|An audit tests whether the system works in practice. A good report separates observations, nonconformities and opportunities for improvement.|Audit a fictional small factory against policy, risk assessment, training, incident records and environmental controls, then write findings, ratings and a follow-up plan.|evidence used;findings rated;follow-up plan|The auditor finds that training records are missing for two workers, rates it minor and sets a due date.'''),
dict(id='environmental-safety',summary='Assess and reduce environmental risks: law and standards, impact assessment, pollution control, waste, water, air and soil management, monitoring, communication and compliance reporting.',icon='Compass',tool='data',tools=['data','notebook','sheets','board'],
nodes=['Assess','Monitor','Control','Report'],modules=['Environmental safety foundations','Risk & impact assessment','Pollution & waste','Water & air quality','Soil, land & compliance'],
src=dict(page='diploma-in-environmental-safety',code='DES/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to environmental safety','Environmental risk assessment and management','Pollution control and waste management','Water and wastewater management','Air quality management and control','Soil and land pollution management']),
rows='''Explain environmental safety and the regulatory framework|Environmental safety protects air, water, soil and people. Laws set limits and duties, so a practitioner checks the current rules for the place and activity.|Prepare a fictional one-page guide for a small factory that lists the main environmental topics, the type of approvals and records a business may need, and how to confirm current requirements.|topics listed;records named;rules checked|The guide tells managers to ask the regulator which permits apply instead of relying on old advice.
Identify sources, pathways and receptors|Risk exists when a source, a pathway and a receptor connect. Removing any link reduces risk.|Draw a fictional source-pathway-receptor diagram for a leaking fuel tank near a well, and propose where to break the chain.|chain drawn;receptor named;break proposed|Diesel leaks to soil, moves to groundwater and reaches the well, so a bund and relocation of the tank break the chain.
Carry out a basic environmental risk assessment|A risk assessment combines likelihood and consequence. Scores guide where to put effort.|Assess six fictional risks for a dyeing unit using a five-level likelihood and consequence scale, rank them and choose controls for the top two.|six risks;scores multiplied;controls chosen|Untreated effluent discharge scoring 4 times 5 equals 20 is ranked first and treatment upgrades are proposed.
Understand environmental impact assessment|An impact assessment predicts effects of a project before it starts, proposes mitigation and involves the community.|Outline a fictional impact assessment for a small cold storage plant with baseline, impacts, mitigation, monitoring and community consultation.|baseline described;mitigation;consultation|The outline measures current noise at the nearest houses and sets a limit for night operation.
Plan waste segregation and disposal|Waste is separated by type so that each stream gets safe treatment. Hazardous waste needs special handling and records.|Create a fictional waste plan for a clinic or workshop that separates general, recyclable and hazardous waste, with bins, labels, storage and record sheets.|streams separated;labels;records|Used oil is stored in a labelled sealed drum on a tray and collected by an authorised handler.
Treat and monitor wastewater|Wastewater treatment removes pollutants before discharge. Sampling shows whether limits are met.|For a fictional effluent with BOD of 300 mg per litre and a treatment efficiency of 90 percent, calculate the outlet BOD and compare it with a limit of 30 mg per litre.|efficiency applied;limit compared;result stated|Ninety percent removal leaves 30 mg per litre, which just meets the limit, so the plant sets a margin.
Interpret air quality data|Air pollution data must be compared with standards over the correct time. A single high reading is not the same as an average.|Interpret a fictional week of daily PM2.5 readings of 40, 55, 70, 62, 48, 80 and 45 micrograms per cubic metre. Calculate the weekly average and the days above a 60 limit.|average computed;days counted;interpretation|The sum is 400, so the average is about 57, and three days (70, 62 and 80) exceed 60.
Assess soil contamination and remediation|Contaminated soil is assessed by sampling, mapping and risk. Remediation is chosen by contaminant, cost and future use.|Plan a fictional investigation of a former petrol station site with sampling grid, laboratory tests, risk screening and remediation options.|sampling plan;options compared;future use|The plan takes soil samples from a 10 metre grid and compares excavation with bioremediation.
Engage a community about an environmental concern|Communities worry about air, water and noise. Open, honest communication and monitoring data build trust.|Plan a fictional meeting with residents near a plant who complain about odour, including the data you bring, the questions you expect, the commitments you will make and a way to follow up.|data shared;questions planned;commitments realistic|The plant manager shares odour logs, agrees on a hotline and promises to publish monthly results.
Prepare an environmental compliance report|A report presents data, compares it with limits, explains exceedances and sets actions. Clear presentation builds trust.|Prepare a fictional quarterly report for a plant with air, water and waste data, one exceedance and a corrective action plan.|data compared;exceedance explained;actions set|A pH reading of 9.4 against a limit of 6.5 to 8.5 triggers a cause analysis and a dosing check.'''),
dict(id='construction-safety',summary='Manage construction site safety: law and standards, hazard identification, hierarchy of controls, site planning, falls and excavation, lifting, PPE, materials handling and incident learning.',icon='Cube',tool='notebook',tools=['notebook','board','sheets','data'],
nodes=['Plan','Inspect','Control','Review'],modules=['Safety foundations','Risk assessment','Site management','Materials, lifting & PPE','Legal & professional practice'],
src=dict(page='diploma-in-construction-safety',code='DCSM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to construction safety management','Risk assessment and hazard identification','Construction site safety management','Safety in materials handling and storage','PPE and worker safety','Construction safety laws and regulations']),
rows='''Explain why construction is a high-risk industry|Construction involves changing sites, many contractors, heavy machinery and work at height. Accidents often come from known causes such as falls and struck-by hazards.|Prepare a fictional induction talk for new workers that explains the five most common ways workers are hurt on sites and one simple habit that prevents each.|five causes;habits stated;plain language|Falls are prevented by never working at an open edge without a guardrail or harness, and the talk repeats this twice.
Identify hazards on a site walk|A walk with a checklist finds hazards before they hurt someone. Photos and exact locations make fixes easier.|Carry out a fictional site walk of a three-storey building under construction and list ten hazards with location, risk and immediate action.|ten hazards;location named;action stated|An uncovered floor opening on the second floor is barricaded and covered immediately.
Use JSA and the hierarchy of controls|Job safety analysis breaks a task into steps and finds controls. The hierarchy puts elimination before PPE.|Prepare a job safety analysis for fictional concrete pouring on an upper slab, listing steps, hazards and controls at the hierarchy levels.|steps listed;hierarchy used;responsibility|The analysis replaces manual lifting with a pump to remove a manual handling hazard.
Plan site layout and housekeeping|A good layout separates people from vehicles, stores materials safely and keeps routes clear. Housekeeping prevents trips and fires.|Draw a fictional site layout with gate, pedestrian route, storage, welfare, fire points and vehicle path, and list five housekeeping rules.|layout drawn;separation shown;rules listed|Pedestrian walkways are separated from truck routes by barriers.
Control falls, scaffolds and ladders|Falls from height are a leading cause of death. Scaffold inspection, guardrails and anchor points are essential.|Create a fictional daily scaffold and ladder inspection checklist with 12 points and describe what happens if a defect is found. Explain fall clearance in simple terms.|checklist complete;defect action;clearance idea|A scaffold with a missing toe board is tagged out of use until repaired.
Manage excavation and trenching safety|Trench collapse can bury workers in seconds. Shoring, access and spoil placement reduce risk.|Prepare a fictional excavation plan for a 2 metre deep trench, including supports, access, spoil distance, utilities check and inspection.|supports specified;utilities checked;inspection|Spoil is placed at least 1 metre back from the edge and a ladder is placed within every 7.5 metres of workers.
Plan lifting and equipment safety|Cranes and lifting equipment need competent operators, correct slings and clear signals. Overloading can cause collapse.|Write a fictional lifting plan for a 2 tonne precast beam, listing load weight, sling choice, signals, exclusion zone and weather limits.|load known;rigging chosen;zone set|The plan checks that the crane's chart load exceeds 2 tonnes with margin and stops work if wind is above the limit.
Handle materials, chemicals and storage|Materials need safe stacking, labelling and storage. Cylinders and fuels need special care.|Create a fictional storage plan for cement bags, gas cylinders and paints, including stack height, ventilation, segregation and fire protection.|storage rules;segregation;fire protection|Gas cylinders are stored upright, chained and separated from paint stores.
Investigate a site accident and set corrective actions|An investigation finds why the accident happened, not only who was nearest. Corrective actions must remove causes.|Investigate a fictional incident in which a worker fell from an unprotected edge. Build a timeline, find immediate and root causes, and set three corrective actions with owners and dates.|timeline built;root causes;actions owned|The investigation finds missing edge protection, no inspection that morning and schedule pressure, and orders guardrails before work resumes.
Write a site safety plan and compliance record|A safety plan collects risks, controls, roles, emergency steps and legal duties. Records prove what was done.|Prepare a fictional safety plan for a two-month renovation with a list of laws to check, training records and incident reporting forms.|plan complete;records listed;laws checked|The plan lists induction records for every worker and requires incidents to be reported on the same day.'''),
]
