COURSES=[
dict(id='company-law',summary='Understand how companies are formed, governed and kept compliant, and how employment and industrial relations law shapes workplaces. Educational only, not legal advice.',icon='Briefcase',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Form','Govern','Comply','Resolve'],modules=['Company basics','Governance & finance law','Employment & industrial relations','Restructuring & compliance','Compliance pack'],
src=dict(page='advanced-certificate-in-industrial-and-company-law',code='ACICL/Q1001',duration='Three Months',eligibility='10+2 or equivalent',modules=['Introduction to industrial and company law','Labour and employment law','Company formation and governance','Company finance and securities law','Mergers, acquisitions and restructuring','Corporate taxation and compliance']),
rows='''Compare business structures|A company is a separate legal person. Sole proprietors, partnerships, limited liability partnerships and companies differ in liability, control, cost and compliance.|Compare four business structures for a fictional three-person software service on liability, ownership, filing duties and ease of raising money. Recommend one and state that current law must be checked.|four structures compared;liability explained;recommendation|A private company limits the founders' liability to their share capital, but it has annual filing duties that a simple partnership does not.
Read the constitution of a company|The documents of a company state its objects and rules. Directors must act within them.|For a fictional company, summarise the purpose of the memorandum and articles in plain words, and explain what happens if directors sign a contract outside the stated objects.|purpose of each document;director limits;consequence|If a director commits the company to a business it is not authorised to carry on, the contract may be challenged and the director may be personally liable.
Run a board meeting properly|Decisions bind the company only if they follow the right process. Notice, quorum, agenda and minutes are the evidence.|Prepare a notice, agenda and minutes for a fictional board meeting approving a bank account and a loan. Show quorum, the resolution wording, who proposed it and who abstained.|notice and quorum;resolution wording;signed minutes|The minutes record that three of five directors attended, which meets the quorum in the articles, and one director declared an interest and did not vote.
Explain the duties of directors|Directors owe duties of care, loyalty and honesty. They must avoid conflicts and act for the benefit of the company and its members.|Analyse three fictional director actions, such as awarding a contract to a relative, and decide which breach duties. State the safeguard the board could use.|duties named;breach spotted;safeguard|Awarding a supply contract to a director's brother without disclosure or competing quotes breaches the duty to avoid conflicts. Disclosure and independent approval are the safeguard.
Understand shares, capital and shareholder rights|Shares represent ownership, with voting and dividend rights. Raising capital changes who owns and controls the company.|A fictional company has 1,00,000 shares held 60-40 by two founders. It issues 50,000 new shares to an investor for cash. Calculate the new ownership percentages and describe the rights the investor should check.|percentages calculated;dilution explained;rights|After issuing 50,000 shares, the founders hold 60,000 and 40,000 of 1,50,000 shares, or 40 percent and 26.7 percent, and the investor holds 33.3 percent.
Apply core employment law principles|Employment law protects workers through contracts, wages, working hours, safety and fair termination. The applicable statutes must be checked for each case.|Review a fictional employment contract and a termination scenario. List contract terms that must be clear, and the steps an employer should follow before ending employment. Mark where the current law decides the detail.|contract terms;fair process;law to be checked|A termination for poor performance follows documented warnings and a hearing, not a surprise message on the last working day.
Handle an industrial dispute|Disputes are best resolved early through discussion, conciliation or other lawful routes. Strikes and lockouts follow legal conditions.|Describe a fictional dispute over bonus payment in a factory, with the steps from grievance to conciliation, the role of a union and what each party must not do while the process continues.|escalation steps;role of union;lawful conduct|Management and union meet, then a conciliation officer is approached. During the process neither side takes unlawful action such as a sudden lockout.
Explain how mergers and restructuring work|A merger combines companies. It requires due diligence, approvals and protection for shareholders, creditors and employees.|For a fictional merger of two small firms, list the due diligence checks, approvals and employee issues, and one reason a deal might be abandoned.|due diligence list;approvals;employee issues|Due diligence discovers an undisclosed tax dispute in one company, so the buyers reduce the price or walk away.
Know when a company faces insolvency|A company that cannot pay its debts must act lawfully. Continuing to trade while insolvent can create liability for directors.|Analyse a fictional company with unpaid suppliers and bank loans. Identify warning signs, options such as restructuring or formal insolvency, and director responsibilities. Say that expert advice is required.|warning signs;options;director responsibility|Repeated bounced cheques and unpaid salaries are warning signs that directors should seek professional advice rather than hope the situation improves.
Build an annual compliance calendar|A compliance calendar lists filings, meetings and renewals with due dates and owners. Missing a date can trigger penalties.|Create a fictional compliance calendar for a private company covering meetings, financial statements, filings, tax payments and records, with an owner and review date for each. Note that dates must be verified against current rules.|calendar built;owners;verification note|The calendar assigns the company secretary to prepare filings one month before each due date and shows a reminder to the director who signs.'''),

dict(id='intellectual-property',summary='Protect and use ideas lawfully: patents, copyright, trademarks, designs, trade secrets, licensing, enforcement and IP strategy for creators and businesses.',icon='Shield',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Identify','Protect','License','Enforce'],modules=['IP basics','Patents & copyright','Trademarks & trade secrets','Licensing & enforcement','IP strategy'],
src=dict(page='advanced-diploma-in-intellectual-property-rights',code='ADIPR/Q1001',duration='Six Months',eligibility="Bachelor's degree or equivalent",modules=['Introduction to IPR','Patents and patent law','Copyrights and related rights','Trademarks and brand protection','Trade secrets and confidential information','IPR enforcement, litigation and international perspectives']),
rows='''Match a creation to the right kind of protection|Different creations are protected differently: inventions, expression, brands, designs and secrets. Choosing the right kind avoids paying for protection that does not apply.|For a fictional product that includes a new water-saving valve, a user manual, a brand name, a bottle shape and a supplier list, name the protection that fits each and explain why.|five items matched;reasoning;limits|The valve may be a patent matter, the manual is a copyright work, the name a trademark, the bottle shape a design and the supplier list a trade secret.
Search before you adopt a name|A trademark search checks whether a similar mark already exists for similar goods. Using a conflicting name can lead to dispute and loss of investment.|Plan a clearance search for a fictional food brand name with spelling and sound variants, the relevant classes, the places to search and how you would decide the risk.|variants considered;classes chosen;risk decision|A name that sounds the same as an existing biscuit brand is a high risk even if it is spelt differently.
Explain who owns a copyright work|Copyright usually belongs to the author, but employment and commissioned work can change this. A written agreement avoids disputes.|Analyse three fictional cases: an employee-written manual, a freelancer-designed logo and a photograph taken by a customer. Decide who likely owns each and what agreement should say.|ownership reasoned;agreement terms;risk|A freelancer who designs a logo may keep the copyright unless the agreement transfers it, so the business obtains a written assignment.
Use copyrighted material lawfully|Some uses need permission, some are allowed within limits, and some content is free to use under stated licences. Checking the licence is part of the work.|For a fictional training video, review five elements, a song, a photo, a quote, a font and a stock clip. Decide permission needed, licence conditions and record each source.|five elements reviewed;licence recorded;fair use limits|A song downloaded from the internet is not free to use. The video team buys a licence or uses music with a clear commercial licence.
Assess whether an invention may be patentable|A patent requires novelty, an inventive step and industrial use, and is lost if the invention is disclosed too early without protection.|Evaluate a fictional invention against novelty, inventive step and usefulness using a prior art search of three documents. State what the inventor should not do before filing.|criteria applied;prior art compared;disclosure caution|Showing the design publicly before filing can destroy novelty, so the inventor signs a confidentiality agreement before discussions with investors.
Draft a basic non-disclosure agreement|A confidentiality agreement defines what is secret, who may use it, for what purpose and for how long. Vague terms are hard to enforce.|Outline a fictional two-way NDA for a business discussion with definition of confidential information, exclusions, permitted use, duration, return of material and remedy. Note that a lawyer should review final terms.|defined information;exclusions;duration|Information already public, or independently developed, is excluded from the definition, so the agreement stays reasonable.
Structure a licence and calculate royalties|A licence gives limited rights for a price and conditions. Royalty clauses must define the base, the rate and reporting.|A fictional licensee sells 20,00,000 of product with a 5 percent royalty on net sales and a minimum annual payment of 1,50,000. Calculate the royalty owed and explain the minimum.|royalty calculated;minimum applied;reporting|Five percent of 20,00,000 is 1,00,000, but the minimum is 1,50,000, so the licensee pays 1,50,000.
Respond to suspected infringement|An accusation or a discovered copy needs a measured response: gather evidence, check rights, consider settlement and avoid threats you cannot support.|A fictional seller finds a competitor using a near-identical logo. Plan the steps: evidence, check of registration and priority, a first letter and escalation options. Explain what you avoid.|evidence collected;rights verified;proportionate response|The business captures dated screenshots, confirms its registration date is earlier, and sends a polite request before considering formal action.
Audit and plan intellectual property for a business|An IP audit lists what a business owns, uses and risks. A plan decides what to protect, license or leave unprotected.|Prepare a fictional IP register for a small design studio with assets, owner, protection status, licence and risk, and set three priorities for the year with costs.|register complete;risks flagged;priorities|The register shows fonts used under a licence expiring in March, which is flagged as a risk and renewed before the next client delivery.
Deliver an IP strategy for a new product|A strategy aligns protection and agreements with business goals and budget. It states what is protected, when and why.|Package a fictional IP strategy for a launch: asset list, protection plan and budget, agreements with staff and freelancers, licence terms, enforcement approach and a review date.|assets to protection;agreements;budget and review|The plan files the trademark before the public launch, secures written assignments from the designer, and keeps the formula as a trade secret with restricted access.'''),

dict(id='public-administration',summary='Understand how governments work and serve citizens: structure, policy, administrative law, accountability, e-governance, development and ethical public service.',icon='Briefcase',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Understand','Decide','Serve','Account'],modules=['Government structure','Policy & governance','Administrative law & rights','E-governance & service delivery','Public policy brief'],
src=dict(page='advanced-certificate-in-public-administration',code='ACPA/Q1001',duration='Three Months',eligibility='10+2 or equivalent',modules=['Introduction to public administration','Government structure and functions','Public policy and governance','Administrative law and public accountability','E-governance and digital administration','Public sector reforms and development administration']),
rows='''Explain the structure of government|Governments divide power between legislature, executive and judiciary, and between levels of government. Knowing who is responsible helps citizens and officials act correctly.|For a fictional problem of a broken village road, trace which levels and offices are responsible for repair, funding and oversight, and which court could hear a dispute.|branches named;level responsibility;path of complaint|The village panchayat looks after local roads, the block or district office may fund repairs and an elected representative can raise the matter in an assembly.
Describe how a policy is made and carried out|Policy moves from problem recognition to design, decision, implementation and review. Each stage involves different people and risks.|Trace a fictional scheme to give school bags to children through the policy cycle. Identify the stakeholders at each stage and one point where the policy could fail.|stages named;stakeholders;failure point|At implementation, bags are delivered to the district but not to remote schools, so monitoring needs a delivery checklist.
Write official notes and drafts|Government work depends on clear file notings and drafts. A good note states the issue, rules, options and a recommendation briefly.|Write a fictional file note asking approval to repair a school boundary wall, with background, rule reference, cost, options and recommendation. Then draft the order that follows.|issue and rule;options;recommendation|The note compares repairing now for 80,000 with a delay that risks worse damage, and recommends approval within the sanctioned limit.
Apply natural justice in a decision|A person affected by a decision must be heard, and the decision-maker must be unbiased and give reasons. Fair process protects both citizens and officials.|Review a fictional case of licence cancellation without notice. List which fairness principles were broken and design a proper process with notice, hearing and written reasons.|principles named;broken steps;corrected process|The licence holder was never told of the complaint or given a chance to reply, so the decision can be challenged for lack of a hearing.
Use the right to information and citizen charters|Citizens can ask for information and are entitled to stated service standards. Officials must respond within defined times and record refusals with reasons.|Draft a fictional application for information about road repair spending, and a citizen charter entry for issuing a certificate within a set time. Describe the escalation if the time is missed.|clear request;service standard;escalation|The charter promises a certificate in 7 days. On day 8 the citizen contacts the nodal officer and files a grievance on the official portal.
Handle a public grievance|Grievance handling records the complaint, assigns responsibility, tracks time and informs the citizen. Closing a file without solving the problem is not resolution.|Design a fictional grievance workflow for a municipality with intake, classification, assignment, deadlines, escalation and feedback. Show how a repeated complaint is detected.|intake and tracking;deadlines;feedback|A complaint about a blocked drain is assigned to ward staff with a 3-day deadline and, if still open, escalated to the engineer automatically.
Plan a digital public service|E-governance can make services faster and fairer, but it needs privacy, access for people without devices and secure records.|Plan an online application for a fictional birth certificate: forms, documents, fees, status tracking, assisted counter for non-digital users and data protection rules.|user steps;inclusion;data protection|People without smartphones can apply at a service centre where staff enter the form for them, so digital service does not exclude them.
Evaluate a development programme|Programmes should be judged by outcomes, cost, reach and fairness. Good evaluation uses indicators set at the start.|Choose a fictional rural water programme and define five indicators with baseline and target values, a data source and one risk of misleading figures.|indicators;baselines;data source|The number of taps installed is an output. Households with safe water for six months of the year is an outcome, which is the true measure.
Follow public money through the budget cycle|Public money moves from budget preparation to approval, spending, audit and reporting. Each stage has rules, and transparency lets citizens see how funds are used.|Trace a fictional 10 lakh sanctioned for a village health sub-centre through proposal, approval, release, expenditure, audit and public display of accounts. Mark where records are required and where misuse could occur.|stages traced;records at each stage;risk point|Funds are released in two instalments, the second only after a utilisation certificate and bills for the first are submitted.
Deliver a public policy brief|A policy brief tells decision-makers the problem, evidence, options, costs and recommendation in two pages.|Write a fictional two-page brief on improving attendance in a government school: problem and evidence, three options with cost and risk, recommended option, implementation steps and measures.|evidence cited;options compared;recommendation|The brief recommends a midday-meal improvement plus attendance follow-up, supported by absence data, and sets a target of 90 percent attendance in two terms.'''),

dict(id='social-work',summary='Practise ethical social work: assessment, casework records, community development, child and family protection, social policy, research and referral.',icon='People',tool='notebook',tools=['notebook','board'],
nodes=['Listen','Assess','Act','Review'],modules=['Social work foundations','Community development','Individuals & families','Policy & research','Practice file'],
src=dict(page='diploma-in-social-work-development',code='DSWD/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to social work','Community development and empowerment','Social work with individuals and families','Social policy and legislation','Social research and impact assessment','Social work in health and rehabilitation']),
rows='''Explain professional values and boundaries|Social work respects dignity, confidentiality and self-determination. Boundaries protect both the person helped and the worker.|Analyse four fictional situations, such as a client offering a gift and a friend asking about a case, and state the appropriate response and the value that guides it.|values named;boundary kept;response|When asked about a neighbour's case at a social event, the worker says they cannot discuss anyone they work with, which protects confidentiality.
Listen and record a first meeting|A first meeting builds trust and gathers the person's own account. Notes should be factual, respectful and kept securely.|Write a fictional first-contact record with reason for contact, the person's view, immediate needs, risks, consent and next steps. Remove any detail that is judgement rather than fact.|facts separated from opinion;consent noted;next steps|The note says Mrs A reports that she cannot pay rent this month, rather than Mrs A is irresponsible with money.
Assess a person's situation with a simple map|An assessment looks at the person, family, community and services. A diagram of relationships and resources shows strengths as well as problems.|Create an ecomap for a fictional older man living alone with limited income, listing supports, stresses, services and strengths, and set two goals with him.|connections shown;strengths included;goals set|The map shows a supportive neighbour and a nearby health centre as strengths, and loneliness and unpaid pension as stressors.
Plan an intervention with the person|Plans are agreed with the person and have actions, owners and dates. Plans imposed on people rarely last.|Write a fictional plan for a family facing school dropout of a child, with goals, actions for family, school and worker, dates and how progress will be reviewed.|agreed goals;owners and dates;review|The plan assigns the mother to meet the teacher, the worker to check scholarship eligibility, and a review in four weeks.
Respond to concerns about a child's safety|Child safety concerns must be taken seriously and reported through the lawful route. The worker does not investigate alone or promise secrecy.|For a fictional child who tells a worker about unsafe treatment, write what you say, what you record, who you inform and what you never promise. Note that the current law and agency procedure apply.|calm response;correct reporting route;no secrecy promise|The worker thanks the child, explains that others must be told to keep the child safe, and records the child's words as said.
Assess community needs participatively|Community members know their needs. Participatory methods such as mapping and ranking involve them in decisions.|Plan a fictional village needs assessment with a resource map, a ranking of problems by residents, a meeting plan including women and marginalised groups, and how results are shared.|participation methods;inclusion;feedback to community|Women and elders are asked at a time they can attend, and the ranked list is read back at a public meeting for correction.
Support a self-help group|A self-help group builds savings, credit and confidence. Clear rules, records and transparency prevent conflict.|Design rules for a fictional group of 12 women: monthly saving of 100, loan rules, interest, meeting schedule, record keeping and how disputes are settled. Calculate savings after 6 months.|rules written;records;dispute process|Twelve members saving 100 a month hold 1,200 a month and 7,200 after six months, kept in a bank account with two signatories.
Read a social welfare law or scheme|Knowing a person's entitlements lets a worker help them claim them. Eligibility, documents and process must be checked on official sources.|For a fictional elderly widow, list five welfare entitlements to check, the documents needed and who to contact, and mark that eligibility must be verified with the official scheme guidelines.|entitlements listed;documents;verification|The worker helps gather an age proof, bank account and residence proof before the application, so it is not rejected for missing papers.
Measure whether an intervention worked|Evaluation needs a baseline, indicators and honest reporting. Activity counts do not show change in people's lives.|Design a fictional evaluation of a six-month literacy class with baseline test, indicators, interview questions, consent and a way to report negative findings.|baseline and indicators;consent;honest reporting|Reading scores rose for most learners, but attendance of working women was low, which the report states with a plan to change class timings.
Deliver a social work practice file|A practice file shows the full cycle: assessment, plan, action, review and learning, in a record another worker can follow.|Assemble a fictional case file with first contact, ecomap, plan, referrals, review notes, ethical issues and a reflection on what you would do differently. Use no real personal data.|full cycle;ethics noted;reflection|The reflection records that the first plan assumed the family could attend weekday appointments, and the revised plan offers evening visits.'''),

dict(id='esg-sustainability',summary='Measure and manage environmental, social and governance performance: materiality, emissions, social standards, governance, reporting and action plans.',icon='Compass',tool='notebook',tools=['notebook','budget','sheets'],
nodes=['Assess','Measure','Report','Improve'],modules=['ESG foundations','Environment','Social & governance','Reporting & data','ESG action plan'],
src=dict(page='diploma-in-environmental-social-and-governance',code='DESG/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Foundations of ESG','Environmental pillar','Social pillar','Governance pillar','ESG reporting and performance measurement','ESG integration and implementation']),
rows='''Explain the three ESG pillars|Environmental, social and governance factors affect risk and long-term value. Each needs its own evidence.|Sort twelve fictional business issues, such as water use, safety incidents and board independence, into the three pillars and explain why each matters to a manufacturer.|issues sorted;reasons;examples|A pollution fine is an environmental risk. A weak complaint process is a governance weakness because problems may not reach the board.
Identify material issues|Material issues are those that matter most to the business and its stakeholders. Not every issue deserves equal effort.|For a fictional garment exporter, list ten issues, rate each by importance to stakeholders and to business success, and choose the five most material.|ten issues rated;stakeholders considered;top five|Worker safety and water pollution rank high because they affect workers, buyers and licences, while office paper use ranks low.
Calculate a simple carbon footprint|Greenhouse gas emissions are estimated by multiplying activity by an emission factor. The source of the factor must be stated.|A fictional office uses 12,000 kWh of electricity and 3,000 litres of fuel in a year. Using the factors given in the case, calculate emissions and identify the biggest source.|activity data;factors cited;total and share|With an electricity factor of 0.7 kg per kWh, the electricity contributes 8,400 kg of carbon dioxide equivalent. The case gives the fuel factor for the rest.
Plan to cut energy and waste|An action should have a baseline, a target, a cost and a payback. Savings that are not measured cannot be proved.|For a fictional factory spending 1,20,000 a month on electricity, propose three measures with cost, expected saving and payback period, and choose the first one.|baseline;saving estimate;payback|Replacing lighting costing 2,40,000 and saving 20,000 a month pays back in 12 months, so it is chosen before larger projects.
Assess labour and safety practices in a supply chain|Social risks include unsafe work, child labour and unfair wages. Audits and worker voices help to find them.|Design a fictional supplier check list covering age verification, wages, hours, safety, grievance channel and unannounced visits, and a response to a serious violation.|checklist;worker voice;response|The supplier audit includes confidential worker interviews, because documents alone can hide overtime and unpaid wages.
Strengthen governance and ethics|Good governance means oversight, transparency and ways to raise concerns without fear. It reduces fraud and builds trust.|Create a fictional governance checklist for a mid-sized company with board independence, conflict of interest register, audit committee, whistleblower policy and anti-corruption rules. Test it on a case.|oversight;whistleblower policy;case test|A manager who reports a bribe request uses a confidential line, and the audit committee, not the manager's boss, receives the report.
Build ESG data you can trust|Reported numbers need a clear definition, source, owner and check. Poor data creates risk of misstatement.|For five fictional ESG metrics, write a data sheet with definition, unit, source, owner, collection frequency and review check, and spot one likely error.|definitions;ownership;error check|Total energy used must include fuel as well as electricity, or the figure will be understated and fail an external review.
Read and avoid greenwashing|Greenwashing is making environmental claims that are not true or cannot be shown. Claims need evidence and clear scope.|Review six fictional marketing claims, such as eco-friendly and carbon neutral, and decide which need evidence, a clearer scope or removal. Rewrite two.|claims reviewed;evidence needs;honest rewrite|The claim 100 percent green is replaced by a precise statement such as packaging is made from 70 percent recycled material, with a source.
Prepare a simple sustainability report|A report tells stakeholders what was done, what was measured and what remains to improve. Honest limits make it credible.|Outline a fictional ESG report with strategy, material issues, five metrics with year-on-year change, targets, governance and a note of data limits.|metrics with change;targets;limits stated|The report shows emissions fell 6 percent, states that water data covers only one site, and commits to extending it next year.
Deliver an ESG action plan|An action plan sets priorities, owners, budgets and measures, and links to the business strategy and risks.|Package a fictional one-year ESG plan: material issues, baselines, targets, owners, budget, risks, reporting calendar and a way for employees to raise concerns.|baselines and targets;owners;calendar|The plan reduces energy use by 10 percent and zero unreported safety incidents, with quarterly review by the board.'''),

dict(id='health-family-welfare',summary='Support community health education: nutrition, maternal and child health, reproductive health with informed choice, disease prevention, population trends and outreach.',icon='People',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Understand','Educate','Refer','Review'],modules=['Health foundations','Nutrition & maternal health','Population & prevention','Adolescent & reproductive health','Outreach plan'],
src=dict(page='advanced-diploma-in-health-family-welfare-and-population-education',code='ADHFWPE/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to health, family welfare and population education','Health and nutrition','Family welfare and maternal health','Population dynamics and demographic trends','Epidemiology and disease prevention','Reproductive health and adolescent care']),
rows='''Explain what shapes a community's health|Health depends on more than medical care: water, food, housing, income, education and access to services all matter.|For a fictional village with frequent diarrhoea cases, list at least six health determinants and match each to an action a health educator could support.|determinants named;actions matched;scope clear|Unsafe drinking water is the likely main cause, so the educator supports safe water storage education and reports the problem to the health authority.
Plan a balanced meal on a budget|A balanced diet includes energy foods, protein, vitamins and minerals. Local, affordable foods can meet needs when planned well.|Plan a fictional one-day menu for a family of four with a stated daily food budget, using local foods. Check it covers cereals, pulses, vegetables, fruit and a protein source.|food groups covered;budget respected;local foods|A menu of rice, dal, seasonal greens and a fruit meets several food groups within the budget, without relying on packaged snacks.
Teach safe food and hygiene|Many illnesses spread through unwashed hands, unsafe water and spoiled food. Simple habits prevent most of them.|Write a fictional ten-minute demonstration for mothers on handwashing, water treatment and food storage, with teaching steps, a question to check understanding and a demonstration plan.|demonstration steps;check question;simple language|The educator shows six steps of handwashing and asks a mother to repeat them, then asks when hands should be washed.
Explain antenatal and newborn care messages|Regular antenatal check-ups, nutrition, rest and danger-sign awareness support safe pregnancy. Educators share messages and refer, they do not diagnose.|Prepare a fictional counselling card for a pregnant woman and her family listing check-up timing as advised locally, nutrition, rest, danger signs requiring immediate care and where to go. Verify details with the local health worker.|key messages;danger signs;referral|Heavy bleeding, severe headache with blurred vision or reduced baby movement are danger signs that need urgent medical care.
Read immunisation records|Vaccines protect children when given on schedule. A record shows what has been given and what is due.|Review a fictional child's immunisation card with three missed doses. Describe how you would explain the importance without blame, check against the current national schedule and refer to the health worker.|record read;non-blaming message;referral|The educator does not decide the schedule but points to the nearest centre and notes the child's due vaccines for the health worker.
Interpret simple population data|Population figures show size, age structure and change. Birth, death and migration drive the changes.|From fictional census-style figures for two villages, calculate growth rate and the share of children and older people, and explain what each result means for services.|growth rate;age shares;service implication|A village with a high share of children needs more school and child health services, while an ageing village needs elder care and pensions.
Describe prevention of common diseases|Prevention reduces illness cheaply. It combines clean water, sanitation, vector control, vaccination and early treatment.|Create a fictional community plan against mosquito-borne disease: environment actions, personal protection, early fever reporting and a monthly check by volunteers.|environmental control;early reporting;volunteer routine|Stagnant water in containers is cleared weekly, and anyone with fever is encouraged to visit the health centre promptly.
Counsel on reproductive health with informed choice|Reproductive health information should be accurate, respectful and voluntary. People decide for themselves with correct information, and coercion is never acceptable.|For a fictional couple asking about family planning, write the counselling steps: listen, give accurate options from approved material, explain benefits and limits, respect their decision and refer for services.|accurate information;voluntary choice;referral|The educator lists the available methods from the approved leaflet and refers the couple to a trained provider, without pressuring them toward any method.
Support adolescents with accurate information|Adolescents need correct information about growth, hygiene, relationships and safety, delivered respectfully and without shame.|Plan a fictional school session for adolescents on menstrual health and hygiene, myths and facts, where to get help and how to handle sensitive questions. Include permission from the school.|myths and facts;respectful tone;where to get help|The session replaces the myth that girls should avoid kitchens during periods with the fact that menstruation is a normal body process.
Deliver a community health education plan|A plan targets a specific health problem with activities, messages, partners, measures and review.|Package a fictional six-month plan for a village: baseline data, target group, activities, materials, partners, indicators and a monitoring sheet with a way to report outcomes honestly.|baseline and target;indicators;partners|The plan aims to raise handwashing at key times from 40 to 70 percent of observed households, using a simple monthly observation sheet.'''),

dict(id='hotel-management',summary='Manage a hotel as a business: operations, front office, food and beverage, rooms, revenue, marketing, finance, guests and enterprise development.',icon='Briefcase',tool='budget',tools=['budget','board','sheets'],
nodes=['Welcome','Operate','Sell','Control'],modules=['Hotel operations','Food & beverage and rooms','Revenue & marketing','Finance & people','Hotel business plan'],
src=dict(page='advanced-diploma-in-hotel-business-management',code='ADHBM/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to hotel business management','Food and beverage management','Housekeeping and facility management','Marketing and sales in the hotel industry','Financial management in hotels','Hotel entrepreneurship and business development']),
rows='''Map the departments of a hotel|A hotel works because departments cooperate. Understanding who does what helps a manager solve problems quickly.|Draw an organisation chart in words for a fictional 50-room hotel and trace how a late check-out request reaches front office, housekeeping and billing.|departments mapped;request flow;responsibilities|The guest asks reception, which tells housekeeping to delay cleaning that room and the billing desk to charge the late check-out fee if applicable.
Handle check-in and check-out without errors|The arrival and departure moments are where most guest problems appear. Clear checks protect revenue and guest satisfaction.|Write step-by-step procedures for check-in and check-out in a fictional hotel, including identity, room allocation, payment, billing review and key return. Add a reply to a guest who disputes a charge.|identity checks;bill review;dispute reply|At check-out the receptionist reads the bill with the guest. A disputed minibar charge is investigated and corrected if the item was not consumed.
Calculate occupancy, average rate and revenue per room|Occupancy shows how many rooms sold, average rate shows price per room sold, and revenue per available room combines both.|A fictional 50-room hotel sells 35 rooms for 3,000 each in one night. Calculate occupancy, average daily rate and revenue per available room, and show how they link.|occupancy;average rate;revenue per available room|Occupancy is 70 percent, average rate 3,000, and revenue per available room 2,100, which equals occupancy times average rate.
Cost a menu and control food waste|Food cost percentage compares ingredient cost with selling price. Control comes from portions, purchasing and waste records.|A fictional dish costs 70 to make and sells at 200. Calculate the food cost percentage and the price needed for a 30 percent target. Suggest two waste controls.|cost percentage;target price;waste controls|70 divided by 200 is 35 percent. To reach 30 percent the price must be about 233, or cost must fall.
Run a banquet event|A banquet depends on a clear order, headcount, timing and communication between kitchen, service and the client.|Prepare a fictional banquet event order for 120 guests with menu, timing, layout, staffing, special diets and an emergency plan. Show the checklist used on the day.|clear order;special diets;day checklist|The event sheet lists 8 vegetarian meals and 2 nut-allergy meals, and the kitchen marks them with clear labels at service.
Set room rates and manage demand|Prices can change with season, day and demand. Rate decisions must protect profit and fairness to guests.|Set weekday, weekend and festival rates for a fictional hotel using demand patterns and costs. Explain a minimum rate and a rule for discounts to corporate clients.|rate logic;minimum rate;discount rule|The weekend rate is 25 percent higher because it sells out most weeks, but the corporate rate stays steady on weekdays to secure regular business.
Market the hotel honestly|Hotel marketing builds bookings through accurate descriptions, good photos and reviews. Overpromising brings bad reviews.|Create a fictional online listing and a review response plan. Check that every claim is true and plan how to reply politely to a negative review about noise.|honest description;review reply;improvement action|The reply thanks the guest, apologises, explains steps taken such as moving rooms away from the road, and invites them to contact the manager.
Prepare a hotel budget and break-even|A budget forecasts revenue and costs. Break-even shows the occupancy needed to cover fixed costs.|A fictional 20-room guest house has monthly fixed costs of 4,50,000, variable cost of 500 per occupied room night and an average rate of 2,500. Calculate break-even occupancy.|contribution;break-even rooms;occupancy percent|Contribution per room night is 2,000, so 225 room nights break even. Over a 30-day month with 20 rooms, 600 room nights exist, so break-even occupancy is 37.5 percent.
Manage staff, training and licences|Good service needs trained, rested staff, and a hotel must hold the licences and meet the safety rules that apply to it.|Create a fictional staffing roster for a day with three shifts, a training plan for new staff, and a compliance checklist for fire safety, food licence and guest records. Note that local rules must be verified.|roster;training;compliance list|The roster has a cover person at night, and the compliance list shows fire extinguisher inspection dates and the food licence renewal date.
Prepare a hotel business plan|A plan shows the concept, market, investment, operations, risks and returns so lenders and owners can make a decision.|Package a fictional business plan for a 15-room heritage guest house: market study, services, investment, staffing, pricing, risks and a three-year forecast with break-even.|market to forecast link;risks;break-even|The plan shows the hotel breaks even at 45 percent occupancy and names seasonality as the biggest risk, with a plan to attract weekday corporate guests.'''),

dict(id='housekeeping',summary='Lead housekeeping safely and efficiently: room standards, cleaning science, laundry, inventory, supervision, safety, guest service and sustainable practice.',icon='Shield',tool='board',tools=['board','budget','notebook'],
nodes=['Plan','Clean','Inspect','Improve'],modules=['Housekeeping basics','Cleaning science & laundry','Inventory & budgets','Safety & guest service','Housekeeping system'],
src=dict(page='advanced-diploma-in-housekeeping-management',code='ADHM/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to housekeeping','Guest room and HR management','Cleaning science and laundry','Inventory and budgeting','Safety and guest service','Technology and interior decoration']),
rows='''Describe the housekeeping department's roles|Housekeeping keeps rooms and public areas clean, safe and ready to sell. It works closely with front office, maintenance and laundry.|Draw the structure of a fictional 40-room hotel's housekeeping team and describe how a room goes from checked out to ready for sale, including who is told at each step.|roles named;room status flow;communication|A room is marked vacant dirty at check-out, cleaned, inspected by a supervisor and then marked vacant clean so reception can sell it.
Write a room cleaning checklist|A checklist makes cleaning consistent and inspectable. It follows an order that avoids recontaminating clean areas.|Create a fictional step-by-step room cleaning checklist covering preparation, dusting, bathroom, bed making, floors and final inspection, with order and the reason for the order.|logical order;inspection point;reasons|Dust is removed from high to low surfaces before floors are vacuumed, so dust that falls is cleaned afterwards.
Choose cleaning agents and use them safely|Different surfaces and soils need different products. Some chemicals are dangerous when mixed, so instructions and safety sheets must be followed.|For a fictional marble floor, glass, toilet and carpet stain, choose a method and product type. State the labels and safety sheet check, and the rule about never mixing certain cleaners.|surface-matched method;safety sheet;no mixing rule|Bleach is never mixed with acid or ammonia-based cleaners because toxic gas can be released.
Manage linen and laundry|Linen is costly and must be controlled by counts, par levels and quality checks. Losses and damage should be tracked.|A fictional hotel has 40 rooms using 2 sets of linen per room and keeps a par of 3. Calculate the stock needed and design a daily count to detect loss.|par calculation;count method;loss control|With a par of 3 and 80 sets in use at full occupancy, the hotel needs 240 sets, counted at laundry send and return.
Plan staffing with room productivity|Staffing depends on rooms to clean, standards and each attendant's workload. Too few staff cause poor quality, and too many waste money.|A fictional hotel expects 56 rooms to clean, and each attendant cleans 14 rooms per shift. Calculate attendants needed and add a plan for two absences.|attendants calculated;absence cover;quality note|56 rooms divided by 14 per attendant needs 4 attendants. Planning for two absences, a pool of on-call staff keeps the standard.
Supervise and inspect fairly|Inspection checks the result, not the person. Clear standards and feedback improve quality.|Create a fictional room inspection form with ten weighted items and a score, and write feedback to an attendant who missed bathroom grout cleaning, with a coaching plan.|weighted items;constructive feedback;follow-up|The supervisor shows the missed area, demonstrates the method and re-inspects the next day, rather than only criticising the score.
Handle guest requests, complaints and lost items|Guest service in housekeeping includes handling special requests, privacy and found items with care and records.|Write procedures for a fictional guest who reports a missing item and for a found wallet. Include logging, storing, notifying and releasing with proof of ownership.|logging;secure storage;proof of ownership|A found wallet is sealed with the finder, logged by two staff, and returned only after the owner describes contents and shows identification.
Control supplies and cost per room|Housekeeping cost per occupied room is a basic measure. Tracking supplies shows waste.|A fictional hotel spends 62,000 on cleaning supplies and amenities in a month for 1,240 occupied rooms. Calculate cost per occupied room and set a saving target with two actions.|cost per room;target;actions|62,000 divided by 1,240 is 50 per occupied room. Dosing chemicals with measured dispensers can reduce waste and the cost.
Prepare for safety and emergencies|Housekeepers face slips, chemicals, lifting and fire hazards. Training and equipment reduce harm.|Write a safety briefing for a fictional housekeeping team covering safe lifting, wet floor signs, personal protective equipment, sharps, chemical storage and fire response.|safe handling;protective equipment;emergency response|Used syringes found in a room are never touched by hand and are reported to the supervisor for safe disposal with tools and a sharps container.
Design a housekeeping operating system|A system links standards, schedules, inspection, stock and training to give consistent results every day.|Package a fictional housekeeping manual: daily plan, checklists, linen control, supply budget, inspection form, safety rules, training plan and monthly quality measures.|complete system;measures;training plan|The manual sets a target of 95 percent of rooms passing first inspection, and reviews the common failure reasons every month.'''),

dict(id='travel-tourism',summary='Plan and sell trips responsibly: tourism basics, documents, ticketing, itineraries and costing, sales, customer care and running a travel agency.',icon='Compass',tool='budget',tools=['budget','notebook','sheets','canva'],
nodes=['Advise','Plan','Book','Support'],modules=['Tourism basics','Travel formalities & ticketing','Itineraries & costing','Sales & customer care','Travel business'],
src=dict(page='professional-certificate-in-travel-agency-management',code='PCTAM/Q0001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Introduction to the travel and tourism industry','Travel documentation and formalities','Air ticketing and reservation systems','Tour packaging and itinerary planning','Sales, marketing and customer handling','Setting up and managing a travel agency']),
rows='''Match a trip to a traveller's needs|A good travel adviser asks about purpose, budget, time, health, interests and comfort before suggesting a destination.|Write ten questions for a fictional family of four planning a holiday and use sample answers to shortlist two destinations with reasons.|useful questions;shortlist;reasons|A family with grandparents and a modest budget may prefer a hill town with easy access over a distant adventure trip.
Check documents and entry requirements|Passports, visas and health rules differ by country and change. The adviser checks official sources and records the checks.|Prepare a fictional document checklist for a traveller going abroad, covering passport validity, visa type, insurance, health requirements and baggage. State how and when you verify current rules.|checklist complete;official sources;verification date|The checklist notes passport validity requirements and tells the traveller to confirm with the embassy site before booking non-refundable tickets.
Read a flight itinerary|A reservation record shows the passenger, flights, times and fare conditions. Errors in names or dates are costly to fix.|Check a fictional itinerary with a name spelling error, a short connection and a baggage allowance difference. Explain each issue and what you would do before ticketing.|errors found;connection risk;baggage rule|A name that does not match the passport must be corrected before ticketing because changes later can be refused or costly.
Quote fares, taxes and fees clearly|A quote should show the base fare, taxes, fees, baggage and change rules so the customer knows the full price and conditions.|Prepare a fictional written quote for two travellers with base fare, taxes, agency fee, baggage allowance, change and refund conditions, and a validity time.|full price shown;conditions;validity|The quote shows total 38,400 for two, states that it is valid for 24 hours, and that a change fee applies after ticketing.
Calculate refund and cancellation outcomes|Cancellation rules decide what can be returned. Clear policy explanation avoids disputes.|A fictional ticket costs 12,000, with a cancellation charge of 2,500 and an agency fee of 300 that is not refundable. Calculate the refund and write the explanation to the customer.|refund calculated;explanation;policy cited|The refund is 12,000 minus 2,500, which is 9,500, and the agency fee is shown separately as non-refundable.
Plan a day-by-day itinerary|An itinerary should be realistic about travel times, rest and opening hours. Packing too much ruins a trip.|Plan a fictional five-day itinerary for a family with a child and grandparents, with times, travel durations, rest breaks, meals and a backup activity for rain.|realistic timings;rest;backup|The second day includes only two activities with a long lunch break because the grandparents tire after long walks.
Cost a package and set a price|A package price covers transport, stay, meals, entry fees, guide and margin. Missing a cost reduces profit.|Cost a fictional four-night group package for 10 travellers with the case costs: transport 40,000, hotel 60,000, meals 20,000, entry fees 5,000 and guide 10,000. Add a 12 percent margin on cost and find the per-person price.|all costs included;margin applied;per-person price|Total cost is 135,000. A 12 percent margin adds 16,200 for 151,200 in total, or 15,120 per person.
Handle a travel disruption|Delays, cancellations and lost bags happen. Calm action and clear communication keep trust.|Write a response plan for a fictional flight cancellation affecting a customer: contact, options, rebooking, compensation rights, hotel and record of costs. Include the message you send.|contact quickly;options;record costs|The agent messages the traveller within minutes with two rebooking options and the airline's published assistance rules.
Promote and sell trips honestly|Travel sellers must describe trips fairly, including limits, extra costs and risks. Honest information reduces complaints.|Review five fictional trip advertisements with phrases such as best price guaranteed and luxury stay. Mark unsupported claims, rewrite them and list what proof you would keep.|claims reviewed;honest rewrite;proof|Best price guaranteed is replaced with a specific price for named inclusions, because no one can guarantee the lowest price everywhere.
Set up the basics of a travel business|A travel business needs registrations, partners, systems, accounts and a plan for risk. Rules must be checked with the authorities.|Package a fictional start-up plan for a small agency: services, registrations to verify, supplier partners, booking process, accounts, customer data protection, insurance and a first-year budget.|services and process;compliance steps;budget|The plan keeps customer money in a separate account until suppliers are paid, and lists the licences to verify before the first booking.'''),

dict(id='temple-management',summary='Administer a temple or religious trust with respect and accountability: records, rituals schedule, crowd safety, finance, volunteers, heritage care and devotee services.',icon='Compass',tool='board',tools=['board','budget','notebook'],
nodes=['Plan','Serve','Protect','Account'],modules=['Trust & records','Rituals, events & crowds','Finance & transparency','People & volunteers','Temple management plan'],
src=dict(page='advanced-diploma-in-temple-management',code='ADTM/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to temple management','Temple architecture and infrastructure maintenance','Temple rituals and worship management','Financial and revenue management','Human resource and volunteer management','Pilgrimage and devotee services']),
rows='''Understand the roles of trustees, staff and committees|A temple trust or committee holds duties to the institution and the community. Clear roles prevent conflict and misuse.|Describe a fictional temple governance structure with trustees, executive officer, priests and volunteers, and list decisions that need trustee approval and those the officer may take.|roles clear;approval levels;conflict avoided|Spending above a set amount needs trustee approval recorded in minutes, while daily purchases of flowers and oil can be approved by the executive officer.
Keep trust records and registers|Registers of assets, donations, property, staff and decisions are the memory of an institution. They must be accurate and protected.|Design a fictional set of temple registers with fields, owners and backups, including a donation register, asset register, event log and visitors book for the office.|registers listed;fields;backup|The asset register records each lamp, vessel and property document with location and condition, so loss is noticed at the annual check.
Plan the daily ritual and festival calendar|Ritual timings, materials and personnel must be coordinated with respect for tradition. A calendar prevents last-minute shortages.|Prepare a fictional monthly calendar of daily services and one festival, listing timings, priests, materials, purchase dates and responsible persons. Respect the temple's own traditions in all details.|calendar complete;materials planned;responsible persons|The festival plan lists flower and oil purchase on a set date a week earlier so supply problems are found before the event.
Estimate crowd capacity and flow|Crowd safety depends on space, entry and exit control, queue design and emergency access. Capacity must follow safety advice, not guesswork.|A fictional temple hall measures 600 square metres. Using a safe density of 2 people per square metre stated by the safety authority in the case, calculate capacity and design entry control for a festival.|capacity calculated;entry control;exit and emergency access|At 2 people per square metre the hall holds 1,200, so tickets or timed entry stop more people entering when it is full.
Prepare for emergencies in a gathering place|Gatherings carry risks of crush, fire, medical emergencies and weather. Staff and volunteers need clear roles and rehearsed routes.|Write an emergency plan for a fictional festival: roles, communication, first aid, evacuation routes, lost child procedure and contact with police and ambulance. Include a drill.|roles;evacuation;lost-child procedure|A lost child is taken to a marked help desk, an announcement is made without naming the child, and the parent must show proof before collecting.
Manage donations transparently|Donations are given in trust. Receipts, counting by more than one person, bank deposit and public accounting protect donors and officials.|Design a fictional donation process for the offering box and online payments: counting with two people, record, bank deposit within a set time, receipts and monthly reconciliation.|dual counting;timely deposit;reconciliation|Two authorised people open the box, count, sign the sheet and deposit at the bank the next working day, and the bank slip is matched to the register.
Prepare a temple budget|A budget plans income and spending for services, repairs, staff, festivals and reserves. It should be approved and compared with actual figures.|Prepare a fictional annual budget with income from offerings, rent and events, and spending on salaries, repairs, festivals and charity. Include a 10 percent reserve and a quarterly review.|income and spending;reserve;review|The budget sets aside a repair reserve because roof leaks found in the monsoon would otherwise force an emergency appeal.
Care for the building and heritage|Old structures need regular inspection and trained conservation advice. Wrong repairs can do permanent damage.|Create a fictional inspection plan for an old temple with checks of roof, walls, paint, drainage, wiring and fire equipment, and a rule to consult a conservation expert before repairs on heritage features.|inspection list;expert rule;wiring and fire safety|Cracks in the old stone are photographed and reported to a conservation expert, instead of being filled with cement by the local contractor.
Serve devotees with dignity and accessibility|A temple should be welcoming to elders, children, disabled visitors and pilgrims from afar. Small facilities make a large difference.|Plan fictional devotee services: queue design with seating, wheelchair access, drinking water, clean toilets, information boards and a complaint box. Describe how feedback leads to action.|accessibility;facilities;feedback loop|A complaint about long standing times leads to benches along the queue and a priority line for elders and the disabled.
Deliver a temple management plan|A management plan joins governance, records, rituals, safety, finance, volunteers and heritage care with clear responsibilities and review dates.|Package a fictional temple management plan: governance chart, registers, calendar, crowd and emergency plans, donation controls, budget, volunteer rules, maintenance schedule and annual review.|complete plan;controls;review|The plan shows who approves expenses, how every donation is traced from box to bank, and how safety is rehearsed before the festival.'''),
]
