COURSES=[
dict(id='hvac-technician',summary='Understand heating, ventilation and air conditioning: refrigeration cycle, load and airflow calculations, components, controls, maintenance, refrigerant responsibility, safety and energy efficiency.',icon='Workflow',tool='notebook',tools=['notebook','sheets','data','board'],
nodes=['Measure','Diagnose','Service','Verify'],modules=['HVAC foundations','Refrigeration & cooling','Heating & ventilation','Controls & electrical','Service practice'],
src=dict(page='certificate-in-hvac-technician',code='CHVACT/Q1001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Introduction to HVAC systems','Refrigeration systems and components','Heating systems and components','Ventilation and air distribution','Air conditioning systems and components','Electrical and control systems in HVAC']),
rows='''Explain heat transfer and the refrigeration cycle|Heat moves by conduction, convection and radiation. A refrigeration cycle moves heat from a cooler space to a warmer one using a refrigerant, compressor, condenser, expansion device and evaporator.|Draw a fictional split air conditioner cycle with the four main components and state what happens to pressure, temperature and state of the refrigerant at each stage.|four components;states described;direction of heat|In the evaporator the low-pressure liquid absorbs room heat and boils to vapour, and in the condenser the hot vapour releases heat outdoors.
Read air properties on a psychrometric chart|Air carries heat and moisture. Dry bulb, wet bulb and humidity decide comfort, and cooling coils remove both heat and moisture.|Plot a fictional room air state of 28 degrees dry bulb and 60 percent humidity, then describe what changes when the coil cools it to 14 degrees and removes moisture.|point plotted;changes described;moisture removed|Cooling below the dew point condenses water, which is why an air conditioner drains water.
Calculate a room cooling load|Cooling load comes from heat entering through walls and windows, people, lights and equipment. Sizing too small or too large wastes comfort and energy.|Estimate the load for a fictional bedroom adding 600 watts of envelope gain, 2 people at 100 watts, 200 watts of lights and equipment, and 300 watts from sun, then convert to tons using 3.517 kilowatts per ton.|loads summed;conversion made;size chosen|The total is 1300 watts or 1.3 kilowatts, which is 0.37 tons, so a 1 ton unit is clearly sufficient and a safety margin is added.
Compute airflow and duct velocity|Air flow is the volume moved per second. Duct size sets velocity, and high velocity makes noise and loses pressure.|A fictional supply duct carries 0.5 cubic metres per second through an area of 0.25 square metres. Calculate velocity, then the sensible cooling in kilowatts if the air is 8 kelvin cooler, using 1.2 for density times specific heat.|velocity computed;cooling computed;noise comment|Velocity is 2 metres per second and cooling is 1.2 times 0.5 times 8, which is 4.8 kilowatts.
Handle refrigerant responsibly|Refrigerants can harm the environment and some are flammable or under pressure. Only trained and authorised technicians handle them, and venting is not allowed.|Write a fictional awareness sheet that explains why refrigerant must be recovered, who may handle it, what leak checks and records are needed, and what to tell a customer who asks a friend to top up gas.|recovery explained;authorised only;records|The sheet says that an unqualified person must not open a sealed system and that recovered refrigerant is recorded and returned for reuse or disposal.
Diagnose a system that cools poorly|Diagnosis follows symptoms to causes. Airflow, filters, charge, controls and power are checked in a logical order.|Create a fictional fault-finding table for an air conditioner that runs but cools weakly, with checks, tools, results and next actions, starting with the cheapest and safest checks.|logical order;tools named;safe first|The technician first checks a clogged filter and blocked outdoor coil before suspecting low refrigerant charge.
Understand ventilation and indoor air quality|Ventilation brings in fresh air and removes pollutants. Air changes per hour compare supply with room volume.|Calculate air changes per hour for a fictional classroom of 150 cubic metres with 450 cubic metres per hour of fresh air, and decide whether a target of 4 is met.|ACH computed;target compared;action|450 divided by 150 gives 3 air changes per hour, which is below 4, so more ventilation or filtration is needed.
Read HVAC wiring and controls|Control circuits switch contactors and fans using thermostats and safety devices. Reading a diagram helps trace faults.|Use a fictional wiring diagram of a split unit to trace the path from thermostat to compressor contactor and list which safety devices would stop it. State isolation steps before touching parts.|path traced;safety devices;isolation|The path passes through the low-voltage transformer, thermostat, pressure switch and contactor coil.
Handle a customer complaint and a repeat breakdown|A repeat failure means the first diagnosis missed the cause. A calm technician re-examines the evidence, tells the truth and fixes the root problem.|Review a fictional case where a split unit trips again two days after a repair. List what you re-check, how you speak to the customer, what you record and when you escalate to a supervisor.|re-diagnosis planned;honest message;escalation|The technician finds a loose terminal that was overheating, repairs it, explains the earlier miss and records the correction in the service file.
Plan preventive maintenance and an efficiency check|A maintenance plan cleans, inspects and tests regularly. Efficiency checks show when energy cost is rising.|Create a fictional service schedule for ten split units and calculate yearly savings if cleaning cuts a 1.5 kilowatt unit's use by 10 percent over 8 hours a day for 300 days at 8 per kilowatt hour.|schedule set;savings computed;records|Annual use is 1.5 times 8 times 300, which is 3600 kilowatt hours, 10 percent is 360, and at 8 that saves 2880.'''),
dict(id='solar-installation',summary='Plan and assess small solar photovoltaic systems: sunlight and sizing, components, string design, mounting, safety, commissioning, maintenance and simple financial checks under qualified supervision.',icon='Spark',tool='data',tools=['data','sheets','notebook','board','budget'],
nodes=['Survey','Design','Install','Commission'],modules=['Solar foundations','Electrical basics','Components & selection','Installation planning','Sizing, grid & business'],
src=dict(page='certificate-in-solar-panel-installation-technician',code='CSPIT/Q1001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Introduction to solar energy and photovoltaic systems','Electrical fundamentals for solar installation','Solar panel system components and selection','Solar panel installation process','Solar power system design and sizing','Grid-connected and off-grid solar systems']),
rows='''Explain how a solar cell and module produce power|A photovoltaic cell turns light into direct current. Module output depends on light, temperature and shading.|Write a fictional explanation for a customer of how a module works, why output falls on a hot cloudy day and what a nameplate rating of 400 watts means.|principle explained;conditions explained;rating defined|The rating is measured in standard test conditions, so real output on a hot day is lower, and the explanation says so.
Choose between on-grid, off-grid and hybrid systems|System type depends on grid reliability, budget and goals. Each has different parts and rules.|Compare the three system types for a fictional shop with frequent power cuts, listing parts, cost direction, benefits and limits, and recommend one.|three compared;recommendation;limits|The shop with frequent cuts is recommended a hybrid system because a grid-only inverter shuts down when the grid fails.
Survey a site for sun and shade|Sun path, tilt, orientation and shade decide yield. A survey avoids a system that underperforms from day one.|Plan a fictional roof survey with orientation, usable area, tilt, shading at morning and evening, roof strength and access, and record results on a form.|survey items listed;shade checked;roof strength|A parapet casts shade on the lower row at 8 am, so the first row is moved 1.5 metres up the roof.
Calculate load and daily energy|Sizing begins with the load the system must supply. Appliance power and hours of use give daily energy.|List fictional loads of four fans of 60 watts for 8 hours, six lights of 10 watts for 6 hours and a refrigerator of 150 watts for 10 hours, and compute the daily energy in kilowatt hours.|loads listed;energy computed;total correct|The fans use 1.92, lights 0.36 and the refrigerator 1.5, giving 3.78 kilowatt hours per day.
Size the array and the inverter|Array size equals daily energy divided by peak sun hours and system efficiency. Inverter size must cover the peak load with margin.|For a fictional home using 6 kilowatt hours a day with 5 peak sun hours and 75 percent efficiency, calculate the array size, the number of 400 watt modules and the inverter size for a 2 kilowatt peak load with a 25 percent margin.|array computed;modules rounded;inverter sized|The array needs 6 divided by (5 times 0.75), which is 1.6 kilowatts, so 4 modules of 400 watts, and the inverter is 2 times 1.25, which is 2.5 kilowatts.
Design strings and check voltage limits|Modules wired in series add voltage. The string voltage must stay inside the inverter's window in hot and cold weather.|Check a fictional string of 4 modules with 41 volt operating voltage and 49 volt open-circuit voltage against an inverter with a 120 to 500 volt tracking range and a 500 volt maximum.|series sums computed;limits compared;margin noted|The operating voltage is 164 volts and the open-circuit voltage is 196 volts, both inside the limits.
Size batteries and cables|Battery capacity covers autonomy and depth of discharge. Cable size limits voltage drop and heating.|Size a fictional battery bank for 6 kilowatt hours a day, 1 day of autonomy and 80 percent usable depth, at 48 volts, and state a drop limit for the DC cable.|capacity computed;amp-hours found;drop limit|The bank needs 6 divided by 0.8, which is 7.5 kilowatt hours, or about 156 amp-hours at 48 volts.
Plan mounting, earthing and safe working|Solar work involves heights, electricity that cannot be switched off while the sun shines and structural loads. Only trained, authorised people do it.|Create a fictional installation safety plan with fall protection, rooftop access, wind loading checks, DC isolation, earthing and surge protection, and the point where a licensed electrician signs off.|height safety;DC risks;sign-off point|The plan marks every DC string as live in daylight and requires a licensed electrician to approve the final connection.
Troubleshoot an underperforming system|A system that produces less than expected may have shading, soiling, faults or settings problems. Data and measurements show which.|Analyse a fictional system that should make 6 kilowatt hours a day but makes 4. Compare data, list possible causes, the order of checks and the safe way to inspect, and compute the performance ratio.|data compared;checks ordered;ratio computed|The performance ratio is 4 divided by 6, which is 67 percent, and the technician inspects shading, soiling and the inverter log before opening any DC box.
Commission, monitor and estimate payback|Commissioning tests the system before handover. Monitoring shows whether it performs as expected, and a payback estimate helps the customer decide.|Prepare a fictional commissioning checklist and calculate payback for a 1.6 kilowatt system costing 96000 that yields 1800 kilowatt hours a year at 7 per kilowatt hour.|checklist complete;savings computed;payback stated|Savings are 1800 times 7, which is 12600 a year, so payback is 96000 divided by 12600, which is about 7.6 years.'''),
dict(id='gardening-nursery',summary='Grow and care for plants responsibly: soil, composting, propagation, watering, nutrition, pests and disease, nursery routines and small gardening services.',icon='Compass',tool='notebook',tools=['notebook','sheets','budget'],
nodes=['Prepare','Plant','Care','Protect'],modules=['Garden foundations','Soil & fertility','Propagation & nursery','Water, nutrition & growth','Pests, disease & enterprise'],
src=dict(page='certificate-in-gardening-skills',code='CGS/Q0001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Introduction to gardening','Soil and fertility management','Plant propagation techniques','Water management in gardening','Plant nutrition and growth','Pest and disease management']),
rows='''Plan a garden around light, space and purpose|A garden works when plants match the available light, soil, space and the time the gardener has. Planning avoids waste.|Draw a fictional plan for a 3 by 2 metre balcony with sun hours, containers, plants for each position and a watering route, and list what you will not grow there.|light mapped;plants matched;limits noted|A spot with 3 hours of sun suits leafy herbs, while tomatoes need a brighter position and are placed elsewhere.
Use tools safely and keep them in order|Sharp and powered tools cause injuries and spread disease if dirty. Cleaning, sharpening and storage keep them useful.|Create a fictional tool care routine for secateurs, a spade, a hose and a sprayer, including cleaning, sharpening, storage and personal protection.|routine clear;disease control;protection|Secateurs are wiped with a disinfectant between diseased plants to avoid spreading infection.
Test and improve soil|Soil texture, structure, acidity and organic matter decide plant health. A simple test shows what to change.|Plan a fictional soil jar test and a pH test for a garden bed, interpret sample results of 50 percent sand, 30 percent silt and 20 percent clay with pH 5.5, and suggest improvements.|tests planned;results read;improvements|The soil is a loam, and with pH 5.5 the gardener adds organic matter and plans a careful liming trial for plants that need less acid soil.
Make compost with the right balance|Compost needs carbon-rich browns, nitrogen-rich greens, air and moisture. A good balance heats up and breaks down faster.|Design a fictional compost pile list of materials with browns and greens, the ratio you aim for, turning schedule and signs of a problem such as a bad smell.|ratio stated;schedule;troubleshooting|A pile of dry leaves and kitchen scraps is turned every week and a wet, smelly pile gets extra dry leaves.
Raise seedlings and test seed quality|Seed germination varies with seed age, moisture and warmth. A simple test tells how many seeds to sow.|A fictional germination test places 50 seeds in damp paper and 38 sprout. Calculate the germination rate and the number of seeds to sow for 100 plants.|rate computed;seeds needed;method|The rate is 38 divided by 50, which is 76 percent, so about 132 seeds are sown to get 100 plants.
Propagate by cuttings, layering and division|Many plants can be multiplied without seed. Method, timing and clean tools influence success.|Plan a fictional propagation table for hibiscus, rose and mint with method, season, cutting size and care, and a record of how many rooted.|methods matched;care described;records|Mint is divided or rooted in water, while hibiscus is taken as a semi-hardwood cutting with leaves trimmed.
Water plants correctly|Too much and too little water both harm plants. Soil, weather and plant type decide how often to water.|Create a fictional watering schedule for a balcony in summer and monsoon, with a finger test, morning timing, drainage checks and signs of over and under watering.|schedule set;test method;signs listed|Plants are watered in the morning when the top 2 centimetres of soil is dry, and saucers are emptied to avoid root rot.
Feed plants with the right nutrients|Plants need nitrogen, phosphorus, potassium and micronutrients. Symptoms and soil tests guide feeding, and too much fertiliser harms.|Calculate fertiliser for a fictional 10 square metre bed that needs 5 grams of nitrogen per square metre using a fertiliser with 20 percent nitrogen, and list application safety rules.|calculation correct;safety rules;timing|The bed needs 50 grams of nitrogen, so 50 divided by 0.2 gives 250 grams of fertiliser spread evenly.
Plan a small nursery business|A nursery needs space, water, stock, records and customers. Costs and losses must be counted before prices are set.|Plan a fictional nursery that raises 2000 seedlings a month with 10 percent loss, cost of 6 per seedling and sale price of 12. Calculate monthly profit and list the records you keep.|loss counted;profit computed;records|With 10 percent loss, 1800 seedlings are sold for 21600, cost is 12000, and monthly profit is 9600 before rent.
Manage pests and disease with integrated methods|Integrated pest management starts with prevention and monitoring, then uses the safest effective control. Chemicals are a last resort and need careful use.|Prepare a fictional integrated plan for aphids and leaf spot on a vegetable bed, including monitoring, cultural, biological and chemical options, a dilution of 2 millilitres per litre for 10 litres and safety steps.|monitoring first;options ordered;dilution computed|The mix needs 20 millilitres for 10 litres, applied in the evening with gloves, a mask and no spraying in wind.'''),
dict(id='irrigation',summary='Plan efficient drip and sprinkler irrigation: crop water needs, system components, layout and hydraulics, installation, maintenance, troubleshooting, costing and subsidy awareness.',icon='Chart',tool='data',tools=['data','sheets','notebook','budget'],
nodes=['Measure','Design','Install','Maintain'],modules=['Irrigation foundations','Drip systems','Sprinkler systems','Design & installation','Operation & enterprise'],
src=dict(page='certificate-in-drip-sprinkler-irrigation-technology',code='CDSIT/Q0001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Introduction to irrigation and water management','Basics of drip irrigation system','Basics of sprinkler irrigation system','Design and installation of irrigation systems','Operation, maintenance and troubleshooting','Government policies, subsidies and entrepreneurship in irrigation']),
rows='''Explain the soil-water-plant relationship|Soil holds water between field capacity and wilting point. Irrigation aims to refill the root zone before the plant is stressed.|Draw a fictional diagram of field capacity, wilting point and readily available water for a loam soil, and explain why sandy soil needs more frequent irrigation.|terms shown;available water;soil contrast|Sandy soil holds less water, so it is irrigated in smaller amounts more often.
Estimate crop water requirement|Crop water need is reference evapotranspiration multiplied by a crop coefficient. It sets how much water to apply.|Calculate the fictional daily water need of 1000 square metres of vegetable crop with ETo of 6 millimetres and a crop coefficient of 0.8, and convert it to litres.|ETc computed;area converted;units correct|ETc is 4.8 millimetres, and 4.8 millimetres over 1000 square metres is 4800 litres per day.
Choose drip, sprinkler or surface irrigation|System choice depends on crop, soil, water quality, energy and cost. Drip saves water, and sprinklers suit some close-spaced crops.|Compare drip, sprinkler and flood irrigation for a fictional orchard, a vegetable plot and a lawn, using efficiency, cost and maintenance, and choose one for each.|three compared;choices reasoned;efficiency noted|Drip is chosen for the orchard because water goes to the root zone, while sprinklers suit the lawn.
Identify drip system components|A drip system includes a pump, filter, mainline, sub-main, laterals and emitters. Each part has a purpose, and filtration is critical.|Create a fictional parts list and head-to-field flow diagram for a one-acre drip system with the role of the filter, valve, pressure regulator and flush point.|parts listed;flow shown;roles explained|A screen filter protects emitters from clogging, and flush valves at the line ends clear sediment.
Design a drip layout and run time|Layout depends on plant spacing, emitter flow and number of plants. Run time is water needed divided by system flow.|Design a fictional plot of 1250 tomato plants with one 4 litre per hour emitter each and a gross requirement of 5333 litres per day after 90 percent efficiency. Calculate flow and run time.|flow computed;run time computed;units|Total flow is 5000 litres per hour, so the run time is 5333 divided by 5000, which is about 1.07 hours.
Design a sprinkler spacing and application rate|Sprinklers must overlap for even coverage. Application rate must be lower than the soil's intake rate to avoid runoff.|A fictional sprinkler delivers 1200 litres per hour on a 12 by 12 metre spacing. Calculate the application rate in millimetres per hour and the time to apply 10 millimetres.|area computed;rate computed;time computed|The area is 144 square metres, the rate is 1200 divided by 144, which is 8.33 millimetres per hour, and 10 millimetres needs 1.2 hours.
Plan pipe sizing, pressure and pump needs|Pipes lose pressure through friction, and elevation changes pressure. Design aims for even emitter flow across the plot.|Prepare a fictional hydraulic check for a lateral line with an allowed 10 percent flow variation, pressure at the inlet, elevation difference and a statement of what to measure to confirm.|variation limit;pressure checked;measurement plan|The designer checks pressure at the first and last emitters and adjusts the pipe diameter if the difference exceeds the limit.
Maintain, flush and troubleshoot|Clogged emitters, leaks and pressure loss lower yield. Routine flushing and checks prevent most problems.|Write a fictional weekly and seasonal maintenance schedule for a drip system, including flushing, filter cleaning, acid or chlorine treatment cautions, leak checks and a troubleshooting table.|schedule set;cleaning steps;troubleshooting table|Filters are cleaned weekly, and laterals are flushed by opening the end caps until water runs clear.
Audit an irrigation system for uniformity|Uniformity shows whether all plants receive similar water. A catch-can or emitter test finds problems.|Test a fictional drip line by measuring flow from ten emitters in one minute and calculate the average and the lowest quarter average to estimate distribution uniformity.|test method;average computed;uniformity judged|If the average is 66 millilitres a minute and the lowest quarter averages 60, uniformity is 60 divided by 66, which is 91 percent.
Cost a system and understand subsidy rules|Costs include equipment, installation and operation. Subsidy schemes have rules that change, so applicants check current guidance.|Prepare a fictional estimate for a one-acre drip system with materials 60000, labour 10000 and a pump 15000, apply a subsidy share of 50 percent as an example only, and list documents to check with the official scheme.|costs summed;subsidy illustrated;rules checked|The total is 85000, and with an example subsidy of 50 percent the farmer pays 42500, but the actual rate must be confirmed with the official scheme.'''),
dict(id='organic-agriculture',summary='Plan organic farming systems: principles and standards, soil biology, compost, crop protection, rotation, livestock welfare, farm economics, certification records and market planning.',icon='Compass',tool='data',tools=['data','sheets','notebook','budget'],
nodes=['Plan','Build soil','Protect','Market'],modules=['Organic foundations','Soil & fertility','Crop production','Systems & sustainability','Farm enterprise'],
src=dict(page='advanced-certificate-in-organic-agriculture',code='ACOA/Q1001',duration='Three Months',eligibility='10+2 or equivalent',modules=['Introduction to organic agriculture','Soil health and fertility management','Organic crop production techniques','Organic livestock management','Agro-ecology and sustainable farming systems','Organic farm management and economics']),
rows='''Describe organic principles and what certification requires|Organic farming relies on ecological processes and avoids most synthetic inputs. Certification means following a standard and keeping records that an inspector can verify.|Write a fictional farmer guide that explains the main principles, the idea of a conversion period, what an inspector checks and why the exact rules must be taken from the certifying body.|principles stated;inspection explained;rules checked|The guide tells the farmer to keep a purchase log of every input and not to rely on neighbours for rules.
Compare organic and conventional systems fairly|Organic and conventional systems differ in inputs, yields, price and environmental effect. A fair comparison uses data, not slogans.|Compare fictional results of 18 quintals per acre at 2800 per quintal and cost 30000 with 22 quintals at 2000 and cost 28000, and state what the comparison leaves out.|revenue computed;profit compared;limits stated|Organic gives 50400 minus 30000, which is 20400, and conventional gives 44000 minus 28000, which is 16000.
Assess soil health|Soil health combines physical, chemical and biological qualities. Simple observation and tests show whether management is working.|Plan a fictional soil health check with texture feel, organic matter indicators, earthworm count, infiltration test and a lab nutrient test, and say how often you repeat it.|tests listed;indicators interpreted;repeat schedule|Five earthworms in a spade-sized pit is recorded as a sign of fair biological activity, and the test is repeated each season.
Make and use compost and vermicompost|Compost and vermicompost return nutrients and improve soil structure. Moisture, temperature and balance of carbon and nitrogen decide quality.|Calculate for a fictional pile how much manure with 0.1 kilogram carbon and 0.005 kilogram nitrogen per kilogram must be mixed with 100 kilograms of straw holding 40 kilograms carbon and 0.5 kilogram nitrogen to reach a ratio of 30 to 1.|equation set up;manure computed;ratio checked|The mix needs 500 kilograms of manure, giving 90 kilograms of carbon and 3 kilograms of nitrogen, a ratio of 30 to 1.
Design a crop rotation and cover cropping plan|Rotation breaks pest cycles, spreads nutrient use and supports soil. Legumes can add nitrogen.|Create a fictional four-year rotation for a one-acre plot with a legume, a heavy feeder, a root crop and a cover crop, and explain how each change helps soil and pests.|four-year plan;roles explained;pests considered|A legume follows the heavy feeder so that nitrogen is restored for the next crop.
Manage weeds, pests and diseases without prohibited inputs|Prevention, biodiversity and approved controls are used before treatment. Inputs must be checked against the standard.|Prepare a fictional crop protection plan for a vegetable crop with prevention, monitoring, a biological control and an approved spray, and a check that each input is permitted.|prevention first;input checked;records kept|The plan uses trap crops and neem-based spray only if the certifier lists it as permitted.
Plan water and biodiversity on the farm|Water harvesting, hedgerows and pollinator habitat help production and resilience. A farm map shows how elements connect.|Draw a fictional farm map with a pond, hedgerow, flowering strips and crop blocks, and explain two benefits of each for pests, water or pollination.|map drawn;benefits explained;connections|Flowering strips along field edges feed pollinators and beneficial insects.
Keep records and prepare for inspection|Records prove compliance. Seed, inputs, field activities, harvest and sales must be traceable.|Design a fictional record book with field history, input log, harvest and sales sheets, and prepare for a mock inspection by listing questions an inspector may ask.|records designed;questions listed;traceability|The sheet records the batch number of purchased seed so the crop can be traced from field to sale.
Respond to an input or pest problem within the rules|Organic farmers face pest outbreaks and input shortages. The response must be effective and allowed by the standard, with records.|Plan a fictional response to an aphid outbreak and a nutrient deficiency on an organic farm. Compare allowed options, record the decision and state when you must tell the certifier.|options compared;permitted checked;certifier informed|The farmer chooses a permitted biological control and a compost tea, records the dates and quantity and asks the certifier before using any new product.
Build a farm plan, budget and marketing strategy|A farm plan sets crops, sales channels, cost and risk. Organic markets reward trust, quality and consistency.|Prepare a fictional business plan for a half-acre organic vegetable farm, with crops, budget, expected income, risks, a direct-sale channel and a customer promise that is honest.|budget set;risks listed;honest promise|The plan expects 12000 income per month from a weekly basket scheme and lists weather and pest risk with a reserve of 20 percent.'''),
dict(id='home-science',summary='Apply home science knowledge: human development, nutrition, textiles, home management, consumer education and family wellbeing, with clear limits on health advice and attention to evidence.',icon='People',tool='notebook',tools=['notebook','sheets','budget','board'],
nodes=['Understand','Plan','Apply','Review'],modules=['Home science foundations','Human development & family','Food & nutrition','Textiles & home management','Resource & consumer management'],
src=dict(page='advanced-certificate-in-home-science',code='ADHS/Q1001',duration='Three Months',eligibility='10+2 or equivalent',modules=['Introduction to home science','Human development and family studies','Food and nutrition','Textiles and clothing','Home management and interior decoration','Resource management and consumer education']),
rows='''Describe the scope of home science and its disciplines|Home science brings together nutrition, child and family studies, textiles, home management and consumer education to improve family wellbeing.|Create a fictional one-page map of the five branches of home science with a real-life question each branch can help answer for a family.|five branches;questions realistic;links shown|The nutrition branch helps a family decide how to plan affordable balanced meals for a week.
Explain stages of human development|People develop through physical, cognitive, emotional and social changes across life. Children differ, so milestones are ranges, not tests of worth.|Prepare a fictional table of four age stages with typical changes in each area and a note on when a parent should consult a paediatrician or doctor.|stages described;ranges not rules;referral note|The table states that a child who loses skills or has no words by a stated age should be assessed by a doctor.
Support family communication and care|Families work better with respect, listening and clear roles. Care for children and older adults needs patience and attention to safety.|Plan a fictional family meeting and a care plan for an elderly grandparent with daily routine, safety checks, communication and support for the caregiver.|respectful process;care plan;caregiver support|The plan adds grab bars in the bathroom and gives the main caregiver a weekly rest.
Identify nutrients and plan balanced meals|Carbohydrates, proteins, fats, vitamins, minerals, fibre and water each have roles. Meal plans match needs, culture, budget and health conditions.|For a fictional daily target of 2000 kilocalories with 55 percent carbohydrate, 15 percent protein and 30 percent fat, calculate grams of each using 4, 4 and 9 kilocalories per gram.|energy split;grams computed;units correct|Carbohydrate is 1100 kilocalories or 275 grams, protein 300 kilocalories or 75 grams and fat 600 kilocalories or about 67 grams.
Preserve and store food safely|Storage temperature, cleanliness and drying or pickling methods keep food safe. Spoilage signs and adulteration awareness protect the family.|Create a fictional storage guide for cooked rice, milk, vegetables and dry grains with temperature, time limit and signs of spoilage, plus a simple home check for adulteration with a reminder that tests are only a first step.|storage times;spoilage signs;adulteration check|Cooked rice is cooled quickly and refrigerated within 2 hours, and a smell or slime means it is discarded.
Choose and care for fabrics|Fibres and weaves decide comfort, durability and care. Reading care labels avoids damage and waste.|Compare cotton, wool, silk and polyester for a fictional school uniform, a winter coat and a wedding dress, and write a care label for each with washing, drying and ironing.|fibres compared;labels written;choices reasoned|Cotton is chosen for the uniform because it is breathable and washes easily, and the label allows machine washing and medium ironing.
Manage time, money and household resources|Budgeting and time planning reduce stress. Needs come before wants, and a savings habit protects against shocks.|Prepare a fictional monthly budget for a family with income 40000 using needs 50 percent, wants 30 percent and savings 20 percent, and adapt it when rent is 22000 and other essentials are 8000.|rule applied;adaptation made;savings kept|Needs take 30000 which is 75 percent, so wants are cut to 4000 and savings are held at 6000, or 15 percent, and the family plans to reduce rent later.
Organise and decorate a safe, healthy home|Layout, light, storage and colour affect comfort. Home safety and hygiene prevent accidents and illness.|Design a fictional layout for a 2-room home with storage, daylight, safety features and a cleaning schedule, and list five hazards to check.|layout clear;hazards listed;schedule|Medicines are stored high and locked, and electrical sockets are covered where small children live.
Evaluate a nutrition claim and a product advertisement|Advertisements and social media often exaggerate. A careful consumer checks the source, the evidence and the cost.|Evaluate two fictional claims, a drink that boosts immunity and a supplement that cures tiredness. Rate evidence, risk and cost, and write a short guide for a family.|claims examined;evidence rated;guide written|The guide says that no single drink boosts immunity and that tiredness lasting weeks should be checked by a doctor.
Act as an informed consumer|Consumers have rights and responsibilities. Reading labels, comparing unit prices and spotting misleading claims prevents loss.|Compare fictional packs of 500 grams for 90 and 1 kilogram for 160, check labels for standard marks and write a complaint letter for a faulty product.|unit price computed;label checked;complaint written|The small pack costs 180 per kilogram and the large pack 160, so the larger pack is cheaper if the family can use it before the expiry date.'''),
]
