COURSES=[
dict(id='astrology-jyotish',summary='Study astrology as a traditional symbolic system: charts, signs, houses, nakshatras, dasha timing, ethics and honest consulting that makes no medical, legal or financial promises.',icon='Compass',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Learn','Calculate','Interpret','Advise'],modules=['Foundations & ethics','Chart construction','Interpretation','Timing & traditions','Responsible practice'],
src=dict(page='advanced-diploma-in-astrology',code='ADA/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Foundations of advanced astrology','Advanced natal chart interpretation','Predictive astrology and forecasting techniques','Relationship and synastry astrology','Horary and electional astrology','Research and case studies in astrology']),
rows='''Place astrology in its historical and cultural context|Astrology is a long-standing symbolic and cultural tradition. It has not been shown by controlled tests to predict events, so a responsible student separates tradition from proof.|Write a fictional one-page briefing for a new student that explains where Vedic and Western astrology come from, what each claims, and what scientific testing has found. State the limits plainly.|history outlined;limits stated;no proof claimed|The briefing says that astrology is studied here as a cultural framework for reflection and that no reading is a guarantee.
Know the signs, planets, houses and elements|The twelve signs, nine planets and twelve houses form the vocabulary of a chart. Fluency with them is needed before interpretation.|Build a fictional reference sheet that lists the twelve signs with element and quality, the planets with their traditional meanings, and the twelve houses with their themes. Quiz yourself on ten items.|signs complete;planets and houses;self-quiz|Taurus is an earth sign of fixed quality ruled traditionally by Venus, and the second house is linked with resources.
Locate the Moon in a nakshatra|The zodiac of 360 degrees is divided into 27 nakshatras of equal span. Each has a ruling planet that sets the starting dasha.|Calculate the span of one nakshatra, then place a fictional Moon at 25 degrees of Aries and name the nakshatra and its lord using a published list.|span calculated;placement correct;lord named|One nakshatra spans 360 divided by 27, which is 13 degrees 20 minutes, so 25 degrees falls in the second nakshatra, Bharani, ruled by Venus.
Draw a chart from given data|A birth chart needs date, time and place and an ephemeris or software. Accuracy of the time changes the ascendant.|Using a fictional birth record, enter the data in free software, copy the sign positions into a square chart and note what would change if the birth time were 20 minutes off.|data entered;chart drawn;time sensitivity noted|A 20 minute error can shift the ascendant degree by about 5 degrees, so the reader notes the uncertainty before interpreting.
Describe planetary strengths and aspects|Planets are said to be strong or weak by sign, house and relationship. Aspects connect houses and planets.|For a fictional chart, list which planets are in own sign or exalted, which aspect each other and which houses are involved. Write a neutral description without predictions of events.|strengths identified;aspects listed;neutral language|Jupiter in Cancer is noted as exalted in the tradition, and the description uses the word indicates rather than will.
Compute a Vimshottari dasha balance|The dasha system divides 120 years among nine planets in a fixed order. The Moon's position within its nakshatra sets how much of the first period remains.|Calculate the balance of the first dasha for a fictional Moon at 10 degrees of Aries, which lies in Ashwini ruled by Ketu with a period of 7 years.|fraction found;balance calculated;order listed|Ten degrees is three quarters of the 13 degree 20 minute span, so one quarter remains, which is 1.75 years or 1 year 9 months of Ketu.
Read a chart for themes without fixed predictions|A reading should offer themes, strengths and questions to consider, not certain events. Language shapes how a client decides.|Rewrite a fictional fatalistic reading such as you will lose your job into three balanced statements that describe a theme, an opportunity and a question for reflection.|no fatalism;opportunity stated;question added|The rewritten line says that the chart emphasises career change and invites the client to consider skills they want to build.
Choose timing and remedies ethically|Muhurta and remedies are part of the tradition. A responsible practitioner never frightens clients or sells costly remedies.|Create a fictional remedy policy that allows free, low-cost and harmless suggestions such as charity or quiet reflection, and prohibits fear, pressure and claims of cure. Add three example scripts.|harmless remedies;no fear;scripts written|When a client asks whether a ritual will remove a health problem, the practitioner says that medical care comes first and that the ritual is a personal choice.
Review your own practice and correct mistakes|Honest practitioners review their work and admit mistakes. Without review, errors repeat and clients lose trust.|Review a fictional year of ten consultations. Identify two readings that were too certain, rewrite them, and plan one change to your notes, wording and follow-up routine.|mistakes found;rewrite done;change planned|The practitioner finds that two readings used the word will, replaces it with may suggest and adds a line about limits to the report template.
Run a consultation with consent, boundaries and referral|A consultation needs consent, privacy and clear limits. Medical, legal, financial and mental health matters go to professionals.|Write a fictional consultation procedure with consent form, fee, time, privacy, record handling and a referral script for a client who describes severe anxiety and a legal dispute.|consent form;referral script;privacy|The practitioner stops the reading, offers the helpline or counsellor details, and does not give legal opinions.'''),
dict(id='vastu-feng-shui',summary='Apply traditional spatial guidelines with building sense: directions, plan reading, rooms and entrances, light and air, Feng Shui concepts, honest remedies and client communication.',icon='Cube',tool='design',tools=['design','notebook','board'],
nodes=['Survey','Analyse','Advise','Review'],modules=['Principles & directions','Residential planning','Commercial & modern buildings','Remedies & ethics','Consulting practice'],
src=dict(page='advanced-diploma-in-vastu-shastra',code='ADVS/Q1001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Introduction to Vastu Shastra','Residential, commercial and industrial Vastu','Vastu for temples and astrology connection','Vastu for apartments, high-rise buildings and interior design','Advanced energy science and modern architecture','Vastu remedies and corrections']),
rows='''Explain Vastu and Feng Shui as traditions|Vastu and Feng Shui are traditional systems for arranging space. Their claims about energy are beliefs, while light, air and comfort are measurable.|Write a fictional leaflet for a new client that explains the origin of each system, what it recommends, and which parts overlap with ordinary good planning such as ventilation and daylight. State limits honestly.|origin outlined;overlap shown;limits stated|The leaflet says that placing a main window to the east can bring morning light, which is a practical benefit whatever the belief.
Find true directions on a site|Direction work depends on accurate north. A compass reading can be changed by nearby metal and must be corrected for the local variation.|Plan a fictional site survey that finds north with a phone compass, a second method such as the shadow stick, and a comparison. Record a bearing and the allowed difference.|two methods;comparison made;error noted|The phone shows 12 degrees east of the shadow-stick line, so the surveyor repeats the reading away from steel.
Read a floor plan and the Vastu grid|A plan is divided into zones by direction. The grid helps discuss where rooms sit but must always yield to law and safety.|Mark the sixteen direction zones on a fictional 30 by 40 foot plot plan of 1200 square feet and list which rooms sit in which zone. Compute the area of each of the four main quadrants.|zones marked;rooms listed;areas computed|Each quadrant of the 1200 square foot plot is 300 square feet, and the kitchen is placed in the south-east quadrant.
Plan rooms and entrances for use|Room placement affects comfort, privacy and services. Entrances should be safe, visible and accessible to all.|Propose a fictional layout for a two-bedroom home in a plot facing east, giving the entrance, kitchen, bedrooms, pooja space and toilets with a reason based on both tradition and daily use.|layout complete;reason given;access considered|The kitchen is placed in the south-east, which is traditional, and also keeps a chimney vent on an outer wall.
Adapt Vastu to flats and constrained plots|Many flats cannot follow ideal rules. A consultant prioritises safety, light and comfort and explains trade-offs.|For a fictional flat with the entrance in the south and a kitchen in the north, list priorities, acceptable adjustments and what you tell the family when a change is impossible.|priorities ranked;adjustment kept simple;honest message|The consultant says that the family does not need to move walls and suggests small changes such as lighting and furniture placement.
Understand Feng Shui bagua and flow|Feng Shui uses a bagua map and ideas of flow around doors and furniture. The practical core is clear circulation and balance.|Draw a fictional bagua over a simple room plan, identify a blocked path and a bed facing the door, and write two practical changes with reasons that do not rely on fear.|map drawn;two changes;no fear|The path from the door to the window is cleared by moving a bookshelf, which improves movement and safety.
Compare traditional guidance with codes and structure|Building codes, structural safety and fire exits are legal duties that override any traditional rule. A consultant never advises unsafe changes.|Create a fictional checklist that shows five traditional suggestions and the code or safety checks needed before applying each, such as load-bearing walls, fire exits and drainage.|checks matched;safety first;examples|A suggestion to remove a wall is held until an engineer confirms it is not load-bearing.
Recommend remedies without harm or deceit|Remedies should be harmless, affordable and optional. They must not mislead the client or replace repair of real defects such as leaks.|Write a fictional remedy menu with free, low-cost and no-cost options, prices, a statement of what each can and cannot do, and a refusal rule for a request to hide a structural crack.|options clear;limits stated;refusal rule|The consultant refuses to cover a wall crack with a charm and recommends an engineer's inspection.
Handle a family conflict caused by a Vastu opinion|A consultant's words can create anxiety or conflict. Calm, honest communication and respect for practical facts reduce harm.|Respond to a fictional family where one member wants to demolish a bedroom after a suggestion while others object. Write the message you send, what you withdraw and how you protect safety and budget.|message calm;suggestion withdrawn;safety protected|The consultant writes that no structural change is needed, explains that the suggestion was optional, and recommends keeping the room unchanged.
Prepare a consulting report and fee|A report records observations, suggestions and limits. Fees must be clear and based on time and travel.|Prepare a fictional report outline for a 1200 square foot home visit and calculate the fee from 3 hours at 1500 per hour, travel 600 and a 18 percent tax on the total.|report outline;fee correct;tax applied|The pre-tax total is 4500 plus 600, which is 5100, and 18 percent tax adds 918 for a final fee of 6018.'''),
dict(id='tarot-reading',summary='Learn tarot as a reflective storytelling and symbolism practice: card structure, spreads, imagery, ethical conduct, probability, boundaries and responsible client sessions.',icon='Spark',tool='notebook',tools=['notebook','board'],
nodes=['Study','Spread','Reflect','Close'],modules=['Tarot foundations','Major & Minor Arcana','Spreads & storytelling','Ethics & wellbeing','Reading practice'],
src=dict(page='diploma-in-tarot-reading',code='DTR/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to tarot','Structure of the tarot deck','Major Arcana cards in detail','Minor Arcana suit of Cups','Minor Arcana suit of Pentacles','Minor Arcana suit of Swords']),
rows='''Describe tarot honestly as a tool for reflection|Tarot began as a card game and later became a symbolic tool. It does not have evidence as a predictor, but can prompt reflection.|Write a fictional welcome note for clients that explains what a tarot session is and is not, and that it offers reflection, not certainty or advice on health, law or money.|purpose explained;limits honest;no guarantees|The note says that the cards are used as images to talk about a question and that no card can tell the client what must happen.
Know the structure of the deck|A standard deck has 78 cards: 22 Major Arcana and 56 Minor Arcana in four suits of 14. Knowing the structure supports reading.|Build a fictional deck map listing the Major cards, the four suits and court cards, and show the arithmetic that gives 78. Add one image of how the suits relate to themes.|counts correct;suits mapped;themes listed|Four suits of 14 cards give 56, and adding the 22 Major cards gives a deck of 78.
Study Major Arcana as a journey|The Major Arcana are often read as a story from the Fool to the World. Each card offers an image and a question.|Choose five Major cards and write for each a description of the image, a traditional keyword and a reflective question for a fictional client.|images described;keywords;questions|For the Hermit the question asks what quiet time the client needs to decide.
Read the Minor Arcana by suit and number|Suits indicate areas of experience, while numbers show stages. Court cards often describe people or approaches.|Create a fictional table of the four suits with a theme and a short stage meaning for ace, five and ten. Use it to interpret two imaginary cards.|suits tabled;stages;two interpretations|The five of Pentacles is read as a hardship stage in the area of material life, followed by a question about where support might be asked for.
Run a single-card and three-card spread|A spread gives structure to a question. Open questions lead to better conversations than yes or no questions.|Rewrite three fictional closed questions into open ones and design a three-card spread with positions. Describe the steps from shuffling to closing the reading.|open questions;positions defined;steps ordered|The question Will I get the job becomes What would help me prepare for this interview, and the spread uses past, present and next step.
Understand chance and avoid false certainty|Cards are drawn at random, so patterns can look meaningful by chance. A reader who knows the odds avoids overclaiming.|Calculate the chance that a fictional three-card spread contains no Major Arcana card, and explain in plain words what a repeated card does and does not mean.|probability calculated;plain explanation;no overclaim|The chance of no Major card is 56 over 78 times 55 over 77 times 54 over 76, which is about 0.364 or 36 percent.
Tell a story and keep the client at the centre|A good reading links cards into a story the client can respond to. The reader invites the client to share meaning rather than dictating it.|Write a fictional transcript of a ten-minute reading where you describe the cards, ask three questions and accept the client's correction of your interpretation.|story coherent;questions asked;correction accepted|When the client says the Tower reminds them of leaving a job rather than a disaster, the reader adjusts the meaning.
Handle distress, boundaries and referrals|A tarot reader is not a therapist or doctor. Some clients are in crisis, and the reader must pause and refer.|Create a fictional crisis protocol for a client who mentions self-harm or a medical emergency, including what you say, who you contact, and what you record.|stop reading;referral steps;record kept|The reader says that they are worried, shares a local helpline and encourages the client to contact someone they trust.
Review a session and improve your practice|Reflection after sessions improves quality. Notes show where wording, pacing or boundaries could be better.|Review a fictional recorded reading and mark moments where you spoke with too much certainty, ignored the client or moved too fast. Rewrite three sentences and set a goal.|moments marked;sentences rewritten;goal set|The reviewer replaces the sentence this card means betrayal with this card can invite a conversation about trust.
Set a session policy and price|Policy covers consent, privacy, duration, fees and refusal rules. Pricing should be honest and transparent.|Write a fictional session policy and price a 45 minute reading and a package of three. Calculate the average per session when the package costs 2400 and a single costs 1000.|policy clear;price calculated;refusal rule|The package of three at 2400 averages 800 per session, saving 200 compared with 1000 each.'''),
dict(id='numerology',summary='Study numerology as a number-symbol tradition: core number calculations, name and date methods, charts, compatibility, honest consulting and ethical practice.',icon='Chart',tool='notebook',tools=['notebook','sheets','data'],
nodes=['Calculate','Interpret','Advise','Review'],modules=['Foundations & ethics','Core numbers','Advanced calculations','Names & compatibility','Practice & reports'],
src=dict(page='diploma-in-numerology',code='DN/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to numerology and historical background','Core numbers and their interpretation','Advanced numerology calculations and techniques','Name numerology and compatibility','Numerology in daily life and remedies','Professional practice and case study analysis']),
rows='''Explain numerology and its limits|Numerology assigns symbolic meaning to numbers. It has no scientific evidence as a predictor, so it must be offered as reflection and tradition.|Write a fictional client note that explains the main systems, what a reading offers, and what it cannot do. State that decisions on money, health and law need professional advice.|systems outlined;limits stated;no guarantee|The note says that numbers are used as symbols for talking about personality and choices, not as proof of future events.
Reduce numbers to a single digit|Most numerology reduces multi-digit numbers by adding digits until one digit remains, except in some systems that keep master numbers. Accuracy matters.|Reduce ten fictional numbers, including 23, 49, 66, 104 and 1999, and mark which would be master numbers 11, 22 or 33 before reduction.|reductions correct;master numbers marked;method shown|The number 1999 becomes 1 plus 9 plus 9 plus 9, which is 28, then 2 plus 8, which is 10, then 1.
Calculate a life path number|The life path number is found by reducing the day, month and year separately, then adding them. It is a method, not a measure.|Calculate the life path for a fictional person born on 14 March 1990, showing each reduction and the final number.|each part reduced;sum correct;steps shown|Day 14 becomes 5, month 3 stays 3, year 1990 becomes 1, and 5 plus 3 plus 1 gives 9.
Calculate name numbers with a letter chart|Pythagorean charts assign values from 1 to 9 to letters. Name numbers depend on spelling and system, so the method must be stated.|Using the Pythagorean letters A=1 to I=9 repeating, calculate the full-name expression number of the fictional name RAVI and show the letter values.|chart used;letters valued;sum reduced|R is 9, A is 1, V is 4 and I is 9, which add to 23 and reduce to 5.
Interpret core numbers carefully|Each core number has traditional keywords. A reader should offer possibilities and avoid labelling people.|For a fictional person with life path 9 and expression 5, write a balanced paragraph with strengths, challenges and a question for reflection, avoiding absolute words.|strengths and challenges;balanced tone;question|The paragraph says that the combination suggests a love of variety and service, and asks how the person balances change with commitment.
Build a numerology chart in a spreadsheet|A spreadsheet can automate letter values and reductions, reducing errors. Testing with known values proves the formulas.|Design a fictional spreadsheet that takes a name and birth date and returns life path and expression numbers, then test it on three examples with hand calculations.|formulas planned;three tests;errors checked|The sheet matches the hand calculation of 9 for 14 March 1990 and 5 for RAVI, so the formulas are accepted.
Discuss name changes and compatibility responsibly|Advice to change a name or end a relationship because of numbers can cause real harm. A responsible reader refuses to make such recommendations.|Write a fictional policy for requests such as changing a name to attract wealth or judging a marriage by numbers, and give a script for explaining your limits kindly.|policy clear;script kind;limits explained|The reader says that the numbers can be a conversation starter but that the couple should decide using their own values and facts.
Avoid exploitation of vulnerable clients|Some clients are anxious or in crisis and may be easily influenced. Ethical readers do not use fear to sell products or repeat sessions.|Create a fictional code of conduct for a numerology practice covering fear-based selling, minors, confidentiality, refunds and when to refer to a counsellor or doctor.|rules clear;minors protected;referral|The code bans selling lucky objects and requires a parent's consent when the client is under 18.
Test numerology claims with a simple check|Claims should be tested where possible. A small experiment shows how often general statements feel accurate to people.|Plan a fictional test in which ten volunteers receive the same generic paragraph and a personal paragraph, and rate how accurate each feels. Describe the method and what each result would mean.|test planned;comparison made;cautious conclusion|If eight of ten rate the generic paragraph as accurate, the result suggests that general statements feel personal.
Prepare a report and price a consultation|A report states the method, results and limits in plain language. Pricing reflects time and preparation.|Prepare a fictional report outline and calculate the fee for 90 minutes of consulting at 1200 per hour plus 400 for preparation and a 10 percent discount for a student.|report outline;fee correct;discount applied|The fee is 1800 plus 400, which is 2200, and the student discount of 220 gives 1980.'''),
dict(id='palmistry',summary='Study palmistry as a traditional observational art: hand shapes, lines, mounts, careful notes, honest limits, ethics and respectful sessions that avoid health or fate claims.',icon='People',tool='notebook',tools=['notebook','board'],
nodes=['Observe','Record','Reflect','Close'],modules=['Foundations & ethics','Hands & shapes','Lines & mounts','Observation practice','Responsible sessions'],
src=dict(page='diploma-in-palmistry',code='DP/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to palmistry','Types and shapes of hands','Major lines of the palm','Minor lines and special signs','Practical palm reading skills','Advanced palmistry and career building']),
rows='''Describe palmistry honestly|Palmistry is a traditional art of reading hands for character and life themes. There is no proof that lines predict events, so claims must be modest.|Write a fictional one-page statement for a practice that explains what a palm reading is, what it cannot do, and why it must not be used for health, legal or financial decisions.|tradition explained;limits stated;no prediction claims|The statement says that the hand is read as a mirror for conversation and that no line shows when a person will fall ill.
Prepare a respectful session|Good palm reading begins with consent, privacy, light and a comfortable setting. The reader should ask before touching.|Plan a fictional session setup with consent wording, seating, lighting, a way to record the hands such as photographs only with permission, and a clear end signal.|consent first;setup safe;end signal|The reader asks for permission before touching the hand and uses a photograph only if the client agrees in writing.
Observe hand shape, skin and fingers|Hand shape and finger proportion are the first features recorded in traditional systems. Observations should be separate from interpretations.|Create a fictional observation sheet with fields for hand shape, palm length, finger length, thumb and skin texture, and fill it for two imaginary hands without judging the owner.|fields filled;observations separate;neutral language|The sheet records a square palm with fingers slightly longer than the palm and writes only the measurements.
Identify the main lines|Life, head, heart and fate lines are the usual starting points. Line depth and length vary with age, work and hand use.|Draw a fictional palm and mark life, head, heart and fate lines. Write what each is traditionally linked with and one reason why it cannot indicate lifespan.|lines drawn;traditional links;limit stated|The life line is traditionally linked with vitality, but the reader explains that its length does not measure how long a person will live.
Locate mounts and minor lines|Mounts are raised areas named after planets, and minor lines add detail. They are read as tendencies in the tradition.|Label the mounts and three minor lines on a fictional palm diagram and write a cautious sentence for each beginning with the words in the tradition.|mounts labelled;cautious wording;minor lines|The sentence says that in the tradition a pronounced mount of Jupiter is associated with leadership and ambition.
Compare readings and test for bias|Different readers may see different things in the same hand. Testing for agreement shows the limits of the method.|Plan a fictional exercise where three readers independently describe the same ten hands and compare the results. Calculate the agreement rate if they agree on 6 of 10 descriptions.|blind comparison;rate calculated;conclusion cautious|Agreement on 6 of 10 is 60 percent, which shows that interpretation varies and a cautious tone is needed.
Avoid cold reading and manipulation|A reader can appear accurate by making vague statements or watching reactions. Ethical practice avoids tricking clients.|Write a fictional ethics note that explains cold reading, gives three vague phrases to avoid and shows how to ask open questions honestly instead.|technique explained;phrases avoided;honest questions|Instead of saying you have been hurt in love, the reader asks what relationships feel important right now.
Handle sensitive topics and referrals|Clients may ask about illness, death or crisis. A palm reader is not a medical professional and must refer.|Prepare a fictional response protocol for a client who asks if their palm shows serious illness, including the statement you make, referral, and what you record.|refuse medical claims;referral;calm tone|The reader says that a hand cannot show illness and encourages the client to speak to a doctor if they are worried.
Reflect on bias and the evidence for palmistry|Studies of palmistry claims do not support strong predictions. A reader who knows this can still offer reflection honestly.|Write a fictional reflection on how confirmation bias can make readings seem accurate, and revise your session script to include a statement about the limits of the method.|bias explained;script revised;limits stated|The new script opens with a sentence that explains that observations are offered as ideas to consider rather than facts.
Set up a practice, policy and fee|A practice needs clear fees, consent forms, privacy rules and a complaint process.|Write a fictional policy and calculate a monthly income for 20 sessions at 600 each with 15 percent costs for rent and materials.|policy complete;income calculated;complaint route|Twenty sessions bring 12000, costs of 1800 leave 10200 before tax.'''),
dict(id='gems-crystals',summary='Learn gemmology and the gem trade: identification, hardness and density tests, treatments, lab-grown stones, valuation, ethical sourcing and honest handling of crystal beliefs.',icon='Cube',tool='data',tools=['data','notebook','budget','sheets'],
nodes=['Observe','Test','Value','Disclose'],modules=['Gem science','Identification','Treatments & processing','Jewellery & valuation','Ethical trade & belief'],
src=dict(page='diploma-in-gems-crystals',code='DGC/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to gemology and crystal science','Gem identification techniques','Crystal healing and metaphysical properties','Cutting, polishing and gemstone processing','Jewelry design and setting techniques','Gemstone business, valuation and certification']),
rows='''Classify gemstones and minerals|Gems are minerals, rocks or organic materials valued for beauty, durability and rarity. A basic classification helps identify them.|Create a fictional reference table of ten gems with mineral name, colour range, hardness and typical uses, and mark which are crystalline minerals and which are organic.|ten gems listed;hardness noted;classes marked|Pearl is organic and soft, while corundum is a crystalline mineral with hardness 9.
Use the Mohs scale safely|The Mohs scale ranks scratch resistance from 1 to 10. Scratch tests can damage stones, so they are used carefully and rarely on finished gems.|Write a fictional procedure that explains the scale, gives five reference minerals and lists when a scratch test must not be used, such as on a set stone of value.|scale explained;five references;caution given|Quartz at 7 will scratch glass and feldspar but not topaz at 8.
Examine with a loupe and light|A 10 times loupe reveals inclusions, surface wear and cut quality. Correct lighting and technique avoid misleading impressions.|Plan a fictional inspection of a faceted stone with lighting, loupe hold, what to look for in the interior and surface, and a record sheet for notes.|method correct;features listed;record sheet|The student holds the loupe close to the eye and the stone close to the loupe, then looks for gas bubbles that suggest glass.
Measure specific gravity|Specific gravity compares a stone's weight with water. It is calculated from weights in air and in water, and helps separate similar stones.|A fictional loose stone weighs 5.00 carats in air and 3.75 carats in water. Calculate its specific gravity and say which gem family it could belong to.|formula used;value correct;family suggested|The specific gravity is 5.00 divided by the difference 1.25, which is 4.0, consistent with corundum such as ruby or sapphire.
Separate natural, lab-grown, treated and imitation stones|Disclosure is essential. A natural stone, a lab-grown stone and a glass imitation have very different values, and a treatment changes value.|Create a fictional disclosure form that states origin, treatments and testing, and write three phrases that are honest and three that mislead.|categories clear;honest phrases;misleading phrases|The phrase heat treated to improve colour is honest, while untreated without testing is misleading.
Understand cutting and polishing|Cut affects brilliance and weight loss. Cabochons and faceted cuts suit different materials, and lapidary work needs safety.|Compare cabochon and faceted cuts for a fictional opal and a fictional garnet, with reasons, weight loss and safety such as dust and eye protection.|cuts compared;weight loss;safety|A cabochon suits opal because it shows play of colour, and a wet saw is used to keep dust down.
Grade and value a stone|Value depends on colour, clarity, cut, weight and market. Price per carat is multiplied by weight, with adjustments for quality.|Value a fictional 2.5 carat sapphire at 8000 per carat, then apply a 15 percent discount for a visible inclusion and a 5 percent dealer margin. Show each step.|base value;discount applied;margin applied|Base value is 2.5 times 8000, which is 20000, the discount of 3000 gives 17000, and a 5 percent margin of 850 gives 17850.
Design and set a simple jewellery piece|Jewellery combines design, metal work and secure setting. A stone must suit its setting and wear.|Plan a fictional pendant with a cabochon, choosing the stone hardness, setting type, metal, finishing and care instructions for a customer who wears it daily.|stone suited;setting chosen;care sheet|A soft stone such as opal is protected in a bezel setting and the care sheet warns against water and impacts.
Check supplier ethics and traceability|Gems can be linked to unsafe mining, child labour or conflict. Responsible buyers ask for origin and records.|Create a fictional supplier checklist that covers origin documents, treatments, labour standards, payment terms and a red-flag list for suspicious offers.|origin asked;labour checked;red flags|The buyer rejects an offer with no paperwork that is priced far below the market rate.
Treat crystal healing claims honestly|Crystals are meaningful to many people, but there is no evidence they treat disease. Honest sellers describe belief as belief.|Write a fictional product description and customer reply policy for crystals that respect personal belief, avoid any health claim, and tell a customer who asks about cancer to follow medical advice.|belief stated as belief;no health claims;medical referral|The description says that many people use rose quartz as a calming reminder and does not say it heals.'''),
dict(id='vedic-culture',summary='Study Vedic and Indian knowledge traditions critically: texts, philosophy, Sanskrit basics, calendars, mathematics methods, Ayurveda and yoga overviews, research skills and respectful interpretation.',icon='Compass',tool='notebook',tools=['notebook','board'],
nodes=['Read','Compare','Evaluate','Share'],modules=['Texts & history','Philosophy & language','Mathematics & calendars','Health traditions & lifestyle','Research & cultural practice'],
src=dict(page='diploma-in-vedic-sciences',code='DIVS/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to Vedic literature','Vedic philosophy','Vedic mathematics','Vedic astrology (Jyotish)','Vedic rituals and yajnas','Ayurveda basics']),
rows='''Map the Vedic literature|Vedic literature includes the four Vedas, their commentaries and later philosophical texts. A timeline and map prevent confusion.|Create a fictional study map that places the four Vedas, Brahmanas, Aranyakas and Upanishads in order, with one line on the content of each and a note on what is uncertain about dates.|order correct;content described;uncertainty noted|The Rigveda is shown as a collection of hymns, and the map notes that scholars differ on exact dates.
Distinguish text, tradition and modern claims|Traditional texts, later commentaries and modern claims are different layers. A critical reader asks what a source actually says.|Evaluate three fictional claims that a Vedic text contains a modern invention. For each, state what the passage says, what the claim adds and how you would check it.|source checked;claim separated;method named|A claim that a hymn describes electricity is checked by reading the translation and finding that it speaks only of fire and lightning.
Study the six philosophical schools|The six classical schools offer different views on knowledge, reality and liberation. A comparison clarifies their differences.|Build a fictional comparison table of Nyaya, Vaisheshika, Sankhya, Yoga, Mimamsa and Vedanta with focus, key idea and one example question each.|six schools;key idea;comparison|Nyaya focuses on logic and valid means of knowledge, while Yoga focuses on disciplined practice of the mind.
Learn basic Sanskrit reading|Sanskrit is read with attention to sounds, script and word forms. Basic skills help read short verses.|Plan a fictional two-week routine to learn the Devanagari alphabet, ten common words and one short verse, with a daily goal and a method of checking pronunciation with a teacher.|alphabet plan;words chosen;teacher check|Each day the learner practices eight letters and writes the five new words in a notebook.
Use Vedic mathematics methods and check them|Some mental calculation methods are popularly called Vedic. Their value is speed in specific cases, and every shortcut must be tested.|Demonstrate for fictional pupils the base-100 method for 98 times 97 and the square of 75, then check each with ordinary multiplication and the digit-sum test.|methods shown;answers checked;digit sum|For 98 times 97 the deficits are 2 and 3, giving 95 and 06, so the answer is 9506, and 75 squared is 5625.
Read the calendar and festival timing|The Panchang records tithi, nakshatra and other elements to date festivals. Lunar and solar systems explain why dates move.|Explain in a fictional teaching note why a lunar festival changes its Gregorian date each year and calculate the gap between 12 lunar months of about 29.5 days and 365 days.|lunar logic;gap calculated;note clear|Twelve lunar months give about 354 days, which is 11 days short of 365, so an extra month is added periodically.
Introduce Ayurveda and yoga as traditions|Ayurveda and yoga are traditional systems with ideas about balance and discipline. A student should understand the ideas and not give medical advice.|Prepare a fictional overview of three Ayurvedic ideas and three yoga ideas with their meaning, plus a clear statement of what the course does not teach, such as diagnosing or treating illness.|ideas explained;limits stated;no medical advice|The overview explains daily routine and seasonal living as traditional ideas and tells readers to consult a qualified doctor for illness.
Compare translations of a verse|Translations differ, and comparing them shows how interpretation enters. A careful reader notes the original term and the translator's choice.|Choose a fictional short verse and compare two translations. List the words that differ, what each choice suggests, and what question a Sanskrit teacher could answer.|words compared;differences explained;question set|One translation renders a term as duty and another as law, so the learner asks the teacher about the original meaning.
Evaluate health claims about traditional practices|Traditional practices may be valued culturally even when evidence is limited. A student checks claims, avoids medical advice and respects the tradition.|Evaluate three fictional claims about a herbal remedy, a breathing practice and a diet. For each, rate evidence, risk and how you would phrase an honest statement.|evidence rated;risk considered;honest wording|The claim that a herb cures diabetes is rated unsupported and risky, and the statement advises people to continue prescribed treatment.
Plan a small research project|Research on traditional knowledge needs a clear question, reliable sources and honest conclusions. Respect for living communities is part of method.|Design a fictional research plan on how a festival is celebrated in two regions, with sources, questions, consent for interviews and how findings will be shared.|question clear;sources listed;consent planned|The plan interviews two elders with their permission and compares the results with a published description.'''),
dict(id='paurohitya',summary='Study the structure of Hindu ritual practice responsibly: ceremonies, mantra learning, calendar and timing, safety, ethics, family communication and the limits of learning without a guru.',icon='People',tool='notebook',tools=['notebook','board','budget'],
nodes=['Learn','Prepare','Conduct','Reflect'],modules=['Tradition & responsibility','Mantra & language','Ceremonies','Fire rituals & safety','Practice with a mentor'],
src=dict(page='certificate-in-paurohitya',code='CIP/Q0001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Introduction to Paurohitya and Vedic traditions','Vedic chanting and mantra recitation','Hindu rituals and ceremonies','Yajnas and homa rituals','Astrology and muhurta selection','Temple rituals and pujas']),
rows='''Understand the role of a priest and its responsibilities|A priest serves families and communities with knowledge, discretion and respect. Authority comes from training, lineage and character.|Write a fictional code of conduct for an assistant priest covering respect for all families, confidentiality, fair fees, dress, punctuality and refusal of requests that harm others.|responsibilities listed;fees fair;confidentiality|The code requires the priest to state fees before the ceremony and to treat all families with equal respect.
Respect the limits of independent study|Mantra and ritual are learned from a teacher. A course can organise knowledge but cannot replace guidance and lived practice.|Create a fictional learning plan that shows what you will study by reading, what you will practise with a mentor, and how you will check pronunciation and procedure.|study and mentor split;check method;humility|The plan places pronunciation with a teacher every week and records feedback in a notebook.
Learn the structure of a daily prayer|Daily prayer has a sequence of preparation, invocation, offering and closing. Understanding the sequence helps a learner follow rather than rush.|Write a fictional outline of a 20 minute household prayer with the order of steps, time for each part and the items needed. Keep it a simple outline with no claims of power.|sequence clear;time totals 20;items listed|Preparation takes 4 minutes, invocation 4, offerings 6, aarti 4 and closing 2.
Study the sixteen samskaras|The samskaras mark stages of life from birth to death. Each has traditional meaning and regional variations.|Build a fictional chart of the sixteen samskaras in order, with the life stage and a note on how practice varies across regions and families.|sixteen listed;stage noted;variation shown|Vivaha, the marriage ceremony, is shown as a life-stage ritual with many regional variations.
Plan a ceremony with the family|A ceremony begins with the family's wishes, budget, guests and customs. Good planning reduces stress and respects the occasion.|Prepare a fictional planning sheet for a house-entering ceremony with date, materials, roles, timeline and budget. Calculate the cost of materials 3500, fees 2100, flowers 800 and sweets 1200.|sheet complete;timeline set;cost correct|The total is 3500 plus 2100 plus 800 plus 1200, which is 7600.
Use the Panchang for timing|The Panchang gives date, tithi and nakshatra. Timing is a tradition, and practical needs such as guests and weather also matter.|Plan how to choose a date for a fictional ceremony using a Panchang and the family's availability, with three candidate dates and the reasons for choosing one.|candidates listed;reasons clear;practical needs|The priest offers three dates, and the family chooses the one that suits elderly relatives travelling from another city.
Manage fire, smoke and safety in homa|Fire rituals involve heat, smoke and ghee. Safety planning protects guests, children and the building.|Create a fictional safety plan for an indoor homa that covers ventilation, a fire extinguisher, a sand bucket, clearance from curtains, ghee handling and a response to a flare-up.|ventilation planned;extinguisher ready;response steps|The priest places the kund away from curtains, keeps a sand bucket nearby and never pours water on a ghee fire.
Conduct rituals ethically with clear explanations|Families should understand what they are asked to do. Honest explanation avoids fear-based selling of extra rituals.|Write a fictional script that explains each step of a short puja in the family's language, states the fee, and refuses to add costly extra rituals through fear.|plain language;fee stated;no fear|The priest says that the ceremony is complete as planned and does not suggest further rituals as a remedy.
Conduct sensitive ceremonies with care|Funeral rites, remembrance and difficult family situations call for gentleness. A priest listens first and works within the family's wishes.|Prepare a fictional approach for supporting a grieving family: what you ask, how you explain each step, what you avoid saying and where you refer for counselling.|listens first;explains steps;referral|The priest asks who will perform each role, explains the order briefly and suggests contacting a grief counsellor if the family wishes.
Compare ritual materials and environmental impact|Flowers, idols and offerings affect the environment. Many communities adopt eco-friendly options.|Compare a fictional immersion of a plaster idol with a clay idol and a symbolic immersion at home, and plan how to dispose of flowers and ash responsibly.|options compared;disposal planned;respect kept|The family chooses a small clay idol and composts the flowers instead of throwing them into the river.'''),
]
