COURSES=[
dict(id='library-science',summary='Organise knowledge for users: library principles, classification, cataloguing, collection development, circulation, reference service, digital libraries and library automation.',icon='Compass',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Acquire','Organise','Serve','Preserve'],modules=['Library foundations','Classification & cataloguing','Collections & circulation','Information services','Digital library plan'],
src=dict(page='diploma-in-library-science',code='DLS/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Foundations of library and information science','Library classification','Library cataloguing and metadata','Library management and administration','Information sources and services','Information technology and library automation']),
rows='''Apply the five laws of library science|The five laws put the reader first: books are for use, every reader has a book, every book has its reader, save the reader's time, and a library is a growing organism.|Evaluate a fictional school library with a locked reference section, no signage and a catalogue three years behind. Match each problem to a law and propose one fix per law.|laws named;problems matched;fixes|Locked books that children cannot borrow break the law that books are for use, so a supervised borrowing rule is introduced.
Choose library types and their services|Academic, public, school and special libraries serve different users and need different collections and services.|Compare four fictional libraries, a village public library, a college library, a hospital library and a law firm library, by users, collection and services. Recommend a priority service for each.|four types compared;users defined;priority service|The hospital library prioritises quick access to clinical guidelines and journal articles for busy staff.
Classify a book with a general scheme|Classification places a book where it will sit among related books. A scheme uses numbers to group subjects, and the number should reflect the main subject.|Using the main classes of a general scheme given in the case, assign a class number to five fictional books and explain the main subject of each. Mark one with two subjects and decide where it goes.|main class chosen;subject reasoning;two-subject decision|A book on Indian history is placed in the history class for India. If a book covers history and economics equally, the cataloguer follows the rule in the scheme and records the choice.
Build a call number|A call number combines class number, author or book number and sometimes a collection or year. It gives each item a unique place on the shelf.|Construct call numbers for six fictional books in the same class, with the author mark and a rule for editions. Arrange them in shelf order.|class and book number;shelf order;edition rule|Two books in the same class are separated by author marks, so Rao comes before Sharma, and a second edition is marked so it sits next to the first.
Catalogue a book with descriptive and subject access|A catalogue record describes an item and gives access points such as author, title and subject. Consistent data makes searching reliable.|Prepare a fictional catalogue record for a book with title, statement of responsibility, edition, publication, physical description, series, subject headings and added entries. Explain why consistent author names matter.|record fields;access points;consistency|Searching for an author finds all his works only if the name is entered the same way each time, so an authority list is used.
Plan collection development|A collection should match user needs and budget. Selection, weeding and balance prevent a library from growing out of date.|For a fictional college library with a 5 lakh annual budget, divide spending among subjects, formats and journals using user surveys and loan data. Define a weeding rule for old items.|needs-based split;weeding rule;evidence|Loan data shows computing books circulate twice as often as literature, so computing receives a larger share, while superseded editions are withdrawn.
Run circulation and track overdue items|Circulation records loans, returns and reservations. Clear rules and accurate records keep stock available and fair for all users.|Design a fictional circulation system with membership rules, loan periods, renewals, reservations, fines and stock verification. Calculate overdue fines for a book returned 6 days late at 2 per day with a 3-day grace period.|clear rules;fine calculation;stock check|With a 3-day grace period and a 2 per day fine, a book 6 days late has 3 chargeable days, so the fine is 6.
Answer reference questions and evaluate sources|A reference librarian finds reliable answers quickly and teaches users to judge sources. Authority, date, evidence and purpose matter.|Answer three fictional reference questions using a mix of print and online sources. Record the source, why you trust it and how you would verify a surprising claim.|source recorded;evaluation;verification|For a statistic found only on a blog, the librarian looks for the original report or an official publication before giving the number.
Introduce library automation and digital resources|Library software manages catalogue, circulation and acquisitions. Digital libraries add e-resources, access controls and licensing.|Plan a fictional move from a card catalogue to library software, with data entry rules, barcoding, training, backup and a digital collection of old theses. Include copyright and access limits.|migration steps;data quality;copyright|Records are entered with a template and checked by a second person, while theses are shared only as the author's permission allows.
Deliver a library service plan|A plan joins collection, organisation, services, staffing, technology and evaluation into one realistic proposal.|Package a fictional plan to improve a school library: user needs survey, collection and shelving plan, cataloguing standards, circulation rules, reading programme, budget and statistics for the annual report.|needs to plan;statistics;budget|The plan tracks visits, loans per student and user satisfaction each term, and shows that loans doubled after the reading programme began.'''),

dict(id='sports-physical-education',summary='Coach and teach physical education safely: anatomy, training principles, health and nutrition, psychology, injury prevention, event organisation, rules and fair play.',icon='People',tool='notebook',tools=['notebook','board','sheets'],
nodes=['Assess','Train','Protect','Organise'],modules=['Foundations & body systems','Training principles','Health, psychology & safety','Events & rules','Coaching programme'],
src=dict(page='diploma-in-physical-education',code='SBDSCPE/Q1001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Foundations of physical education','Anatomy and physiology in sports','Health education and nutrition','Sports psychology and sociology','Sports training and yoga','Organisation, administration, rules and officiating']),
rows='''Explain the aims of physical education|Physical education supports health, movement skill, teamwork and lifelong activity. It is for every child, not only the talented.|Write a short fictional programme statement for a school PE department, with four aims and a plan for including students with disability or low confidence.|aims stated;inclusion;examples|A student with an injured leg can still lead warm-ups or keep score, so every student remains part of the lesson.
Describe how the body responds to exercise|Exercise raises heart rate and breathing, uses muscles and energy, and over time adapts the body. Knowing this helps plan safe sessions.|For a fictional student running 800 metres, describe what happens in the heart, lungs and muscles during and after, and how fitness changes with weeks of training.|systems named;short and long term;plain explanation|Heart rate rises to deliver oxygen to muscles. With regular training the same run feels easier because the heart pumps more blood per beat.
Plan a safe warm-up and cool-down|A warm-up prepares the body and mind for activity, and a cool-down helps recovery. Both should match the activity.|Design a fictional 10-minute warm-up and 5-minute cool-down for a football session, listing exercises, duration and reasons. Include a safety check of the ground and equipment.|stages;reasons;safety check|The warm-up moves from jogging to dynamic movements that resemble the game, and the field is checked for stones and holes.
Measure fitness with simple tests|Fitness tests show a starting point and progress. They must be done safely, consistently and with respect for each student's privacy.|Plan fictional tests for endurance, strength, flexibility and speed for 30 students, with equipment, steps, scoring and a rule about not displaying ranks publicly. Record how to repeat tests fairly.|test choice;consistency;privacy|Each student's result is shared privately and compared with their own earlier score, not publicly ranked against classmates.
Apply training principles in a weekly plan|Training works through overload, progression, specificity, recovery and variety. Too much too soon causes injury.|Create a fictional 4-week conditioning plan for school athletes with sessions, intensity, rest days and a progression rule that raises load gradually. Explain the role of recovery.|principles applied;progression;recovery|Running volume rises by a small step each week, with a lighter fourth week so the body can adapt.
Plan nutrition and hydration for young athletes|Young athletes need balanced meals and fluids. Supplements are not a shortcut and some are risky or banned.|Plan a fictional match-day eating and drinking plan for 15-year-old athletes with meals, snacks and hydration, and write advice about supplements and anti-doping rules.|balanced plan;hydration;supplement caution|Athletes eat a carbohydrate-rich meal a few hours before, drink water regularly, and are advised not to take any supplement without medical advice.
Support motivation and manage pressure|Athletes perform better when they feel competent, supported and in control. Over-pressure and public blame harm motivation.|For a fictional young player who freezes in matches, write a coaching plan using goal setting, simple routines and positive feedback, and avoid public criticism. Include when to involve parents or a professional.|goals;routine;respectful feedback|The coach sets a process goal of making three good passes rather than demanding a win, and gives feedback privately.
Respond to common sports injuries|Prevention and prompt first aid reduce harm, but serious injuries need medical care. Staff should be trained by a certified provider.|Prepare a fictional injury response card for sprains, bleeding, fainting and suspected head injury, with immediate steps, when to call for help and what to record. State that hands-on first aid requires certified training.|steps;escalation;record|A player with a suspected head injury is removed from play, not left alone and not allowed to return until medically cleared.
Run a tournament fairly|Fixtures, rules, officials and safety must be planned. The format should fit the number of teams and time.|For a fictional school tournament with 12 teams, compare knockout and league formats, calculate matches needed, byes and total time, and write rules for tie-breakers and conduct.|format compared;matches calculated;rules|A 12-team knockout needs 11 matches and uses byes to reach 16 slots. A 6-team league needs 15 matches.
Design a coaching programme|A programme joins assessment, goals, sessions, safety, communication and review for a group or individual.|Package a fictional 8-week school athletics programme: assessment, goals, session plans, safety checks, parent communication, tests and a review that adjusts the plan.|assessment to plan;safety;review|The review shows most improvement in endurance and little in sprint speed, so the next block adds short-sprint drills.'''),

dict(id='fitness-training',summary='Design safe, effective exercise programmes: screening, anatomy, training principles, strength, cardio, nutrition basics, motivation, group coaching and professional ethics.',icon='Spark',tool='budget',tools=['budget','notebook','sheets'],
nodes=['Screen','Assess','Programme','Review'],modules=['Screening & anatomy','Strength & cardio programming','Nutrition & special populations','Coaching & behaviour','Training business'],
src=dict(page='diploma-in-fitness-trainer',code='DFT/Q001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to fitness training','Principles of exercise science','Cardiovascular training and endurance','Nutrition and supplementation','Fitness assessments and corrective exercise','Sports psychology and coaching skills']),
rows='''Screen a new client before exercise|Screening finds health conditions that need medical advice before training. Training someone who should first see a doctor can cause harm.|Prepare a fictional readiness questionnaire and consent form for a new client and decide what you do when the client reports chest pain with effort. Explain what you record.|screening questions;doctor referral;consent|A client who reports chest pain during activity is advised to see a doctor first, and training starts only after medical clearance.
Know the main muscles and how joints move|Understanding where muscles sit and how joints move helps you choose exercises and cue them correctly.|Match ten fictional exercises to the main muscles and joint actions they involve, and explain a safe alternative for a client with sore knees.|muscles matched;joint actions;alternative|A squat works the thighs and buttocks through hip and knee bending. A box squat to a chair limits depth for a client with sore knees.
Calculate heart-rate zones with limits|Heart-rate zones help set cardio intensity, but formulas are estimates and some medicines change heart rate. Perceived effort is a useful check.|For a fictional 40-year-old client, estimate maximum heart rate with the common age formula, calculate 60 and 80 percent zones and add a talk test as a check. State the limits of the estimate.|zone calculation;talk test;limits|The estimate is 180 beats per minute, so the moderate zone is about 108 to 144. The client should be able to speak in short sentences.
Design a beginner strength session|A beginner session uses basic movements, controlled technique and modest loads. Quality matters more than weight.|Design a fictional 45-minute full-body beginner workout with warm-up, six exercises, sets, repetitions, rest and cool-down. Explain how you teach technique and when you increase load.|balanced session;technique cues;progression rule|The trainer moves up in weight only when the client can do all sets with good form and still has a couple of repetitions in reserve.
Apply progressive overload safely|Progress comes from gradual increases in load, volume or difficulty. Rapid jumps cause injury and burnout.|Write a fictional 8-week progression for a client doing push-ups from knees to standard push-ups, with weekly steps and a rule for slowing down when pain or fatigue appears.|weekly steps;pain rule;rest|The client progresses from incline push-ups on a wall to a bench, then the floor, and stops an exercise that causes joint pain.
Explain nutrition basics within your scope|Fitness trainers can share general healthy-eating guidance. They do not prescribe diets for medical conditions or recommend risky supplements.|Write fictional advice for a client who asks about protein and fat loss, covering balanced eating principles and when to refer to a dietitian. Say what you will not recommend.|general guidance;scope;referral|The trainer talks about meals, portions and water, and refers a client who has diabetes to a qualified dietitian before any diet change.
Adapt training for special populations|Older adults, pregnant clients and people with health conditions need adapted exercise and often medical advice.|Plan fictional adaptations for a 62-year-old beginner with high blood pressure and a pregnant client in the second trimester, with medical clearance, intensity limits and exercises to avoid. State that specialist advice is required.|clearance;adaptations;exercises avoided|The older client avoids breath-holding and heavy straining and warms up slowly, while the pregnant client follows the doctor's advice on position and intensity.
Coach behaviour and motivation|Clients succeed when they set realistic goals and build habits. Coaches support rather than shame.|Write a fictional coaching conversation for a client who has missed three sessions. Include listening, reframing, a small goal, an action plan and a follow-up message.|listening;small goal;follow-up|The trainer asks what got in the way and agrees on two short sessions per week for two weeks before building up again.
Lead a group class safely|Group classes need clear cues, options for different abilities and attention to safety. A coach watches the room, not the mirror.|Plan a fictional 40-minute group circuit for 15 mixed-ability clients with stations, timing, easier and harder options, space layout and safety checks. Add how you manage a client who pushes too hard.|stations and options;spacing;safety|Each station has an easier and a harder version, and clients are reminded that sharing the work at their own level is the goal.
Build a training plan and a small business model|A personal trainer sells results and trust. Clear packages, honest claims, records and insurance matter.|Package a fictional trainer plan: client screening, 12-week programme, progress records, session pricing, cancellation rules, privacy rules and honest marketing, with break-even sessions per month.|programme and records;honest claims;break-even|At a fixed monthly cost of 12,000 and a margin of 600 per session, the trainer needs 20 sessions a month to cover costs.'''),

dict(id='weight-management',summary='Support healthy weight management within professional scope: energy balance, nutrition, activity, behaviour, special populations, myths, safe referral and ethical practice.',icon='Chart',tool='budget',tools=['budget','notebook','sheets'],
nodes=['Assess','Plan','Support','Refer'],modules=['Assessment & scope','Nutrition & activity','Behaviour & mind','Medical context & special groups','Programme design'],
src=dict(page='advanced-diploma-in-obesity-and-weight-management',code='ADOWM/Q1001',duration='Six Months',eligibility="Bachelor's degree or equivalent",modules=['Introduction to obesity and weight management','Nutritional approaches','Exercise and physical activity','Psychological and behavioural aspects','Medical and pharmacological interventions','Technology and innovations']),
rows='''Calculate BMI and understand its limits|Body mass index is weight divided by height squared. It is a screening number, not a diagnosis, and it does not show body fat, muscle or health by itself.|For a fictional adult weighing 70 kg at 1.65 m, calculate BMI, compare it with the cut-offs given in the case and explain two reasons why BMI can mislead.|calculation;cut-offs from case;limits|70 divided by 1.65 squared is about 25.7. A muscular athlete can have a high BMI without excess fat.
Take a respectful history and know your scope|A weight consultant asks about habits, health and goals with respect. They do not diagnose or treat disease and refer when needed.|Prepare a fictional intake form covering eating pattern, activity, sleep, medicines, health conditions and goals, and list the red flags that require a doctor before any plan.|intake questions;red flags;referral|A client with diabetes who takes insulin must have a doctor involved before changes in diet, since changing meals can affect blood sugar.
Explain energy balance simply|Weight changes when energy intake and use differ over time. Calories matter, but food quality, hunger and habits decide what is sustainable.|Explain energy balance to a fictional client using a food diary example and a rough rule of about 7,700 kilocalories per kilogram of body fat. State why this is only an estimate and a safe pace to aim for.|rule explained;estimate caution;safe pace|A steady daily deficit of 500 kilocalories leads to about 0.5 kg a week, but the body adapts so progress is rarely perfectly linear.
Plan balanced meals with portion awareness|A healthy plan uses vegetables, protein, whole grains and healthy fats in sensible portions, using local and affordable foods.|Plan a fictional three-day menu for a vegetarian office worker aiming to lose weight gradually, using a plate model, local foods and a budget. Include snack swaps.|plate model;local foods;snack swaps|The plan uses dal, vegetables and a small portion of whole grain, and replaces sweet tea and fried snacks with fruit and roasted chana.
Compare diet approaches honestly|Fad diets may produce quick changes but are hard to sustain and may be unsafe for some people. Evidence and fit with the person matter.|Compare three fictional diet styles on how they work, who should avoid them, sustainability and evidence quality. Write a respectful reply to a client who wants a very low-calorie crash diet.|honest comparison;safety;respectful reply|A very low-calorie crash diet is declined without judgment, with an explanation of risks and an offer of a gradual plan.
Set up safe activity for weight loss|Regular activity supports health and weight maintenance. Start gradually, choose activities the person enjoys and add movement through the day.|Design a fictional 6-week activity plan for a sedentary client with sore knees, mixing walking, low-impact movement and strength, with progression and safety stops.|gradual plan;low impact;stop rules|The client starts with 10-minute walks after meals and adds time each week, avoiding high-impact jumping until the knees are comfortable.
Build habits with behaviour change tools|Lasting change comes from small steps, planning for obstacles and self-monitoring without self-blame.|Write a fictional habit plan using goal setting, an implementation plan, a barrier plan and weekly review for a client who snacks at night. Use language that avoids shame.|small goals;obstacle plan;kind language|If I feel like snacking after 9 pm, I will have a glass of water and a piece of fruit, is easier to follow than I will stop eating at night.
Recognise eating disorders and refer|Disordered eating is a health condition. A weight consultant must notice warning signs, avoid reinforcing them and refer to a qualified professional.|Review fictional signs in a client who skips meals, measures food obsessively and fears gaining weight. Write the conversation you would have and the referral steps. State that you do not manage eating disorders.|warning signs;caring approach;referral|The consultant expresses concern, stops the weight loss plan and helps the client contact a doctor or mental health professional.
Work safely with children and with medical conditions|Children, pregnant women, older adults and people with medical conditions need specialist-led advice. A consultant supports within a medical plan.|Prepare fictional guidance on how to respond to a parent asking for a weight loss diet for a 10-year-old and to a client with thyroid disease. Explain your role and the referrals.|children cautions;medical team;scope|For a child, the consultant encourages family activity and healthy meals and refers the parent to a paediatrician before any weight target is set.
Deliver an ethical weight management programme|A programme sets realistic outcomes, honest marketing, privacy rules and review points, and does not sell false hope.|Package a fictional 12-week programme: intake, goals, education sessions, activity plan, tracking, referral rules, privacy, honest claims and a review that includes non-weight outcomes such as energy and sleep.|honest claims;non-weight outcomes;referral rules|The programme advertises support and education, not guaranteed kilos lost, and measures waist, stamina and sleep alongside weight.'''),

dict(id='yoga-foundations',summary='Learn yoga as a practice and tradition: the eight limbs, ethics, asana safety, breathing, relaxation, meditation basics, anatomy awareness and a personal practice plan.',icon='Compass',tool='notebook',tools=['notebook'],
nodes=['Understand','Practise','Adapt','Reflect'],modules=['Yoga foundations','Asana & safety','Breath & relaxation','Meditation & lifestyle','Practice plan'],
src=dict(page='diploma-in-yoga',code='DY/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to yoga','Asanas','Pranayama','Meditation techniques','Anatomy and physiology for yoga','Yoga therapy and healing']),
rows='''Explain what yoga is and where it comes from|Yoga is a system of practices for body, breath and mind with roots in Indian philosophy. It is more than physical exercise.|Write a one-page fictional introduction for a beginner class that explains yoga in plain language, the meaning of the word, and how modern classes relate to the tradition. Avoid medical claims.|plain language;tradition respected;no medical claims|Yoga means union or discipline, and a modern class may include postures, breathing and relaxation drawn from a longer tradition.
Name the eight limbs and apply two to daily life|The eight limbs are ethical restraints, observances, postures, breath control, withdrawal of the senses, concentration, meditation and absorption. They give yoga a way of living.|List the eight limbs and choose one restraint and one observance to apply to a fictional person's work day, such as honesty and cleanliness. Describe one practical action for each.|eight limbs named;two applied;practical actions|Practising truthfulness at work means giving an accurate update about a delayed task rather than hiding the problem.
Practise safe alignment in basic postures|Safe posture work respects the body's limits, moves slowly and avoids pain. More depth is not better.|Write the instructions and three safety cues for five fictional basic postures, including a standing, seated, forward bend, twist and relaxation pose. Include one modification for stiff hips.|clear instructions;safety cues;modification|A seated forward bend uses a folded blanket under the hips and a bent knee, so the spine stays long rather than rounding to reach the feet.
Understand contraindications|Some conditions need extra care in certain postures and breathing practices. A teacher or practitioner asks about health first and recommends medical advice when needed.|Create a fictional contraindication table for inversions, strong twists, forward bends and breath holding for high blood pressure, pregnancy, back injury and eye conditions. Explain how you adapt the plan.|conditions matched;adaptation;medical advice|A practitioner with high blood pressure avoids long head-below-heart positions and breath holding, and checks with a doctor.
Sequence a sun salutation and a short practice|A sequence moves the body in a logical order from gentle to stronger and back to calm. Breath and movement are linked.|Write a fictional 20-minute beginner sequence with centring, warm-up, a sun salutation in its steps, standing postures and relaxation. Mark timing and breath cues.|logical order;breath link;timing|The sequence starts with gentle neck and shoulder movements, builds through a slow sun salutation and ends with five minutes of lying relaxation.
Learn basic breathing practices safely|Simple breath awareness and slow breathing are suitable for beginners. Strong or retained breathing practices require guidance and are not for everyone.|Describe the steps for three fictional beginner breathing practices, their purpose and safety limits, and list who should avoid strong practices without medical advice.|three practices;limits;who avoids|A person with respiratory trouble or high blood pressure does not practise breath retention or forceful breathing without advice.
Guide a relaxation practice|Relaxation helps the body recover from stress. A calm voice, comfort and clear steps help people settle.|Write a fictional 10-minute guided relaxation script with positioning, breath awareness, a body scan and a gentle return. Include what to do if someone feels uneasy.|calm script;comfort;return to alertness|If a participant feels uneasy during relaxation, the guide invites them to open their eyes, notice the room and breathe slowly, with permission to stop.
Practise simple concentration and meditation|Meditation trains attention. Short, regular practice is more useful than long, forced sessions.|Plan a fictional 4-week beginner meditation routine with time, posture, focus object and how to handle a wandering mind. Include a simple log.|short regular practice;focus method;simple practice log|The first week uses five minutes of breath counting, and each time the mind wanders the practitioner gently returns to the count.
Build a personal practice and lifestyle plan|A personal practice fits the person's time, health and goals, and combines movement, breath, rest and reflection.|Create a fictional weekly practice plan for a busy office worker, with times, practices, rest days, a plan for low-energy days and a monthly review question.|realistic schedule;rest;review|On low-energy days the plan reduces to ten minutes of gentle stretching and slow breathing rather than skipping practice.
Deliver a beginner yoga programme|A programme joins philosophy, practice, safety, adaptation and progress notes into a coherent beginner course.|Package a fictional 8-week beginner programme with weekly themes, class outlines, safety notes, home practice, a feedback form and a respectful way to teach the tradition.|structured weeks;safety;feedback|The programme begins each class with a short centring and ends with relaxation, and asks participants after week four what feels helpful and what feels difficult.'''),

dict(id='yoga-instruction',summary='Teach yoga safely and professionally: lesson planning, cueing, modifications, consent and touch, health screening, class management, assessment and ethical practice.',icon='People',tool='notebook',tools=['notebook','board'],
nodes=['Screen','Plan','Teach','Review'],modules=['Teaching foundations','Lesson design','Safety & inclusion','Groups & settings','Teaching practice file'],
src=dict(page='diploma-in-yoga-education',code='DYE/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Foundations of yoga and Indian philosophy','Anatomy and physiology for yoga practice','Hatha yoga: asana, shatkarma and mudra','Patanjali and meditation','Yoga education and teaching methodology','Applied yoga and spiritual development']),
rows='''Define your teaching role and boundaries|A yoga teacher guides practice. They do not diagnose, prescribe treatment or replace a doctor, and they keep clear boundaries with students.|Write a fictional teacher statement of role and scope for a class handout, including what you offer, what you do not, and how you respond to a medical question.|role stated;scope limits;referral line|When a student asks if yoga will cure a heart problem, the teacher says yoga may complement care but they must follow their doctor's advice.
Screen students and obtain informed consent|Teachers learn about health conditions before class and explain the practice. Students choose what to do and may stop at any time.|Prepare a fictional health form and verbal consent script for a new student, including injuries, medicines, pregnancy and a reminder that students may rest at any time.|useful questions;consent;right to stop|The teacher says, Move only as far as feels comfortable. You are always free to rest in child's pose.
Plan a one-hour class|A class has a clear purpose, gradual build-up and a calm finish. Timing allows for explanation and rest.|Plan a fictional 60-minute class for adult beginners with centring, warm-up, main postures, breathing, relaxation and closing, with timing and the aim of each part.|timed plan;aim of each part;progression|The plan allocates ten minutes to final relaxation so students are not rushed out of the class.
Cue clearly and demonstrate well|Short, specific cues help students move safely. Demonstration and checking understanding reduce confusion.|Rewrite five vague fictional cues, such as straighten up, into clear instructions for a standing posture and a seated posture, and plan a demonstration with student-facing positions.|clear cues;demonstration;check understanding|Instead of relax your shoulders, the teacher says lift the shoulders toward the ears, then let them drop away from the ears.
Offer modifications and props|Props and options make practice accessible. Teachers offer choices rather than singling out students.|For a fictional class with a stiff older student, a student with sore wrists and a pregnant student, plan modifications and props for three postures, with language that keeps all students included.|modifications;props;inclusive language|The teacher offers a chair for seated postures to everyone, so the older student does not feel singled out.
Use touch and adjustments only with consent|Hands-on adjustments can help but may be unwelcome or unsafe. Verbal cues and demonstration come first, and touch needs clear permission.|Write a fictional consent routine for adjustments, including asking permission, explaining where and why, accepting no, and respecting cultural and personal boundaries.|permission asked;no accepted;alternatives|The teacher asks, May I adjust your hip position? and uses a verbal cue if the student declines.
Teach children and groups with different needs|Children, older adults and corporate groups need different pacing, language and goals. A teacher adapts without losing safety.|Plan fictional 30-minute sessions for children aged 8 and a corporate group at desks, with games, language, postures, safety and an adapted ending for each.|age-appropriate;setting-appropriate;safety|The corporate session uses seated spinal movements and breathing that can be done at a desk, and avoids floor work in office clothes.
Assess progress and give feedback|Feedback helps students improve and stay motivated. Progress includes comfort, awareness and consistency, not only flexibility.|Create a fictional progress sheet with indicators beyond flexibility such as stress, sleep, breath awareness and attendance. Write feedback for a student who compares themselves with others.|varied indicators;kind feedback;individual focus|The teacher praises steady attendance and a calmer breath rather than praising how far the student can fold forward.
Follow ethics and build a sustainable teaching practice|Ethical teachers are honest, respectful and aware of their limits. They keep records, insurance and clear fees.|Write a fictional code of conduct and business outline for a new teacher: honest advertising, boundaries, privacy, cancellation rules, insurance and record keeping. Include a response to a student who wants to date the teacher.|code of conduct;honest claims;boundary|The teacher advertises beginner-friendly classes and does not claim to cure illnesses, and declines a relationship with a student to protect the teaching relationship.
Deliver a four-week teaching programme|A programme shows planning, safety, inclusion and review across several classes with a theme building week by week.|Package a fictional four-week programme for beginners with weekly themes, class plans, modifications, consent routines, home practice, feedback forms and a reflection on what you would change.|progressive plan;safety and consent;reflection|After week two feedback shows students want more time on relaxation, so week three adds five minutes and shortens standing work.'''),

dict(id='yoga-science',summary='Study yoga with an evidence-aware mind: philosophy, physiology, advanced practice analysis, breath and meditation research, limits of therapeutic claims and ethical teaching.',icon='Spark',tool='notebook',tools=['notebook'],
nodes=['Read','Analyse','Evaluate','Teach'],modules=['Philosophy & texts','Physiology of practice','Breath, meditation & research','Application & limits','Evidence-informed practice'],
src=dict(page='advanced-diploma-in-yoga-science',code='ADYS/Q0001',duration='Six Months',eligibility='10+2 or equivalent',modules=['Foundations of yoga science','Human anatomy and physiology in yoga','Advanced asanas and therapeutic applications','Advanced pranayama and yogic breathing','Meditation, mindfulness and consciousness','Yoga therapy and holistic healing']),
rows='''Read a classical yoga text with context|Classical texts were written in particular times and languages. Responsible reading notes the context, translation and interpretation.|Choose a fictional short passage on yoga ethics and write a summary of its meaning, the context, two possible interpretations and one way it applies to a modern teacher. State your source.|context noted;two readings;application|One translation of an ethical principle emphasises non-harm in action, while another includes thought and speech, so the summary notes the difference.
Describe the muscles and joints used in a posture|A posture can be analysed by joint positions and the muscles working or lengthening. Individual anatomy varies, so one form does not fit all.|Analyse a fictional student in a standing forward bend and a chair-supported twist in terms of joints, muscles stretched and muscles working. Explain why one person's limit may be bone, not muscle.|joint actions;muscle work;individual difference|A person whose hip joint shape limits bending will not reach the floor however long they stretch, which is normal variation.
Explain the physiology of breathing|Breathing involves the diaphragm, rib muscles, airways and the nervous system. Slow breathing can influence relaxation, but claims should match the evidence.|Describe in plain language the mechanics of inhalation and exhalation and how slow breathing relates to the stress response, citing a fictional study summary and what it can and cannot show.|mechanics;stress link;evidence limits|A small study with ten participants and no control group suggests but does not prove a benefit, so the teacher presents it as promising.
Read a research study critically|A study's value depends on design, sample size, comparison group, measures and bias. Headlines often overstate findings.|Evaluate a fictional study claiming that eight weeks of yoga improves sleep. Identify the design, sample, control, outcome measure, possible bias and what you would conclude.|design identified;weaknesses;cautious conclusion|With no control group and only self-reported sleep, the improvement could reflect expectation or time, so the result is limited.
Distinguish traditional frameworks from biomedical claims|Concepts such as subtle energy channels belong to traditional frameworks. They are not the same kind of claim as measured physiology, and each should be taught in its own language.|Write a fictional teacher's note that explains a traditional energy concept as part of the tradition and separates it from measurable effects such as breathing rate. Show how to avoid saying that it cures disease.|clear separation;respectful;no cure claim|The teacher says, In the tradition, this practice is described as balancing the energy channels, and separately notes that research measures changes in breathing and heart rate.
Analyse an advanced posture and its risks|Advanced postures demand strength, flexibility and body awareness. Risk rises when practice goes beyond readiness.|Choose a fictional demanding posture such as a shoulder stand, list prerequisites, risks, progressions, props and who should avoid it. Decide how you would teach it in a mixed class.|prerequisites;risks;alternatives|A teacher offers a supported legs-up-the-wall position as an alternative for students with neck problems or high blood pressure.
Design a meditation practice with evidence in mind|Meditation methods differ in aim and effect. Responsible instruction explains possible benefits and the fact that some people find it distressing.|Create a fictional 6-week mindfulness course outline with session aims, home practice, safety guidance for distress and a plan to evaluate the course using a simple, ethical questionnaire.|structure;distress plan;evaluation|The teacher tells participants that discomfort can arise, that they can open their eyes at any time, and gives contact for support services.
Define the limits of yoga as a complementary approach|Yoga may support wellbeing alongside medical care. It does not replace treatment, and teachers must not discourage medical advice.|Write a fictional policy for responding to a student with diabetes or depression who asks to stop medicine because of yoga. Include your reply and the referral.|clear limit;reply;referral|The teacher says never to stop medicine without the doctor's advice, and encourages sharing the practice with the doctor.
Review a wellness claim before you repeat it|Claims about health often travel faster than evidence. A careful teacher checks the source, the size of the effect and whether the claim fits the audience before repeating it.|Take three fictional social-media claims about yoga, such as curing a condition in a week, and rate each for source, evidence and risk. Write a respectful reply you would give a student who repeats one.|source checked;risk rated;respectful reply|The claim that one breathing practice cures asthma is rated high risk because it could lead a student to stop medicine, so the reply thanks the student, explains the limit and suggests speaking to their doctor.
Create an evidence-informed yoga class|A good class connects traditions, safe practice and honest statements about benefits.|Package a fictional class plan for people with desk-related neck and back tension, with practices, rationale, safety notes, limits of claims, references to simple evidence and a feedback method.|rationale;honest claims;feedback|The plan states that practices may ease tension and improve comfort for some people, not that they heal disc injuries.'''),

dict(id='yoga-therapy',summary='Support wellbeing with yoga as a complementary approach: scope of practice, intake and red flags, adaptation, stress and sleep, common conditions with medical guidance, documentation and ethics.',icon='Shield',tool='notebook',tools=['notebook','board'],
nodes=['Intake','Adapt','Support','Refer'],modules=['Scope & intake','Practice adaptation','Common concerns','Mind & women\'s health','Complementary programme'],
src=dict(page='certificate-in-yoga-therapy',code='CYT/Q0001',duration='Three Months',eligibility='10th Grade or equivalent',modules=['Introduction to yoga therapy','Anatomy and physiology in yoga therapy','Yogic practices for therapy','Yoga therapy for physical ailments','Yoga therapy for mental health and emotional wellbeing','Yoga therapy for women\'s health']),
rows='''Explain yoga therapy and its limits|Yoga therapy applies yoga practices to support a person's wellbeing alongside medical care. It does not diagnose, cure or replace treatment.|Write a fictional client information sheet explaining what the service is, what it is not, the role of the client's doctor, privacy and how to complain. Avoid promises.|scope explained;no cure promise;doctor role|The sheet says the service supports relaxation and comfort and works alongside the client's medical care, not instead of it.
Take a safe intake and spot red flags|An intake asks about health, medicines and symptoms. Some symptoms need urgent medical attention rather than yoga.|Prepare a fictional intake form and a red-flag list covering chest pain, sudden severe headache, fainting, unexplained weight loss, severe breathlessness and thoughts of self-harm, with the action for each.|intake questions;red flags;action|A client who describes sudden chest pain is told to seek urgent medical care and the session does not proceed.
Work with the client's medical team|Complementary practitioners share information with the client's permission and follow medical advice about limits.|Draft a fictional consent and communication note to a client's doctor asking whether there are limits on movement or breathing practices, and plan what you do if the doctor advises against a practice.|written consent;specific question;respect advice|If the doctor advises against forward bends because of a recent surgery, those postures are removed from the plan.
Adapt practices for a person with back discomfort|Gentle movement and awareness can support comfort. Pain during practice means stop, and ongoing back pain needs medical assessment.|Plan a fictional 20-minute gentle routine for an office worker with mild back stiffness, with movements, props, pain rules and when to see a doctor. Do not claim to treat disc problems.|gentle movements;pain rule;medical review|If a movement increases pain or sends pain down the leg, the client stops and consults a doctor before continuing.
Support breathing and relaxation for stress|Slow breathing and relaxation can help people feel calmer. They are not a treatment for anxiety disorders, and some people feel uneasy during them.|Write a fictional stress-support session plan with grounding, slow breathing, relaxation and a closing check. Add a safe response if the client becomes distressed.|calming steps;distress response;referral|If a client feels panicky, the practitioner guides slow breathing with eyes open and suggests professional support if this happens often.
Support better sleep habits|Sleep depends on routine, environment, light, caffeine and stress. Relaxation practices can be part of a bedtime routine, and long-term insomnia needs medical review.|Create a fictional two-week sleep support plan with a bedtime routine, relaxation practice, tracking sheet and the signs that mean the client should see a doctor.|routine;tracking;medical signs|The plan sets a consistent bedtime, no screens in the last half hour and a ten-minute relaxation, and asks the client to see a doctor if sleeplessness continues.
Adapt practice for chronic conditions with medical clearance|People with conditions such as diabetes or high blood pressure may benefit from gentle activity, but changes in medicine or sugar levels must be managed by their doctor.|For a fictional client with high blood pressure and diabetes, list precautions, the clearance you need, signs to stop practice and what you will never advise about medicines or food.|clearance;precautions;never advise|The practitioner never advises changing medicines, and asks a client who feels dizzy or shaky to sit down, eat as advised by their doctor and seek help.
Support women's health with appropriate specialist guidance|Prenatal and postnatal practice, menstrual and menopause support need specialist training and attention to medical advice.|Plan how a fictional practitioner responds to a pregnant client: medical clearance, gentle breathing, positions to avoid as per specialist guidance, when to refer to a prenatal teacher and warning signs that mean urgent care.|clearance;specialist referral;warning signs|The practitioner who is not trained in prenatal yoga refers the client to a qualified prenatal teacher and shares general relaxation only.
Handle a difficult case ethically|Complementary practitioners meet cases that test their limits, such as a client who wants to stop treatment or a family member who asks for private details. Ethics means pausing, protecting the client and seeking advice.|Write a fictional case note for a client who says a doctor's advice was wrong and asks you to support stopping medicine. Record your response, who you consult, what you refuse to do and how you follow up.|limit stated;consultation;follow-up|The practitioner declines to comment on the medicine, encourages the client to talk to the prescribing doctor, records the conversation in the notes and offers a call back after the appointment.
Document sessions and run a complementary programme|Records show what was agreed and done. A programme has clear goals, sessions and review, with honest outcome measures.|Package a fictional six-week complementary programme for a client with stress and neck tension: consent, goals, session notes, measures such as comfort and sleep, communication with the doctor and final review.|consent and notes;honest measures;review|At review the client reports better sleep and less neck tension, and the practitioner records that these are the client's reported experiences, not proof of cure.'''),

dict(id='meditation',summary='Learn and teach meditation responsibly: attention and mindfulness practices, breath, concentration, compassion, emotional wellbeing, group guidance, safety and ethics.',icon='Spark',tool='notebook',tools=['notebook'],
nodes=['Settle','Practise','Guide','Care'],modules=['Foundations of meditation','Mindfulness & breath','Concentration & compassion','Emotional wellbeing & safety','Teaching practice'],
src=dict(page='diploma-in-meditation',code='DIM/Q0001',duration='Six Months',eligibility='10th Grade or equivalent',modules=['Introduction to meditation','Mindfulness and awareness techniques','Breathwork and pranayama in meditation','Concentration and visualisation techniques','Chakra and energy meditation','Meditation for emotional and mental wellbeing']),
rows='''Explain what meditation is and is not|Meditation is training attention and awareness. It is not a quick fix, does not require special belief and is not a replacement for medical care.|Write a short fictional explanation for a beginner that corrects three myths, such as stopping thoughts and instant calm, and states one honest limit.|myths corrected;honest limit;plain language|Meditation is not about having no thoughts but about noticing them and returning attention gently.
Set up a sustainable practice|Short regular practice builds the habit. Posture, place and time should suit the person.|Plan a fictional 4-week practice for a busy student with time, place, posture options, a reminder cue and a simple log. Include what to do when a day is missed.|short and regular;posture options;missed-day plan|The student sits for five minutes after brushing teeth and, if a day is missed, simply begins again the next morning without self-criticism.
Practise breath awareness|Following the natural breath is a simple, common way to train attention. It should not be forced.|Write a fictional step-by-step guided breath awareness practice for eight minutes, with posture, focus, how to handle distraction and a closing. Note that breathing should not be strained.|clear steps;distraction guidance;no strain|When attention wanders, the practitioner notes thinking and gently returns to the feeling of breath at the nostrils or abdomen.
Guide a body scan|A body scan moves attention slowly through the body. It helps notice tension but may be uncomfortable for some people, so choice and pace matter.|Write a fictional 10-minute body scan script with positioning, pace, language and an invitation to skip any area that feels uncomfortable.|slow pace;choice language;comfort|The guide says, If an area feels uncomfortable, you can skip it or focus on a neutral place like the hands.
Train concentration with an object|Focusing on an object, sound or phrase builds steady attention. Strain, tension and judgment reduce the benefit.|Design a fictional concentration practice using a candle, a sound or a phrase, with duration, safety such as eye comfort, and a troubleshooting list for sleepiness and restlessness.|object chosen;safety;troubleshooting|If a candle gaze causes eye strain, the practitioner closes the eyes and recalls the image or switches to a sound.
Practise kindness and compassion|Compassion practices direct kind wishes to oneself and others. They should be offered gently, as some people find self-kindness hard.|Write a fictional kindness practice script with phrases, an order of recipients and an alternative for a person who cannot feel warmth toward themselves.|phrases;gentle order;alternative|The script begins with a person the practitioner finds easy to care for, rather than themselves, and adds themselves later.
Recognise when meditation is not the right tool|Some people experience distress, panic or intrusive memories during meditation. A facilitator offers choices and refers when needed.|Prepare a fictional safety note for a meditation class covering warning signs, what the facilitator says, how to ground a participant and when to suggest professional support.|warning signs;grounding;referral|The facilitator invites a distressed participant to open their eyes, feel their feet on the floor and name five things they can see.
Lead a short group session|A group session needs a clear structure, calm voice, welcome and safety. The facilitator models steadiness and does not push beliefs.|Plan a fictional 30-minute community session with opening, instruction, practice, discussion and closing, including a rule about not pressuring anyone and a note on participants' privacy.|structure;no pressure;privacy|The facilitator asks participants not to share each other's stories outside the group, which protects trust.
Adapt meditation for different cultures and beliefs|Participants bring different beliefs and comfort levels. A responsible facilitator offers secular language, respects traditions and avoids pushing a worldview.|Rewrite a fictional 10-minute practice script in three versions for a secular workplace, a faith-based community group and a school class, keeping safety guidance the same and changing only the language.|three versions;respectful wording;safety kept|The workplace version uses the phrase attention to the breath, the community version invites participants to use a personal prayer word if they wish, and all three keep the choice to stop at any time.
Design a short programme for a workplace|A workplace programme must fit time, culture and voluntary participation. Claims must stay modest.|Package a fictional four-week workplace programme with weekly themes, 20-minute sessions, optional participation, a feedback form and honest claims about outcomes.|voluntary;modest claims;feedback|Participation is voluntary, and the programme announcement says it may help people manage stress, not that it will remove stress.'''),

dict(id='massage-spa',summary='Plan safe, respectful relaxation massage and spa services: client intake, contraindications, consent and draping, hygiene, technique planning, body mechanics and spa operations.',icon='Shield',tool='notebook',tools=['notebook','board','budget'],
nodes=['Consult','Prepare','Treat','Care'],modules=['Professional foundations','Consultation & safety','Technique planning','Spa operations','Spa treatment protocol'],
src=dict(page='certificate-in-relaxation-massage-techniques',code='CRMT/Q0001',duration='Two Months',eligibility='No formal qualification required',modules=['Introduction to massage therapy','Anatomy and physiology','Techniques and methods','Body mechanics and posture','Specialised massage techniques','Health and safety protocols']),
rows='''Set professional boundaries and ethics|Massage involves trust and touch. Clear boundaries, consent and respect for privacy protect clients and therapists.|Write a fictional code of conduct for a spa therapist covering consent, draping, appropriate conversation, no sexual behaviour, confidentiality and how to end a session if a client acts inappropriately.|boundaries;consent;ending a session|If a client makes an inappropriate comment, the therapist states the boundary calmly and ends the session if it continues.
Complete a client consultation|A consultation records health, preferences and any reasons not to massage. It is the first safety check.|Prepare a fictional consultation form covering health conditions, medicines, allergies, recent injuries, pregnancy, areas to avoid and consent, and role-play a short interview.|health questions;preferences;consent|The form asks about skin conditions and allergies to oils, since a reaction would end the session and may need medical attention.
Know when not to massage|Some conditions make massage unsafe, such as fever, infection, certain skin conditions, clots or recent surgery. When unsure, ask for medical advice.|Make a fictional contraindication chart with condition, reason and action for ten situations. Decide what you do when a client has swollen painful calf and what you tell them.|conditions listed;actions;referral|A client with a swollen, painful calf is not massaged and is advised to seek urgent medical care, since a blood clot is possible.
Prepare the room and maintain hygiene|A clean, quiet, warm room with fresh linen and washed hands supports safe, comfortable treatment.|Create a fictional room preparation and cleaning checklist covering linen, surface cleaning, hand hygiene, oils, temperature, music and waste. Add a schedule for deep cleaning.|checklist;hygiene;schedule|After each client, linen is replaced and surfaces are wiped with a suitable cleaner before the next booking.
Drape and position a client with dignity|Draping covers the client except the area being worked on. Comfortable positioning and respect for dignity are essential.|Describe in steps how a fictional therapist explains draping, leaves the room while the client undresses, drapes the client and uncovers only one area at a time. Include pillows for comfort.|clear explanation;privacy;comfort|The therapist says, Please undress to your comfort level and lie under the sheet. I will knock before returning.
Plan a relaxation sequence using basic strokes|Gentle, flowing strokes with steady pressure can relax muscles. Pressure and speed depend on the client's comfort and the area treated.|Plan a fictional 30-minute back and shoulder relaxation sequence with strokes in order, pressure levels, communication check-ins and areas to avoid, such as the spine itself.|ordered strokes;pressure checks;areas avoided|The therapist asks, Is the pressure comfortable? at the start and again halfway, and adjusts without discussion or argument.
Protect the therapist with good body mechanics|Poor posture and repeated strain injure therapists. Table height, stance and use of body weight reduce risk.|Plan a fictional therapist's setup with table height, stance, use of body weight, rest between clients and daily stretches, and explain why the therapist should not massage with sore thumbs.|table height;stance;rest|The table is set so the therapist's arms are straight and body weight, not thumb strength, delivers pressure.
Respond to a complaint or incident professionally|Even careful therapists meet complaints or incidents. A calm response protects the client, records facts and learns from the event.|Write a fictional incident procedure for a client who feels dizzy after a session or complains about pressure. Include immediate care, record keeping, an apology that does not admit fault falsely, and a review step.|immediate care;facts recorded;review step|The therapist helps the client sit, offers water, checks how they feel before they leave, records the time and details in the log, and reviews pressure choices with the manager the next day.
Price spa services and manage appointments|Services need clear descriptions, prices, times and policies. Cancellation and scheduling rules prevent conflict.|Create a fictional spa menu with five services, durations, prices and rules for booking, late arrival, cancellation and a consent reminder. Calculate revenue for a therapist with 5 sessions a day.|clear menu;policies;revenue calculation|Five 60-minute sessions at 1,200 produce 6,000 a day, and a 15-minute buffer between clients is built into the schedule.
Design a spa treatment protocol|A protocol records every step from welcome to aftercare so each client receives consistent, safe service.|Package a fictional 60-minute relaxation treatment protocol: consultation, preparation, procedure, timing, hygiene, aftercare advice, record keeping and complaint handling.|complete steps;aftercare;records|The protocol ends with water, a quiet minute and advice to avoid heavy exercise for the rest of the day, and a record of any reaction.'''),
]
