import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright'),root=path.resolve('dist'),out=path.resolve('docs/screenshots');fs.mkdirSync(out,{recursive:true});
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.woff2':'font/woff2','.webp':'image/webp','.png':'image/png'};
const server=http.createServer((r,res)=>{try{let file=path.join(root,decodeURIComponent(new URL(r.url,'http://x').pathname));if(new URL(r.url,'http://x').pathname.startsWith('/verify/'))file=path.join(root,'verify.html');if(file.endsWith('/'))file+='index.html';res.writeHead(200,{'content-type':types[path.extname(file)]||'application/octet-stream'});res.end(fs.readFileSync(file))}catch{res.writeHead(404);res.end('Not found')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/';
const browser=await chromium.launch({...(process.env.ACADEMY_CHROMIUM?{executablePath:process.env.ACADEMY_CHROMIUM}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader'],headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));let count=0;
await context.route('**/api/auth/session',r=>r.fulfill({json:{signedIn:true,registered:true,user:{id:'controlled-preview-learner',email:'fixture@example.test'},profile:{status:'Active',consent_at:'fixture-consent'}}}));
await context.route('**/runtime.js',r=>r.fulfill({contentType:'text/javascript',body:"window.ACADEMY_MODE='preview';"}));
const go=async route=>{await p.goto(url+'index.html#'+route);await p.waitForFunction(requested=>{const actual=location.hash.slice(1)||'home',expected=requested==='studio/print'?'shop':requested,lesson=/^lesson\/[^/]+\/[^/]+\/\d+$/.test(requested)&&actual.split('/').slice(0,3).join('/')===requested.split('/').slice(0,3).join('/');return document.getElementById('main').dataset.route===actual&&(actual===expected||lesson)},route);await p.waitForSelector('#main h1, #main h2')};
const check=async(condition,message)=>{assert(condition,message);count++};
await go('home');await p.screenshot({path:out+'/desktop.png',fullPage:true});
await go('paths');await check(await p.locator('.course-card').count()===129,'every course is listed');await p.locator('#path-search').fill('Websites');await check(await p.locator('.course-card').count()===1,'path search');
await go('programmes');await p.waitForSelector('#programme-list .journey-item');await check(await p.locator('#programme-list .journey-item').count()===48,'48 original programmes');
await go('lesson/start/start-01/0');await p.getByRole('button',{name:'Save step & continue'}).click();await check(p.url().endsWith('/0'),'empty step is gated');
const notes=[
'I will build a controlled folder structure for the fictional café supplier records. The office lead will approve the final list before a colleague uses it.',
'The source says an approved file may be older than a draft. I will confirm approval with the Office lead and preserve the draft separately until that review.',
'I created incoming, working and approved folders. The approved file is supplier-list-v1.csv, owned by the Office lead. A draft is stored in working with its review status.',
'Expected: the approved list is shared read-only with the named colleague. Actual: the draft remains separate. A missing approval blocks release. I retested with an approval recorded.',
'I used separate folders because review status must be obvious. A single shared folder would make drafts easy to confuse with approved work. This plan needs a real access-control check in a deployed file service.',
'The handover includes the folder plan, the approved supplier-list-v1.csv filename, the Office lead approval owner, and the missing-approval failure test. All data is fictional.'
];
for(let i=0;i<6;i++){await p.locator('#recipe-answer[data-recipe="'+['objective','inspection','work','test','reflection','handover'][i]+'"]').waitFor();await p.locator('#recipe-answer').fill(notes[i]);if(i===3)for(const c of await p.locator('[data-criterion]').all())await c.check();if(i<5){await p.getByRole('button',{name:'Save step & continue'}).click();await p.waitForURL('**/'+(i+1),{timeout:3000})}else{await p.locator('#evidence-consent').check();await p.getByRole('button',{name:'Check evidence structure'}).click();await check(await p.locator('.check-fail').count()===0,'complete evidence passes');const download=p.waitForEvent('download');await p.getByRole('button',{name:'Export this evidence'}).click();const file=await download;const data=JSON.parse(fs.readFileSync(await file.path(),'utf8'));await check(data.checks.pass&&data.assessmentStatus==='Local practice only','download remains practice evidence');await p.getByRole('button',{name:'Complete practice recipe'}).click()}}
await p.waitForURL('**#completed/start/start-01');await go('portfolio');await check(await p.locator('#main').innerText().then(t=>t.includes('Create your first controlled workspace')),'portfolio records actual practice');
await p.reload();await p.waitForSelector('#main h1, #main h2');await check(await p.locator('.journey-item').count()===1,'practice persists across reload');
await go('lesson/start/start-01/2');await p.screenshot({path:out+'/lesson-desktop.png',fullPage:true});
await go('studio/web');await p.getByRole('button',{name:'Run preview'}).click();await check(await p.frameLocator('iframe').locator('h1').textContent()==='A little café. A warm welcome.','web preview executes');await check(await p.locator('iframe').getAttribute('sandbox')==='allow-scripts','sandbox has no same-origin permission');
await go('studio/data');await p.getByRole('button',{name:'Calculate summary'}).click();await check((await p.locator('#tool-output').innerText()).includes('180.00'),'CSV calculates net total');await p.locator('#tool-data').fill('item,amount\ninvalid,');await p.getByRole('button',{name:'Calculate summary'}).click();await check((await p.locator('#tool-output').innerText()).includes('missing or invalid'),'CSV rejects missing values');await p.getByRole('button',{name:'Run SELECT query'}).click();await check(await p.locator('#tool-output tbody tr').count()===3,'SQL returns sample rows');
await go('studio/prompt');await p.getByRole('button',{name:'Build my prompt'}).click();await check((await p.locator('#tool-output').innerText()).includes('TASK'),'prompt builder');
await go('studio/flow');await p.getByRole('button',{name:'Run simulation'}).click();await check((await p.locator('#tool-output').innerText()).includes('Policy checks passed'),'workflow positive checks');
await go('studio/api');await p.locator('#api-actor').selectOption('bob');await p.getByRole('button',{name:'Send simulated request'}).click();await check((await p.locator('#tool-output').innerText()).includes('403'),'API denies other caller');
await go('studio');await check(await p.locator('.workspace-tabs a').count()===11,'eleven tools without manufacturing studio');await go('studio/print');await check(p.url().endsWith('#shop'),'old manufacturing tool link redirects to access');
await go('shop');await check((await p.locator('#main').innerText()).includes('Paid enrolment is not open yet'),'no fake checkout');
await go('certificates');await p.screenshot({path:out+'/certificate-desktop.png',fullPage:true});await check(await p.locator('.certificate-sample').count()===1,'sample certificate unmistakable');
await go('calendar');await p.locator('[name=title]').fill('My next practical project');await p.locator('[name=date]').fill('2027-01-05T17:00');await p.getByRole('button',{name:'Add learning session'}).click();await p.getByText('My next practical project',{exact:true}).waitFor();await check((await p.locator('#main').innerText()).includes('My next practical project'),'planner persists');
await go('glossary');await p.locator('#glossary-search').fill('Webhook');await check(await p.locator('#glossary-list dt').count()===1,'glossary filter');
await p.keyboard.press('Control+k');await p.locator('#global-search').fill('controlled workspace');await check((await p.locator('#search-results').innerText()).includes('Create your first controlled workspace'),'global project search');await p.keyboard.press('Escape');
await go('staff');await check((await p.locator('#main').innerText()).includes('Staff access is required'),'staff preview denied');
await p.goto(url+'workspace.html?programme=DB-02');await p.waitForSelector('.stagebody');await check((await p.locator('#main h1').innerText()).includes('Web'),'legacy programme deep link');await p.screenshot({path:out+'/original-workspace-desktop.png',fullPage:true});
await go('paths');await check(!(await p.locator('#main').innerText()).includes('3D design'),'manufacturing pathway removed');
await p.evaluate(()=>sessionStorage.setItem('dba-author-preview','1'));await go('path/web');await p.getByRole('link',{name:'Open next project',exact:true}).click();await p.waitForURL('**#lesson/web/web-01/0');await check(p.url().endsWith('/0'),'choosing a pathway starts at its first lesson');
await go('lesson/web/web-01/5');await check(p.url().endsWith('/0'),'future lesson stages cannot be skipped');await check(await p.locator('.recipe-disabled').count()===5,'future stages clearly unavailable');
await go('receipt/demo');await p.locator('.receipt-paper').waitFor();await check((await p.locator('.receipt-label').innerText()).includes('SAMPLE'),'receipt demo unmistakably marked');await check(await p.locator('.receipt-printer').evaluate(el=>el.classList.contains('is-printing')),'receipt feed animation starts');await p.waitForTimeout(2700);await p.screenshot({path:out+'/receipt-desktop.png',fullPage:true});
await check(await p.locator('[data-receipt-action=print]').count()===0,'sample cannot be exported as a paid receipt');
// Responsive route sweep; exercise actual layouts and record the screenshot matrix together.
await p.setViewportSize({width:390,height:844});
for(const route of ['home','paths','path/web','lesson/start/start-01/2','receipt/demo','studio/data','certificates','calendar','glossary','shop','portfolio','onboarding']){await go(route);if(route==='receipt/demo')await p.waitForTimeout(2700);await check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow: '+route);if(['home','lesson/start/start-01/2','receipt/demo','certificates'].includes(route))await p.screenshot({path:out+'/'+({home:'mobile','lesson/start/start-01/2':'lesson-mobile','receipt/demo':'receipt-mobile',certificates:'certificate-mobile'}[route])+'.png',fullPage:true})}
await go('home');await p.locator('#mobile-menu').click();await check(await p.locator('#sidebar').evaluate(el=>getComputedStyle(el).display)!=='none','mobile navigation opens');await p.getByLabel('Main navigation').getByRole('link',{name:'Browse courses',exact:true}).click();await p.locator('#sidebar').waitFor({state:'hidden'});await check(await p.locator('#sidebar').evaluate(el=>getComputedStyle(el).display)==='none','mobile navigation closes on navigation');
const publicPage=await context.newPage();publicPage.on('pageerror',e=>errors.push(e.message));let bootstrapCalls=0;
await publicPage.route('**/runtime.js',route=>route.fulfill({contentType:'text/javascript',body:"window.ACADEMY_MODE='connected';"}));
await publicPage.route('**/api/academy/catalogue',route=>route.fulfill({json:JSON.parse(fs.readFileSync(path.join(root,'catalogue.json'),'utf8'))}));
await publicPage.route('**/api/academy/bootstrap',route=>{bootstrapCalls++;return route.fulfill({status:401,json:{error:'Sign in required'}})});
await publicPage.route('**/api/academy/verify/ffffffffffffffffffffffffffffffffffffffffffffffff',route=>route.fulfill({json:{status:'Active',name:'Example learner',course:'Digital confidence',id:'TEST-PUBLIC-RECORD',issuedAt:'2026-09-01',scope:'Test fixture only',evidenceHash:'example-test-digest'}}));
await publicPage.goto(url+'verify/ffffffffffffffffffffffffffffffffffffffffffffffff');await publicPage.getByRole('heading',{name:'Verify an Academy certificate'}).waitFor();await check((await publicPage.locator('#main').innerText()).includes('Example learner'),'public verification renders without an account');await check(bootstrapCalls===0,'public verification does not require authenticated bootstrap');await publicPage.close();
const localPage=await context.newPage();localPage.on('pageerror',e=>errors.push(e.message));await localPage.goto('file://'+path.join(root,'index.html')+'#home');await localPage.locator('#access-gate [data-access-actions]').waitFor({state:'visible'});await check(await localPage.locator('.academy-shell').isHidden(),'unpacked files cannot bypass registration');await localPage.close();
await check(errors.length===0,'No JavaScript exceptions: '+JSON.stringify(errors));
fs.writeFileSync('docs/browser-validation.json',JSON.stringify({checkedAt:new Date().toISOString(),checks:count,errors,viewports:[1440,390],scope:'Registered teaching UI with controlled identity and local practice fixtures; anonymous and native registration gates tested separately against the actual compiled Worker. Live payment providers are not connected.'},null,2));console.log('Browser checks passed: '+count);await browser.close();server.close();
