import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve('dist'),out=path.resolve('docs/screenshots');let ready=false,signedIn=false,purpose='normal',profile=null,signup=[],login=[],recovery=[],password=[],savedProfile=[],confirmation=[];
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.woff2':'font/woff2','.webp':'image/webp','.png':'image/png'};
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://x'),p=u.pathname;const json=(value,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(value))};if(p.startsWith('/api/')){let raw='';for await(const chunk of req)raw+=chunk;const body=raw?JSON.parse(raw):{};
 if(p==='/api/auth/config')return json({configured:ready,emailPassword:ready,chatgpt:false,secureSessions:ready});
 if(p==='/api/auth/session')return json(signedIn?{signedIn:true,registered:!!profile,user:{id:'ui-test-learner',email:'learner@example.test',purpose},profile}:{signedIn:false});
 if(p==='/api/auth/signup'){signup.push(body);return json({message:'Check your inbox to confirm your email, then return here to sign in.'},202)}
 if(p==='/api/auth/login'){login.push(body);if(body.password==='incorrect-password')return json({error:'Check your details and confirm your email.'},401);signedIn=true;return json({next:'/onboarding'})}
 if(p==='/api/auth/recover'){recovery.push(body);return json({message:'If this address can receive a recovery email, check its inbox.'},202)}
 if(p==='/api/auth/confirm'){confirmation.push(body);signedIn=true;await new Promise(r=>setTimeout(r,400));return json({next:'/onboarding'})}
 if(p==='/api/auth/password'){password.push(body);return json({message:'Password updated. Sign in again with your new password.'})}
 if(p==='/api/auth/logout'){signedIn=false;return json({signedOut:true})}
 if(p==='/api/account/profile'){if(req.method==='PUT'){savedProfile.push(body);profile={...body,status:'Active',consent_at:new Date().toISOString()}}return json({profile})}
 return json({error:'Not part of this UI fixture'},404);
 }try{const rel=['/','/learn','/dashboard'].includes(p)?'/index.html':['/sign-in','/register','/forgot-password','/reset-password','/auth/confirm','/onboarding','/account'].includes(p)?'/auth.html':p;const file=path.join(root,decodeURIComponent(rel));res.writeHead(200,{'content-type':types[path.extname(file)]||'application/octet-stream'});res.end(fs.readFileSync(file))}catch{res.writeHead(404);res.end('Not found')}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:process.env.ACADEMY_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader'],headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));let checks=0;const check=(ok,text)=>{assert(ok,text);checks++};const go=async route=>{await p.goto(url+route);await p.locator('#main h1').waitFor()};
try{
 await p.route('**/runtime.js',r=>r.fulfill({contentType:'text/javascript',body:"window.ACADEMY_MODE='preview';"}));
 await p.route('**/api/auth/session',r=>r.fulfill({json:{signedIn:true,registered:true,user:{id:'controlled-preview-learner',email:'fixture@example.test'},profile:{status:'Active',consent_at:'fixture-consent'}}}));
 await go('/index.html#home');const nav=await p.locator('#navigation .nav-link').allTextContents();check(nav.includes('Practice workspace'),'professional practice is in main Academy navigation');check(nav.includes('Academy guide'),'guide is in main navigation');check(await p.locator('#account-actions a').count()===2,'register and sign-in visible');
 await p.locator('#navigation').getByRole('link',{name:'Practice workspace',exact:true}).click();await p.getByRole('link',{name:'Professional Practice Workspace',exact:false}).first().click();await p.getByRole('heading',{name:'Professional Practice Workspace',exact:true}).waitFor();check(JSON.stringify(await p.locator('#navigation .nav-link').allTextContents())===JSON.stringify(nav),'same navigation in original workspace');check(await p.locator('#navigation [aria-current=page]').innerText()==='Practice workspace','workspace navigation active');
 await p.locator('#practice-navigation summary').click();await p.locator('#nav [data-view=tools]').click();check(await p.locator('#practice-section-label').innerText()==='Tool library','workspace section selection');check(!(await p.locator('#practice-navigation').getAttribute('open')),'workspace section menu collapses after selection');
 await p.reload();await p.locator('#main h1').waitFor();check(await p.locator('#practice-section-label').innerText()==='Tool library','workspace section survives refresh');
 await go('/workspace.html?view=evidence');check((await p.locator('#main').innerText()).includes('Evidence'),'professional evidence deep link');
 await go('/workspace.html?programme=DB-02');check(await p.locator('.rail .stage').count()===12,'all twelve original stages intact');await p.locator('[data-stage=LEARN]').click();await p.reload();await p.locator('.stagebody').waitFor();check((await p.locator('#context-label').innerText()).endsWith('LEARN'),'professional stage survives refresh');await p.locator('[data-stage=BRIEF]').click();await p.screenshot({path:out+'/professional-desktop.png',fullPage:true});
 await go('/index.html#guide');check(await p.locator('.guide-toc a').count()===15,'fifteen guide chapters');const chapters=await p.locator('.guide-toc a').evaluateAll(els=>els.map(e=>e.getAttribute('href')));for(const href of chapters){await p.goto(url+'/index.html'+href);await p.locator('.guide-article h2').waitFor();check((await p.locator('.guide-article').innerText()).length>850,'substantive guide chapter '+href)}
 await go('/index.html#guide/professional');check(await p.locator('.guide-article tbody tr').count()===12,'guide explains twelve mission stages');await p.screenshot({path:out+'/guide-desktop.png',fullPage:true});
 await p.unroute('**/api/auth/session');
 await go('/register');await p.getByRole('heading',{name:'Account access is temporarily unavailable.'}).waitFor();check(await p.locator('#sidebar,#navigation').count()===0,'unconfigured registration has no Academy navigation');check(await p.locator('[href*=preview]').count()===0,'no preview escape from registration');await p.screenshot({path:out+'/register-desktop.png',fullPage:true});
 await go('/sign-in');await p.getByRole('heading',{name:'Account access is temporarily unavailable.'}).waitFor();await p.screenshot({path:out+'/signin-desktop.png',fullPage:true});
 ready=true;await go('/register');await p.waitForFunction(()=>!document.querySelector('.auth-submit').disabled);await p.locator('[name=email]').fill('learner@example.test');await p.locator('[name=password]').fill('example-passphrase-123');await p.locator('[name=confirmPassword]').fill('different-passphrase');await p.locator('[name=consent]').check();await p.locator('.auth-submit').click();check(signup.length===0,'password mismatch blocks signup');check(await p.locator('[name=confirmPassword]').evaluate(el=>!!el.validationMessage),'mismatch has accessible validation message');await p.locator('[name=confirmPassword]').fill('example-passphrase-123');await p.locator('[data-password=account-password]').click();check(await p.locator('[name=password]').getAttribute('type')==='text','password visibility control');await p.locator('.auth-submit').click();await p.getByRole('status').filter({hasText:'Check your inbox'}).waitFor();check(signup.length===1&&signup[0].consent===true&&signup[0].email==='learner@example.test','signup sends expected account data');check(!('confirmPassword' in signup[0]),'confirmation field stays client-side');check(await p.locator('[name=password]').inputValue()==='','password cleared after signup response');
 await go('/sign-in');await p.waitForFunction(()=>!document.querySelector('.auth-submit').disabled);await p.locator('[name=email]').fill('learner@example.test');await p.locator('[name=password]').fill('incorrect-password');await p.locator('.auth-submit').click();await p.locator('#account-message[role=alert]').waitFor();check(login.length===1&&!signedIn,'sign-in rejection does not create session');check(await p.locator('.auth-submit').isEnabled(),'failed sign-in can be retried');
 await p.locator('[name=password]').fill('example-passphrase-123');await p.locator('.auth-submit').click();await p.waitForURL('**/onboarding');await p.locator('[name=name]').waitFor();check(await p.locator('#sidebar,#navigation').count()===0,'profile completion retains account-only chrome');await p.locator('[name=name]').fill('Example Learner');await p.locator('[name=country]').fill('United Arab Emirates');await p.locator('[name=goal]').selectOption('DB-00');await p.locator('[name=hours]').fill('3');await p.locator('[name=consent]').check();await p.locator('.auth-submit').click();await p.waitForURL('**/dashboard');await p.locator('.enrolled-courses .course-card').first().waitFor();check(savedProfile.length===1&&savedProfile[0].goal==='DB-00'&&savedProfile[0].hours===3,'onboarding saves profile and continues');
 signedIn=false;await go('/forgot-password');await p.waitForFunction(()=>!document.querySelector('.auth-submit').disabled);await p.locator('[name=email]').fill('learner@example.test');await p.locator('.auth-submit').click();await p.getByRole('status').filter({hasText:'If this address'}).waitFor();check(recovery.length===1,'recovery uses provider-backed endpoint');
 signedIn=true;purpose='recovery';await go('/reset-password');check(await p.locator('[name=currentPassword]').count()===0,'recovery session accepts new password without old password');await p.locator('[name=password]').fill('another-passphrase-456');await p.locator('[name=confirmPassword]').fill('another-passphrase-456');await p.locator('.auth-submit').click();await p.getByRole('status').filter({hasText:'Password updated'}).waitFor();check(password.length===1,'password update submitted once');check(await p.locator('.auth-submit').isDisabled(),'recovery ends at sign-in after change');
 signedIn=false;purpose='normal';await p.goto(url+'/auth/confirm?token_hash=fixture-token&type=signup');await p.waitForFunction(()=>!location.search);await p.waitForURL('**/onboarding');check(confirmation.length===1&&confirmation[0].type==='signup','email confirmation completes through endpoint');check(await p.locator('#navigation').count()===0,'nested auth route has no Academy navigation');
 // Real connected boot uses the same profile to start professional practice.
 const accountPage=await context.newPage();await accountPage.route('**/runtime.js',r=>r.fulfill({contentType:'text/javascript',body:"window.ACADEMY_MODE='connected';"}));await accountPage.goto(url+'/workspace.html');await accountPage.locator('#main h1').waitFor();await accountPage.getByRole('button',{name:'Continue mission',exact:true}).click();check((await accountPage.locator('#context-label').innerText()).startsWith('DB-00'),'account programme seeds professional practice');await accountPage.close();
 const publicPage=await context.newPage();await publicPage.route('**/api/auth/session',r=>r.fulfill({json:{signedIn:false,registered:false}}));await publicPage.goto(url+'/index.html#guide');await publicPage.waitForURL('**/sign-in');await publicPage.locator('#account-content h1').waitFor();check(await publicPage.locator('#sidebar,#navigation,.guide-article').count()===0,'signed-out guide route closes instead of exposing navigation');await publicPage.close();
 await p.route('**/runtime.js',r=>r.fulfill({contentType:'text/javascript',body:"window.ACADEMY_MODE='preview';"}));
 await p.route('**/api/auth/session',r=>r.fulfill({json:{signedIn:true,registered:true,user:{id:'controlled-preview-learner',email:'fixture@example.test'},profile:{status:'Active',consent_at:'fixture-consent'}}}));
 ready=false;signedIn=false;await p.setViewportSize({width:390,height:844});for(const route of ['/register','/sign-in','/forgot-password','/index.html#guide','/index.html#guide/professional','/workspace.html','/workspace.html?programme=DB-02','/workspace.html?view=tools','/workspace.html?view=evidence']){await go(route);await p.waitForTimeout(50);check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow '+route);if(['/register','/sign-in','/index.html#guide','/workspace.html?programme=DB-02'].includes(route))await p.screenshot({path:out+'/'+({'/register':'register-mobile','/sign-in':'signin-mobile','/index.html#guide':'guide-mobile','/workspace.html?programme=DB-02':'professional-mobile'}[route])+'.png',fullPage:true})}
 await p.locator('#mobile-menu').click();await p.locator('#navigation').getByRole('link',{name:'Academy guide',exact:true}).click();await p.locator('.guide-article').waitFor();check(await p.locator('#nav-scrim').count()===0,'mobile navigation closes and clears overlay');
 check(errors.length===0,'no page errors '+JSON.stringify(errors));fs.writeFileSync('docs/integration-ui-validation.json',JSON.stringify({checkedAt:new Date().toISOString(),checks,errors,viewports:[1440,390],scope:'Shared Academy navigation, original workspace, 15 guide chapters, registration/login/recovery/onboarding/confirmation UI with controlled account API fixtures. Email-provider responses are controlled fixtures; anonymous guide access is denied.'},null,2));console.log('Academy integration UI checks passed: '+checks);
}catch(error){console.error('Integration failure context:',JSON.stringify({url:p.url(),signupCalls:signup.length,loginCalls:login.length,recoveryCalls:recovery.length,passwordCalls:password.length,accountMessage:await p.locator('#account-message').textContent().catch(()=>null),accountHeading:await p.locator('#account-content h1').textContent().catch(()=>null)}));throw error}finally{await browser.close();await new Promise(r=>server.close(r))}
