import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright'),root=path.resolve('dist');
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.woff2':'font/woff2','.webp':'image/webp','.png':'image/png'};
const server=http.createServer((req,res)=>{try{let file=path.join(root,new URL(req.url,'http://localhost').pathname);if(file.endsWith('/'))file+='index.html';res.writeHead(200,{'content-type':types[path.extname(file)]||'application/octet-stream'});res.end(fs.readFileSync(file))}catch{res.writeHead(404);res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({...(process.env.ACADEMY_CHROMIUM?{executablePath:process.env.ACADEMY_CHROMIUM}:{}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader']}),context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));let checks=0;const check=(v,label)=>{assert(v,label);checks++};
const id='order-'+'a'.repeat(40),catalogue=JSON.parse(fs.readFileSync('dist/catalogue.json','utf8'));let order={id,product_id:'web-pathway',title:'Websites & product building',status:'Awaiting payment',amount:25000,currency:'aed',created:'2026-09-30T10:00:00Z',receipt:null,activeCourseIds:[],courseIds:['web']};
try{
await p.route('**/api/auth/session',r=>r.fulfill({json:{signedIn:true,registered:true,user:{id:'test-learner',email:'fixture@example.test'},profile:{status:'Active',consent_at:'fixture-consent'}}}));
await p.route('**/runtime.js',r=>r.fulfill({contentType:'text/javascript',body:"window.ACADEMY_MODE='connected';"}));
await p.route('**/api/academy/bootstrap',r=>r.fulfill({json:{user:{id:'test-learner',name:'Example Learner',role:'Learner'},catalogue,products:[],work:[],awards:[],entitlements:order.activeCourseIds.map(course_id=>({course_id}))}}));
await p.route('**/api/academy/course/start',r=>r.fulfill({json:JSON.parse(fs.readFileSync('content/atlas.json')).tracks[0]}));await p.route('**/api/academy/course/safety',r=>r.fulfill({json:JSON.parse(fs.readFileSync('content/atlas.json')).tracks.find(t=>t.id==='safety')}));
await p.route('**/api/orders/'+id,r=>r.fulfill({json:order}));
const url='http://127.0.0.1:'+server.address().port+'/?checkout=returned#receipt/'+id;
await p.goto(url);await p.getByRole('heading',{name:'Confirming your payment.'}).waitFor();check(await p.locator('.receipt-paper').count()===0,'return URL does not display a paid receipt');check(await p.locator('[data-receipt-action=download]').count()===0,'no download before confirmation');
order={...order,status:'Paid',activeCourseIds:['web'],receipt:{number:'DBR-'+id.slice(6),orderId:id,title:order.title,amount:25000,currency:'aed',confirmedAt:'2026-09-30T10:01:00Z',courseIds:['web'],durationDays:365,refundedAmount:0}};
await p.getByRole('button',{name:'Check payment status'}).click();await p.getByRole('heading',{name:'Payment confirmed. You’re ready to learn.'}).waitFor();check((await p.locator('.receipt-total').innerText()).includes('250.00'),'receipt displays confirmed amount');check(await p.locator('.receipt-printer.is-printing').count()===1,'actual confirmed receipt starts printing');check(await p.getByRole('link',{name:'Open Websites & product building →'}).count()===1,'confirmed access offers correct pathway');
await p.waitForTimeout(2700);await p.screenshot({path:'docs/screenshots/receipt-confirmed-desktop.png',fullPage:true});
const download=p.waitForEvent('download');await p.getByRole('button',{name:'Download receipt record'}).click();const record=JSON.parse(fs.readFileSync(await(await download).path(),'utf8'));check(record.currentOrderStatus==='Paid'&&record.receipt.amount===25000,'download reflects confirmed receipt');
check(await p.evaluate(()=>window.AcademyReceipt.money(100,'jpy')).then(s=>s.includes('100')&&!s.includes('1.00')),'zero-decimal currency is displayed correctly');
await p.emulateMedia({media:'print'});check(await p.locator('.receipt-paper').isVisible(),'receipt visible in print layout');check(!(await p.locator('.printer-housing').isVisible()),'printer hardware excluded from printed receipt');check(!(await p.locator('.receipt-next').isVisible()),'learning controls excluded from printed receipt');await p.emulateMedia({media:'screen',reducedMotion:'reduce'});
await p.getByRole('button',{name:'Replay receipt animation'}).click();check(await p.locator('.receipt-paper').evaluate(el=>getComputedStyle(el).animationName)==='none','reduced-motion preference respected');
await p.setViewportSize({width:390,height:844});check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'confirmed receipt fits mobile');await p.screenshot({path:'docs/screenshots/receipt-confirmed-mobile.png',fullPage:true});
order={...order,status:'Refunded',activeCourseIds:[],receipt:{...order.receipt,refundedAmount:25000}};await p.reload();await p.getByRole('heading',{name:'Your payment record.'}).waitFor();check((await p.locator('.receipt-paper').innerText()).includes('Refunded'),'refund status remains visible on original receipt');check(await p.getByRole('link',{name:'Review access options',exact:true}).count()===1,'refunded access sends learner back to access options');
check(errors.length===0,'no payment UI exceptions: '+errors.join('; '));
fs.writeFileSync('docs/receipt-ui-validation.json',JSON.stringify({checks,errors,scope:'Browser UI with mocked owned-order and identity responses; real merchant not connected.'},null,2));console.log('Payment UI checks passed: '+checks);
}finally{await browser.close();server.close()}
