import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createApplication} from '../server/application.mjs';
import {nodeHandler} from '../server/http.mjs';
const require=createRequire(path.resolve('package.json'));
let playwright;
try{playwright=require('playwright')}catch{playwright=require((process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||'')+'/playwright')}
const {chromium}=playwright,temporary=fs.mkdtempSync(path.join(os.tmpdir(),'academy-portable-ui-'));
const nativeFetch=globalThis.fetch,identityOrigin='https://fixture-project.supabase.co';
const users=['learner','owner'].map(name=>({id:name,email:name+'@example.test',email_confirmed_at:'2026-01-01T00:00:00Z'}));
globalThis.fetch=async(input,init={})=>{
  const u=new URL(typeof input==='string'?input:input.url);
  if(u.origin!==identityOrigin)return nativeFetch(input,init);
  const body=init.body?JSON.parse(init.body):{};
  if(u.pathname.endsWith('/signup'))return Response.json({user:users.find(u=>u.email===body.email)});
  if(u.pathname.endsWith('/token')||u.pathname.endsWith('/verify')){
    const user=users.find(u=>u.email===(body.email||body.token_hash||body.refresh_token?.slice(8)));
    return Response.json({access_token:user.email,refresh_token:'refresh:'+user.email,expires_in:3600,user});
  }
  if(u.pathname.endsWith('/user'))return Response.json(users.find(u=>u.email===init.headers.Authorization?.slice(7)));
  if(u.pathname.endsWith('/logout'))return Response.json({});
  throw Error('Unexpected identity fixture');
};
const app=await createApplication({NODE_ENV:'development',ACADEMY_PUBLIC_URL:'http://127.0.0.1:3000',ACADEMY_OWNER_EMAIL:'owner@example.test',ACADEMY_SESSION_KEY:'ab'.repeat(32),TURSO_DATABASE_URL:'file:'+path.join(temporary,'ui.db'),SUPABASE_URL:identityOrigin,SUPABASE_PUBLISHABLE_KEY:'fixture-publishable',ACADEMY_AUTO_MIGRATE:'true',ACADEMY_PAYMENT_PUBLIC:'false'});
const server=http.createServer(nodeHandler(app));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const origin='http://127.0.0.1:'+server.address().port;app.env.ACADEMY_PUBLIC_URL=origin;
const browser=await chromium.launch({...(process.env.ACADEMY_CHROMIUM?{executablePath:process.env.ACADEMY_CHROMIUM}:{}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
let checks=0;const check=(v,msg)=>{assert(v,msg);checks++},errors=[],context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),p=await context.newPage();
p.on('pageerror',e=>errors.push(e.message));
try {
  await p.goto(origin+'/dashboard');
  await p.getByRole('heading',{name:'Welcome back.'}).waitFor();
  check(new URL(p.url()).pathname==='/sign-in','Anonymous dashboard opens sign-in');
  check(await p.locator('#sidebar').count()===0,'No anonymous course sidebar');
  check(await p.locator('#account-email').count()===1&&await p.getByRole('link',{name:'Continue with ChatGPT'}).count()===0,'Portable account page uses email/password');
  await p.goto(origin+'/register');
  await p.getByRole('heading',{name:'Create your learner account'}).waitFor();
  await p.locator('#account-email').fill('learner@example.test');
  await p.locator('#account-password').fill('fixture-long-passphrase');
  await p.locator('#account-confirmPassword').fill('fixture-long-passphrase');
  await p.locator('[name=consent]').check();
  await p.getByRole('button',{name:'Create account',exact:true}).click();
  await p.locator('.auth-message').filter({hasText:'Check your inbox'}).waitFor();
  check((await app.db.prepare('SELECT count(*) AS n FROM profiles').first()).n===0,'Signup alone creates no completed Academy profile');
  await p.goto(origin+'/auth/confirm?token_hash=learner%40example.test&type=email');
  await p.getByRole('heading',{name:'Complete your registration',exact:true}).waitFor();
  check(!p.url().includes('token_hash'),'Confirmation token removed from page URL');
  await p.locator('#account-name').fill('Learner UI fixture');
  await p.locator('#account-country').fill('India');
  await p.locator('[name=consent]').check();
  await p.getByRole('button',{name:'Create my account & enter Academy'}).click();
  await p.getByRole('heading',{name:'My courses',exact:true}).waitFor();
  check(await p.locator('.enrolled-courses .course-card').count()===2,'Real session opens only two free foundations');
  check(await p.getByRole('link',{name:'Launch & team',exact:true}).count()===0,'Learner lacks owner navigation');
  await p.goto(origin+'/dashboard#plan');
  await p.getByRole('heading',{name:'Your learning plan',exact:true}).waitFor();
  await p.locator('[name=hours]').fill('7');
  await p.getByRole('button',{name:'Save my weekly plan'}).click();
  await p.locator('.plan-start-link').waitFor();
  await p.reload();
  await p.locator('[name=hours]').waitFor();
  check(await p.locator('[name=hours]').inputValue()==='7','Browser reload restores durable libSQL plan');
  await p.goto(origin+'/dashboard#guide/account');
  await p.getByRole('heading',{name:'Your Academy guide.',exact:true}).waitFor();
  check((await p.locator('.guide-article').textContent()).includes('Enter your email and a unique password'),'Guide follows email-based workflow');
  await p.goto(origin+'/workspace.html');
  await p.locator('#main h1,#main h2').first().waitFor();
  check(await p.getByRole('link',{name:'My learning plan',exact:true}).count()===1,'Original workspace shares navigation in independent deployment');
  await p.setViewportSize({width:390,height:844});
  await p.goto(origin+'/dashboard#home');
  await p.getByRole('heading',{name:'My courses',exact:true}).waitFor();
  check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Portable dashboard fits mobile');
  fs.mkdirSync('docs/screenshots',{recursive:true});
  await p.screenshot({path:'docs/screenshots/portable-learner-mobile.png',fullPage:true});
  await context.clearCookies();
  await p.goto(origin+'/workspace.html');
  await p.getByRole('heading',{name:'Welcome back.'}).waitFor();
  check(await p.locator('#sidebar').count()===0,'Original workspace is locked after cookie removal');
  await p.locator('#account-email').fill('owner@example.test');
  await p.locator('#account-password').fill('fixture-long-passphrase');
  await p.getByRole('button',{name:'Sign in',exact:true}).click();
  await p.getByRole('heading',{name:'Complete your registration',exact:true}).waitFor();
  await p.locator('#account-name').fill('Owner UI fixture');
  await p.locator('[name=consent]').check();
  await p.getByRole('button',{name:'Create my account & enter Academy'}).click();
  await p.getByRole('heading',{name:'My courses',exact:true}).waitFor();
  await p.goto(origin+'/dashboard#operations');
  await p.getByRole('heading',{name:'Launch & team',exact:true}).waitFor();
  check(await p.locator('.launch-person').count()===8,'Owner sees administrator/demo/six-teacher setup');
  check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Portable launch fits mobile');
  await p.screenshot({path:'docs/screenshots/portable-launch-mobile.png',fullPage:true});
  check(errors.length===0,'No runtime page exceptions: '+errors.join('; '));
  fs.writeFileSync('docs/portable-ui-validation.json',JSON.stringify({checkedAt:new Date().toISOString(),checks,errors,scope:'Actual portable Node server and libSQL database; real browser cookie, registration, confirmation, profile, role, plan and workspace workflow. Supabase HTTP responses are controlled fixtures, not live email delivery.'},null,2));
  console.log('Portable browser checks passed: '+checks);
} finally {
  await browser.close();await new Promise(resolve=>server.close(resolve));app.close();globalThis.fetch=nativeFetch;fs.rmSync(temporary,{recursive:true,force:true});
}
