"""Maps every scraped IISDT listing (by URL slug) to one Academy course.
Variants that differ only by level or marketing title are merged into one course."""
C=[
# Computing & IT
('computer-applications','Computer Applications','Computing & IT','dca adca apdca certificate-in-computer-applications industry-oriented-diploma-in-computer-science-and-it-tools advanced-diploma-in-information-technology-computer-applications advanced-diploma-in-computer-software'),
('computer-basics','Computer Concepts & Office Automation','Computing & IT','certificate-in-computer-conceptccc certificate-in-computer-fundamental office-automation-and-internet-oai'),
('office-suite','MS Office & Advanced Excel','Computing & IT','m-s-office certificate-in-advanced-excel'),
('data-entry-typing','Data Entry & Typing','Computing & IT','data-entry-operatordeo https-iisdt-in-product-steno-english-typing-https-iisdt-in-product-steno-english-typing steno-hindi-typing'),
('tally-erp','Tally & Computerised Accounting','Computing & IT','tally'),
('graphic-dtp','Graphic Design & Desktop Publishing','Computing & IT','diploma-in-graphic-designing certificate-in-desk-top-publishing-dtp'),
('animation-multimedia','Animation, VFX & Multimedia','Computing & IT','2d-3d-animation certificate-in-vfx-video-editing advanced-diploma-in-multimedia-application'),
('autocad','AutoCAD Drafting','Computing & IT','diploma-in-autocad'),
('hardware-networking','Computer Hardware, Repair & Networking','Computing & IT','diploma-in-computer-hardware-and-networking certificate-in-advanced-networking diploma-in-computer-repair-and-diagnostic-techniques'),
('mobile-repair','Mobile Phone Repair Technician','Computing & IT','diploma-in-mobile-phone-repairing certificate-course-in-mobile-repairing mobile-phone-hardware-repair-technician'),
('c-cpp-programming','C & C++ Programming','Computing & IT','certificate-in-c-programming certificate-in-c c-programming-language'),
('server-web-programming','PHP & ASP.NET Web Programming','Computing & IT','certificate-in-php certificate-in-asp-net-programming'),
('software-development','Software & Web Application Development','Computing & IT','diploma-in-software-development advanced-diploma-in-software-web-application-development'),
('ai-machine-learning','AI & Machine Learning','Computing & IT','advanced-diploma-in-ai-and-machine-learning professional-diploma-in-information-technology-and-ai'),
('data-science','Data Science','Computing & IT','advanced-diploma-in-data-science'),
('digital-marketing-seo','Digital Marketing & SEO','Computing & IT','certificate-in-seo diploma-in-digital-marketing advanced-diploma-in-digital-marketing'),
('computer-trainer','Computer & IT Trainer Skills','Computing & IT','computer-trainer-proficiency-diploma diploma-in-computer-education-training-skills certificate-in-computer-education-support-skills diploma-in-it-training-and-instructional-skills diploma-in-computer-training-digital-literacy certificate-in-digital-teaching-learning-technologies'),
('office-it-support','Office IT & Tech Support','Computing & IT','professional-diploma-in-office-it-and-tech-support'),
('cctv-installation','CCTV Installation Technician','Computing & IT','certificate-in-cctv-installation-technician'),
('mis-technology-operations','Management Information Systems & Technology Operations','Computing & IT','diploma-in-management-information-system professional-diploma-in-technology-and-operations-management'),
# Accounting & finance
('financial-accounting','Financial Accounting & Accounts Executive','Accounting & finance','certificate-in-accounts certificate-in-financial-accounting diploma-in-financial-accounting professional-diploma-in-financial-accounting advanced-diploma-in-finance-and-accounts accounts-executive'),
('gst-taxation','GST, Accounting & Taxation','Accounting & finance','gst diploma-in-accounting-taxation diploma-in-corporate-tax-planning'),
('financial-management','Financial Management & Reporting','Accounting & finance','diploma-in-financial-management advanced-diploma-in-finance-management diploma-in-financial-reporting-and-control-account'),
('financial-planning','Financial Planning & Investment','Accounting & finance','diploma-in-financial-planning diploma-in-investment-planning-and-management advanced-certification-in-financial-risk-insurance-planning'),
('stock-market','Stock Market & Capital Markets','Accounting & finance','diploma-in-stock-broker certificate-in-capital-markets advanced-diploma-in-indian-stock-market'),
('banking-lending','Banking, Mutual Funds & Loan Processing','Accounting & finance','certificate-in-banking-and-mutual-fund advanced-diploma-in-banking-sales-representative loan-approval-officer'),
('insurance-advisory','Insurance Advisory & Health Insurance','Accounting & finance','certificate-in-life-insurance-advisor diploma-in-health-economics-and-insurance'),
('international-economy','International Economy & Finance','Accounting & finance','diploma-in-international-economy-and-finance'),
('quantitative-techniques','Quantitative Techniques in Business','Accounting & finance','diploma-in-quantitative-techniques-in-business'),
# Business & management
('human-resource-management','Human Resource Management','Business & management','diploma-in-human-resource-management diploma-in-strategic-hrm diploma-in-personnel-management-industrial-relations diploma-in-hr-and-payroll-management'),
('sales-marketing-management','Sales & Marketing Management','Business & management','advanced-diploma-in-sales-and-marketing-management diploma-in-industrial-marketing diploma-in-international-marketing diploma-in-marketing-and-public-relationship-management'),
('brand-product-management','Brand & Product Management','Business & management','certificate-in-brand-management diploma-in-product-and-brand-management'),
('business-strategy','Business Strategy, Corporate & Cooperative Management','Business & management','certificate-in-business-strategy advanced-certification-in-corporate-management-operations diploma-in-cooperative-management'),
('project-quality-management','Project Management & Six Sigma','Business & management','diploma-in-project-management diploma-in-six-sigma'),
('entrepreneurship','Entrepreneurship Development','Business & management','diploma-in-entrepreneurship advanced-diploma-in-entrepreneurship-development'),
('business-communication','Business Communication & Personality Development','Business & management','certificate-in-business-communication certificate-in-advance-communication diploma-in-communication-skills-trainers diploma-in-personality-development-trainer'),
('english-language','English Language & Proficiency','Business & management','certificate-in-english-language-learning certificate-of-proficiency-in-english'),
('customer-relationship','Customer Relationship Management','Business & management','diploma-in-customer-relationship-management'),
('office-administration','Office Administration & Front Desk','Business & management','advanced-diploma-in-office-administration-and-management diploma-in-office-assistanship certificate-in-receptionist diploma-in-front-office-operation-management'),
('supply-chain-logistics','Supply Chain & Logistics Management','Business & management','certificate-in-supply-chain-management diploma-in-supply-chain-management diploma-in-logistic-management diploma-in-logistics-supply-chain-management-retail-management diploma-in-material-management'),
('courier-delivery','Courier & Delivery Operations','Business & management','diploma-in-courier-and-logistics-management courier-delivery-executive'),
('inventory-warehouse','Inventory & Warehouse Management','Business & management','diploma-in-inventory-and-warehouse-management certificate-in-warehouse-worker'),
('cold-storage','Cold Storage Management','Business & management','diploma-in-cold-storage-manager cold-storage-supervisor'),
('export-import','Export-Import Management','Business & management','advanced-diploma-in-export-import-management'),
('retail-vehicle-sales','Retail Management & Vehicle Sales','Business & management','advanced-diploma-in-retail-management diploma-in-sales-consultant-pre-owned-vehicles'),
('healthcare-administration','Healthcare & Hospital Administration','Business & management','diploma-in-strategic-management-for-hospital hospital-front-desk-coordinator'),
# Law, governance & society
('company-law','Industrial & Company Law','Law, governance & society','advanced-certificate-in-industrial-and-company-law'),
('intellectual-property','Intellectual Property Rights','Law, governance & society','advanced-diploma-in-intellectual-property-rights'),
('human-rights','Human Rights','Law, governance & society','advanced-diploma-in-human-rights'),
('public-administration','Public Administration & Indian Political System','Law, governance & society','advanced-certificate-in-public-administration advanced-certification-in-indian-political-system-administration'),
('social-work','Social Work & Development','Law, governance & society','diploma-in-social-work-development'),
('esg-sustainability','Environmental, Social & Governance (ESG)','Law, governance & society','diploma-in-environmental-social-and-governance'),
('health-family-welfare','Health, Family Welfare & Population Education','Law, governance & society','advanced-diploma-in-health-family-welfare-and-population-education'),
# Hospitality, travel & events
('hotel-management','Hotel & Resort Management','Hospitality, travel & events','advanced-diploma-in-hotel-business-management advanced-certification-in-hotel-resort-business-management advanced-diploma-in-accounting-hospitality'),
('housekeeping','Housekeeping Management','Hospitality, travel & events','advanced-diploma-in-housekeeping-management diploma-in-hospital-house-keeping'),
('travel-tourism','Travel, Tourism & Travel Agency Management','Hospitality, travel & events','certificate-in-tour-and-travel-management certificate-in-tour-and-travel certificate-in-tours-travel-tourism-management certificate-in-tourism-management certificate-in-travel-tourism-operations professional-certificate-in-travel-agency-management'),
('event-wedding','Event & Wedding Management','Hospitality, travel & events','diploma-in-event-management advanced-diploma-in-event-management diploma-in-wedding-management'),
('cooking-baking','Cooking & Baking','Hospitality, travel & events','diploma-in-cooking-and-baking'),
('temple-management','Temple Management','Hospitality, travel & events','advanced-diploma-in-temple-management'),
# Education & training
('montessori','Montessori Education','Education & training','montessori-teacher-training advanced-diploma-in-montessori-teacher-training diploma-in-montessori-early-childhood-learning certificate-in-early-childhood-montessori-education'),
('nursery-preprimary','Nursery & Pre-Primary Teacher Training','Education & training','nursery-teacher-training-ntt pre-primary-teacher-training diploma-in-pre-school-teacher-training certificate-in-nursery-education-skills advanced-diploma-in-nursery-teacher-training'),
('early-childhood-care','Early Childhood Care & Development','Education & training','advance-certificate-in-early-childhood-care-and-education certificate-in-preschool-child-development-learning diploma-in-child-caregiver-skills'),
('teaching-methods','Primary Education & Teaching Methods','Education & training','diploma-in-primary-education diploma-in-practical-teaching-methods-and-classroom-management advanced-diploma-in-practical-teaching-and-learning-strategies advanced-training-in-preschool-primary-teaching-methods'),
('school-management','School Management','Education & training','advanced-diploma-in-school-management'),
('counselling','Career, Education & Applied Counselling','Education & training','diploma-in-career-and-education-counseling certificate-in-applied-counselling-skills'),
('library-science','Library Science','Education & training','diploma-in-library-science'),
('sports-physical-education','Sports Coaching & Physical Education','Education & training','diploma-in-physical-education'),
# Yoga, fitness & wellbeing
('fitness-training','Fitness, Personal Training & Bodybuilding','Yoga, fitness & wellbeing','diploma-in-fitness-trainer diploma-in-personal-trainer diploma-in-body-building diploma-in-fitness-cum-yoga-trainer'),
('weight-management','Obesity & Weight Management','Yoga, fitness & wellbeing','advanced-diploma-in-obesity-and-weight-management'),
('yoga-foundations','Yoga Foundations','Yoga, fitness & wellbeing','certificate-course-in-yoga diploma-in-yoga certificate-in-yogaasana-and-pranayama certificate-in-yoga-practice-wellness diploma-in-yoga-wellness-practices'),
('yoga-instruction','Yoga Education & Instruction','Yoga, fitness & wellbeing','diploma-in-yoga-education diploma-course-in-yoga-education certificate-in-yoga-instruction-skills diploma-in-yoga-instruction-practice diploma-in-yoga-trainer diploma-in-yoga-science-facilitation'),
('yoga-science','Yoga Science & Advanced Practice','Yoga, fitness & wellbeing','advanced-diploma-in-yoga-science advanced-yoga-practitioner-therapy-training'),
('yoga-therapy','Yoga Therapy & Nature Care','Yoga, fitness & wellbeing','certificate-in-yoga-therapy diploma-in-therapeutic-yoga diploma-in-yoga-and-nature-care diploma-in-yoga-nature-care advanced-training-in-yoga-acupressure-techniques diploma-in-yoga-and-massage'),
('meditation','Meditation & Mindfulness','Yoga, fitness & wellbeing','certificate-in-meditation diploma-in-meditation certificate-in-mindfulness-and-meditation-focused-yoga diploma-in-meditation-yoga-and-tantra'),
('massage-spa','Relaxation Massage & Spa Therapy','Yoga, fitness & wellbeing','certificate-in-relaxation-massage-techniques diploma-in-spa-relaxation-techniques diploma-in-spa-trainer diploma-in-advanced-spa-wellness-services'),
# Beauty & personal care
('beauty-care','Beauty Care & Wellness','Beauty & personal care','advanced-diploma-in-beauty-care diploma-in-beauty-parlour diploma-in-beauty-care diploma-in-beauty-care-wellness diploma-in-advanced-beauty-wellness-services'),
('makeup-artistry','Makeup Artistry & Bridal Styling','Beauty & personal care','diploma-in-professional-makeup bridal-fashion-and-makeup-artist diploma-in-make-up-hair-dressing'),
('hair-salon','Hair Styling, Barbering & Salon Management','Beauty & personal care','diploma-in-hair-stylist diploma-in-barber salon-management'),
('nail-technician','Nail Technician','Beauty & personal care','diploma-in-nail-technician'),
# Fashion, art & design
('tailoring','Tailoring & Garment Making','Fashion, art & design','diploma-in-tailoring self-employed-tailor sewing-machine-operator'),
('fashion-design','Fashion Designing & Pattern Making','Fashion, art & design','certificate-in-advanced-fashion-designing fashion-designer diploma-in-pattern-master'),
('hand-embroidery','Hand Embroidery','Fashion, art & design','hand-embroiderer'),
('interior-design','Interior Designing','Fashion, art & design','diploma-in-interior-designing'),
('drawing-painting','Drawing, Painting, Art & Craft','Fashion, art & design','advanced-diploma-in-drawing-and-painting certificate-in-drawing-painting-skills certificate-in-art-craft-skills'),
('carpentry-furniture','Carpentry & Furniture Design','Fashion, art & design','diploma-in-carpenter-furniture-design'),
# Traditional & cultural studies
('astrology-jyotish','Astrology & Jyotish Shastra','Traditional & cultural studies','advanced-diploma-in-astrology diploma-in-astrology advanced-diploma-in-jyotish-shastra diploma-in-jyotish-shastra advanced-diploma-in-astrological-sciences'),
('vastu-feng-shui','Vastu & Feng Shui','Traditional & cultural studies','advanced-diploma-in-vastu-shastra diploma-in-vastu-shastra advanced-diploma-in-vaastu-science diploma-in-feng-shui'),
('tarot-reading','Tarot Reading','Traditional & cultural studies','diploma-in-tarot-reading'),
('numerology','Numerology','Traditional & cultural studies','diploma-in-numerology'),
('palmistry','Palmistry','Traditional & cultural studies','diploma-in-palmistry'),
('gems-crystals','Gemstones & Crystals','Traditional & cultural studies','diploma-in-gems-crystals'),
('vedic-culture','Vedic Sciences, Indian Culture & Philosophy','Traditional & cultural studies','diploma-in-vedic-sciences diploma-in-indian-culture-philosophy'),
('paurohitya','Paurohitya (Ritual Practice)','Traditional & cultural studies','certificate-in-paurohitya'),
# Safety, fire & environment
('fire-technician','Fire Technician & Fire Service Skills','Safety, fire & environment','certificate-in-fireman certificate-in-fire-technician certificate-in-fire-service-technician certificate-in-fire-sub-officer'),
('fire-safety-management','Fire Safety Management','Safety, fire & environment','certificate-in-fire-safety-management certificate-in-fire-and-safety-management certificate-in-fire-and-safety certificate-in-fire-safety-fire-prevention certificate-in-fire-safety-and-hazard-management certificate-in-fire-safety-and-hazards-management certificate-in-fire-industrial-safety-management advanced-certificate-in-fire-engineering-safety-management advanced-certificate-in-fire-industrial-safety-management advanced-certificate-in-fire-safety-and-hazards-management advanced-certificate-in-safety-management'),
('industrial-safety','Industrial Safety & Hazard Management','Safety, fire & environment','certificate-in-industrial-safety certificate-in-industrial-safety-hazard-management certificate-in-industrial-hazards-safety-management advanced-certification-in-industrial-hazard-prevention diploma-in-industrial-safety certificate-in-industrial-safety-disaster-management'),
('health-safety-environment','Health, Safety & Environment (HSE)','Safety, fire & environment','certificate-in-health-safety-environment diploma-in-health-safety-environment diploma-in-health-safety-environment-management diploma-in-health-environment-safety-engineering advanced-certificate-in-occupational-safety-health-and-environment-management certificate-in-health-safety-at-workplace'),
('environmental-safety','Environmental Safety Management','Safety, fire & environment','diploma-in-environmental-safety diploma-in-environment-safety-management advanced-certificate-in-industrial-environment-safety'),
('construction-safety','Construction Safety & Health','Safety, fire & environment','diploma-in-construction-safety diploma-in-construction-safety-and-health'),
('construction-supervision','Construction Supervision','Safety, fire & environment','diploma-in-construction-supervisor diploma-in-civil-construction-supervisor'),
('electrical-safety','Electrical Safety','Safety, fire & environment','diploma-in-electrical-safety'),
('disaster-management','Disaster Management','Safety, fire & environment','diploma-in-disaster-management certificate-in-disaster-management'),
('food-quality','Food Quality Control & Inspection','Safety, fire & environment','certificate-in-food-quality-control-inspection'),
('security-services','Security Services & Crisis Management','Safety, fire & environment','diploma-in-security-officer-skills-and-crisis-management diploma-in-security-supervisor advanced-diploma-in-security-services-management'),
# Technical trades
('electrician','Electrician Technician','Technical trades','electrician-technician-program'),
('hvac-technician','HVAC Technician','Technical trades','certificate-in-hvac-technician'),
('solar-installation','Solar Panel Installation Technician','Technical trades','certificate-in-solar-panel-installation-technician'),
# Agriculture & home
('gardening-nursery','Gardening & Plant Nursery Management','Agriculture & home science','certificate-in-gardening-skills certificate-in-plant-nursery-management'),
('irrigation','Drip & Sprinkler Irrigation Technology','Agriculture & home science','certificate-in-drip-sprinkler-irrigation-technology'),
('organic-agriculture','Organic Agriculture','Agriculture & home science','advanced-certificate-in-organic-agriculture'),
('home-science','Home Science','Agriculture & home science','advanced-certificate-in-home-science'),
]
