import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
c=json.loads((root/'content/curriculum.json').read_text())
methods={
'records':('Make a reliable operating decision','We will read the case before entering anything. A newer file, a bigger number or a familiar-looking option is not automatically correct. We need a reason that comes from the supplied facts.','Choose one field. Find the source fact that controls it. If you need a calculation, work it out first. Enter the value, run the checker and read the reason beside any failed item.','If a value is missing, stop and identify who can confirm it. Do not replace missing evidence with a confident guess.'),
'document':('Prepare something another person can use','We are creating a usable piece of professional work. A long paragraph is not enough. The person receiving it needs to know what to do, who owns the next action and how to check the result.','Start with the requested outcome. Add the source facts, decision, owner, check and next action. Keep assumptions visible. Write one clear section at a time, then check that every required section is present.','A structure check can detect missing sections. It cannot decide whether your advice is professionally sound; a qualified person must review that.'),
'html':('Build an interface people can use','Think of the page in three parts. HTML tells the browser what each element means. CSS decides how it looks and fits. JavaScript changes what happens when somebody interacts with it.','Build the meaningful structure first. Preview it. Add layout rules, then interaction. Use a real label for each field and a real button for each action. Test with the keyboard and at the requested screen width.','A page that looks right can still fail. Check the action, the field error and the small-screen layout, not just the first screenshot.'),
'api':('Understand a request and its response','An API is a way for one piece of software to ask another piece to do a specific job. A request has an action, an address and sometimes input. The response tells us what happened.','Choose the method and resource path. Check who is making the request. Send it and inspect the status and returned data. Then try the invalid and wrong-owner cases. A successful status alone is not enough.','Knowing a record ID does not give you permission to see it. Also, retrying a request must not create the same booking twice.'),
'sql':('Ask a precise question of a table','A table holds rows of facts. SQL is a language for asking which facts you want. We will use a small, documented trainer, so you can see the result directly beside the source.','Name the columns you need with SELECT and the table with FROM. Add WHERE to keep only matching rows. Add ORDER BY when the order matters. Run the query and compare every result with the source.','A query can run successfully and still answer the wrong question. Check its meaning, selected rows and total before accepting it.'),
'permissions':('Give each person only the access they need','Permissions answer two questions: what action may this person take, and on whose records? We will use the stated role policy rather than assuming that every signed-in person can do everything.','Read the role policy. For each action, choose deny, own records, assigned records or all records. Run the matrix checks, then try the case where the person should be refused.','A verifier checks evidence. In this case, that responsibility does not include changing the underlying booking.'),
'ledger':('Record a transaction once and keep it balanced','A ledger records both sides of a transaction. In this training case, cash comes in and revenue is recorded. Both sides must have the same amount, and a repeated event must reuse its existing posting.','Identify the event. Choose the specified accounts, enter both amounts and turn on duplicate protection. Process the posting once, then repeat it. Compare the entry count and both totals.','Equal totals do not prove you used the right accounts. Check the amount, account names and duplicate behavior separately.'),
'events':('Keep the latest trustworthy state','Messages can arrive late or twice. We need a rule that prevents an old message from moving the record backward, and another rule that prevents the same event from being applied twice.','Read the feed in its arrival order. Enable the newer-revision rule and repeated-ID rule. Process the feed and inspect each decision. The final state must come from the newest accepted revision.','Arrival order is not version order. A late message can be older than the state you already hold.'),
'uploads':('Check a file before accepting it','A filename is not proof of safe content. We will check the permitted type, size and basic file signature, then calculate a content fingerprint so the exact file can be identified later.','Use a fictional TXT, CSV or PDF below the stated limit. Run intake. Inspect its metadata and fingerprint. Then try the unsupported type and oversized fixtures and confirm that both are refused.','These local checks do not scan for malware or upload the original file. A real release still needs server-side validation, scanning and protected storage.'),
'workflow':('Automate a controlled process','Automation means applying a sequence of rules consistently. Before an action can have an effect, we need valid input, duplicate protection, the required human approval and a record of what happened.','Define the steps in their required order. Set a small retry limit and a positive waiting time. Name the owner who receives failures when the retry limit is reached. Run the normal and missing-input cases.','A retry is another attempt after a temporary failure. Unlimited retries can repeat damage; they are not a recovery plan.')}
stages={
'BRIEF':('Understand the task','Let’s start by getting clear about the job. Read the scenario below. Tell me what you will deliver, which facts matter and what this task does not cover. We are defining success before touching the tool.','Read the brief, write your delivery objective and confirm the practice boundaries.'),
'LEARN':('Understand the method','I’ll explain the method before you use it. Read the short walkthrough, predict the demonstration result and then run it. The example is separate from your assignment, so you can experiment without changing your work.','Work through the explanation, then describe the principle in your own words.'),
'INVESTIGATE':('Check the facts','Now let’s look at what we actually know. Separate confirmed facts from assumptions. Look for a missing value or a risky assumption that could change your decision. Record your source inspection when you have checked it.','Inspect the source, identify a gap or risk and record what you found.'),
'TRY':('Make a small first attempt','You do not need a perfect result yet. Make one small attempt in the work area and run it. Read what actually happened. If it fails, that gives us useful information about the next change.','Run a small attempt and record what it revealed.'),
'BUILD':('Do the complete job','You have seen the method and tried a small part. Now produce the full requested result. Use the case facts, run the current checks and finish the operating actions where this mission requires them.','Build the requested result and resolve the failed checks.'),
'BREAK':('Find a failure safely','Let’s see whether your control holds when something goes wrong. Run the supplied failure test and inspect its actual result. We want to know why the bad input was refused, or why it slipped through.','Run the controlled failure test and explain its cause.'),
'FIX':('Correct and check again','Choose the problem you observed. Make a focused correction, or verify the control that already refused the bad input. Run the work again after the failure test and keep the result.','Describe the correction or confirmed control and keep a successful retest.'),
'TEST':('Prove the result','Now repeat the checks on the current version of your work. Compare the expected result with the actual result. Include one normal case and one failure case so another person can repeat your check.','Run the current checks and record expected versus actual behavior.'),
'EXPLAIN':('Explain your decision','Imagine a colleague asks why you chose this approach. Answer with a source fact or an observed test result. Mention one reasonable alternative and explain one limit of your solution.','Explain your choice, the evidence behind it and its limit.'),
'DEFEND':('Answer a reviewer’s questions','A professional review checks your reasoning as well as your output. Work through these questions one at a time. Give specific evidence and say clearly what you have not established.','Answer each review question using your own work and test evidence.'),
'SHIP':('Hand over usable work','Let’s make the result useful to someone else. Export the current work, name its recipient and explain how they can reproduce the result. State what still needs a real release or qualified review.','Export the current work and write the handover instructions.'),
'EVIDENCE':('Prepare your review pack','You have a work product, test results and a correction history. Now identify where the evidence came from and how it may be used. Prepare the pack, then send it through the services desk when you are ready.','Confirm the evidence boundaries and prepare the submission pack.')}
out={}
for p in c['programmes']:
 for mod in p['modules']:
  for m in mod['missions']:
   h,intro,method,mistake=methods[m['engine']]
   out[m['id']]={'programme':p['title'],'objective':m['title'],'methodTitle':h,'introduction':intro,'method':method,'commonMistake':mistake,'principle':m['principle'],'steps':[
    {'title':'First, understand the job','body':f"Let’s work on this task: {m['title'].lower()}. Here is your client or operating brief: {m['scenario']}"},
    {'title':'Here is the method','body':intro+' '+method},
    {'title':'Before you accept the result','body':mistake+' '+m['principle']}],
    'stages':{k:{'title':v[0],'spoken':v[1],'nextAction':v[2]} for k,v in stages.items()}}
(root/'content/mentorship.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
(root/'dist/mentorship.js').write_text('window.ACADEMY_MENTORSHIP='+json.dumps(out,ensure_ascii=False,separators=(',',':'))+';\n')
print(f'Built professional walkthroughs for {len(out)} missions and {len(out)*12} stage introductions.')
