"""Authored recipe curriculum. No third-party lessons are copied."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
LEVELS=['Beginner','Builder','Professional','Advanced','Expert practice']
# title | principle | concrete work | review criteria. Every row is a distinct project.
TRACKS=[
('start','Digital confidence','Start from zero. Build the habits that make every other skill easier.','Compass','DB-00',True,'''Create your first controlled workspace|A folder groups work; a filename identifies a file; a version records a change. An approved file can be older than an unapproved draft.|Plan a workspace for a fictional café. Include incoming, working and approved folders. Name a supplier list and identify who may approve it.|folder structure;versioned filename;approval owner
Share a file safely|Permission controls what someone may do. A named viewer can read; an editor can change. Public access is a separate decision.|A colleague needs weekly order totals, not customer phone numbers. Write a sharing request with the smallest dataset and permission.|minimum dataset;named recipient;viewer permission
Find reliable information|A search result is a lead. The underlying author, publication date and primary evidence determine whether it supports your decision.|Compare a software manual with an anonymous tip. Record one fact, its source, and an uncertainty you must resolve.|primary source;publication context;unresolved question
Write a clear work update|A useful update separates completed work, blockers and the next action so the recipient knows whether to intervene.|Your fictional order report is delayed because two delivery dates are missing. Write an update with an owner and a realistic next checkpoint.|completed work;blocker and owner;next checkpoint
Build a repeatable checklist|A checklist describes observable actions, not vague goals. Each action needs an expected result.|Turn a weekly report into a repeatable routine: collect, validate, summarize, review and archive. Add a check for duplicate rows.|ordered actions;duplicate check;review record
Make a trustworthy spreadsheet|A spreadsheet cell holds a value or a formula. Preserve source values and show calculations separately.|Use the data desk to total 12, 18 and 9 orders. Explain why the total is 39 and how you would flag an empty day.|source values;formula and result;missing-data rule
Recover a lost draft|A backup is useful only if you can restore it. Local browser storage is not a cloud copy.|Export your Academy backup, record its date, and describe a restore drill that compares a known note before and after.|backup name;restore sequence;comparison check
Organize a small project|A task has a result, an owner and a deadline. Dependencies explain what must happen first.|Plan a fictional café menu update. Separate content, approval, publication and verification. Identify the critical dependency.|deliverables and owners;dependency;acceptance check
Audit a handover|A new person should be able to repeat your work using the handover alone. Hidden assumptions are defects.|Review your earlier spreadsheet routine. Add source version, reproduction steps, expected total and an escalation contact.|source version;reproduction steps;escalation owner
Deliver your digital operations kit|Expert practice integrates earlier skills under a changed constraint. It does not establish workplace expertise by itself.|A replacement colleague joins with read-only access. Package the folder plan, report, checklist and recovery procedure without giving edit access unnecessarily.|integrated evidence;changed-constraint response;limitations'''),
('web','Websites & product building','Go from your first page to a tested, accessible product handover.','Code','DB-02',False,'''Make your first useful page|HTML describes meaning. A heading introduces a section, a paragraph explains it, and a button performs an action.|In the web studio build a café page with one main heading, a short description and a contact link. Explain each element.|semantic structure;contact action;clear content
Style a responsive layout|CSS changes appearance. Flexible widths let content fit small screens without horizontal scrolling.|Create two content sections that stack on a narrow screen. Use readable text, generous spacing and an obvious primary action.|flexible layout;small-screen result;primary action
Build an accessible form|A visible label tells a person what to enter. Native controls carry keyboard behavior; errors should explain recovery.|Create a contact form with a name, email, message and submit button. Link each label to its input and test empty submission.|associated labels;validation feedback;keyboard sequence
Store a browser draft|Browser storage is tied to an origin and device. Save only appropriate data and handle missing or invalid records.|Build a note editor that saves a draft. Explain what happens when storage is cleared and provide an export option.|save and restore;failure handling;export path
Separate the interface from the API|A browser request is untrusted. A backend must validate the caller, resource and requested action independently.|Use the API trainer to inspect a fictional booking. Design allowed responses for owner, another learner and invalid input.|request contract;ownership rule;error responses
Model product states|Loading, empty, error and success are distinct states. A clear interface tells people what to do in each one.|Design a saved-project list for all four states and prevent a second submission while the first is pending.|four states;duplicate control;recovery action
Test the complete journey|A unit check proves one behavior. An end-to-end check follows the real path through several components.|Write and run a test plan from form entry to confirmation, including invalid email, double click and a failed response.|happy path;failure path;observed results
Measure accessibility and performance|A beautiful page must remain usable by keyboard and on a slow connection. Measurements need a stated method.|Audit a page for focus order, labels, contrast and image size. Record actual observations and fixes, without inventing scores.|measurement method;observations;retest
Plan a safe deployment|A release needs configuration, checks and a rollback. Secrets belong on the server, not in browser bundles.|Write a release plan for the café site including environment values, smoke tests and a previous-version recovery path.|configuration boundary;smoke checks;rollback steps
Defend a client-ready web product|A professional handover connects requirements to evidence and identifies unfinished work explicitly.|Package your page, form, test report and deployment notes. Defend a change request to support a second language.|requirement evidence;change analysis;handover package'''),
('data','Data & decision making','Turn raw records into careful, explainable business decisions.','Chart','DB-05',False,'''Read a table with confidence|A row is one record; a column describes one attribute. An identifier distinguishes records even when names repeat.|Describe a fictional orders table with order_id, day, amount and status. Identify which column should be unique.|row meaning;column definitions;unique identifier
Clean without losing the source|Cleaning should preserve the original and log changes. A blank amount differs from a genuine zero.|Clean a six-row order sample containing a duplicate identifier, a blank amount and mixed date formats. Write the rules before editing.|source preservation;cleaning rules;exception log
Ask a precise business question|A useful metric specifies its population, time period and calculation. A total without these boundaries is ambiguous.|Define weekly completed-order revenue. Decide how refunds and unpaid orders affect the metric.|population;time boundary;calculation rule
Calculate and reconcile|A total is trustworthy when it reconciles with its source. Check row counts and monetary sums independently.|Use the data desk to aggregate fictional amounts 120, 80 and -20. Reconcile the net 180 with the three source records.|calculation;reconciliation;exception check
Query a relational dataset|SELECT chooses columns, WHERE filters rows, and ORDER BY sorts the result. Filtering before aggregation changes the question.|Use the SQL trainer to retrieve orders above a stated amount. Explain the difference between row count and revenue sum.|query;result interpretation;count versus sum
Design a clear dashboard|A chart should answer a question. Axes, units and denominators stop a visual from overstating change.|Design a weekly operations dashboard with volume, completion rate and an exception list. Specify each metric formula.|decision question;metric definitions;exception action
Avoid misleading comparisons|An apparent increase can reflect a changed population. Compare like periods and record data coverage.|Compare two fictional weeks with different operating days. Show totals and per-day values and explain the limitation.|comparable basis;normalized calculation;limitation
Control access to reports|Aggregated data can still expose people in small groups. Restrict sensitive detail and review exports.|Design separate report views for an operations lead and an external vendor. Explain withheld fields and access checks.|role views;field minimization;export control
Make an evidence-based recommendation|A recommendation should connect observed data, uncertainty and the cost of being wrong.|Use a fictional rise in failed deliveries to recommend one bounded experiment with a success metric and stop condition.|evidence;experiment;stop condition
Hand over an auditable analysis|Another analyst should reproduce the answer from the same versioned inputs. Record transformations and assumptions.|Package a data dictionary, cleaned table, query, dashboard specification and decision note; handle a late refund as a changed constraint.|reproducible inputs;transformation log;late-data response'''),
('ai','AI for useful work','Write better instructions, evaluate results, and keep people in control.','Spark','DB-04',False,'''Write your first useful AI brief|An AI instruction works better when it names the task, context, boundaries and expected output. Fluent output can still be wrong.|Use the prompt studio to draft a request for a fictional café opening announcement. Specify audience, tone, facts and length.|task and audience;source facts;output format
Separate facts from guesses|Generated text is a draft, not a source. Check factual claims against original evidence.|Review a fictional announcement that invents opening hours. Mark unsupported claims and write a corrected instruction.|unsupported claim;primary evidence;correction
Protect private information|Data sent to an external service follows that service's terms. Use synthetic examples when real records are not authorized.|Prepare an anonymized customer-support scenario without names, phone numbers, account details or credentials.|data minimization;synthetic example;approval boundary
Create reusable prompt recipes|A reusable prompt has explicit variables and a stable review checklist. Version changes so results can be compared.|Build a template for summarizing meeting notes, with fields for decisions, owners, dates and unresolved questions.|variables;structured output;review checklist
Evaluate outputs with a rubric|Evaluate accuracy, completeness and adherence separately. One attractive answer does not establish reliability.|Create three fictional support questions and a rubric. Compare two draft responses and record exact failures.|test set;scoring criteria;failure evidence
Ground answers in approved content|Retrieval supplies relevant evidence; it does not remove the need to verify. An answer should abstain when evidence is missing.|Design a knowledge assistant restricted to a two-page policy. Specify citation behavior and a missing-answer response.|approved sources;citation rule;abstention
Build a human approval gate|A draft and a sent message have different consequences. Separate generating, reviewing and executing actions.|Use the automation desk to route an AI-written refund reply for approval before it can be sent.|draft stage;approver;execution boundary
Test adversarial instructions|Untrusted documents can contain instructions that conflict with the task. Treat document text as data.|Write a test where a retrieved note says to ignore rules and expose contacts. Define the expected refusal and safe output.|untrusted instruction;expected behavior;test record
Track cost and quality together|A cheaper workflow may require more review. Measure useful accepted outputs, latency and human effort.|Plan an evaluation with a fixed question set, an acceptance threshold and a monthly budget guard.|quality metric;cost calculation;budget limit
Deliver a responsible AI workflow|A production workflow needs documented boundaries, monitoring and a person who can stop it.|Package your prompt template, evaluation set, privacy rules and approval flow. Handle a changed policy without silently reusing old answers.|versioned assets;monitoring owner;policy-change response'''),
('automation','Automation & AI agents','Build workflows that handle errors, duplicates, and approvals.','Workflow','DB-12',False,'''Map a repetitive task|An automation starts with a trigger, transforms inputs and produces an outcome. First understand the manual process.|Map a fictional enquiry from form submission through validation, assignment and acknowledgement.|trigger;transformation;outcome
Validate incoming information|Inputs can be missing, malformed or unexpected. Reject invalid records before downstream actions.|Define required email and enquiry fields, accepted formats, and a useful error result.|schema;validation rules;error response
Build your first workflow|A workflow connects small explicit steps. Test one step before enabling the whole chain.|Use the automation desk to create intake, validate, review and acknowledge steps with fictional inputs.|ordered steps;sample input;expected output
Prevent duplicate actions|A stable event identifier lets the system recognize retries. A retry should not send a second acknowledgement.|Simulate event ENQ-101 twice. Record how an idempotency key prevents a duplicate effect.|stable key;duplicate result;retained record
Handle temporary failures|Retry temporary problems with a bounded policy. Permanent validation errors need correction, not endless retries.|Design a three-attempt delivery policy with increasing delays and an exception queue.|retry limit;failure classification;exception queue
Add role-based approval|An approver needs permission for the specific action and record. A role label alone is not sufficient.|Route a discount request to an authorized manager and block the requester from approving their own request.|scoped permission;separation;denied test
Make an agent use tools safely|Tool access should be narrower than the agent's overall goal. Validate parameters before execution.|Specify an agent allowed to read stock and draft a reorder, while a person must approve purchase.|allowed tools;parameter validation;human approval
Observe a workflow in operation|Logs need correlation identifiers and useful outcomes without sensitive data. Alerts should have an owner.|Design a run log for an enquiry workflow and an alert for repeated failed deliveries.|correlation id;safe log fields;alert owner
Recover from partial completion|A process can stop after one external action succeeds. Reconciliation finds the real state before retrying.|A confirmation was sent but the status update failed. Write a recovery flow that avoids sending it again.|state reconciliation;safe retry;recovery evidence
Handover a resilient automation|Reliability is demonstrated with fault cases, monitoring and documented recovery, not just a successful first run.|Package the flow, schema, duplicate test, retry test and recovery playbook; handle a new downstream rate limit.|test matrix;runbook;rate-limit response'''),
('business','Business operations','Practice real workflows using clear records and controlled decisions.','Briefcase','DB-21',False,'''Understand an operational record|A record documents an event or decision. Its owner and status show what can happen next.|Create a fictional purchase request with item, quantity, purpose, requester and approval state.|record fields;owner;status
Build a reliable task board|A board shows work state. Moving a task should represent an actual change in evidence or ownership.|Create five tasks for a small order process and define entry and exit conditions for each column.|task outcomes;state rules;owners
Control purchasing exceptions|An exception is a case that does not meet the standard process. Escalation preserves responsibility.|A supplier requests a changed bank account. Record the request and a separate verification step before payment preparation.|exception record;independent verification;hold decision
Manage inventory reservations|Available stock differs from physical stock when some units are reserved. Avoid assigning the same units twice.|For 20 units on hand and 7 reserved, calculate 13 available. Explain a rejected request for 14.|stock equation;reservation rule;oversell test
Reconcile a transaction trail|Reconciliation compares independent records and records differences rather than forcing totals to match.|Compare a fictional order, delivery and invoice with one quantity mismatch. Prepare an exception note.|source comparison;mismatch;resolution owner
Write a customer resolution|A good response states what is known, the next action and the expected checkpoint without promising an unapproved outcome.|Draft a reply for a delayed shipment whose new date is unconfirmed. Route the issue to the responsible operator.|confirmed facts;next action;checkpoint
Map role permissions|Use least privilege and record ownership. People should have the permissions required by their responsibilities.|Build a requester, approver and auditor permission matrix and test self-approval denial.|permission matrix;ownership boundary;denied case
Measure operational performance|A service metric needs an agreed definition and a consistent data source. Averages can hide exceptions.|Define on-time completion, rework rate and unresolved exceptions for a fictional service desk.|metric definitions;data source;exception threshold
Improve one process responsibly|A change needs a baseline, a bounded pilot and a rollback if outcomes worsen.|Design a pilot to reduce order-entry errors using a validation checklist and a weekly review.|baseline;pilot measure;rollback
Deliver an operating playbook|A playbook connects normal work, exceptions, roles and evidence. A replacement operator must be able to use it.|Package intake, reservation, approval and reconciliation procedures for a fictional small business.|integrated process;exception handling;handover'''),
('design','Design & communication','Turn a brief into clear, consistent, accessible experiences.','Pen','DB-16',False,'''Turn a request into a brief|A design brief names the audience, task, content and constraints. Preferences do not replace user needs.|Write a brief for a café booking page used on mobile. Define the one action visitors must complete.|audience;primary task;constraints
Create a content hierarchy|Hierarchy tells the reader where to begin and what matters next. Use meaningful headings and grouping.|Organize booking information into title, availability, requirements and action. Remove repeated instructions.|priority order;grouping;clear action
Build a consistent type system|A type scale gives related text consistent roles. Readable line length matters more than decorative variety.|Define heading, body, label and helper-text roles using the repository's fonts. Check a long title and a narrow screen.|text roles;long-content behavior;small-screen check
Use color with purpose|Color can reinforce meaning but must not be the only signal. Include labels and visible states.|Design error, success and pending messages with text and icons, retaining the DigitalBurj brand palette.|meaningful states;non-color signal;contrast check
Prototype the main journey|A prototype tests task flow. Each screen should clarify state and the next action.|Map booking, review, confirmation and correction screens. Test a user changing the date midway.|journey;recovery path;observed issue
Write interface copy|Useful copy names the action and explains consequences. Errors should say what happened and how to recover.|Rewrite vague save and error messages for a booking form, including a network failure.|specific action;consequence;recovery guidance
Evaluate accessibility|Keyboard navigation, labels and understandable content help more people complete tasks. Test actual behavior.|Audit a prototype with keyboard only. Record focus order, field labels and any trapped or invisible controls.|test method;observed barriers;fixes
Create a reusable component contract|A component defines content, states and behavior as well as appearance. Reuse should preserve meaning.|Document a form field with default, focus, disabled, error and success states and a long helper message.|state set;behavior;content limits
Run a practical usability session|Observe whether a person completes the task. Avoid coaching them toward the outcome during the test.|Write a neutral booking task, observation sheet and consent script for a voluntary test.|neutral task;observations;consent
Hand over a coherent experience|Design decisions should connect to user needs and implementation evidence. Document uncertainty honestly.|Package the brief, component rules, test findings and revised journey; respond to a right-to-left language requirement.|traceable decisions;test evidence;localization analysis'''),
('career','Freelancing & client delivery','Scope, communicate, price practice projects, and hand over reliable work.','People','DB-20',False,'''Describe a useful service|A service describes an outcome for a specific client. A list of tools does not explain the result.|Write a service for a small business that needs a controlled weekly report. Define inputs and outputs.|client problem;inputs;outcome
Ask discovery questions|Discovery exposes constraints before promising a solution. Ask about current work and failure costs.|Prepare five questions for a client with duplicate order records, including volume, ownership and success criteria.|current process;constraints;success criteria
Write a bounded scope|Scope defines included work, exclusions and acceptance. Ambiguity creates disputes later.|Draft a reporting project scope with two revisions, a source-data assumption and named acceptance checks.|deliverables;exclusions;acceptance
Estimate work transparently|An estimate separates effort, uncertainty and external cost. It should not be presented as a guarantee.|Estimate discovery, build, testing and handover hours for a fictional project; record the largest uncertainty.|effort breakdown;assumptions;uncertainty
Build a credible portfolio story|A portfolio should distinguish practice, paid work and independent review. Explain your actual contribution.|Turn one Academy project into a case study with problem, approach, evidence and limitations.|honest scope;process evidence;result
Manage a change request|A changed requirement may change time, price and acceptance. Record the decision before changing delivery.|A client adds a second dashboard halfway through. Write impact, options and an approval request.|impact;options;approval point
Handle feedback professionally|Clarify the observable issue and its impact before defending a preference. Agree how the fix will be checked.|Respond to feedback that a report is hard to read. Ask a precise question and propose a measurable revision.|clarification;revision;acceptance check
Prepare a secure handover|Transfer usable documentation and appropriate access. Do not send credentials in ordinary messages.|Prepare a handover with ownership, deployment instructions, account transfer and a support boundary.|ownership;secure access transfer;support terms
Operate a reliable service|A sustainable service needs scheduling, quality checks and a way to handle incidents or capacity limits.|Write a weekly delivery routine and an escalation plan for missed input data.|delivery cadence;quality gate;escalation
Defend a professional engagement|Professional judgment includes declining unsupported promises and explaining tradeoffs.|Package discovery, scope, estimate, evidence and handover for a fictional client; respond to an unrealistic deadline.|engagement evidence;tradeoff;responsible boundary'''),
('delivery','Production & expert practice','Integrate your skills under changing requirements and independent review.','Shield','DB-22',False,'''Define a system boundary|A system boundary identifies users, data, external services and responsibilities. Unknowns should stay visible.|Map a fictional enquiry system with browser, backend, database and email provider. Assign responsibility at each boundary.|components;data flow;responsibilities
Model failure before launch|A failure model asks what can go wrong and how to detect and recover. Prioritize impact and likelihood.|List failures for sign-in, save, payment and notification, then name detection and recovery for each.|failure cases;detection;recovery
Define permissions on the server|The server must authorize each action using trusted identity and resource ownership. A hidden button is not enforcement.|Design learner, reviewer and owner permissions. Include a direct API request that tries to read another learner's evidence.|trusted identity;ownership check;denied request
Make writes repeatable|Retries and concurrent edits are normal. Stable keys and revision checks prevent duplicate or lost writes.|Design a progress save with an expected revision and a purchase event with a unique provider ID.|revision check;idempotency;conflict response
Protect release configuration|Secrets, public configuration and data migrations have different lifecycles. Review them separately.|Create a deployment checklist with secret injection, migration order, domain setup and post-release checks.|secret handling;migration order;smoke test
Design observability with purpose|Monitoring should show service health and user impact without collecting unnecessary private data.|Define failure rate, request latency and queue age; give each alert a threshold, owner and response.|metrics;alert ownership;privacy
Run a recovery exercise|A recovery plan becomes useful when tested against a known backup and explicit success criteria.|Design a restore exercise for learner records with a timestamped backup, isolated restore and reconciliation.|recovery source;isolated test;reconciliation
Plan capacity and cost|Scaling requires measurements of load, data growth and service limits. Architecture labels do not prove capacity.|Create a load-test plan for 100, 500 and 1000 concurrent practice sessions and a cost model with stated assumptions.|load profile;success thresholds;cost assumptions
Defend an architecture decision|An architecture decision records context, alternatives, tradeoffs and consequences so others can revisit it.|Compare a single service with a separate grading queue for untrusted code execution. Explain isolation and operational cost.|alternatives;security boundary;consequences
Complete an independently reviewed capstone|Expert practice ends with defensible evidence and independent assessment. Course completion alone is not professional expertise.|Combine a product, tests, access rules, deployment plan and recovery evidence; request separate review and verification of your claims.|integrated capstone;changed-constraint defense;independent assessment''')]
from expansion import EXTRA_TRACKS, EXAMPLES, MODULES, TOOLS, DIAGRAMS
TRACKS += EXTRA_TRACKS
from iisdt.adapter import build as build_subject_courses
SUBJECT=build_subject_courses()
TRACKS += SUBJECT['tracks']
for part,data in(('examples',EXAMPLES),('modules',MODULES),('tools',TOOLS),('diagrams',DIAGRAMS)):data.update(SUBJECT[part])
TOOL_FOR={'web':'web','data':'data','ai':'prompt','automation':'flow','finance':'budget','design':'design','logistics':'board','leadership':'board'}|SUBJECT['tool_for']
LEGACY={'nocode':'DB-17','localai':'DB-04','cloud':'DB-06','content':'DB-16','leadership':'PC-CC01'}
PROGRAMMES={'start':['DB-00','PC-AD01'],'web':['DB-02','DB-03','DB-10','DB-11'],'data':['DB-05'],'ai':['DB-04','DB-15'],'automation':['DB-12'],'business':['DB-13','DB-19','DB-21','PC-RE01','PC-DC01','PC-BF01','PC-IN01','PC-IM01','PC-HR01','PC-SM01','PC-SA01','PC-CS01','PC-PC01','PC-RT01','PC-HT01','PC-TC01','PC-HC01','PC-FM01','PC-CM01'],'design':['DB-16'],'career':['DB-20'],'delivery':['DB-22','DB-08'],'nocode':['DB-01','DB-14','DB-17'],'localai':['DB-04'],'cloud':['DB-06'],'content':['DB-16'],'safety':['DB-07'],'finance':['DB-09','PC-AC01','PC-PR01','PC-AR01'],'logistics':['PC-LG01','PC-WH01','PC-EX01'],'commerce':['DB-18','PC-EC01'],'leadership':['PC-CC01']}|{tid:[] for tid in SUBJECT['category']}
CATEGORY={'start':'Foundations','safety':'Foundations','web':'Build & technology','nocode':'Build & technology','cloud':'Build & technology','ai':'AI & automation','automation':'AI & automation','localai':'AI & automation','design':'Creative work','content':'Creative work','data':'Business & operations','business':'Business & operations','finance':'Business & operations','logistics':'Business & operations','commerce':'Business & operations','career':'Professional growth','leadership':'Professional growth','delivery':'Professional growth'}|SUBJECT['category']
tracks=[]
for tid,title,summary,icon,legacy,free,rows in TRACKS:
 missions=[]
 for i,line in enumerate(rows.splitlines()):
  parts=line.split('|'); name,principle,task,criteria=parts[:4]; terms=criteria.split(';')
  example=parts[4] if len(parts)>4 else EXAMPLES[tid].splitlines()[i]
  missions.append({'id':f'{tid}-{i+1:02}', 'title':name,'level':LEVELS[i//2], 'levelIndex':i//2, 'minutes':[25,30,40,45,55,60,75,80,90,120][i], 'principle':principle,'example':example,'visual':{'nodes':DIAGRAMS[tid],'caption':principle.split('. ')[0].rstrip('.')+'.'},'moduleIndex':i//2,'recommendedTools':TOOLS[tid],'task':task,'criteria':terms,'tool':parts[5] if len(parts)>5 else TOOL_FOR.get(tid,'notebook'),'ingredients':['The fictional scenario in the brief','Your private draft and test notes','The built-in workspace and an evidence export'],'steps':[{'title':'Understand','instruction':f'Read “{name}”. In one sentence, explain the intended outcome and who needs it. Use your own words.'},{'title':'Explain in your own words','instruction':'Explain the concept in your own words. Relate it to the worked example, identify one source fact, and say what you would still need to check.'},{'title':'Build','instruction':task},{'title':'Test & fix','instruction':f'Check {terms[0]}, {terms[1]} and {terms[2]}. Record an expected result, an observed result and one failure or limitation. Correct your draft and check again.'},{'title':'Reflect','instruction':'Explain why your approach fits this brief. Compare one alternative and describe a situation where your result would not be sufficient.'},{'title':'Submit evidence','instruction':'Export the recipe and work product. A reviewer should be able to repeat your checks. Confirm that you used fictional or authorized information.'}], 'reviewRequired':True})
 track={'id':tid,'title':title,'summary':summary,'icon':icon,'legacy':LEGACY.get(tid,legacy),'legacyProgrammeIds':PROGRAMMES[tid],'free':free,'category':CATEGORY[tid],'modules':[{'title':label,'level':LEVELS[j],'missionIds':[m['id'] for m in missions[j*2:j*2+2]]} for j,label in enumerate(MODULES[tid])],'recommendedTools':TOOLS[tid],'levels':LEVELS,'missions':missions,'minutes':sum(m['minutes'] for m in missions),'outcome':missions[-1]['title'],'prerequisites':[] if tid=='start' else ['start']}
 if SUBJECT['aliases'].get(tid):track['aliases']=SUBJECT['aliases'][tid]
 if SUBJECT['notice'].get(tid):track['notice']=SUBJECT['notice'][tid]
 tracks.append(track)
glossary=[('API','A defined way for one program to request work or information from another.'),('Authentication','Checking who a person or service is.'),('Authorization','Checking whether that identity may perform this action on this record.'),('Backend','Server-side code that applies rules and manages stored data.'),('CAD','Computer-aided design: creating a measurable model of an object.'),('Certificate','A record of a specified achievement issued under stated assessment rules.'),('Cloud','Computers and storage operated remotely and accessed over a network.'),('Database','An organized store of records that can be queried and updated.'),('Entitlement','A server record granting an account access to specified learning content.'),('Evidence','Work products and observations that support a claim.'),('FDM','A 3D-printing process that deposits material in successive layers.'),('Frontend','The interface a person sees and interacts with.'),('Idempotency','A repeated request produces one intended effect rather than duplicating it.'),('Infill','The internal structure a slicer plans inside a printed object.'),('JSON','A text format for structured data using objects, lists and simple values.'),('Layer height','The vertical thickness of a planned print layer, usually measured in millimetres.'),('Local storage','Data saved by a browser for one site on one device.'),('MVP','A small product scope used to test a specific assumption with real users.'),('Parameter','A named input whose value controls a calculation or model.'),('Portfolio','A collection of work with clear context, contribution and evidence.'),('Prompt','Instructions and context supplied to a generative model.'),('Regression','Previously working behavior that fails after a change.'),('Rubric','Explicit criteria used to assess a piece of work consistently.'),('Sandbox','An isolated environment for controlled practice or execution.'),('Schema','A definition of expected data fields, types and constraints.'),('Slicer','Software that converts a 3D model into planned layers and printer instructions.'),('SQL','A language used to query and manage relational data.'),('STL','A triangle-mesh file format commonly used to exchange printable geometry.'),('Tolerance','The allowed difference between a target dimension and a measured result.'),('Webhook','An HTTP message a service sends when an event occurs.')]
references=[{'title':'MDN: learning web development','url':'https://developer.mozilla.org/en-US/docs/Learn_web_development'},{'title':'Hugging Face: learning resources','url':'https://huggingface.co/learn'},{'title':'Ollama: documentation','url':'https://docs.ollama.com/'},{'title':'Stripe: fulfilling orders','url':'https://docs.stripe.com/checkout/fulfillment'}]
glossary=[g for g in glossary if g[0] not in {'CAD','FDM','Infill','Layer height','Slicer','STL','Tolerance'}]
references=[r for r in references if not r['title'].startswith('Prusa:')]
a={'version':'5.0','levels':LEVELS,'tracks':tracks,'glossary':[{'term':a,'definition':b} for a,b in glossary],'references':references,'authoredAt':'2026-09-30','assessment':'Authored practice content. Independent subject review is required before assessed credentials can be issued.'}
(ROOT/'content/atlas.json').write_text(json.dumps(a,indent=2))
(ROOT/'dist/preview-data.js').write_text('window.ACADEMY_ATLAS='+json.dumps(a,separators=(',',':'))+';')
meta={**a,'tracks':[{k:v for k,v in t.items() if k!='missions'}|{'missionCount':len(t['missions']),'outline':[{'id':m['id'],'title':m['title'],'level':m['level'],'minutes':m['minutes']} for m in t['missions']]} for t in tracks]}
(ROOT/'dist/catalogue.json').write_text(json.dumps(meta,separators=(',',':')))
(ROOT/'content/source/iisdt-syllabi.json').write_text(json.dumps(SUBJECT['provenance'],indent=1,ensure_ascii=False)+'\n')
def offer_price(p):return 44900 if p['reference']['duration'].split()[0] in('One','Two','Three') else 89900 if 'advanced' in p['reference']['url'] else 69900
offers=[{'id':p['id']+'-course','title':p['title']+' course','status':'Draft','amount':offer_price(p),'currency':'inr','courseIds':[p['id']],'durationDays':365,'providers':['razorpay'],'termsUrl':'https://academy.digitalburj.com/terms','refundPolicy':'Owner to confirm the refund policy before this offer is approved.','reviewApproval':''} for p in SUBJECT['provenance']]
(ROOT/'content/default-offers.json').write_text(json.dumps(offers,indent=1)+'\n')
count=len(tracks); projects=count*10; subject=len(SUBJECT['category'])
doc=[f"# Curriculum map\n\n{count} courses, five named modules per course and {projects} authored project recipes. Every recipe follows Understand → Explain → Build → Test & fix → Reflect → Submit. Practice times are estimates; independent subject approval is required for assessed delivery.\n\nThe original 48 programmes and 192 missions are preserved and mapped to course access. {subject} subject-area courses merge near-duplicate programme variants into one course each and are standalone: they have no mapped professional programme and use fictional practice cases only. Their alignment records are in content/source/iisdt-syllabi.json.\n"]
for t in tracks:
 rows=['| Module | Level | Project | Practice minutes |','|---|---|---|---|']+[f"| {mod['title']} | {mod['level']} | {m['title']} | {m['minutes']} |" for mod in t['modules'] for m in t['missions'] if m['id'] in mod['missionIds']]
 block=[f"## {t['title']}",t['summary'],f"Access: {'Free foundations' if t['free'] else 'Purchase or approved grant'}. Outcome: {t['outcome']}",'\n'.join(rows)]
 if t.get('notice'):block.insert(3,'Scope note: '+t['notice'])
 if t['legacyProgrammeIds']:block.append('Mapped professional programmes: '+', '.join(t['legacyProgrammeIds'])+'.')
 doc.append('\n\n'.join(block)+'\n')
(ROOT/'docs/CURRICULUM_MAP.md').write_text('\n'.join(doc))
print(f"Authored {len(tracks)} pathways, {sum(len(t['missions']) for t in tracks)} project recipes, {sum(len(t['missions']) for t in tracks)*6} step instructions.")
