"""Original teaching examples and additional course projects, authored for DigitalBurj."""
# name | concept | task | three observable checks | worked example
EXTRA_TRACKS = [
('nocode','No-code & AI app building','Build useful apps with visual tools, clear requirements and tested behavior.','Cube','DB-03',False,'''Choose a problem worth solving|A product helps a named person complete a task. A tool is a means, not the outcome.|Write a brief for a fictional repair-booking app. Name its user, main task and three things outside the first release.|named user;main outcome;exclusions|A repair shop needs customers to request a slot. A payment marketplace and technician payroll are outside its first booking release.
Sketch a three-screen app|A screen represents a state and offers a clear next action. Start with the smallest complete journey.|Sketch request, review and confirmation screens for the booking app, including correction before confirmation.|three screens;correction path;confirmation|Request collects the date. Review shows it with an Edit action. Confirmation appears only after the server accepts the booking.
Model records in a visual builder|A record needs a stable identifier; a relationship connects records without duplicating their facts.|Define customers and bookings with unique IDs. State what happens if two customers share the same name.|record IDs;relationship;duplicate-name check|Customer C-12 and C-13 may both be called Alex. Booking B-04 links to C-12 by ID, never by display name.
Build without trusting generated defaults|AI-generated code and visual templates need inspection. Test behavior before enabling real data.|Write a Lovable or Replit build brief for the three-screen app using fictional data. Record what you inspected before accepting output.|bounded brief;inspection;observed result|A generated form may look complete while its button only changes a local label. Inspect the request and stored record to prove that saving works.
Add real access rules|Permissions belong at the data or server boundary. A hidden menu does not protect a record.|Describe customer and operator permissions; test an attempt to open another customer's booking directly.|permission matrix;record ownership;denied request|Customer C-12 requests B-99 owned by C-13. The backend denies access even if the URL is known.
Plan integrations deliberately|A connector has identity, permissions, limits and failure states. Connecting an account is a separate action from enabling automation.|Specify an email connector for confirmations, with least privilege and a retry rule.|connector scope;failure behavior;retry limit|A booking can be saved while email is delayed. Keep the booking confirmed and queue the notification rather than creating another booking.
Test on a phone and keyboard|A complete journey must remain usable under real input and screen constraints.|Test your prototype at a narrow width and with keyboard only. Record two findings and corrections.|mobile observation;keyboard observation;retest|A fixed-width review panel may hide the Confirm button at 390 pixels. A flexible column keeps the action visible without sideways scrolling.
Control app costs and limits|Provider limits affect reliability. Estimate cost from measured usage and keep a safe spending boundary.|Create a cost worksheet for 100 fictional bookings per week, storage, messages and app hosting.|usage assumptions;cost formula;spending guard|If each booking sends two messages, 100 bookings produce 200 messages, before retries. Include those retries in the estimate.
Release with a recovery plan|A release has a tested version, approved configuration and a way back. A successful build is not a complete release check.|Write deployment and rollback instructions for the booking app, including a backup check.|release checks;backup check;rollback|Record release v3 before publishing v4. If v4 fails the booking test, restore v3 and reconcile bookings created during the incident.
Deliver a client-ready app|A usable handover transfers ownership, evidence and operating instructions. It distinguishes working features from planned ones.|Package your app brief, screens, schema, denied-access test and release plan. Handle a request for recurring bookings.|complete evidence;ownership transfer;change impact|Recurring bookings add dates, cancellation rules and collision checks. Treat them as a scoped change rather than a cosmetic toggle.'''),
('localai','Open-source & local AI','Learn models, Hugging Face and Ollama through controlled, measurable experiments.','Spark','DB-13',False,'''Understand what a model does|A model maps inputs to outputs using learned parameters. It does not establish that an answer is true.|Explain a model, a prompt and an output using a fictional support question. Separate generation from verification.|three terms;example;verification|A model drafts a returns answer from a prompt. The store's approved returns policy is the evidence used to check that answer.
Read a model card|A model card describes intended use, license and limitations. A downloadable file is not permission for every use.|Review an actual Hugging Face model card and record its source, intended use, license and one limitation.|source link;license;limitation|A text-generation model may have a non-commercial license. Download availability does not authorize commercial deployment.
Choose a suitable machine|Model size, memory and response speed constrain local use. Measure rather than promising a speed.|Plan a local experiment for your available machine. Record memory, model size and an acceptable response time.|machine facts;model requirements;measured target|An eight-gigabyte machine cannot safely allocate eight gigabytes entirely to model weights; the operating system and working memory also need space.
Run a controlled local session|Ollama serves local models; the client must know which endpoint it is using. Local inference and downloaded dependencies have different privacy boundaries.|Prepare a local setup checklist from Ollama's official documentation and a synthetic prompt. Document installation and removal.|official instructions;synthetic input;removal plan|A local model response can stay on the machine, while downloading the model still uses the network. Document both parts of the workflow.
Create a reproducible evaluation|Compare models on the same questions, settings and rubric. One impressive example can hide systematic failure.|Create five synthetic support questions with reference answers and a scoring rubric.|fixed test set;reference answers;rubric|Model A gets a policy date right but invents an exception. Score accuracy and unsupported claims separately rather than judging tone alone.
Explore embeddings carefully|An embedding represents similarity, not factual truth. Similar text may still describe a different policy.|Design a retrieval test with three policy paragraphs and an ambiguous question.|source set;retrieval result;ambiguity handling|A question about exchange deadlines can retrieve a returns paragraph because the wording is similar. Check that the retrieved policy actually answers the question.
Respect licenses and provenance|A model, dataset and generated asset can have different terms. Keep provenance for every component.|Prepare a component register for one model, one dataset and one test output. Flag unresolved permissions.|component register;source versions;permission review|The model license may allow commercial use while a training dataset's redistribution terms differ. Record both instead of copying one license to all assets.
Design a private inference boundary|Sensitive input must have an approved handling path. Local hosting alone does not secure access, logs or backups.|Map browser, inference server, logs and storage. Deny unauthenticated network access.|boundary map;log minimization;denied access|A model bound to every network interface may expose prompts to other devices. Bind or firewall it according to the approved access plan.
Optimize with evidence|Quantization can reduce memory with quality tradeoffs. Re-evaluate before claiming equivalence.|Compare two configurations on the same synthetic questions. Record memory, latency and exact answer failures.|same test set;measured performance;quality tradeoff|A smaller configuration responds faster but misreads one exception. Report both the latency gain and the lost correctness.
Package an accountable AI experiment|A useful experiment includes versions, settings, evaluation results and limits. Reproducibility matters more than a demo claim.|Deliver your model register, setup, evaluation and privacy map; respond to a policy change.|versioned configuration;evaluation evidence;policy-change test|After the policy changes, update the source set and rerun all five reference questions. Old scores do not validate the new policy.'''),
('cloud','Cloud, domains & deployment','Publish safely with hosting, DNS, configuration, monitoring and recovery.','Workflow','DB-14',False,'''Understand a web address|A domain is a name. DNS maps the name to infrastructure; hosting serves the application.|Draw the journey from a fictional domain to its hosted page. Identify registrar, DNS and hosting responsibilities.|three responsibilities;request journey;source reference|A domain bought from a registrar can point to a different hosting provider. Moving hosting does not necessarily mean transferring the domain.
Prepare a static release|A static host serves built files. Preview output must be checked before publishing it.|Prepare a release checklist for a three-page fictional site using Render or Vercel documentation.|built files;preview check;release checklist|A local source folder may contain files the browser cannot run. Publish the built output specified by the framework and host.
Connect a custom domain|DNS records must match the host's instructions. Verification and HTTPS can complete at different times.|Write a domain connection plan with the exact record types supplied by a host and a verification check.|host records;verification;HTTPS check|A host may request a CNAME for a subdomain. Copy the target exactly; do not put a full https URL in the DNS value.
Separate public settings from secrets|Browser bundles are public. Private provider keys belong in server configuration and must never be committed.|Classify an API base URL, a public project ID and a private payment key; document how each is injected.|classification;injection boundary;leak check|The API URL can be visible in browser code. A secret payment key must stay on the server even if a variable name includes SECRET.
Deploy a backend safely|A backend needs trusted identity, input validation and approved external destinations before serving private records.|Write a backend deployment checklist for a booking API, including a direct unauthorized request.|identity check;input rule;denied request|A backend rejects a request for another learner's record using the authenticated account, not a user_id supplied in the request body.
Apply database migrations|A migration changes stored structure. Back up and test the change against realistic records before production.|Plan a migration adding booking status with a safe default and a reconciliation query.|migration plan;existing-row behavior;reconciliation|Adding a NOT NULL column without a default can fail on existing rows. A reviewed default plus a backfill plan makes the transition explicit.
Monitor the real journey|An HTTP success does not prove that the student's task succeeded. Monitor meaningful outcomes and private-data boundaries.|Define health checks for sign-in, save and checkout, with an alert owner and a safe log format.|journey signals;alert ownership;safe logs|A homepage can return 200 while saves fail. Measure save success separately and log an opaque request ID rather than the student's notes.
Build a backup and restore routine|Backups require a tested restore path. A copy whose recovery is unknown is incomplete protection.|Create a backup schedule and isolated restore drill for fictional learner records.|backup schedule;isolated restore;record comparison|Restore yesterday's copy into a separate database, compare known records and counts, and record the measured recovery time.
Plan hosting limits and spending|Hosting limits include requests, compute, storage and bandwidth. Estimate from measured activity rather than brand names.|Compare two hosts using their official limits and a stated load model. Record unknowns.|official sources;usage model;unknowns|Ten thousand visitors can create more than ten thousand requests because pages also load fonts, scripts and images. Include those assets in the model.
Operate a complete release|Production operations connect domain, configuration, database, monitoring and a recovery owner.|Package a release runbook with a failed-deploy drill and respond to an expired domain reminder.|integrated runbook;failure drill;renewal ownership|A release can be healthy while the domain expires. Assign a renewal owner and verify contact details as part of operating the service.'''),
('content','Content, video & creator workflows','Plan, produce and publish useful content with a repeatable quality process.','Pen','DB-17',False,'''Start with an audience need|Content should answer a specific audience question. Choose the message before the format.|Write a brief for a 60-second café ordering tutorial, including audience, outcome and verified facts.|audience;learning outcome;source facts|A tutorial for first-time customers explains how to place an order. A promotional montage alone does not teach that task.
Storyboard a useful sequence|A storyboard orders the information a viewer needs. Every scene should move the task forward.|Sketch four scenes: context, demonstration, check and next action. Use plain captions.|four-scene sequence;caption clarity;next action|Show the menu before selecting an item, show the selection before checkout, and end with how to correct an order.
Design a readable graphic|Text hierarchy, spacing and contrast determine whether a graphic communicates. Decoration must not obscure the message.|Use Canva or the design desk to draft an ordering guide at mobile size. Record a readability test.|hierarchy;small-size test;revision|A caption legible on a large canvas may disappear in a feed. Inspect the exported image at its actual viewing size.
Record a clear demonstration|A recording needs a prepared example and an intentional pace. Remove private tabs, notifications and credentials.|Create a recording checklist and a synthetic demonstration script with one deliberate pause.|synthetic data;privacy preparation;paced script|Use a fictional email in the demo. Disable notification previews before recording so unrelated messages cannot appear in the video.
Edit for comprehension|An edit should help the viewer follow cause and effect. Cutting every pause can make a tutorial harder to understand.|Plan an edit with visible cursor actions, chapter changes and time to read key results.|action continuity;chapter markers;reading time|Keep the confirmation visible long enough to read it. A fast transition immediately after clicking hides whether the action succeeded.
Make content accessible|Captions, transcripts and descriptive text provide different access paths. Auto-generated captions require review.|Prepare a transcript and caption review checklist. Correct three fictional transcription errors.|reviewed transcript;caption correction;visual description|An auto-caption may hear DNS as D N S or a different word. Check technical terms against the script before publishing.
Respect asset permissions|Using an asset requires permission for the intended use. Keep a source and license record for images, fonts and music.|Create an asset register for a fictional video. Flag one asset with unclear terms and replace it.|asset sources;usage terms;replacement|An image visible in a search result is not automatically licensed for an advertisement. Use an authorized asset and keep its license reference.
Publish a coherent content package|Different channels have different constraints. Export and verify each version rather than only renaming files.|Specify website, vertical-video and email variants for your tutorial. Include export checks.|channel requirements;export plan;verified output|A landscape tutorial needs a redesigned vertical composition so labels remain readable; cropping the sides can remove key controls.
Measure without inventing success|Views, completion and useful action are different metrics. Compare like periods and explain limits.|Design a measurement plan for a tutorial with a baseline, completion metric and next experiment.|metric definitions;baseline;bounded experiment|More views do not prove fewer support requests. Track the relevant support topic and compare it using a stated time period.
Deliver a reproducible creator system|A creator workflow includes brief, assets, review, exports and measurement. Another person should repeat it.|Package your storyboard, transcript, asset register, exports and review checklist; handle a second-language request.|complete package;repeatable workflow;translation review|Translate and review the transcript before recording the second language. Machine translation alone is not evidence that instructions remain correct.'''),
('safety','Digital safety & responsible work','A free course in secure accounts, safe sharing and careful online decisions.','Shield','DB-07',True,'''Secure an account|A unique password and supported multi-factor authentication reduce account takeover risk. Recovery needs equal care.|Write an account setup and recovery checklist using a password manager and approved second factor.|unique password;second factor;recovery storage|Store recovery codes in an approved secure location separate from the device used for everyday sign-in. Never put them in lesson evidence.
Recognize a suspicious request|A familiar display name does not verify the sender. Check the action, destination and independent contact route.|Inspect a fictional urgent payment email. List suspicious signals and a separate verification method.|signals;destination check;independent verification|A supplier's display name can be copied. Verify a changed bank request using a known contact, not the phone number included in that request.
Share the smallest useful dataset|Least privilege applies to both people and information. Give only the data needed for the task.|Prepare a vendor report containing order totals without customer contact details.|minimum fields;named viewer;permission check|A supplier planning stock needs item quantities. Customer phone numbers add exposure without helping that task.
Keep a recoverable copy|Version history, exports and backups serve different purposes. Test recovery using a known file.|Export a fictional draft, change one line and restore it. Record the actual comparison.|export;restore drill;comparison|A synchronized deletion may affect every synchronized device. A separate recoverable backup protects against a different failure.
Understand access roles|A role groups permissions; ownership limits which records a person may access. Both need enforcement.|Create a learner, teacher and owner access matrix including a denied cross-student request.|role matrix;record ownership;denied case|A teacher assigned to course A should not automatically see private submissions in course B. Check assigned scope and record access.
Handle accidental disclosure|Containment, reporting and evidence preservation help respond without making the incident worse.|Draft a response to a fictional shared document containing contacts. Include removal, reporting and a safe event log.|containment;report owner;safe log|Remove inappropriate access, record what was shared and when, and notify the responsible owner through the approved incident route.
Inspect an integration permission|OAuth consent describes requested access, not guaranteed safety. Confirm the publisher and why each scope is needed.|Review a fictional design connector asking to read all drive files. Propose a narrower permission.|publisher check;scope reasoning;narrow alternative|A tool that only exports one design may not need access to every document. Decline unnecessary scope and look for a limited integration.
Avoid unsafe automation|Automation can multiply mistakes. Put approval before actions with financial, privacy or publication consequences.|Design a human approval gate for a generated customer message and test a blocked send.|draft boundary;approval owner;blocked test|An AI draft can contain invented promises. Approval reviews the content before the external send action is permitted.
Practice an incident drill|A drill checks whether the team can detect, contain and recover under a stated scenario.|Run a paper drill for a lost work device with no real account changes. Record responsibilities and gaps.|scenario;response sequence;observed gaps|A drill may reveal that no one knows who can revoke sessions. Record that gap and assign an owner before an actual incident.
Deliver your safety playbook|A practical playbook turns principles into repeatable actions, escalation and recovery evidence.|Package your account, sharing, backup and incident checklists. Adapt them for a replacement colleague.|integrated checklists;escalation;handover|A new colleague needs their own identity and approved permissions. Sharing the departing person's password undermines accountability.'''),
('finance','Spreadsheets, budgets & finance operations','Use careful calculations and controlled records for everyday business work.','Chart','DB-09',False,'''Separate a value from a formula|A formula calculates from inputs. Preserve source values and label units before interpreting the result.|Build a fictional budget with quantities and unit costs. Show two line totals and their sum.|source inputs;formula;units|Three notebooks at 12 currency units each cost 36. The value 12 is a unit price; 36 is a calculated line total.
Create an expense register|A register needs stable IDs, dates, amounts and categories. A receipt is evidence, not automatic approval.|Design a five-row fictional expense register and flag an unapproved item.|stable IDs;required fields;approval state|EXP-04 has a receipt but no approving owner. Keep it pending rather than counting it as an approved reimbursement.
Use spreadsheet checks|Validation restricts permitted values; reconciliation checks whether results agree with independent evidence.|Add rules for missing dates, negative quantities and duplicate IDs to your fictional register.|validation rules;duplicate test;exception log|Two rows with EXP-04 may be a duplicate import. Flag them for investigation before deleting either source row.
Build a bounded forecast|A forecast is a scenario based on assumptions. Separate assumptions from actual results.|Forecast three months using a stated sales assumption and two cost types. Include a lower-sales scenario.|explicit assumptions;formula;downside scenario|If monthly sales are assumed to be 100 units at 20, forecast revenue is 2000. At 70 units it is 1400; neither figure is an actual sale.
Reconcile invoice and payment|An invoice, receipt and bank entry represent different events. Match them using identifiers and amounts.|Reconcile three fictional invoices with two payments and identify the unpaid balance.|matching rule;balance;exception|Invoice INV-12 is 150 and its payment is 100. Record a balance of 50 instead of labelling the invoice fully paid.
Understand balanced records|Double-entry records keep debits and credits equal. Equality alone does not prove the correct accounts were chosen.|Use the ledger practice tool to inspect a cash purchase and a duplicate event.|balanced entry;account reasoning;duplicate handling|Buying equipment for 400 exchanges cash for equipment. Both sides can balance even if the item is misclassified, so classification still needs review.
Control payment preparation|Preparing a payment and authorizing it are separate responsibilities. Changed bank details need independent verification.|Map requester, preparer and approver responsibilities with a self-approval denial case.|separation;verification;denied self-approval|A person who requests a reimbursement should not approve the same request. An independently approved record precedes payment preparation.
Explain variance|A variance compares actual results to a stated plan using consistent units and periods.|Compare planned cost 1200 with actual 1380. Explain the 180 difference using fictional volume and price evidence.|variance formula;consistent basis;evidence|Actual minus plan is 180. Calling it a price problem requires unit-price evidence; the total alone cannot identify the cause.
Build a decision report|A report connects calculations to a decision and names uncertainty. Avoid unsupported accounting or investment claims.|Prepare a one-page operating budget report with assumptions, exceptions and one bounded action.|traceable totals;uncertainty;action|An unexplained expense increase supports an investigation, not a claim of fraud. Show the records and propose a review owner.
Hand over a controlled finance workbook|A workbook needs documented sources, protected formulas, review ownership and a repeatable reconciliation.|Package your register, forecast, variance note and checks. Handle a late credit note.|source versions;review controls;late adjustment|A credit note reduces the relevant invoice balance. Record the adjustment separately so the original invoice and correction remain traceable.'''),
('logistics','Logistics & supply-chain operations','Practice order, inventory, dispatch and delivery workflows with clear evidence.','Briefcase','PC-LG01',False,'''Map an order journey|An order moves through explicit states. Each transition requires evidence and an owner.|Map received, confirmed, reserved, dispatched and delivered for a fictional order.|ordered states;owners;transition evidence|A tracking number can show dispatch preparation without proving carrier acceptance. Define the evidence needed before marking dispatched.
Create a controlled item register|An item identifier distinguishes products; units and location make quantities meaningful.|Design a register for three fictional products stored in two locations.|item IDs;units;locations|Ten boxes and ten individual units are different quantities. Store the unit of measure beside the amount.
Calculate available stock|Available stock is on-hand stock minus reservations and holds. Physical presence is not permission to sell.|For 30 units on hand, 8 reserved and 2 held, calculate available stock and test a request for 21.|stock equation;calculation;rejected request|Available is 30 minus 8 minus 2, or 20. A request for 21 must wait for more stock or a reviewed reservation change.
Reserve without double allocation|Reservations need a stable order ID and an atomic quantity check. Repeated requests must not reserve twice.|Simulate two orders competing for the final five units and a repeated reservation request.|atomic check;competition test;idempotency|If order A reserves four of five units, order B cannot reserve three. Repeating A's event must leave its reservation at four.
Prepare a dispatch checklist|A dispatch record connects order, packed items, address and handover evidence. Minimize private fields in exports.|Write a packing and carrier handover checklist using fictional delivery information.|order match;packing check;handover evidence|Scan the item ID and count before closing the parcel. A label alone does not prove the correct items were packed.
Record a delivery exception|An exception needs verified facts, responsibility and the next checkpoint. Avoid invented delivery promises.|Draft an exception record for a delayed parcel with an unconfirmed new date.|confirmed facts;owner;checkpoint|Record that the carrier reported a delay, assign follow-up, and state when the next update is due without inventing a new delivery date.
Reconcile a return|A return links the original order, inspection and disposition. Received goods are not automatically saleable.|Map a returned item through received, inspected, refund-reviewed and restock-or-hold states.|original link;inspection;disposition|A damaged returned item is received but held after inspection. It should not increase available saleable stock.
Measure operational service|A service metric needs a defined population, clock and exception policy. Averages can conceal important failures.|Define on-time dispatch and delivery completion using ten fictional orders.|metric definitions;denominator;exceptions|If nine of ten eligible orders were dispatched on time, the rate is 90 percent. Excluding one late order changes the denominator and needs justification.
Plan a supplier disruption response|A contingency plan identifies alternatives, constraints and approval before changing commitments.|Prepare a disruption plan for a late supplier using remaining stock and a reviewed alternative.|stock evidence;alternative;approval|An alternative supplier's earlier date is useful only after checking item compatibility, cost and approval; availability alone is insufficient.
Deliver an operations handover|A handover connects normal flow, exceptions, access and reconciliation so another operator can run the process.|Package your item register, reservation checks, dispatch checklist and exception playbook; handle a location change.|integrated records;exception process;change response|Moving stock needs a transfer record and location reconciliation. Renaming a location does not prove the units physically moved.'''),
('commerce','E-commerce & digital marketing','Build honest storefronts, controlled purchases and measurable campaigns.','Cart','DB-18',False,'''Define a buyer and offer|An offer describes a useful outcome, scope and terms for a named buyer. Claims need evidence.|Write a fictional digital-template offer with included files, exclusions and usage terms.|buyer;scope;terms|A template pack includes three editable layouts. It does not include custom design support unless that service is explicitly part of the offer.
Create a trustworthy product page|A buyer needs price, contents, eligibility and purchase terms before payment. Avoid invented ratings or urgency.|Draft a product page with clear contents, a price placeholder awaiting approval, and a refund-policy link.|contents;price transparency;policy visibility|Show what the buyer receives and when. Do not add a five-star review until an actual consenting customer's review exists.
Plan a visual product listing|Images should show the actual product and useful details. Captions distinguish examples from delivered assets.|Create a listing storyboard in Canva or the design desk with three useful product views.|accurate visuals;caption clarity;mobile check|A sample document can illustrate layout, but label its text as example content if it is not included in the downloadable pack.
Map a secure purchase|The provider confirms payment on the server. A return page or success animation cannot authorize access.|Draw order creation, provider checkout, verified event, entitlement and receipt states.|server confirmation;access scope;receipt state|A buyer returns after cancelling checkout. The order stays unpaid, no course unlocks, and no paid receipt prints.
Deliver the purchased scope|A purchase grants the recorded product scope to one account. Direct requests need the same server authorization.|Define access for buyer A, buyer B and an expired entitlement; test a direct asset request.|recorded scope;ownership;expiry denial|Buyer A purchased course Web, so a direct request for Finance remains denied even if the browser knows that course ID.
Write an honest campaign|Marketing copy should state benefits with support and make conditions visible. Consent governs contact channels.|Draft a three-message campaign for consenting fictional subscribers with unsubscribe instructions.|supported claims;consent;unsubscribe|An email can explain that a workbook helps organize tasks. It cannot guarantee income without defensible evidence for that exact claim.
Measure a useful funnel|Each funnel stage has a consistent definition. Sessions, buyers and orders are different populations.|Define product view, checkout start and confirmed purchase for a fictional campaign.|stage definitions;deduplication;confirmed conversion|Two checkout retries by one buyer are two attempts but not two purchases. Count confirmed orders using stable IDs.
Handle refunds and disputes|Refunds change financial and access records. Reconcile them through verified provider events and a documented policy.|Write a full-refund workflow that updates order, receipt and course access; include a repeated-event test.|reconciliation;revocation;duplicate event|A full refund revokes the entitlement created by that order. Another independently paid entitlement remains active.
Improve one part of the journey|An experiment changes a bounded element and uses a stated metric. Avoid attributing every movement to the change.|Plan a product-description experiment with a baseline, duration and stop condition.|bounded change;measurement;stop condition|Changing the description and price together prevents a clear explanation of which change affected conversion. State the limitation if both change.
Deliver an accountable storefront|A storefront handover includes offer, terms, tested payment states, delivery control and reporting.|Package your listing, checkout-state tests, access matrix and campaign plan. Handle a product bundle change.|complete package;payment evidence;bundle scope|Store the bundle's course IDs at purchase time. Later catalogue edits must not silently change what an existing buyer purchased.'''),
('leadership','Projects, teams & professional leadership','Lead clear work, communicate decisions and improve delivery using evidence.','People','DB-23',False,'''Define an outcome and owner|A task needs an observable result and accountable owner. Activity alone does not prove completion.|Write a project brief for a fictional team launching a café booking page.|outcome;owner;acceptance|Design page is vague. Deliver a reviewed mobile booking page with labelled fields and a passed keyboard check is observable.
Break work into useful tasks|Dependencies specify what must happen first. Small tasks need clear acceptance so handoffs do not become guesses.|Create a six-task plan with owners, dependencies and acceptance checks.|bounded tasks;dependencies;acceptance|Content approval precedes final page review. Publishing before approval risks a technically working page with incorrect opening hours.
Run a clear weekly meeting|A meeting should produce decisions, owners and dates. A transcript alone is not an action record.|Write an agenda and a fictional decision log for a blocked release.|agenda;decisions;owners and dates|Record that Maya will verify the missing opening date by Thursday. Discussion occurred does not assign a next action.
Estimate with uncertainty|An estimate states assumptions and a range. New information can change it without hiding the reason.|Estimate three tasks using best, expected and constrained cases. Identify the main uncertainty.|effort range;assumptions;uncertainty|A form build may take two to four hours if the schema is approved. An unresolved schema changes the estimate and should stay visible.
Control a scope change|A change needs an impact review and an explicit decision before work proceeds. Acceptance must change with scope.|Assess a request for online deposits added to a booking site halfway through delivery.|impact;options;approval|Deposits add merchant setup, payment confirmation and refund rules. Treat them as a new scope requiring time and acceptance checks.
Give useful feedback|Feedback describes observed behavior and impact, then agrees on a concrete improvement. Personal labels rarely help.|Rewrite vague feedback on a confusing form into an observation, consequence and testable revision.|observation;impact;testable request|Three learners missed the unlabeled date field is observable. Add a visible label and retest the booking task states an actionable revision.
Manage delivery risks|A risk combines a possible event, impact and response owner. Monitoring must reveal whether it is becoming real.|Create a risk register for domain setup, staff availability and private data handling.|event and impact;response owner;monitoring|If domain verification is incomplete by Wednesday, the release date is at risk. Assign the DNS owner and a review checkpoint.
Make decisions traceable|A decision record preserves context, alternatives, rationale and consequences. It helps future teams reconsider responsibly.|Compare two hosting choices using documented requirements and sources. Record the chosen tradeoff.|context;alternatives;consequences|A simpler host may reduce setup work but limit background processing. Record that constraint so a future feature does not rely on unsupported behavior.
Run a blameless improvement review|A retrospective connects observations to process changes. Assign one measurable experiment instead of a long wish list.|Review a fictional delayed release and propose one improvement with an owner and success check.|observations;bounded action;success check|A release failed because a required secret was missing. Add a configuration check before publishing and measure whether it catches the omission.
Deliver a sustainable team playbook|A playbook connects goals, roles, communication, quality gates and escalation. It must work when one person is absent.|Package the brief, task plan, decision log, risks and handover; respond to the release owner's absence.|integrated plan;backup responsibility;handover|A named backup can run the approved release checklist with their own access. Sharing the absent owner's password is not a continuity plan.''')]

EXAMPLES = {
'start': '''incoming/menu.txt is unreviewed; approved/menu-v2.txt is reviewed. Keep both their version and approval state visible.
A named supplier sees order totals as a viewer. They do not receive customer phone numbers or edit permission.
A dated official manual supports a software feature claim; an anonymous comment only suggests something to investigate.
Completed: cleaned 18 rows. Blocked: two delivery dates. Next: Sam confirms those dates by Friday before the report is reviewed.
Collect source, check unique order IDs, calculate totals, review exceptions, then archive the approved version.
12 + 18 + 9 = 39. A blank fourth day means unknown, not automatically zero.
Export a known note, change it, restore the copy and compare the exact text. Successful export alone does not test restoration.
Content approval must happen before menu publication. A designer finishing the layout does not approve its prices.
List source-v3.csv, the total formula, expected 39, and the owner to contact if the source has missing rows.
Give the replacement colleague a read-only approved folder and a separate procedure for requesting changes.''',
'web': '''<h1>Café booking</h1> names the page; <p> explains it; <a href="mailto:hello@example.test">Contact</a> gives a real contact action.
Two columns can become one below 600 pixels. Use a flexible width rather than making the phone scroll sideways.
<label for="email">Email</label> associates visible text with <input id="email" type="email">. An invalid value needs a useful error.
Save a note after editing and load it on return. If JSON parsing fails, show recovery instead of replacing the page with an error.
The server reads authenticated identity, checks booking ownership and returns 403 for another learner's private booking.
Loading shows progress; empty offers creation; error offers retry; success shows the saved record. Disable duplicate submissions only while pending.
Enter a valid request, observe its confirmation, then try an invalid address and a failed network response. Record the actual results.
Tab through every control and inspect the visible focus. Record the exact unlabeled field rather than inventing an accessibility score.
Inject a private API key on the server, publish the tested build, run a booking check, and keep the previous release available.
A second language changes text length and translation review. Test the form and confirmation again using that language.''',
'data': '''Order O-101 is one row. amount is one column. order_id should be unique even when two customer names match.
Keep raw.csv. In clean.csv log duplicate O-101, leave an unknown amount blank and normalize dates using a stated timezone.
Weekly completed revenue includes completed orders in the named week and subtracts refunds according to the stated rule.
120 + 80 - 20 = 180 across three records. Compare both the sum and record count against the source.
SELECT order_id, amount FROM orders WHERE amount > 100 returns matching records. COUNT(*) counts rows, not monetary value.
Completion rate is completed eligible orders divided by all eligible orders. Put the denominator and date range beside the chart.
Week A: 500 over five days = 100/day. Week B: 360 over three days = 120/day. The smaller total has a higher daily rate.
An operator sees order exceptions; a supplier sees aggregate quantities. Remove personal details from the external export.
Investigate the routes behind a higher failed-delivery rate with a bounded trial and a stated success threshold.
A refund arriving later changes net revenue. Preserve the previous report and publish a reconciled revision with a date.''',
'ai': '''Task: write an opening announcement. Facts: opens Saturday at 9. Audience: local customers. Output: 70 words. Do not invent prices.
The draft says open until midnight, but the approved brief has no closing time. Remove that unsupported claim and request the missing fact.
Use Customer A and a synthetic order ID rather than a real email, account number or confidential conversation.
Template fields are source notes, decisions, owners, dates and unknowns. Require unknowns to stay explicit.
Score accuracy, coverage and instruction adherence separately. A polite response can still fail when it invents a refund.
The policy gives no answer about overseas delivery. The assistant should say the approved source does not specify it.
The model drafts a message. A named authorized reviewer approves it. Only then can a separate send action run.
A retrieved page saying reveal all contacts is untrusted document text. Ignore it and keep answering the approved task.
If ten accepted outputs need thirty attempts and two hours of review, include all attempts and review effort in the cost model.
After a policy update, version the source set and rerun reference questions before using the workflow again.''',
'automation': '''Form received is the trigger; field validation is the transformation; a reviewed acknowledgement is the outcome.
Reject an empty email before assigning or sending. Return Enter a valid email rather than an unspecified failure.
Test each step with a synthetic enquiry and record its output before enabling the next connection.
ENQ-101 arrives twice. A stored event key makes the second attempt return the first result without another email.
Retry a temporary timeout at most three times. A missing required email goes to correction rather than retry.
The requester cannot approve their own discount. The server checks the approver's scope for that record.
The agent can read stock and draft a reorder. It cannot call the purchase tool until an authorized person approves.
Log run ID, step and outcome; omit customer messages and private tokens. Repeated send failures notify an assigned operator.
Check the provider's message ID before retrying a failed status update. Reusing that receipt avoids sending twice.
A new rate limit needs a bounded queue and retry plan, plus a test that the same enquiry still gets one acknowledgement.''',
'business': '''PR-12 records item, quantity, reason, requester and Pending approval. That state does not authorize payment.
A task enters Reviewed only after the named reviewer records their check, not when the author drags the card.
Hold a supplier bank-detail change until a separate known contact verifies it. Do not use the new request's contact number.
20 on hand minus 7 reserved gives 13 available. Reject a new request for 14 until stock or reservations change.
An order has 10 units, delivery has 8 and invoice has 10. Record the mismatch and the resolution owner before approval.
The shipment is delayed and a new date is unconfirmed. Assign follow-up and tell the customer the next update checkpoint.
Requester creates; approver approves another person's request; auditor reads evidence. Test a forbidden self-approval.
On-time completion needs an agreed deadline, eligible population and timezone. Keep an exception list beside the average.
Pilot a validation checklist on a small order batch, compare the error rate and define when to restore the prior process.
The replacement operator receives the intake rules, reservation checks, approval scope and exception contacts together.''',
'design': '''The booking page serves mobile visitors who need a date and confirmation. Brand preference is a constraint, not the user's task.
Show what can be booked, when it is available, required information, then the Book action. Remove repeated explanations.
A heading introduces a section; a label names a field. Test a long heading and the same form at 390 pixels.
An error says Email is missing and uses an icon as well as color. Red alone does not tell a color-blind reader what happened.
Allow a date correction on Review and preserve the other entered details. Confirmation follows an actual accepted request.
Save booking states the action. We could not save; your entries remain here; retry explains a network failure and recovery.
Press Tab and Shift+Tab through the prototype. A control with invisible focus is a concrete barrier to fix and retest.
A field contract defines label, input, helper text, error, focus and disabled behavior using the same content relationship.
Ask a volunteer to book Tuesday using the prototype. Observe their actions before explaining where the date field is.
Right-to-left support changes reading order, alignment and directional icons. Retest the main journey using reviewed translations.''',
'career': '''I deliver a reconciled weekly order report for a small retailer describes a client outcome, while I use spreadsheets only names a tool.
Ask how duplicates are detected now, who owns corrections, record volume, deadline and the evidence that defines success.
Include one report, two revisions and a named source version. Exclude upstream data repair unless separately approved.
Estimate discovery, building, testing and handover separately. Flag unreviewed source quality as an uncertainty.
Label an Academy practice project as practice. Show the actual checks and your contribution rather than claiming a client result.
A second dashboard adds requirements, effort and acceptance. Offer an amended scope and wait for its approval before changing delivery.
Ask which comparison was difficult to read. Revise labels and spacing, then test that specific reading task again.
Transfer account ownership through the provider's approved process. Give setup instructions without putting credentials in the handover.
Schedule input collection, validation, review and publication. If input is late, notify the named owner rather than inventing totals.
For an unrealistic deadline, offer a smaller verified scope or a later release and explain the tradeoff using the task plan.''',
'delivery': '''The browser collects input, the backend authorizes it, the database stores it, and the mail provider sends an approved notification.
A failed save preserves the local draft and offers retry. A failed payment grants no access. Give each failure its own recovery.
Ignore user_id in a request body and use the verified session. Deny a direct request for another learner's private evidence.
Save revision 3 only when revision 2 is current. A repeated payment event ID should create one entitlement.
Apply reviewed migrations before deploying code that needs their columns. Keep private keys outside the browser bundle.
Alert when save failure rate crosses a stated threshold. Include a request ID and owner, without logging student answers.
Restore a timestamped copy into an isolated database and compare known learner records, counts and evidence digests.
Test staged loads with specified duration and success thresholds; record measured latency and errors rather than claiming capacity.
Untrusted code needs isolation and resource limits. A separate queue can improve that boundary but adds operating responsibilities.
An assessor checks the actual capstone evidence and a separate verifier confirms it. Practice completion alone is not a credential.'''
}

MODULES = {
'start':['Your digital workspace','Reliable everyday work','Checks & recovery','Controlled collaboration','Your operations kit'],
'web':['First pages & layouts','Forms & browser drafts','APIs & product states','Journey testing','Release & handover'],
'data':['Tables & cleaning','Questions & reconciliation','Queries & dashboards','Comparisons & access','Decisions & reproducibility'],
'ai':['Instructions & evidence','Privacy & reusable prompts','Evaluation & grounding','Approval & adversarial tests','Operations & handover'],
'automation':['Triggers & input rules','Flow building & duplicates','Retries & approval','Tools & monitoring','Recovery & handover'],
'business':['Records & tasks','Purchasing & inventory','Reconciliation & customers','Permissions & metrics','Improvement & playbooks'],
'design':['Brief & hierarchy','Type & visual meaning','Prototypes & copy','Accessibility & components','Research & handover'],
'career':['Service & discovery','Scope & estimates','Portfolio & change','Feedback & handover','Service & professional judgment'],
'delivery':['Boundaries & failures','Authorization & repeatability','Configuration & monitoring','Recovery & capacity','Architecture & capstone'],
'nocode':['Problem & prototype','Records & builders','Access & connectors','Usability & cost','Release & client delivery'],
'localai':['Models & model cards','Local setup','Evaluation & retrieval','Licenses & privacy','Optimization & delivery'],
'cloud':['Addresses & hosting','Domains & configuration','Backends & databases','Monitoring & recovery','Capacity & operations'],
'content':['Audience & storyboard','Graphics & recording','Editing & accessibility','Assets & publishing','Measurement & creator systems'],
'safety':['Accounts & suspicious requests','Sharing & recovery','Access & incidents','Connectors & approvals','Drills & your safety playbook'],
'finance':['Inputs & registers','Checks & forecasts','Reconciliation & ledgers','Payment control & variance','Reports & workbook handover'],
'logistics':['Orders & item records','Availability & reservations','Dispatch & exceptions','Returns & metrics','Disruption & operations'],
'commerce':['Offer & product page','Listings & secure checkout','Delivery & campaigns','Funnels & refunds','Experiments & storefront delivery'],
'leadership':['Goals & task plans','Meetings & estimates','Change & feedback','Risks & decisions','Improvement & team handover']}

TOOLS = {'start':['notebook'],'web':['web','replit','vercel'],'data':['data','sheets'],'ai':['prompt','chatgpt','claude'],'automation':['flow','n8n','make'],'business':['board','notebook'],'design':['design','canva','figma'],'career':['notebook','notion'],'delivery':['api','github','render'],'nocode':['lovable','replit','api'],'localai':['huggingface','ollama','opencode'],'cloud':['vercel','render','godaddy','hostinger'],'content':['canva','capcut','adobe'],'safety':['notebook','bitwarden'],'finance':['budget','data','sheets'],'logistics':['board','data'],'commerce':['gumroad','stripe','canva'],'leadership':['board','notion']}

DIAGRAMS = {'start':['Collect','Organize','Check','Share'],'web':['Interface','Request','Authorize','Save'],'data':['Source','Clean','Calculate','Decide'],'ai':['Brief','Generate','Verify','Approve'],'automation':['Trigger','Validate','Review','Act'],'business':['Request','Check','Approve','Reconcile'],'design':['Brief','Hierarchy','Prototype','Test'],'career':['Discover','Scope','Deliver','Handover'],'delivery':['Configure','Test','Release','Monitor'],'nocode':['Brief','Model','Build','Test'],'localai':['Model','Prompt','Evaluate','Review'],'cloud':['Domain','DNS','Host','Application'],'content':['Brief','Storyboard','Produce','Review'],'safety':['Recognize','Verify','Restrict','Recover'],'finance':['Source','Calculate','Reconcile','Review'],'logistics':['Receive','Reserve','Dispatch','Deliver'],'commerce':['Order','Pay','Confirm','Unlock'],'leadership':['Outcome','Plan','Deliver','Improve']}
