const fs=require('fs'),assert=require('assert'),vm=require('vm');
const C=JSON.parse(fs.readFileSync(__dirname+'/curriculum.json')),E=(require('../dist/engines.js'),globalThis.AcademyEngines);global.crypto=require('crypto').webcrypto;
const missions=C.programmes.flatMap(p=>p.modules.flatMap(x=>x.missions));assert.equal(C.programmes.length,48);assert.equal(missions.length,192);assert.equal(new Set(missions.map(m=>m.id)).size,192);assert.equal(C.stages.length,12);assert(C.products.every(p=>!p.purchasable));
let checked=0;for(const m of missions){assert.equal(m.lessons.length,3);const d={fields:{},actions:[],code:'',fileLog:[]};if(m.engine==='html')continue;
if(m.engine==='records')for(const f of m.fields)d.fields[f.key]=String(f.target);
if(m.engine==='document')m.sections.forEach((s,i)=>d.fields['section'+i]='A specific fictional delivery record, with decisions, source evidence, constraints and handover for review.');
if(m.engine==='api'){Object.assign(d.fields,{validation:true,ownership:true,idempotency:true,method:m.variant==='read'||m.variant==='access'?'GET':'POST',path:m.variant==='read'||m.variant==='access'?'/bookings/BK-100':'/bookings',actor:m.variant==='access'?'bob':'alice',body:JSON.stringify({customerId:'alice',service:'repair',quantity:1}),requestKey:'K1'});}
if(m.engine==='sql')d.code=m.variant==='all'?'SELECT * FROM orders':m.variant==='filter'?"SELECT id, customer FROM orders WHERE status = 'pending'":m.variant==='aggregate'?'SELECT SUM(quantity * unit_price) AS total FROM orders':"SELECT id, quantity FROM orders WHERE status = 'pending' ORDER BY quantity DESC";
if(m.engine==='permissions')for(const [r,acts]of Object.entries(E.permissionExpected))for(const[a,v]of Object.entries(acts))d.fields[r+'_'+a]=v;
if(m.engine==='ledger')Object.assign(d.fields,{debit:'100',credit:'100',eventId:'EVENT1',debitAccount:'Cash',creditAccount:'Revenue',deduplicate:true});
if(m.engine==='events')Object.assign(d.fields,{deduplicate:true,monotonic:true});
if(m.engine==='workflow')d.code=JSON.stringify({steps:['validate','deduplicate','human_approval','record_result'],maxRetries:2,retryDelaySeconds:5,deadLetterOwner:'Operations'});
if(m.engine==='uploads')d.fileLog=[{accepted:true,sha256:'a'.repeat(64)},{accepted:false,reason:'Unsupported extension'},{accepted:false,reason:'File exceeds limit'}];
const result=E.run(m,d);assert(result.pass,m.id+' '+JSON.stringify(result));assert(E.probe(m,d).rejected,m.id+' probe');if(m.engine==='ledger'){E.run(m,d);assert.equal(d.runtime.entries.length,1)}checked++;
}
assert.equal(E.calculate('=(100-20)*1.05'),84);assert(Number.isNaN(E.calculate('=1/0')));assert(Number.isNaN(E.calculate('=process.env')));assert.throws(()=>E.query('SELECT * FROM orders; DROP TABLE orders'));
const {parseHTML}=require(process.env.ACADEMY_DOM_MODULE||'linkedom');const {window}=parseHTML(fs.readFileSync(__dirname+'/../dist/workspace.html','utf8'));const memory={};Object.assign(window,{localStorage:{getItem:k=>memory[k]||null,setItem:(k,v)=>memory[k]=v},setTimeout:()=>0,clearTimeout:()=>{},confirm:()=>true,console,Blob,TextDecoder,URLSearchParams,location:{search:""}});const ctx=vm.createContext(window);for(const name of ['curriculum','engines','mentorship','mentor','services','app'])vm.runInContext(fs.readFileSync(__dirname+'/../dist/'+name+'.js','utf8'),ctx);
assert(window.document.getElementById('main').textContent.includes('learning'));let routes=0;for(const b of [...window.document.querySelectorAll('[data-view]')]){b.dispatchEvent(new window.Event('click',{bubbles:true}));assert(window.document.getElementById('main').innerHTML.length>150);routes++}assert.equal(routes,14);
let stageScreens=0;for(const m of missions){const b=window.document.createElement('button');b.dataset.action='open-mission';b.dataset.id=m.id;window.document.body.append(b);b.dispatchEvent(new window.Event('click',{bubbles:true}));b.remove();for(const stage of C.stages){const b=window.document.querySelector('[data-stage="'+stage+'"]');assert(b,m.id+' '+stage);b.dispatchEvent(new window.Event('click',{bubbles:true}));assert(window.document.getElementById('main').textContent.includes(stage));stageScreens++}}assert.equal(stageScreens,2304);const empty={fields:{},notes:{},stages:{},runs:[],probes:[],actions:[]};for(const stage of C.stages)assert(window.AcademyQA.gate(missions[0],empty,stage));
assert.equal(Object.keys(window.ACADEMY_MENTORSHIP).length,192);for(const lesson of Object.values(window.ACADEMY_MENTORSHIP)){assert.equal(lesson.steps.length,3);assert.equal(Object.keys(lesson.stages).length,12)}
console.log(JSON.stringify({stageScreens,mentorWalkthroughs:192,programmes:48,missions:192,lessonUnits:576,engineMissionChecks:checked,negativeProbes:checked,navigationRoutes:routes,browserRendering:'Not verified; DOM navigation only'}));
(async()=>{const{File}=require('buffer');assert((await E.validateFile(new File(['id,value\n1,100'],'case.csv'))).accepted);assert(!(await E.validateFile(new File(['bad'],'case.pdf'))).accepted);assert(!(await E.validateFile(new File(['x'],'case.exe'))).accepted);assert(!(await E.validateFile(new File([new Uint8Array(1024*1024+1)],'case.txt'))).accepted);console.log('Upload type, signature, hash and size checks passed')})().catch(e=>{console.error(e);process.exitCode=1});
