import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';import {createAPI,verifySignature,digest} from '../worker/api.mjs';
const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));
class Statement{constructor(q){this.q=q;this.args=[]}bind(...a){this.args=a;return this}async first(){return sql.prepare(this.q).get(...this.args)||null}async all(){return{results:sql.prepare(this.q).all(...this.args)}}async run(){const v=sql.prepare(this.q).run(...this.args);return{meta:{changes:Number(v.changes)}}}}
const DB={prepare:q=>new Statement(q),batch:async rows=>{sql.exec('BEGIN');try{const a=[];for(const row of rows)a.push(await row.run());sql.exec('COMMIT');return a}catch(e){sql.exec('ROLLBACK');throw e}}};const C=JSON.parse(fs.readFileSync('content/curriculum.json'));const api=createAPI(C),env={DB,ACADEMY_OWNER_EMAIL:'owner@example.test'};let checks=0;
async function call(path,method='GET',payload,user='learner',email=user+'@example.test',origin='https://academy.example.test'){const r=await api(new Request('https://academy.example.test/api/'+path,{method,headers:{...(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':email}:{}),origin,'content-type':'application/json'},...(payload?{body:JSON.stringify(payload)}:{})}),env);return{status:r.status,body:await r.json()}}
function expect(r,status){assert.equal(r.status,status,JSON.stringify(r.body));checks++;return r.body}
expect(await call('status','GET',null,null),401);expect(await call('status'),200);expect(await call('snapshot','PUT',{body:{version:2,drafts:{}},expectedRevision:0}),200);expect(await call('snapshot','PUT',{body:{version:2},expectedRevision:0}),409);assert.equal(expect(await call('snapshot','GET',null,'other'),200).body,null);expect(await call('snapshot','PUT',{body:{version:2},expectedRevision:1},'learner',undefined,'https://attacker.test'),403);
expect(await call('credentials','POST',{submissionId:'missing'}),409);expect(await call('checkout','POST',{productId:'DB-02'}),409);expect(await call('submissions','POST',{missionId:'DB-00-M01',evidence:{revision:1}}),400);
const evidence={revision:1,stages:Object.fromEntries(C.stages.map(s=>[s,{revision:1}])),lastRun:{pass:true,revision:1},fields:{evidenceAck:true},code:'fictional evidence'};const submission=expect(await call('submissions','POST',{missionId:'DB-00-M01',evidence}),201);assert(expect(await call('submissions','POST',{missionId:'DB-00-M01',evidence}),200).duplicate);expect(await call('submissions/'+submission.id,'GET',null,'other'),404);assert.equal((await call('submissions','GET',null,'owner')).body.items.length,1);
const staff={name:'Qualified person',domains:['DB-00'],qualification:'Checked professional experience, subject qualifications, sample review and conflict-of-interest evidence recorded by the owner.',expires:'2030-01-01'};
expect(await call('staff','POST',{...staff,userId:'r',role:'Reviewer'}),403);expect(await call('staff','POST',{...staff,userId:'owner',role:'Reviewer'},'owner'),400);expect(await call('staff','POST',{...staff,userId:'r',role:'Reviewer'},'owner'),200);expect(await call('staff','POST',{...staff,userId:'v',role:'Verifier'},'owner'),200);expect(await call('review','POST',{id:submission.id,action:'assign',reviewer:'learner',verifier:'v',version:1},'owner'),400);expect(await call('review','POST',{id:submission.id,action:'assign',reviewer:'r',verifier:'v',version:1},'owner'),200);
expect(await call('review','POST',{id:submission.id,action:'review',version:2,scores:[4,4,4,4,4],feedback:staff.qualification,approve:true}),403);expect(await call('review','POST',{id:submission.id,action:'review',version:1,scores:[4,4,4,4,4],feedback:staff.qualification,approve:true},'r'),409);expect(await call('review','POST',{id:submission.id,action:'review',version:2,scores:[4,4,4,4,4],feedback:staff.qualification,approve:true},'r'),200);expect(await call('credentials','POST',{submissionId:submission.id}),409);expect(await call('review','POST',{id:submission.id,action:'verify',version:3,feedback:staff.qualification,approve:true},'r'),403);expect(await call('review','POST',{id:submission.id,action:'verify',version:3,feedback:staff.qualification,approve:true},'v'),200);const record=expect(await call('credentials','POST',{submissionId:submission.id}),201);assert(expect(await call('credentials','POST',{submissionId:submission.id}),200).duplicate);expect(await call('credentials/'+record.id,'GET',null,'other'),404);expect(await call('revoke','POST',{id:record.id,reason:staff.qualification},'owner'),200);assert.equal(expect(await call('credentials/'+record.id),200).status,'Revoked');
const ticket=expect(await call('requests','POST',{kind:'Appeal',message:staff.qualification}),201);assert.equal(expect(await call('requests','GET',null,'other'),200).items.length,0);expect(await call('request-reply','POST',{id:ticket.id,status:'Resolved',reply:staff.qualification}),403);expect(await call('request-reply','POST',{id:ticket.id,status:'Resolved',reply:staff.qualification},'owner'),200);expect(await call('audit'),403);expect(await call('audit','GET',null,'owner'),200);
const raw='{"id":"evt_test"}',t=Math.floor(Date.now()/1000),key=await crypto.subtle.importKey('raw',new TextEncoder().encode('whsec_test'),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(t+'.'+raw))).toString('hex');assert(await verifySignature(raw,`t=${t},v1=${sig}`,'whsec_test'));assert(!await verifySignature(raw+'x',`t=${t},v1=${sig}`,'whsec_test'));assert(!await verifySignature(raw,`t=1,v1=${sig}`,'whsec_test'));assert.equal((await digest(raw)).length,64);checks+=4;
console.log(`${checks} backend checks passed: privacy, cloud conflicts, qualification scope, role separation, review states, credentials, appeals, payment blocking and signature verification.`);
