import type { SessionUser } from "./auth.js";
import type { NextResponse } from "next/server";
export function requestId(): string;
export function deny(message?: string, status?: number): NextResponse;
export function requireRole(user: SessionUser | null, ...roles: SessionUser["role"][]): user is SessionUser;
export function audit(actorId: number | null, action: string, entity: string, entityId?: string | number, before?: string, after?: string, rid?: string, ip?: string): void;
export function notify(userId: number, kind: string, text: string): void;
export function fail(rid: string, e: unknown, context?: string): NextResponse;
export function recordFail(email: string): void;
export function checkLocked(email: string): boolean;
export function clearFails(email: string): void;
export function capabilityBand(level: number): string;
export function sessionFromRequest(req: unknown, getSessionUser: (t: string | undefined) => SessionUser | null): Promise<SessionUser | null>;
export function clientIp(req: Request): string;
export function rateLimit(key: string, limit: number, windowMs: number): boolean;
export function limited(req: Request, scope: string, limit: number, windowMs?: number): boolean;
export function isOrgProjectCaller(project: { id: number; client_id?: number; org_id: number | null }, user: { id: number; role: string }): Promise<boolean>;
