// Catalog: one blueprint per course (DB-00…DB-22). Full lesson content lives in
// per-course files (db-00.ts, …). Validator checks both together.
import type { Course } from "./types";

const B = (
  id: string, title: string, category: string, difficulty: string, durationWeeks: number,
  prerequisites: string[], audience: string, outcomes: string[], skills: string[],
  careers: string[], modules: { id: string; objective: string; scenario: string }[],
  finalProject: string, evidence: string[], next: string[],
): Course => ({
  id, title, category, difficulty, durationWeeks, prerequisites, audience, outcomes, skills, careers,
  modules: modules.map((m) => ({ ...m, lessons: [] })),
  finalProject, assessment: { kinds: ["scenario-decision", "practical-submission", "defense"], passNote: "All outcomes evidenced; defense passed." },
  evidence, next, version: "1.0.0",
});

const M = (id: string, objective: string, scenario: string) => ({ id, objective, scenario });

export const CATALOG: Course[] = [
B("DB-00", "Digital Foundations", "Digital Foundations", "Starter", 4, [], "Complete beginners; no code needed",
  ["Explains browser→server→database→deploy for any product", "Owns files, terminal, Git basics", "Publishes a live landing page"],
  ["web-fundamentals", "documentation"], ["Digital Starter"],
  [M("DB-00-M1", "Orient in the digital world", "A shop asks: what happens when someone visits our site?"), M("DB-00-M2", "Own your workspace", "First client hands you a messy project folder"), M("DB-00-M3", "Trace the internet", "Client site won't open — where do you look?"), M("DB-00-M4", "Command the machine", "Make a computer follow instructions"), M("DB-00-M5", "Never lose work again", "You broke yesterday's site — recover it"), M("DB-00-M6", "Ship it live", "Client wants the URL tonight")],
  "Personal/business landing page, deployed with custom domain checklist.", ["Live URL", "Repo with history", "Written explanation"], ["DB-01", "DB-02"]),
B("DB-01", "Real-World Problem Solving & Product Thinking", "Product", "Starter", 4, ["DB-00"], "Everyone (the most important course)",
  ["Separates symptoms from root problems", "Writes requirements with acceptance criteria", "Produces scope + not-building list"],
  ["discovery", "requirements", "scoping", "estimation"], ["All paths"],
  [M("DB-01-M1", "Hear the real ask", "Client: 'I need an app.'"), M("DB-01-M2", "Discover the problem", "Logistics firm: 'operations are slow'"), M("DB-01-M3", "Write requirements", "Transport company on WhatsApp + Excel"), M("DB-01-M4", "Map the process", "Current → bottleneck → proposed"), M("DB-01-M5", "Decide build/buy/automate", "'We want an ERP' — is that the answer?"), M("DB-01-M6", "Scope like a professional", "The client discovery room")],
  "Discovery pack for a fictional company: problem statement, map, requirements, scope.", ["Discovery pack", "Recorded defense"], ["DB-02", "DB-17", "DB-19"]),
B("DB-02", "Professional Web Development", "Software Engineering", "Builder", 8, ["DB-00", "DB-01"], "Aspiring builders",
  ["Builds responsive, accessible business sites", "Consumes APIs with proper states", "Deploys production builds"],
  ["html-css", "javascript", "react", "testing"], ["Digital Starter", "Digital Builder"],
  [M("DB-02-M1", "Ship in 24 hours", "Local business needs a site by tomorrow"), M("DB-02-M2", "Look professional", "Style, type, spacing, components"), M("DB-02-M3", "Fix the phone version", "Desktop fine, mobile terrible"), M("DB-02-M4", "Make it interactive", "Forms that validate before submit"), M("DB-02-M5", "Audit a bad UI", "Find hierarchy, form and a11y failures"), M("DB-02-M6", "Component thinking", "Rebuild with React"), M("DB-02-M7", "Ship it", "Approval received — launch tonight")],
  "Production-quality business site from a fictional brief.", ["Live site", "Repo", "Lighthouse report"], ["DB-03", "DB-15"]),
B("DB-03", "Backend, APIs & Databases", "Software Engineering", "Builder", 8, ["DB-02"], "Web builders going full-stack",
  ["Designs REST APIs with validation", "Models relational data correctly", "Separates authentication from authorization", "Handles concurrency safely"],
  ["nodejs", "express", "rest-apis", "sql", "postgres", "data-modeling", "auth", "authz"], ["Digital Builder", "AI Product Builder"],
  [M("DB-03-M1", "Remember the customer", "Site must remember users"), M("DB-03-M2", "Connect two systems", "Website and CRM must exchange data"), M("DB-03-M3", "Serve 10,000 customers", "Where do they live?"), M("DB-03-M4", "Close the invoice leak", "Customer A sees Customer B's invoice"), M("DB-03-M5", "Survive the double-click", "Two buyers, one item, same second")],
  "Business app: login → dashboard → orders → admin, tested.", ["Repo", "API docs", "Test report"], ["DB-05", "DB-06", "DB-09"]),
B("DB-04", "AI-Native Software Development", "AI Engineering", "Builder", 6, ["DB-02"], "Builders who refuse AI dependence",
  ["Directs AI with context and constraints", "Reviews AI code for bugs and risks", "Verifies before shipping"],
  ["prompt-design", "context-engineering", "ai-review", "ai-debugging"], ["AI Product Builder", "AI Automation Specialist"],
  [M("DB-04-M1", "Calibrate the tool", "What AI can/can't do"), M("DB-04-M2", "Brief like an architect", "Context, constraints, expected output"), M("DB-04-M3", "Review ruthlessly", "AI code with planted flaws"), M("DB-04-M4", "Triage three diagnoses", "Only one is correct"), M("DB-04-M5", "Verify everything", "AI vs Engineer final")],
  "Real feature built with AI assistance + written verification log.", ["Feature", "Verification log", "Defense recording"], ["DB-12", "DB-06"]),
B("DB-05", "Data, PostgreSQL & Business Data", "Data & Analytics", "Builder", 6, ["DB-03"], "Backend builders going deep",
  ["Models normalized schemas", "Writes reporting SQL", "Protects integrity with constraints"],
  ["sql", "postgres", "data-modeling", "reporting-sql"], ["Digital Builder"],
  [M("DB-05-M1", "Fix the spreadsheet of lies", "CEO's customer data contradicts itself"), M("DB-05-M2", "Answer business questions", "Revenue by lane, churn by cohort"), M("DB-05-M3", "Protect the data", "Backups, integrity, lifecycles")],
  "Business data layer with reports and recovery plan.", ["Schema", "Queries", "Recovery doc"], ["DB-09", "DB-06"]),
B("DB-06", "Production Engineering", "DevOps/Cloud/Production", "Professional", 6, ["DB-03"], "Builders going live",
  ["Runs dev/staging/prod safely", "Ships via CI with rollback ready", "Recovers from incidents"],
  ["ci-cd", "deployment", "monitoring", "backups", "incident-response"], ["Digital Builder", "Professional Operator"],
  [M("DB-06-M1", "Environments that don't leak", "Secrets in chat — fix the practice"), M("DB-06-M2", "Deploy without fear", "Build, migrate, release, verify"), M("DB-06-M3", "Wake up to alerts", "Monitoring that pages the right human"), M("DB-06-M4", "Incident room", "Database connection fails at noon")],
  "App live with monitoring, backups and rollback runbook.", ["Live URL", "Runbook", "Incident report"], ["DB-07", "DB-08"]),
B("DB-07", "Secure Software & Cybersecurity", "Cybersecurity", "Professional", 6, ["DB-03"], "Builders who ship trust",
  ["Finds OWASP-class flaws in own code", "Enforces authz server-side", "Handles secrets, uploads, webhooks safely"],
  ["threat-modeling", "owasp-top10", "injection-defense", "secrets-management", "rbac", "rate-limiting"], ["AI Product Builder", "Professional Operator"],
  [M("DB-07-M1", "Think like an attacker", "Threat-model a login flow"), M("DB-07-M2", "Close the classic holes", "Injection, XSS, CSRF, IDOR drills"), M("DB-07-M3", "Audit mission", "10 planted vulns — find and fix")],
  "Security audit report on own prior project.", ["Audit report", "Fixed code", "Retest log"], ["DB-09"]),
B("DB-08", "Software Testing & Quality Engineering", "Software Testing & Quality", "Professional", 6, ["DB-02"], "Builders who prove it works",
  ["Writes strategy covering 5 paths", "Automates browser E2E with Playwright", "Diagnoses flaky vs real failures"],
  ["testing", "playwright", "regression", "load-testing"], ["Digital Builder", "QA Engineer"],
  [M("DB-08-M1", "Test the paths", "Happy, wrong, malicious, failure, concurrency"), M("DB-08-M2", "Automate the browser", "Playwright suite for checkout"), M("DB-08-M3", "Catch the double-charge", "Regression that earns its keep")],
  "Full regression suite + defect report for a checkout.", ["Suite", "Reports", "CI config"], ["DB-06"]),
B("DB-09", "Payments, Ledgers, Webhooks & Money", "Software Engineering", "Advanced", 5, ["DB-03", "DB-08"], "Builders touching money",
  ["Designs idempotent money flows", "Reconciles like an accountant", "Gates payouts with approvals"],
  ["payments", "idempotency", "ledger", "reconciliation"], ["Professional Operator"],
  [M("DB-09-M1", "Follow the money", "Lifecycle, capture, refund, chargeback"), M("DB-09-M2", "Survive the storm", "Duplicate webhooks + timeouts + pending refunds")],
  "Simulated payment system with ledger and reconciliation.", ["Ledger export", "Recovery doc"], ["DB-06"]),
B("DB-10", "Real-Time Applications", "Software Engineering", "Professional", 4, ["DB-03"], "Builders of live systems",
  ["Ships presence, notifications and live dashboards", "Handles reconnects and duplicates"],
  ["websockets", "monitoring"], ["Professional Operator"],
  [M("DB-10-M1", "Make it live", "Driver status must update instantly"), M("DB-10-M2", "Survive the disconnect", "Offline, ordering, duplicates")],
  "Live operations dashboard.", ["Live URL", "Reconnect test log"], ["DB-06"]),
B("DB-11", "Documents, Uploads & Storage", "Software Engineering", "Professional", 4, ["DB-03", "DB-07"], "Builders handling files",
  ["Stores private files with signed access", "Validates and versions documents"],
  ["storage", "rbac"], ["Professional Operator"],
  [M("DB-11-M1", "Lock the vault", "Confidential uploads, correct eyes only"), M("DB-11-M2", "Prove the chain", "Versions, hashes, evidence")],
  "Secure document vault with access log.", ["Vault", "Access log"], ["DB-07"]),
B("DB-12", "AI Agents, Automation & Business Workflows", "AI Engineering", "Flagship", 8, ["DB-04"], "Future automation specialists",
  ["Maps automatable work honestly", "Ships guarded agents with human approval", "Measures hours returned"],
  ["agent-design", "guardrails", "workflow-automation", "webhooks", "human-in-loop", "ai-eval", "ai-cost"], ["AI Automation Specialist", "AI Product Builder"],
  [M("DB-12-M1", "Find the 4-hour morning", "What repeats daily?"), M("DB-12-M2", "Design the loop", "Trigger → validate → execute → verify → record"), M("DB-12-M3", "Bound the agent", "Answer, escalate, never-touch"), M("DB-12-M4", "Ship the employee", "One business function, measured")],
  "Working AI employee for a real workflow.", ["Workflow", "Eval log", "Cost report"], ["DB-13", "DB-19"]),
B("DB-13", "CRM / ERP / HRM", "Business Systems", "Consultant", 6, ["DB-01"], "Operators and consultants",
  ["Maps pipelines to real sales steps", "Designs one operating system from spreadsheet chaos"],
  ["crm-ops", "erp-ops", "hrm-ops"], ["AI Automation Specialist", "Transformation Consultant"],
  [M("DB-13-M1", "Stop losing leads", "Pipeline matching reality"), M("DB-13-M2", "One system", "6 spreadsheets + 4 WhatsApp groups → OS")],
  "Mini business OS with migration plan.", ["OS demo", "Migration doc"], ["DB-19"]),
B("DB-14", "Mobile App Builder", "Mobile Development", "Builder", 6, ["DB-02", "DB-03"], "Builders going pocket-size",
  ["Ships authenticated mobile apps on real backends", "Handles offline, push and permissions"],
  ["mobile-basics"], ["AI Product Builder"],
  [M("DB-14-M1", "Leave the desk", "Field staff can't use desktop"), M("DB-14-M2", "Ship to stores", "Build, permissions, release")],
  "Mobile app on a real backend.", ["Store listing", "Backend link"], ["DB-06"]),
B("DB-15", "Search & AI Visibility Engineering", "SEO/AEO/GEO", "Consultant", 5, ["DB-02"], "Growth-minded builders",
  ["Makes businesses machine-understandable", "Earns citations, not just rankings"],
  ["seo-technical", "aeo", "geo"], ["Transformation Consultant"],
  [M("DB-15-M1", "Be understood", "Good company, invisible online"), M("DB-15-M2", "Own the answer", "Entities, FAQs, schema, citations")],
  "Visibility audit + implemented fixes.", ["Audit", "Before/after"], ["DB-16"]),
B("DB-16", "Social Media & Content Operations", "Social & Content", "Consultant", 5, [], "Operators and founders",
  ["Runs a 30-day content system from zero", "Reports funnel impact, not vanity"],
  ["content-systems"], ["Transformation Consultant"],
  [M("DB-16-M1", "System over viral", "Pillars, hooks, calendar"), M("DB-16-M2", "Produce and measure", "30 days, then report the funnel")],
  "30-day content system + performance report.", ["Calendar", "Report"], []),
B("DB-17", "From Idea to MVP", "Product", "Founder", 5, ["DB-01"], "Founders and product minds",
  ["Validates before building", "Defines testable MVPs with pricing"],
  ["scoping", "estimation"], ["AI Product Builder"],
  [M("DB-17-M1", "Interrogate the idea", "Great idea — should it exist?"), M("DB-17-M2", "Define the smallest bet", "MVP + prototype + pricing")],
  "Validation sprint pack.", ["Pack", "Prototype"], ["DB-18"]),
B("DB-18", "Build, Launch & Grow", "Product", "Founder", 8, ["DB-17", "DB-03"], "Founders shipping SaaS",
  ["Launches instrumented products", "Iterates on retention, not opinions"],
  ["scoping"], ["AI Product Builder"],
  [M("DB-18-M1", "Architect the bet", "MVP that can take users"), M("DB-18-M2", "Launch and learn", "Onboarding, pricing, retention loops")],
  "Live SaaS with analytics and paying-intent signal.", ["Live URL", "Metrics"], ["DB-06"]),
B("DB-19", "Digital Transformation Consulting", "Transformation", "Consultant", 6, ["DB-01", "DB-12"], "Future consultants",
  ["Audits business, process and tech", "Prices roadmaps in hours saved"],
  ["transformation-audit", "roadmapping", "roi-analysis"], ["Transformation Consultant"],
  [M("DB-19-M1", "Enter the company", "Map what actually happens"), M("DB-19-M2", "Rank and roadmap", "NOW/30/90/12-month plan with ROI")],
  "Professional transformation audit report.", ["Report", "Roadmap"], ["DB-20"]),
B("DB-20", "Client Delivery & Freelancing", "Freelancing", "Professional", 5, ["DB-01"], "Builders going independent",
  ["Runs discovery-to-handover professionally", "Defends scope without burning trust"],
  ["proposals", "contracts", "client-comms", "change-control"], ["All freelance paths"],
  [M("DB-20-M1", "Win the work", "Positioning, discovery, proposal"), M("DB-20-M2", "Survive the client", "Creep, delays, difficult news, handover")],
  "Simulated end-to-end client engagement.", ["Proposal", "Handover pack"], ["DB-21"]),
B("DB-21", "Business Operations & Practice", "Operations", "Professional", 4, ["DB-20"], "Independents scaling up",
  ["Operates five clients without chaos", "Documents, backs up, renews"],
  ["documentation", "operations"], ["Professional Operator"],
  [M("DB-21-M1", "Build your OS", "Folders, SOPs, finance, support"), M("DB-21-M2", "Stay alive", "Incidents, vendors, renewals")],
  "Personal operating system, documented.", ["OS handbook"], ["DB-22"]),
B("DB-22", "Professional Challenge", "Master", "Master", 3, ["DB-06", "DB-07", "DB-08", "DB-20"], "Graduates proving everything",
  ["Delivers under constraints", "Defends every decision across 8 interviews"],
  ["incident-response"], ["Professional Operator"],
  [M("DB-22-M1", "72 hours", "CargoFlow Logistics: discover → demo"), M("DB-22-M2", "The gauntlet", "10 injected incidents, live response"), M("DB-22-M3", "The defense", "8 interviews, no hiding")],
  "Defended demo + full evidence pack + Capability Record.", ["Evidence pack", "Record"], []),
];
