// DB-00 full production content — template for all future course batches.
import type { Course, Lesson } from "./types";

const L = (
  id: string, title: string, coldOpen: string, why: string,
  concept: string[], example: string, exercise: string,
  q: string, opts: string[], ans: number, whyAns: string, evidence: string,
  mistakes: string[] = ["Skimming without doing — this course is pass-by-artifact, not pass-by-reading."],
  failure = "Your work won't save, load, or deploy. Retrace the chain: file → path → tool → service.",
): Lesson => ({
  id, title, coldOpen, why, concept, example,
  practice: "Professionals keep one canonical place per artifact and name things so strangers understand.",
  mistakes, failure, exercise,
  check: { question: q, options: opts, answer: ans, why: whyAns },
  evidence,
});

const DB00_LESSONS: Lesson[] = [
L("DB-00-M1-L1", "What actually happens on a visit",
  "A shop owner asks: a customer tapped our ad — then what, exactly?",
  "Because every later decision (hosting, speed, checkout) hangs off this chain.",
  ["A browser asks a server for files over HTTP(S).", "The server returns HTML, CSS, JS, images.", "The browser renders them; forms send data back the same way."],
  "Type a shop URL, open devtools Network tab, reload: count the requests. That list is the whole business, in transit.",
  "Explain the chain aloud in under 60 seconds, naming each hop.",
  "What sends the page to the visitor's browser?",
  ["The domain name itself", "The server, over HTTP(S)", "The logo file", "The visitor's email app"], 1,
  "Domains point; servers respond. Confusing the two causes most beginner DNS panic.",
  "60-second recorded explanation."),
L("DB-00-M1-L2", "Sites vs apps vs SaaS",
  "Two quotes land: a 5-page site and a booking platform. Why is one 10× the other?",
  "Because scope disguised as vocabulary is how beginners undercharge and overpromise.",
  ["Sites present; apps remember; SaaS rents ongoing value.", "Logins, databases and payments move a project up the ladder.", "Name the rung before quoting a price."],
  "Classify three real local businesses into site / app / SaaS and justify each in one line.",
  "Write the one-line classification for a clinic with online booking.",
  "A clinic with online booking is…?", ["A static site", "An application", "A domain registrar", "A font"], 1,
  "Booking means memory, accounts and state — application territory.",
  "Classification sheet with reasons."),
L("DB-00-M2-L1", "The builder's workspace",
  "Your first client sends a ZIP named final-final-v2. What do you do before touching anything?",
  "Because disorganized files become lost work, billing disputes and shame.",
  ["One project, one folder; names with dates and versions.", "Editors over notepads; terminals over clicking.", "Environment variables keep secrets out of code."],
  "Create client-acme-2026/ with 01-discovery … 05-delivery subfolders and a README stating what's inside.",
  "Set up the folder and README now.",
  "Where do secrets like API keys belong?",
  ["Inside the HTML file", "In environment variables, never committed", "In the folder name", "In a screenshot"], 1,
  "Committed secrets leak forever; env vars stay local. This rule never bends.",
  "Folder tree screenshot + README."),
L("DB-00-M2-L2", "Terminal without fear",
  "The tutorial says 'open terminal'. Your stomach drops. Fix that in 20 minutes.",
  "Because every deployment, log and server lives behind this window.",
  ["pwd/ls/cd navigate; mkdir/touch create; cat reads.", "Tab completes; up-arrow recalls; Ctrl+C escapes.", "Copy-paste commands you can't explain is how outages start."],
  "Navigate to your project, list files, create notes.txt, print it — all by keyboard.",
  "Run the five-command drill twice.",
  "Ctrl+C in a terminal…?", ["Deletes the internet", "Interrupts the running command", "Saves the file", "Opens settings"], 1,
  "It's the escape hatch. Learn it before you need it.",
  "Terminal transcript of the drill."),
L("DB-00-M3-L1", "Trace the click",
  "Client: 'our site won't open'. Where do you look first — and second?",
  "Because guessing wastes hours; tracing takes minutes.",
  ["Domain → DNS → IP → server → HTTP response → render.", "Each hop has its own failure signature.", "Check in order; skip nothing."],
  "Diagram the six hops for digitalburj.com from memory, then verify two with real tools.",
  "Draw and verify the chain.",
  "A DNS failure means…?", ["The server is hacked", "The name isn't resolving to an address", "CSS failed to load", "The user needs a new phone"], 1,
  "DNS only maps names to numbers. If it fails, nothing downstream is even reached.",
  "Hand diagram + verification notes."),
L("DB-00-M3-L2", "Status codes save friendships",
  "A form breaks. The console says 404, then 500. Which is whose fault?",
  "Because reading two digits correctly halves every debugging session.",
  ["2xx success, 3xx redirect, 4xx your request is wrong, 5xx our server failed.", "404: missing thing. 500: broken code. 403: not allowed."],
  "Trigger each code deliberately against a test endpoint and screenshot the trio.",
  "Produce all three codes on demand.",
  "Your dashboard shows 403 on someone else's invoice. That means…?",
  ["Page not found", "Logged in but not permitted — investigate authorization", "Server crashed", "Try a different browser"], 1,
  "403 is the server saying 'I know you, and no.' It points at permissions, not existence.",
  "Screenshot trio with one-line causes."),
L("DB-00-M4-L1", "Make it follow instructions",
  "No code yet — just logic. A door that opens for members, not strangers.",
  "Because every program is decisions plus repetition plus memory.",
  ["Variables store, conditions branch, loops repeat, functions package.", "Write the door rule in plain words first, then pseudocode."],
  "Pseudocode: member list, guest attempt, allow/deny with a logged reason.",
  "Write the door rule two ways.",
  "A loop is for…?", ["Storing one value", "Repeating work over many items", "Designing logos", "Sending email once"], 1,
  "One item: variable. Many items, same job: loop.",
  "Pseudocode photo or file."),
L("DB-00-M4-L2", "Errors are information",
  "Your first script crashes. Good — that's the lesson starting.",
  "Because beginners who fear errors debug slowly for years.",
  ["Read bottom-up: last line names the error, lines above show the path.", "Change one thing, rerun, note what moved.", "Rubber-duck the logic aloud before asking for help."],
  "Break a working snippet three different ways; log each message and meaning.",
  "Collect three crashes with translations.",
  "Best first response to an error?",
  ["Reinstall everything", "Read the last line, then trace upward", "Delete the file", "Ask AI for full rewrite"], 1,
  "Error messages are directions, not insults. The last line is the address.",
  "Crash log with translations."),
L("DB-00-M5-L1", "Never lose work again",
  "You broke yesterday's working site at midnight. The client calls at 9am.",
  "Because version history is the difference between an incident and a disaster.",
  ["Init, add, commit with real messages; branches isolate experiments.", "GitHub hosts the truth; pull requests are conversations.", "Revert beats rewrite when the clock is ticking."],
  "Break a page, commit the fix on a branch, merge via pull request.",
  "Run the break-and-recover drill.",
  "The midnight fix for a broken live page is…?",
  ["Edit directly on the server", "Revert to the last good commit, then fix forward", "Delete the repo", "Wait for inspiration"], 1,
  "Revert first restores service; heroics second. Clients remember uptime.",
  "Repo link with branch history."),
L("DB-00-M5-L2", "Messages for future you",
  "Six months later, 'fixed stuff' helps nobody. Write history that helps.",
  "Because commit messages are documentation for the person you'll be.",
  ["Imperative mood, scope prefix, reason over what.", "Link the why: ticket, client ask, incident number."],
  "Rewrite five lazy messages from real repos into professional ones.",
  "Rewrite the lazy five.",
  "Best commit message?",
  ["fixed stuff", "fix(checkout): guard duplicate webhook delivery", "UPDATE", "final final v2"], 1,
  "Scope + verb + reason. Future-you says thanks.",
  "Before/after message list."),
L("DB-00-M6-L1", "Ship it live",
  "Approval received. The URL goes to the client tonight. Walk the checklist.",
  "Because 'works on my machine' has ended more client relationships than bugs.",
  ["Build, deploy, domain, HTTPS, mobile check, production verify.", "Keep a launch list; tick it in order, every time."],
  "Deploy your landing page; verify on your phone over mobile data.",
  "Ship and verify tonight.",
  "First check after deploy?",
  ["Redesign the hero", "Load it on a phone, click everything", "Post on social media", "Delete local files"], 1,
  "Production is a different computer. Verify there, not here.",
  "Live URL + phone-checklist photo."),
L("DB-00-M6-L2", "Hand over like a professional",
  "The site is live. What does the client actually receive?",
  "Because handover quality decides whether you get the next project.",
  ["Credentials ownership transfer, not screenshots of passwords.", "One-page care doc: what breaks, who to call, what it costs.", "Offer the retainer before they ask for free help forever."],
  "Write the one-page handover for your deployed site.",
  "Deliver the handover pack.",
  "Passwords should be handed over via…?",
  ["Chat message", "Secure vault transfer with ownership change", "Sticky note photo", "Email subject line"], 1,
  "Chat logs leak; vaults transfer. Ownership, not copies.",
  "Handover document."),
];

export const DB00: Course = {
  id: "DB-00", title: "Digital Foundations", category: "Digital Foundations",
  difficulty: "Starter", durationWeeks: 4, prerequisites: [], audience: "Complete beginners; no code needed",
  outcomes: ["Explains browser→server→database→deploy for any product", "Owns files, terminal, Git basics", "Publishes a live landing page with handover"],
  skills: ["web-fundamentals", "documentation"], careers: ["Digital Starter"],
  modules: [
    { id: "DB-00-M1", objective: "Orient in the digital world", scenario: "A shop asks what happens on a visit.", lessons: DB00_LESSONS.filter((l) => l.id.includes("-M1-")) },
    { id: "DB-00-M2", objective: "Own your workspace", scenario: "A messy client folder lands on your desk.", lessons: DB00_LESSONS.filter((l) => l.id.includes("-M2-")) },
    { id: "DB-00-M3", objective: "Trace the internet", scenario: "A site won't open; find the hop.", lessons: DB00_LESSONS.filter((l) => l.id.includes("-M3-")) },
    { id: "DB-00-M4", objective: "Command the machine", scenario: "Make a computer follow instructions.", lessons: DB00_LESSONS.filter((l) => l.id.includes("-M4-")) },
    { id: "DB-00-M5", objective: "Never lose work", scenario: "Midnight breakage, 9am client call.", lessons: DB00_LESSONS.filter((l) => l.id.includes("-M5-")) },
    { id: "DB-00-M6", objective: "Ship and hand over", scenario: "Approval received — launch tonight.", lessons: DB00_LESSONS.filter((l) => l.id.includes("-M6-")) },
  ],
  finalProject: "Personal/business landing page: deployed URL, repo with real history, handover doc.",
  assessment: { kinds: ["scenario-decision", "practical-submission", "defense"], passNote: "Live URL verified + history readable + 10-minute defense passed." },
  evidence: ["Live URL", "Repo with history", "Handover doc", "Defense recording"],
  next: ["DB-01", "DB-02"],
  version: "1.0.0",
};
