import fs from 'node:fs';
import vm from 'node:vm';
import * as simple from 'simple-icons';
const text=fs.readFileSync('dist/academy-standard.js','utf8'),match=text.match(/const tools=(\[[\s\S]*?\n\]);/);
if(!match)throw Error('Tool catalogue not found');
const tools=vm.runInNewContext(match[1]);
const slugs={adobe:'adobecreativecloud',vscode:'visualstudiocode',sheets:'googlesheets',mastercard:'mastercard',googlepay:'googlepay',binance:'binance'};
const purpose={notebook:'Pen',web:'Code',data:'Chart',prompt:'Spark',flow:'Workflow',api:'Terminal',design:'Palette',board:'Board',budget:'Calculator',json:'Braces',contrast:'Contrast',canva:'Palette',chatgpt:'Spark',lovable:'Heart',vscode:'Code',adobe:'Pen',capcut:'Video',crypto:'Wallet',razorpay:'Wallet'};
const additions=[['razorpay','Razorpay'],['visa','Visa'],['mastercard','Mastercard'],['googlepay','Google Pay'],['binance','Binance Pay'],['crypto','Crypto wallet']];
const records=[...tools.map(t=>[t[0],t[1]]),...additions],icons={},provenance=[];
for(const [id,title]of records){const mark=Object.values(simple).find(i=>i?.slug===(slugs[id]||id));icons[id]={title,...(mark?{path:mark.path,kind:'brand'}:{purpose:purpose[id]||'Terminal',kind:'purpose'})};provenance.push({id,title,kind:mark?'brand':'purpose',source:mark?mark.source:'DigitalBurj purpose pictogram',...(mark?{slug:mark.slug}:{})})}
const aliases={'API console':'api','Hugging Face':'huggingface','Open code':'opencode','OpenCode':'opencode','VS Code':'vscode','Adobe':'adobe','Master card':'mastercard','MasterCard':'mastercard','Google pay':'googlepay','Binance':'binance'};
const out=`/* Local tool pictograms. Selected Simple Icons 16.33.0 paths, CC0-1.0; see content/tool-icon-provenance.json. */\n(() => {'use strict';const marks=${JSON.stringify(icons)},aliases=${JSON.stringify(aliases)};
const extra={Palette:'M12 3a9 9 0 1 0 0 18h2a2 2 0 0 0 1-3.7 1.4 1.4 0 0 1 .5-2.6H18a3 3 0 0 0 3-3C21 6.5 17 3 12 3 M7 10h.01 M10 7h.01 M15 7h.01 M17 11h.01',Board:'M3 4h18v16H3Z M9 4v16 M15 4v16 M5 8h2 M11 8h2 M17 8h2 M5 12h2 M11 12h2',Calculator:'M6 3h12v18H6Z M9 7h6 M9 11h.01 M15 11h.01 M9 15h.01 M15 15h.01 M9 18h.01 M15 18h.01',Braces:'M8 3H6v7l-2 2 2 2v7h2 M16 3h2v7l2 2-2 2v7h-2',Contrast:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 3v18',Heart:'M12 21 3.5 12.5a5.5 5.5 0 0 1 8.5-7 5.5 5.5 0 0 1 8.5 7Z',Video:'M3 5h13v14H3Z m13 5 5-3v10l-5-3',Wallet:'M3 5h16v15H3Z M3 5l14-3v3 M15 11h7v5h-7Z M18 13.5h.01'};
function icon(id,size=20){const m=marks[id];if(!m)return '';const attrs='class="tool-icon" data-tool-icon="'+id+'" data-icon-kind="'+m.kind+'" width="'+size+'" height="'+size+'" viewBox="0 0 24 24" aria-hidden="true" focusable="false"';return m.path?'<svg '+attrs+' fill="currentColor"><path d="'+m.path+'"/></svg>':extra[m.purpose]?'<svg '+attrs+' fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="'+extra[m.purpose]+'"/></svg>':window.AcademyShell.icon(m.purpose,size).replace('<svg ','<svg class="tool-icon" data-tool-icon="'+id+'" data-icon-kind="purpose" ')}
const names=[...Object.entries(marks).filter(([id])=>!['make','render','blender'].includes(id)).map(([id,m])=>[m.title,id]),...Object.entries(aliases)].sort((a,b)=>b[0].length-a[0].length),lookup=new Map(names.map(([n,id])=>[n.toLowerCase(),id]));
const escaped=names.map(([n])=>n.replace(/[.*+?^\${}()|[\]\\]/g,'\\$&')),pattern=new RegExp('(?<![\\w])('+escaped.join('|')+')(?![\\w])','gi');
function decorate(root){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode()){const n=walker.currentNode;if(!n.parentElement?.closest('script,style,textarea,select,option,pre,code,svg,[data-tool-label],.tool-with-icon,.vendor-mark,.tool-chip,.workspace-tabs'))nodes.push(n)}for(const n of nodes){pattern.lastIndex=0;if(!pattern.test(n.nodeValue))continue;pattern.lastIndex=0;let last=0,found;const frag=document.createDocumentFragment();while((found=pattern.exec(n.nodeValue))){frag.append(document.createTextNode(n.nodeValue.slice(last,found.index)));const span=document.createElement('span');span.className='tool-with-icon';span.dataset.toolLabel=lookup.get(found[0].toLowerCase());span.innerHTML=icon(span.dataset.toolLabel,16);span.append(document.createTextNode(found[0]));frag.append(span);last=pattern.lastIndex}frag.append(document.createTextNode(n.nodeValue.slice(last)));n.replaceWith(frag)}}
window.ToolIcons={icon,decorate,marks};})();\n`;
fs.writeFileSync('dist/tool-icons.js',out);
fs.writeFileSync('content/tool-icon-provenance.json',JSON.stringify({package:'simple-icons',version:'16.33.0',license:'CC0-1.0',source:'https://github.com/simple-icons/simple-icons',icons:provenance},null,2)+'\n');
console.log('Built '+records.length+' local tool/payment pictograms.');
