const authJSON=(body,status=200,cookie)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'private, no-store',...(cookie?{'set-cookie':cookie}:{})}});
const authError=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const authNow=()=>new Date().toISOString();
const authCookie=token=>`__Host-academy_session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=604800`;
const clearAuthCookie='__Host-academy_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0';
const authHash=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const toBase64=bytes=>btoa(String.fromCharCode(...bytes));
const fromBase64=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
export async function sealTokens(data,key){if(!/^[a-f0-9]{64}$/.test(key||''))authError('Secure session storage is not configured.',503);const raw=Uint8Array.from(key.match(/../g).map(x=>parseInt(x,16))),cipher=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),result=await crypto.subtle.encrypt({name:'AES-GCM',iv},cipher,new TextEncoder().encode(JSON.stringify(data)));return toBase64(iv)+'.'+toBase64(new Uint8Array(result))}
export async function openTokens(data,key){const[iv,body]=data.split('.'),raw=Uint8Array.from(key.match(/../g).map(x=>parseInt(x,16))),cipher=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['decrypt']);return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:fromBase64(iv)},cipher,fromBase64(body))))}
async function authBody(r){if(r.headers.get('origin')!==new URL(r.url).origin||r.headers.get('sec-fetch-site')==='cross-site')authError('Use the academy page to submit this form.',403);if(!r.headers.get('content-type')?.startsWith('application/json'))authError('Invalid form format.',415);const raw=await r.text();if(new TextEncoder().encode(raw).length>16000)authError('The form is too large.',413);try{return JSON.parse(raw)}catch{authError('The form is not valid.',400)}}
const ownerIdentity=(r,env)=>{const id=r.headers.get('oai-authenticated-user-id'),email=r.headers.get('oai-authenticated-user-email');return id&&email&&env.ACADEMY_OWNER_EMAIL&&email.toLowerCase()===env.ACADEMY_OWNER_EMAIL.toLowerCase()?{id,email,provider:'platform-owner',verified:true}:null};
export function sitesIdentity(r,env){
 if(env.ACADEMY_PLATFORM_AUTH!=='sites')return null;
 // Sites dispatch consumes caller credentials and supplies these headers.
 // This path is enabled only on the Sites-managed Worker, never local intake.
 const id=r.headers.get('oai-authenticated-user-id'),email=r.headers.get('oai-authenticated-user-email');
 if(!id||id.length>200||!email||email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return null;
 return{id,email,provider:'chatgpt',verified:true,purpose:'normal'};
}
export function createAuth(C){const programmes=new Set(C.programmes.map(p=>p.id));
async function config(env){if(env.SUPABASE_URL&&env.SUPABASE_PUBLISHABLE_KEY)return{url:env.SUPABASE_URL,key:env.SUPABASE_PUBLISHABLE_KEY};const row=await env.DB.prepare("SELECT value FROM settings WHERE key='identity_provider'").first();return row?JSON.parse(row.value):null}
async function provider(env,path,payload,token,method){const cfg=await config(env);if(!cfg||!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(cfg.url)||!cfg.key)authError('Email sign-in is not connected yet. The owner can connect the identity project in Admin settings.',503);let response;try{response=await fetch(cfg.url+'/auth/v1/'+path,{method:method||(payload?'POST':'GET'),signal:AbortSignal.timeout(15000),headers:{apikey:cfg.key,'content-type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(payload?{body:JSON.stringify(payload)}:{})})}catch{authError('The sign-in service is unavailable. Please try again.',503)}const text=await response.text();let data={};try{data=JSON.parse(text)}catch{}if(!response.ok){if(response.status>=500)authError('The sign-in service is unavailable. Please try again.',503);authError('The sign-in request could not be completed. Check the details, confirm your email or request a fresh recovery link.',401)}return data}
async function profileFor(env,id){return env.DB.prepare('SELECT * FROM profiles WHERE user_id=?').bind(id).first()}
async function resolveProviderUser(env,user,r){if(!user?.id||!user.email||!user.email_confirmed_at)authError('Confirm your email before entering the academy.',401);let profile=await env.DB.prepare('SELECT * FROM profiles WHERE auth_subject=?').bind(user.id).first();if(profile)return{id:profile.user_id,email:user.email,provider:'email',subject:user.id,verified:true,profile};const legacy=ownerIdentity(r,env);const id=legacy&&legacy.email.toLowerCase()===user.email.toLowerCase()?legacy.id:'sb:'+user.id;profile=await profileFor(env,id);if(profile){if(profile.auth_subject&&profile.auth_subject!==user.id)authError('This academy account is already linked to a different identity.',409);await env.DB.prepare('UPDATE profiles SET auth_subject=?,email=?,updated=? WHERE user_id=?').bind(user.id,user.email,authNow(),id).run()}return{id,email:user.email,provider:'email',subject:user.id,verified:true,profile}}
async function issueSession(env,data,r,purpose='normal'){if(!data.access_token||!data.refresh_token)authError('Confirm your email, then sign in.',401);const verified=await provider(env,'user',null,data.access_token),identity=await resolveProviderUser(env,verified,r);const token=toBase64(crypto.getRandomValues(new Uint8Array(32))).replace(/[+/=]/g,x=>x==='+'?'-':x==='/'?'_':''),hash=await authHash(token),now=Math.floor(Date.now()/1000),encrypted=await sealTokens({access:data.access_token,refresh:data.refresh_token},env.ACADEMY_SESSION_KEY);await env.DB.prepare('INSERT INTO sessions(hash,user_id,subject,tokens,provider_expiry,expires,created,last_seen,purpose) VALUES(?,?,?,?,?,?,?,?,?)').bind(hash,identity.id,verified.id,encrypted,now+(data.expires_in||3600),now+604800,authNow(),authNow(),purpose).run();return{identity,cookie:authCookie(token)}}
async function identity(r,env){if(!env.DB)return null;const native=sitesIdentity(r,env),token=r.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('__Host-academy_session='))?.split('=')[1];if(!token){if(!native)return null;const profile=await profileFor(env,native.id);return{...native,profile}}if(!/^[a-zA-Z0-9_-]{40,60}$/.test(token))return null;const row=await env.DB.prepare('SELECT * FROM sessions WHERE hash=?').bind(await authHash(token)).first();if(!row||row.expires<=Date.now()/1000)return null;let tokens;try{tokens=await openTokens(row.tokens,env.ACADEMY_SESSION_KEY)}catch{authError('Your session cannot be restored. Sign in again.',401)}if(row.provider_expiry<Date.now()/1000+30){let refreshed;try{refreshed=await provider(env,'token?grant_type=refresh_token',{refresh_token:tokens.refresh})}catch(e){if(e.status===401)await env.DB.prepare('DELETE FROM sessions WHERE hash=?').bind(row.hash).run();throw e}tokens={access:refreshed.access_token,refresh:refreshed.refresh_token};await env.DB.prepare('UPDATE sessions SET tokens=?,provider_expiry=? WHERE hash=?').bind(await sealTokens(tokens,env.ACADEMY_SESSION_KEY),Math.floor(Date.now()/1000)+(refreshed.expires_in||3600),row.hash).run()}
let user;try{user=await provider(env,'user',null,tokens.access)}catch(e){if(e.status===401){await env.DB.prepare('DELETE FROM sessions WHERE hash=?').bind(row.hash).run();return null}throw e}if(user.id!==row.subject||!user.email_confirmed_at)return null;const profile=await profileFor(env,row.user_id);if(profile?.status==='Suspended')authError('This academy account is suspended. Contact the owner for help.',403);await env.DB.prepare('UPDATE sessions SET last_seen=? WHERE hash=?').bind(authNow(),row.hash).run();return{id:row.user_id,email:user.email,subject:user.id,provider:'email',verified:true,profile,purpose:row.purpose,sessionHash:row.hash,tokens}}
async function limit(r,env,path,email=''){const time=Math.floor(Date.now()/1000/900)*900,ip=r.headers.get('cf-connecting-ip')||r.headers.get('oai-authenticated-user-id')||'unknown';for(const [scope,max] of [[ip+'|'+path,60],[ip+'|'+path+'|'+email.toLowerCase(),12]]){const key=await authHash(scope+'|'+time);await env.DB.prepare('INSERT INTO auth_limits(key,count,window) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1').bind(key,time).run();const row=await env.DB.prepare('SELECT count FROM auth_limits WHERE key=?').bind(key).first();if(row.count>max)authError('Too many attempts. Wait 15 minutes before trying again.',429)}await env.DB.prepare('DELETE FROM auth_limits WHERE window<?').bind(time-900).run()}
async function handle(r,env){const path=new URL(r.url).pathname.slice(5);try{if(!env.DB)authError('Account storage is unavailable.',503);if(path==='auth/config'&&r.method==='GET'){const email=!!await config(env)&&/^[a-f0-9]{64}$/.test(env.ACADEMY_SESSION_KEY||''),chatgpt=env.ACADEMY_PLATFORM_AUTH==='sites';return authJSON({configured:email||chatgpt,emailPassword:email,chatgpt,method:chatgpt?'ChatGPT sign-in': 'Email and password',secureSessions:chatgpt||email})}
if(path==='auth/session'&&r.method==='GET'){const id=await identity(r,env),profile=id?.profile|| (id?.id?await profileFor(env,id.id):null);return authJSON(id?.id?{signedIn:true,registered:profile?.status==='Active'&&!!profile.consent_at,user:{id:id.id,email:id.email,provider:id.provider,purpose:id.purpose},profile,admin:id.verified&&profile?.status==='Active'&&!!profile.consent_at&&id.email?.toLowerCase()===env.ACADEMY_OWNER_EMAIL?.toLowerCase()}:{signedIn:false,registered:false})}
if(path==='auth/login'||path==='auth/signup'||path==='auth/recover'||path==='auth/confirm'){if(r.method!=='POST')authError('Use the form to submit this request.',405);const b=await authBody(r);await limit(r,env,path,String(b.email||''));if(path!=='auth/confirm'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.email||''))authError('Enter a valid email address.');if(['auth/login','auth/signup'].includes(path)&&typeof b.password!=='string')authError('Enter your password.');if(path==='auth/signup'){if(b.password.length<12||b.password.length>128)authError('Use a password between 12 and 128 characters.');if(!b.consent)authError('Confirm that you want to create and store your academy account.');await provider(env,'signup?redirect_to='+encodeURIComponent(new URL(r.url).origin+'/auth/confirm'),{email:b.email,password:b.password});return authJSON({message:'Check your inbox to confirm your email, then return here to sign in. Account registration does not grant staff permissions.'},202)}
if(path==='auth/recover'){await provider(env,'recover?redirect_to='+encodeURIComponent(new URL(r.url).origin+'/reset-password'),{email:b.email});return authJSON({message:'If this address can receive a recovery email, check its inbox for the next step.'},202)}
let data;if(path==='auth/confirm'){if(!['email','signup','recovery'].includes(b.type)||!b.tokenHash||b.tokenHash.length>1000)authError('This confirmation link is incomplete. Request a new link.');data=await provider(env,'verify',{token_hash:b.tokenHash,type:b.type})}else data=await provider(env,'token?grant_type=password',{email:b.email,password:b.password});const session=await issueSession(env,data,r,b.type==='recovery'?'recovery':'normal');return authJSON({signedIn:true,next:b.type==='recovery'?'/reset-password':session.identity.profile?'/dashboard':'/onboarding'},200,session.cookie)}
if(path==='auth/logout'&&r.method==='POST'){await authBody(r);let id;try{id=await identity(r,env)}catch{}const token=r.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('__Host-academy_session='))?.split('=')[1];if(token&&/^[a-zA-Z0-9_-]{40,60}$/.test(token))await env.DB.prepare('DELETE FROM sessions WHERE hash=?').bind(await authHash(token)).run();if(id?.tokens)try{await provider(env,'logout?scope=local',{},id.tokens.access)}catch{}return authJSON({signedOut:true,next:env.ACADEMY_PLATFORM_AUTH==='sites'?'/signout-with-chatgpt?return_to=%2Fsign-in':'/sign-in'},200,clearAuthCookie)}
if(path==='auth/password'&&r.method==='POST'){const b=await authBody(r),id=await identity(r,env);if(!id?.tokens)authError('Open the recovery link or sign in first.',401);if(typeof b.password!=='string'||b.password.length<12||b.password.length>128)authError('Use a password between 12 and 128 characters.');if(id.purpose!=='recovery'){if(typeof b.currentPassword!=='string')authError('Enter your current password.');await provider(env,'token?grant_type=password',{email:id.email,password:b.currentPassword})}await provider(env,'user',{password:b.password},id.tokens.access,'PUT');await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(id.id).run();return authJSON({message:'Password updated. Sign in again with your new password.'},200,clearAuthCookie)}
if(path==='account/profile'){const id=await identity(r,env);if(!id?.id)authError('Sign in first.',401);if(id.purpose==='recovery')authError('Set your new password first.',403);if(id.profile?.status==='Suspended')authError('This academy account is suspended. Contact the owner for help.',403);if(r.method==='GET')return authJSON({profile:await profileFor(env,id.id),user:{id:id.id,email:id.email}});if(r.method!=='PUT')authError('Unsupported account action.',405);const b=await authBody(r);if(String(b.name||'').trim().length<2||String(b.name).length>120||String(b.country||'').length>100||!programmes.has(b.goal)||!Number.isInteger(b.hours)||b.hours<1||b.hours>40||String(b.timezone||'').length>80||!b.consent)authError('Enter your name, programme, weekly hours and account storage consent.');const old=await profileFor(env,id.id),t=authNow();await env.DB.prepare('INSERT INTO profiles(user_id,auth_subject,email,name,country,goal,hours,timezone,consent_at,status,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET email=excluded.email,name=excluded.name,country=excluded.country,goal=excluded.goal,hours=excluded.hours,timezone=excluded.timezone,updated=excluded.updated').bind(id.id,id.subject||null,id.email,b.name.trim(),b.country||'',b.goal,b.hours,b.timezone||'UTC',old?.consent_at||t,'Active',t,t).run();const invite=await env.DB.prepare("SELECT * FROM staff_invites WHERE lower(email)=? AND status='Pending' AND expires>=?").bind(id.email.toLowerCase(),t.slice(0,10)).first();if(invite&&id.verified){await env.DB.batch([env.DB.prepare('INSERT INTO staff(user_id,name,role,domains,qualification,expires,approved_by,created) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET role=excluded.role,domains=excluded.domains,qualification=excluded.qualification,expires=excluded.expires,approved_by=excluded.approved_by').bind(id.id,invite.name,invite.role,invite.domains,invite.qualification,invite.expires,invite.approved_by,t),env.DB.prepare("UPDATE staff_invites SET status='Accepted' WHERE id=?").bind(invite.id)])}return authJSON({saved:true,profile:await profileFor(env,id.id)})}
if(path.startsWith('admin/')){const id=await identity(r,env);if(!id?.verified||id.profile?.status!=='Active'||!id.profile?.consent_at||id.email?.toLowerCase()!==env.ACADEMY_OWNER_EMAIL?.toLowerCase())authError('Only the academy owner can use this admin area.',403);
if(path==='admin/overview'&&r.method==='GET'){const count=async table=>(await env.DB.prepare('SELECT count(*) AS n FROM '+table).first()).n;return authJSON({learners:await count('profiles'),staff:await count('staff'),submissions:await count('submissions'),requests:await count('requests'),credentials:await count('credentials'),identityConfigured:!!await config(env),staffItems:(await env.DB.prepare('SELECT * FROM staff ORDER BY created DESC').all()).results,inviteItems:(await env.DB.prepare('SELECT * FROM staff_invites ORDER BY created DESC').all()).results})}
if(path==='admin/learners'&&r.method==='GET')return authJSON({items:(await env.DB.prepare('SELECT user_id,email,name,country,goal,hours,status,created,updated FROM profiles ORDER BY created DESC LIMIT 200').all()).results});
if(path==='admin/provider'&&r.method==='GET'){const cfg=await config(env);return authJSON({configured:!!cfg,url:cfg?.url||'',method:'Supabase email and password',secretsConfigured:!!env.ACADEMY_SESSION_KEY})}
if(path==='admin/provider'&&r.method==='PUT'){const b=await authBody(r);if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(b.url||'')||!/^sb_publishable_[A-Za-z0-9_-]+$/.test(b.key||''))authError('Enter the project URL and a publishable key from your Supabase project.');await env.DB.prepare("INSERT INTO settings(key,value,updated) VALUES('identity_provider',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated=excluded.updated").bind(JSON.stringify({url:b.url,key:b.key}),authNow()).run();return authJSON({saved:true,message:'Identity connection saved. Configure email confirmation, SMTP and redirect URLs in the identity project, then run a real sign-in test.'})}
if(path==='admin/staff-invites'&&r.method==='POST'){const b=await authBody(r);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.email||'')||String(b.name||'').length<2||!['Reviewer','Verifier','Reviewer and verifier'].includes(b.role)||!Array.isArray(b.domains)||!b.domains.length||b.domains.some(x=>!programmes.has(x))||String(b.qualification||'').length<60||!/^\d{4}-\d{2}-\d{2}$/.test(b.expires||'')||b.expires<authNow().slice(0,10))authError('Enter the staff member, checked qualifications, valid programme scope and review date.');if(b.email.toLowerCase()===id.email.toLowerCase())authError('Appoint a different staff member; do not approve your own qualification.');const inviteId=crypto.randomUUID();await env.DB.prepare('INSERT INTO staff_invites(id,email,name,role,domains,qualification,expires,status,approved_by,created) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,role=excluded.role,domains=excluded.domains,qualification=excluded.qualification,expires=excluded.expires,status=excluded.status,approved_by=excluded.approved_by').bind(inviteId,b.email.toLowerCase(),b.name,b.role,JSON.stringify(b.domains),b.qualification,b.expires,'Pending',id.id,authNow()).run();return authJSON({saved:true,message:'Staff appointment recorded. The matching confirmed account receives the scope on onboarding. No invitation email was sent; the matching verified account can register and claim the appointed role.'},201)}
if(path==='admin/suspend'&&r.method==='POST'){const b=await authBody(r);if(b.userId===id.id||!['Active','Suspended'].includes(b.status))authError('Choose another learner and a valid account status.');const found=await profileFor(env,b.userId);if(!found)authError('Learner not found.',404);await env.DB.batch([env.DB.prepare('UPDATE profiles SET status=?,updated=? WHERE user_id=?').bind(b.status,authNow(),b.userId),env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(b.userId)]);return authJSON({saved:true})}
}
return authJSON({error:'Account action not found.'},404);
}catch(e){if(!e.status)console.error('Account service failure',path,e.message);return authJSON({error:e.status?e.message:'The account service is unavailable. Keep your current work and try again.'},e.status||503)}}return{handle,identity};}
