import {receiptSnapshot} from './receipts.mjs';
import {teachingPlan,teachingFulfilment,teachingRevocation} from './teaching.mjs';
const fail=(m,status=400)=>{throw Object.assign(Error(m),{status})},stamp=()=>new Date().toISOString(),bytes=s=>new TextEncoder().encode(s);
const digest=async s=>hex(await crypto.subtle.digest('SHA-256',bytes(s))),hex=b=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('');
const hmac=async(text,key,hash='SHA-512')=>hex(await crypto.subtle.sign('HMAC',await crypto.subtle.importKey('raw',bytes(key),{name:'HMAC',hash},false,['sign']),bytes(text)));
const equal=(a,b)=>{if(!a||!b||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0};
const sorted=v=>Array.isArray(v)?v.map(sorted):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sorted(v[k])])):v;
export const major=(amount,currency)=>amount/10**(['ISK','UGX'].includes(currency.toUpperCase())?2:new Intl.NumberFormat('en',{style:'currency',currency:currency.toUpperCase()}).resolvedOptions().maximumFractionDigits);
const https=value=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password}catch{return false}};
export function approvedProducts(env,tracks){let products=[];try{products=JSON.parse(env.ACADEMY_LIVE_PRODUCTS||'[]')}catch{}return Array.isArray(products)?products.filter(p=>p&&/^[a-z0-9][a-z0-9-]{2,99}$/.test(p.id||'')&&(!p.providers||Array.isArray(p.providers))&&p.status==='Live'&&p.reviewApproval&&p.refundPolicy&&https(p.termsUrl)&&Number.isSafeInteger(p.amount)&&p.amount>0&&/^[a-z]{3}$/i.test(p.currency||'')&&Array.isArray(p.courseIds)&&p.courseIds.length&&p.courseIds.every(id=>tracks[id])&&Number.isInteger(p.durationDays||365)&&(p.durationDays||365)>=1&&(p.durationDays||365)<=3650).map(p=>({...p,currency:p.currency.toLowerCase()})):[]}
export function paymentAvailability(env){let assets=[];try{assets=JSON.parse(env.ACADEMY_CRYPTO_ASSETS||'[]').filter(a=>/^[a-z0-9]{2,30}$/.test(a.id)&&typeof a.label==='string')}catch{}const available={razorpay:!!(/^rzp_live_[A-Za-z0-9]{8,80}$/.test(env.RAZORPAY_KEY_ID||'')&&env.RAZORPAY_KEY_SECRET&&env.RAZORPAY_WEBHOOK_SECRET&&env.RAZORPAY_VERIFIED&&env.ACADEMY_PAYMENT_PUBLIC==='true'),stripe:!!(env.STRIPE_SECRET_KEY&&env.STRIPE_WEBHOOK_SECRET&&env.STRIPE_PUBLISHABLE_KEY),gumroad:!!(env.GUMROAD_ACCESS_TOKEN&&env.GUMROAD_WEBHOOK_SECRET&&env.GUMROAD_SELLER_ID),binance:!!(env.BINANCE_PAY_KEY&&env.BINANCE_PAY_SECRET&&env.BINANCE_PAY_PUBLIC_KEY&&env.BINANCE_PAY_CERTIFICATE_SN&&env.BINANCE_PAY_MERCHANT_ID),crypto:!!(env.NOWPAYMENTS_API_KEY&&env.NOWPAYMENTS_IPN_SECRET&&assets.length),assets};if(env.ACADEMY_PAYMENT_PUBLIC==='false')for(const provider of ['razorpay','stripe','gumroad','binance','crypto'])available[provider]=false;return available}
export function purchaseTerms(p){return {title:p.title||p.id,amount:p.amount,currency:p.currency.toLowerCase(),courseIds:p.courseIds,durationDays:p.durationDays||365,termsUrl:p.termsUrl,refundPolicy:p.refundPolicy,teachingPlan:p.teachingPlan||null}}
export function publicProduct(p,env){const ready=paymentAvailability(env),providers=(p.providers||['stripe']).filter(x=>ready[x]&&(x!=='razorpay'||p.currency.toLowerCase()==='inr')&&(x!=='stripe'||p.priceId)&&(x!=='gumroad'||p.gumroadProductId&&p.currency.toLowerCase()==='usd'&&https(p.gumroadUrl)));return {id:p.id,title:p.title||p.id,amount:p.amount,currency:p.currency,courseIds:p.courseIds,durationDays:p.durationDays||365,termsUrl:p.termsUrl,refundPolicy:p.refundPolicy,teachingPlan:p.teachingPlan||null,purchaseTerms:purchaseTerms(p),providers}}
async function providerFetch(url,init){const r=await fetch(url,{...init,signal:AbortSignal.timeout(15000)});let b;try{b=await r.json()}catch{fail('The payment provider could not be reached. Your order remains unpaid.',502)}if(!r.ok)fail('The payment provider could not complete this request. No learning access was granted.',502);return b}
export async function binanceCall(env,path,data){const body=JSON.stringify(data),t=String(Date.now()),nonce=crypto.randomUUID().replaceAll('-',''),signature=(await hmac(t+'\n'+nonce+'\n'+body+'\n',env.BINANCE_PAY_SECRET)).toUpperCase();return providerFetch('https://bpay.binanceapi.com'+path,{method:'POST',headers:{'content-type':'application/json','BinancePay-Timestamp':t,'BinancePay-Nonce':nonce,'BinancePay-Certificate-SN':env.BINANCE_PAY_KEY,'BinancePay-Signature':signature},body})}
async function fulfil(db,order,scope,eventId,details){const s=(q,...a)=>db.prepare(q).bind(...a),time=stamp();if(!['Awaiting payment','Paid'].includes(order.status))fail('This order is not eligible for payment fulfilment.',409);const scopes=JSON.parse(scope.scopes),expires=new Date(Date.now()+scope.duration_days*86400000).toISOString();await db.batch([s("UPDATE orders SET status='Paid' WHERE id=? AND status='Awaiting payment'",order.id),s("INSERT OR IGNORE INTO payment_receipts(order_id,body,refunded_amount) SELECT ?,?,0 WHERE EXISTS(SELECT 1 FROM orders WHERE id=? AND status='Paid')",order.id,JSON.stringify(receiptSnapshot(order,scope,time)),order.id),...scopes.map(c=>s("INSERT OR IGNORE INTO entitlements(id,user_id,course_id,source_id,status,expires,created) SELECT ?,?,?,?,'Active',?,? WHERE EXISTS(SELECT 1 FROM orders WHERE id=? AND status='Paid')",crypto.randomUUID(),order.user_id,c,order.id,expires,time,order.id)),...teachingFulfilment(db,order,scope,time),s('INSERT OR IGNORE INTO payment_events(id,body,created) VALUES(?,?,?)',eventId,JSON.stringify(details),time)]);const current=await s('SELECT status FROM orders WHERE id=?',order.id).first();return {paid:current.status==='Paid',status:current.status,orderId:order.id}}

async function revoke(db,order,status){const s=(q,...a)=>db.prepare(q).bind(...a);await db.batch([s('UPDATE orders SET status=? WHERE id=?',status,order.id),s("UPDATE entitlements SET status='Revoked' WHERE source_id=?",order.id),...teachingRevocation(db,order.id,stamp())]);return {status}}
async function gumroadSale(env,saleId){if(!/^[A-Za-z0-9_=\-]{5,120}$/.test(saleId||''))fail('Enter the purchase ID from your Gumroad receipt.');const result=await providerFetch('https://api.gumroad.com/v2/sales/'+encodeURIComponent(saleId)+'?access_token='+encodeURIComponent(env.GUMROAD_ACCESS_TOKEN),{method:'GET'});return result.success?result.sale:null}
function gumroadMatches(p,env,order,meta){return p&&p.seller_id===env.GUMROAD_SELLER_ID&&p.purchaser_id!==p.seller_id&&p.product_id===meta.productId&&p.email?.toLowerCase()===meta.email&&p.price===order.amount&&p.currency?.toLowerCase()===order.currency.toLowerCase()&&p.paid===true&&!p.is_recurring_charge&&!p.subscription_id&&!p.is_preorder_authorization}
async function gumroadSuccessful(env,p){
 // A sale lookup can include failed/test records. The authenticated Sales list filters to successful charges (or free trials); a paid one-off sale must also appear there.
 const query=new URLSearchParams({access_token:env.GUMROAD_ACCESS_TOKEN,product_id:p.product_id,email:p.email});if(Number.isFinite(Date.parse(p.created_at))){const day=new Date(p.created_at);query.set('after',day.toISOString().slice(0,10));query.set('before',new Date(+day+2*86400000).toISOString().slice(0,10))}
 for(let page=0;page<10;page++){const data=await providerFetch('https://api.gumroad.com/v2/sales?'+query,{method:'GET'});if(!data.success||!Array.isArray(data.sales))return false;if(data.sales.some(s=>s.id===p.id))return true;if(!data.next_page_url)return false;const next=new URL(data.next_page_url,'https://api.gumroad.com');if(next.origin!=='https://api.gumroad.com'||next.pathname!=='/v2/sales'||!next.searchParams.get('page_key'))return false;query.set('page_key',next.searchParams.get('page_key'))}return false;
}
export async function reconcilePayment(env,order){const db=env.DB,s=(q,...a)=>db.prepare(q).bind(...a),provider=await s('SELECT * FROM payment_providers WHERE order_id=?',order.id).first(),scope=await s('SELECT * FROM order_access WHERE order_id=?',order.id).first();if(!provider||!scope)return {status:order.status};const meta=JSON.parse(provider.body);
 if(provider.provider==='razorpay')return reconcileRazorpay(env,order,provider,scope);
 if(provider.provider==='binance'){const b=await binanceCall(env,'/binancepay/openapi/order/query',{merchantTradeNo:meta.tradeNo,prepayId:provider.reference});const p=b.data;if(b.status!=='SUCCESS'||!p||String(p.prepayId)!==provider.reference||p.merchantTradeNo!==meta.tradeNo||String(p.merchantId)!==String(env.BINANCE_PAY_MERCHANT_ID))fail('The wallet payment could not be matched to this merchant order.',409);if(meta.quoteCurrency&&meta.quoteAmount){if(p.currency?.toLowerCase()!==meta.quoteCurrency.toLowerCase()||Number(p.totalFee)!==meta.quoteAmount)fail('Wallet quote does not match the stored purchase.',409)}else if(p.fiatCurrency&&p.fiatAmount!=null){if(p.fiatCurrency.toLowerCase()!==order.currency.toLowerCase()||Number(p.fiatAmount)!==major(order.amount,order.currency))fail('Wallet amount does not match the order.',409)}else if(p.currency.toLowerCase()!==order.currency.toLowerCase()||Number(p.totalFee)!==major(order.amount,order.currency))fail('Wallet amount does not match the order.',409);if(p.status==='REFUNDED')return revoke(db,order,'Refunded');if(p.status==='PAID')return fulfil(db,order,scope,'binance:'+p.transactionId,{provider:'binance',reference:p.transactionId});return {status:p.status};}
 if(provider.provider==='crypto'){const p=await providerFetch('https://api.nowpayments.io/v1/payment/'+encodeURIComponent(provider.reference),{headers:{'x-api-key':env.NOWPAYMENTS_API_KEY}});if(String(p.payment_id)!==provider.reference||p.order_id!==order.id||p.price_currency.toLowerCase()!==order.currency.toLowerCase()||Number(p.price_amount)!==major(order.amount,order.currency)||p.pay_currency!==meta.payCurrency)fail('Crypto payment does not match the stored order.',409);if(p.payment_status==='refunded')return revoke(db,order,'Refunded');if(p.payment_status==='finished'&&Number(p.actually_paid)>=Number(meta.payAmount))return fulfil(db,order,scope,'crypto:'+provider.reference,{provider:'crypto',reference:provider.reference});return {status:p.payment_status};}
 if(provider.provider==='gumroad'&&provider.reference){const p=await gumroadSale(env,provider.reference);if(!gumroadMatches(p,env,order,meta))fail('Gumroad purchase does not match this order.',409);if(p.refunded||p.disputed||p.chargedback||p.access_revoked)return revoke(db,order,p.disputed||p.chargedback?'Disputed':p.refunded?'Refunded':'Access withdrawn');if(!await gumroadSuccessful(env,p))fail('The provider has not confirmed a successful paid sale.',409);return fulfil(db,order,scope,'gumroad:'+provider.reference,{provider:'gumroad',reference:provider.reference});}
 return {status:order.status};
}
export async function handleCheckout(path,method,b,{env,db,id,tracks}){
const s=(q,...a)=>db.prepare(q).bind(...a),one=(q,...a)=>s(q,...a).first(),origin=new URL(b.requestURL).origin;
if(path==='payment/config'&&method==='GET'){return {...paymentAvailability(env),publishableKey:env.STRIPE_PUBLISHABLE_KEY||null,products:approvedProducts(env,tracks).map(p=>publicProduct(p,env))}}
if(path==='payment/session'&&method==='POST'){
 const p=approvedProducts(env,tracks).find(p=>p.id===b.productId),available=paymentAvailability(env),provider=b.provider;if(!p||!publicProduct(p,env).providers.includes(provider)||!available[provider])fail('This purchase method is not available for this course.',409);if(!/^[a-zA-Z0-9-]{16,80}$/.test(b.requestKey||''))fail('A checkout request key is required.');if(b.acceptTerms!==true)fail('Accept the displayed purchase and refund terms first.');const terms=purchaseTerms(p);if(JSON.stringify(sorted(b.expectedTerms))!==JSON.stringify(sorted(terms)))fail('Purchase details changed. Reopen checkout and review the current price and terms.',409);const plan=teachingPlan(p,p.courseIds);if(plan.courseId){const teachers=(await s("SELECT domains FROM staff WHERE role='Mentor' AND expires>=?",stamp().slice(0,10)).all()).results||[];if(!teachers.some(t=>JSON.parse(t.domains).includes(plan.courseId)))fail('Teacher-supported enrolment for this course is not open yet.',409)}
 const oid='order-'+(await digest(id.id+'|'+p.id+'|'+provider+'|'+b.requestKey)).slice(0,40),old=await one('SELECT * FROM orders WHERE id=?',oid);if(old&&!['Preparing checkout','Awaiting payment'].includes(old.status))fail('This order is already final. Check your orders before beginning a new purchase.',409);if(old&&(old.amount!==p.amount||old.currency!==p.currency))fail('Purchase terms changed. Begin a new purchase.',409);
 await db.batch([s('INSERT OR IGNORE INTO orders(id,user_id,product_id,status,amount,currency,created) VALUES(?,?,?,?,?,?,?)',oid,id.id,p.id,'Preparing checkout',p.amount,p.currency,stamp()),s('INSERT OR IGNORE INTO order_access(order_id,scopes,duration_days,product_title,teaching_plan,purchase_terms) VALUES(?,?,?,?,?,?)',oid,JSON.stringify(p.courseIds),p.durationDays||365,p.title||p.id,JSON.stringify(plan),JSON.stringify(terms))]);const scope=await one('SELECT * FROM order_access WHERE order_id=?',oid);if(scope.scopes!==JSON.stringify(p.courseIds)||scope.duration_days!==(p.durationDays||365)||scope.teaching_plan!==JSON.stringify(plan)||scope.purchase_terms!==JSON.stringify(terms))fail('Purchase scope changed. Begin a new order.',409);
 const stored=await one('SELECT * FROM payment_providers WHERE order_id=?',oid);if((stored?.reference||stored&&JSON.parse(stored.body).public?.url)&&provider!=='stripe'){const meta=JSON.parse(stored.body);return {orderId:oid,provider,...meta.public}}
 const claimed=await s('INSERT OR IGNORE INTO payment_providers(order_id,provider,body,updated) VALUES(?,?,?,?)',oid,provider,'{}',stamp()).run();if(!claimed.meta.changes&&(!stored||!stored.reference))fail('Checkout preparation is already in progress. Check your order before trying again.',409);
 let reference=null,meta={},publicData={};
 if(provider==='razorpay'){const receipt='db_'+(await digest(oid)).slice(0,32),result=await razorpayCall(env,'/orders',{amount:p.amount,currency:'INR',receipt,partial_payment:false,notes:{academy_order_id:oid}});if(!/^order_[A-Za-z0-9]+$/.test(result.id||'')||result.amount!==p.amount||result.currency!=='INR'||result.receipt!==receipt||result.notes?.academy_order_id!==oid||result.status!=='created'||result.amount_paid!==0)fail('The merchant order could not be matched to the approved purchase.',409);reference=result.id;meta={receipt};let business={};try{business=JSON.parse(env.ACADEMY_BUSINESS||'{}')}catch{}publicData={keyId:env.RAZORPAY_KEY_ID,providerOrderId:result.id,amount:p.amount,currency:'INR',businessName:business.name||'DigitalBurj Academy',title:p.title||p.id};}
 if(provider==='stripe'){if(!p.priceId)fail('This price is not approved for card checkout.',409);const form=new URLSearchParams({mode:'payment',ui_mode:'elements','line_items[0][price]':p.priceId,'line_items[0][quantity]':'1',client_reference_id:oid,return_url:origin+'/dashboard?checkout=returned#receipt/'+oid,'metadata[order_id]':oid});const r=await providerFetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:'Bearer '+env.STRIPE_SECRET_KEY,'content-type':'application/x-www-form-urlencoded','Idempotency-Key':oid},body:form});if(r.amount_total!==p.amount||r.currency?.toLowerCase()!==p.currency.toLowerCase())fail('The provider price does not match the approved course price. No payment form was opened.',409);if(!r.id||!r.client_secret)fail('Secure card checkout is unavailable. No access was granted.',502);reference=r.id;publicData={clientSecret:r.client_secret,publishableKey:env.STRIPE_PUBLISHABLE_KEY};}
 if(provider==='gumroad'){if(!p.gumroadProductId||!https(p.gumroadUrl))fail('This Gumroad product is not configured.',409);const u=new URL(p.gumroadUrl);if(u.hostname!=='gumroad.com'&&!u.hostname.endsWith('.gumroad.com'))fail('Unexpected Gumroad checkout destination.',409);publicData={url:u.href};meta={productId:p.gumroadProductId,email:id.email.toLowerCase()};}
 if(provider==='binance'){const tradeNo=oid.slice(6,38);const r=await binanceCall(env,'/binancepay/openapi/v3/order',{env:{terminalType:'WEB'},merchantTradeNo:tradeNo,fiatAmount:major(p.amount,p.currency),fiatCurrency:p.currency.toUpperCase(),description:(p.title||p.id).slice(0,200),goodsDetails:[{goodsType:'02',goodsCategory:'D000',referenceGoodsId:p.id.slice(0,32),goodsName:(p.title||p.id).slice(0,200)}],returnUrl:origin+'/dashboard#receipt/'+oid,cancelUrl:origin+'/dashboard#receipt/'+oid,webhookUrl:origin+'/api/payments/binance'});if(r.status!=='SUCCESS'||!r.data?.prepayId||!https(r.data.checkoutUrl)||!new URL(r.data.checkoutUrl).hostname.endsWith('.binance.com'))fail('Binance could not create a merchant checkout.',502);reference=String(r.data.prepayId);publicData={url:r.data.checkoutUrl};if(r.data.fiatCurrency?.toLowerCase()!==p.currency.toLowerCase()||Number(r.data.fiatAmount)!==major(p.amount,p.currency)||!r.data.currency||!Number.isFinite(Number(r.data.totalFee))||Number(r.data.totalFee)<=0)fail('Binance quote does not match the approved price.',409);meta={tradeNo,quoteCurrency:r.data.currency,quoteAmount:Number(r.data.totalFee)};}
 if(provider==='crypto'){const asset=available.assets.find(a=>a.id===b.payCurrency);if(!asset)fail('Choose an approved asset and network.');const pmt=await providerFetch('https://api.nowpayments.io/v1/payment',{method:'POST',headers:{'content-type':'application/json','x-api-key':env.NOWPAYMENTS_API_KEY},body:JSON.stringify({price_amount:major(p.amount,p.currency),price_currency:p.currency.toLowerCase(),pay_currency:asset.id,order_id:oid,order_description:p.title||p.id,ipn_callback_url:origin+'/api/payments/crypto',is_fixed_rate:true,is_fee_paid_by_user:false})});if(!pmt.payment_id||!pmt.pay_address||!Number.isFinite(Number(pmt.pay_amount))||Number(pmt.pay_amount)<=0||pmt.pay_currency!==asset.id)fail('Crypto checkout is unavailable. No access was granted.',502);reference=String(pmt.payment_id);publicData={payAddress:pmt.pay_address,payAmount:pmt.pay_amount,payCurrency:asset.id,assetLabel:asset.label};meta={payAmount:pmt.pay_amount,payCurrency:asset.id};}
 await db.batch([s("UPDATE orders SET session_id=?,status='Awaiting payment' WHERE id=? AND status IN ('Preparing checkout','Awaiting payment')",provider==='stripe'?reference:null,oid),s('INSERT INTO payment_providers(order_id,provider,reference,body,updated) VALUES(?,?,?,?,?) ON CONFLICT(order_id) DO UPDATE SET reference=excluded.reference,body=excluded.body,updated=excluded.updated',oid,provider,reference,JSON.stringify({...meta,public:provider==='stripe'?{}:publicData}),stamp())]);return {orderId:oid,provider,...publicData};
}
if(path==='payment/razorpay/confirm'&&method==='POST'){const order=await one('SELECT * FROM orders WHERE id=? AND user_id=?',b.orderId,id.id),provider=order&&await one("SELECT * FROM payment_providers WHERE order_id=? AND provider='razorpay'",order.id);if(!order||!provider)fail('This merchant order is not available to you.',404);if(!/^pay_[A-Za-z0-9]+$/.test(b.paymentId||'')||b.providerOrderId!==provider.reference||!equal(await hmac(provider.reference+'|'+b.paymentId,env.RAZORPAY_KEY_SECRET,'SHA-256'),b.signature))fail('The payment confirmation signature is invalid.',400);const scope=await one('SELECT * FROM order_access WHERE order_id=?',order.id);return reconcileRazorpay(env,order,provider,scope,b.paymentId)}
if(['payment/status','payment/gumroad/claim'].includes(path)&&method==='POST'){
 const o=await one('SELECT * FROM orders WHERE id=? AND user_id=?',b.orderId,id.id);if(!o)fail('This order is not available to you.',404);if(path==='payment/gumroad/claim'){const p=await one("SELECT * FROM payment_providers WHERE order_id=? AND provider='gumroad'",o.id);if(!p)fail('This is not a Gumroad order.');const data=JSON.parse(p.body),sale=await gumroadSale(env,b.saleId);if(sale?.id!==b.saleId||!gumroadMatches(sale,env,o,data)||sale.refunded||sale.disputed||sale.chargedback||sale.access_revoked||!await gumroadSuccessful(env,sale))fail('Use a confirmed, unrefunded purchase for this product and the same account email.',409);const used=await one("SELECT order_id FROM payment_providers WHERE provider='gumroad' AND reference=?",sale.id);if(used&&used.order_id!==o.id)fail('This purchase has already been linked to an order.',409);const linked=await s('UPDATE payment_providers SET reference=?,updated=? WHERE order_id=? AND (reference IS NULL OR reference=?)',sale.id,stamp(),o.id,sale.id).run();if(!linked.meta.changes)fail('This order already has a different purchase reference.',409);}
 return reconcilePayment(env,o);
}
fail('Payment action not found.',404);
}
export async function alternativeWebhook(r,env){const json=(b,status=200)=>new Response(JSON.stringify(b),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});try{if(!env.DB)fail('Payment storage unavailable.',503);const raw=await r.text();if(bytes(raw).length>100000)fail('Notification too large.',413);const gumroad=new URL(r.url).pathname.endsWith('/gumroad');if(gumroad){if(!env.GUMROAD_ACCESS_TOKEN||!equal(new URL(r.url).searchParams.get('hook'),env.GUMROAD_WEBHOOK_SECRET))fail('Invalid notification.',400);const body=r.headers.get('content-type')?.includes('application/json')?JSON.parse(raw):Object.fromEntries(new URLSearchParams(raw));if(!/^[A-Za-z0-9_=\-]{5,120}$/.test(body.sale_id||''))fail('Invalid sale reference.',400);const provider=await env.DB.prepare("SELECT order_id FROM payment_providers WHERE provider='gumroad' AND reference=?").bind(body.sale_id).first();if(!provider)return json({received:true,unlinked:true});await reconcilePayment(env,await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(provider.order_id).first());return json({received:true})}const b=JSON.parse(raw),binance=new URL(r.url).pathname.endsWith('/binance');
 if(new URL(r.url).pathname.endsWith('/razorpay')){if(!env.RAZORPAY_WEBHOOK_SECRET||!equal(await hmac(raw,env.RAZORPAY_WEBHOOK_SECRET,'SHA-256'),r.headers.get('x-razorpay-signature')))fail('Invalid payment notification signature.',400);if(!['payment.captured','order.paid','refund.processed','payment.dispute.created','payment.dispute.under_review','payment.dispute.lost'].includes(b.event))return json({received:true,ignored:true});const paymentId=b.payload?.payment?.entity?.id||b.payload?.refund?.entity?.payment_id;let reference=b.payload?.payment?.entity?.order_id||b.payload?.order?.entity?.id;if(!reference&&/^pay_[A-Za-z0-9]+$/.test(paymentId||''))reference=(await razorpayCall(env,'/payments/'+paymentId)).order_id;if(!/^order_[A-Za-z0-9]+$/.test(reference||''))fail('Payment order reference is missing.',400);const provider=await env.DB.prepare("SELECT * FROM payment_providers WHERE provider='razorpay' AND reference=?").bind(reference).first();if(!provider)fail('This merchant order is not reconciled yet. Retry.',409);const order=await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(provider.order_id).first(),scope=await env.DB.prepare('SELECT * FROM order_access WHERE order_id=?').bind(provider.order_id).first();if(b.event.startsWith('payment.dispute.')){const disputeId=b.payload?.dispute?.entity?.id;if(!/^disp_[A-Za-z0-9]+$/.test(disputeId||''))fail('Invalid dispute reference.',400);const dispute=await razorpayCall(env,'/disputes/'+disputeId),payment=await razorpayCall(env,'/payments/'+dispute.payment_id);if(dispute.id!==disputeId||dispute.payment_id!==paymentId||payment.order_id!==provider.reference||payment.amount!==order.amount||payment.currency?.toLowerCase()!==order.currency||dispute.currency?.toLowerCase()!==order.currency||!Number.isSafeInteger(dispute.amount)||dispute.amount<=0||dispute.amount>order.amount)fail('The disputed payment does not match this merchant order.',409);if(['open','under_review','lost','closed'].includes(dispute.status)){await revoke(env.DB,order,'Disputed');return json({received:true})}return json({received:true,ignored:true})}await reconcileRazorpay(env,order,provider,scope,paymentId);return json({received:true})}
 if(binance){const t=r.headers.get('BinancePay-Timestamp'),nonce=r.headers.get('BinancePay-Nonce'),sig=r.headers.get('BinancePay-Signature');if(!env.BINANCE_PAY_PUBLIC_KEY||r.headers.get('BinancePay-Certificate-SN')!==env.BINANCE_PAY_CERTIFICATE_SN||!/^\d+$/.test(t||'')||Math.abs(Date.now()-Number(t))>300000||!nonce||nonce.length!==32||!sig)fail('Invalid payment notification.',400);const pem=env.BINANCE_PAY_PUBLIC_KEY.replace(/-----[^-]+-----|\s/g,''),key=await crypto.subtle.importKey('spki',Uint8Array.from(atob(pem),c=>c.charCodeAt(0)),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);if(!await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,Uint8Array.from(atob(sig),c=>c.charCodeAt(0)),bytes(t+'\n'+nonce+'\n'+raw+'\n')))fail('Invalid payment signature.',400);const data=typeof b.data==='string'?JSON.parse(b.data):b.data;const provider=await env.DB.prepare("SELECT order_id FROM payment_providers WHERE provider='binance' AND reference=?").bind(String(data?.prepayId||b.bizId||'')).first();if(!provider)fail('Order is not reconciled yet. Retry.',409);const order=await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(provider.order_id).first();await reconcilePayment(env,order);return json({returnCode:'SUCCESS',returnMessage:null});
 }if(!env.NOWPAYMENTS_IPN_SECRET||!equal((await hmac(JSON.stringify(sorted(b)),env.NOWPAYMENTS_IPN_SECRET)),r.headers.get('x-nowpayments-sig')))fail('Invalid payment signature.',400);const provider=await env.DB.prepare("SELECT order_id FROM payment_providers WHERE provider='crypto' AND reference=?").bind(String(b.payment_id||'')).first();if(!provider)fail('Order is not reconciled yet. Retry.',409);const order=await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(provider.order_id).first();await reconcilePayment(env,order);return json({received:true});
}catch(e){return json({error:e.status?e.message:'Notification could not be reconciled. Retry.'},e.status||503)}}
async function razorpayCall(env,path,body){if(!env.RAZORPAY_KEY_ID||!env.RAZORPAY_KEY_SECRET)fail('Razorpay is not connected.',409);return providerFetch('https://api.razorpay.com/v1'+path,{method:body?'POST':'GET',headers:{Authorization:'Basic '+btoa(env.RAZORPAY_KEY_ID+':'+env.RAZORPAY_KEY_SECRET),'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})})}
async function reconcileRazorpay(env,order,provider,scope,paymentId){if(!scope||!/^order_[A-Za-z0-9]+$/.test(provider.reference||''))fail('The stored merchant order is incomplete.',409);const meta=JSON.parse(provider.body),external=await razorpayCall(env,'/orders/'+provider.reference);if(external.id!==provider.reference||external.amount!==order.amount||external.currency?.toLowerCase()!==order.currency||external.receipt!==meta.receipt||external.notes?.academy_order_id!==order.id)fail('The merchant order does not match this purchase.',409);let p;if(paymentId){if(!/^pay_[A-Za-z0-9]+$/.test(paymentId))fail('Invalid payment reference.');p=await razorpayCall(env,'/payments/'+paymentId)}else{const list=await razorpayCall(env,'/orders/'+provider.reference+'/payments');p=list.items?.find(p=>['captured','refunded'].includes(p.status))}if(!p)return {status:order.status};if(p.order_id!==provider.reference||p.amount!==order.amount||p.currency?.toLowerCase()!==order.currency||!/^pay_[A-Za-z0-9]+$/.test(p.id||''))fail('The payment does not match the stored purchase.',409);if(external.status!=='paid'||external.amount_paid!==order.amount||external.amount_due!==0)return {status:order.status};if(!Number.isSafeInteger(p.amount_refunded)||p.amount_refunded<0||p.amount_refunded>order.amount)fail('The refund amount could not be reconciled.',409);if(p.amount_refunded===order.amount){await env.DB.prepare('UPDATE payment_receipts SET refunded_amount=? WHERE order_id=?').bind(p.amount_refunded,order.id).run();return revoke(env.DB,order,'Refunded')}if(['Refunded','Disputed','Access withdrawn'].includes(order.status))return {status:order.status};if(p.status!=='captured'||p.captured!==true)return {status:order.status};const result=await fulfil(env.DB,order,scope,'razorpay:'+p.id,{provider:'razorpay',reference:p.id});await env.DB.batch([env.DB.prepare('UPDATE payment_receipts SET refunded_amount=? WHERE order_id=?').bind(p.amount_refunded,order.id),env.DB.prepare("INSERT OR IGNORE INTO audit(id,actor,action,record,details,created) VALUES(?,?,'payment_confirmed',?,'{}',?)").bind('razorpay:'+p.id,order.user_id,order.id,stamp())]);return result}
