const enc=new TextEncoder(),fail=(message,status=400)=>{throw Object.assign(Error(message),{status})};
const key=async(secret)=>{if(!/^[a-f0-9]{64}$/.test(secret||''))fail('Secure merchant storage is unavailable. Contact the owner.',503);return crypto.subtle.importKey('raw',Uint8Array.from(secret.match(/../g),x=>parseInt(x,16)),{name:'AES-GCM'},false,['encrypt','decrypt'])};
const aad=enc.encode('DigitalBurj:merchant:version1');
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));
async function seal(value,secret){const iv=crypto.getRandomValues(new Uint8Array(12)),body=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad},await key(secret),enc.encode(JSON.stringify(value)));return JSON.stringify({version:1,iv:b64(iv),body:b64(body)})}
async function open(value,secret){const b=JSON.parse(value),bytes=x=>Uint8Array.from(atob(x),c=>c.charCodeAt(0));if(b.version!==1)fail('Merchant connection must be restored by the owner.',503);try{return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(b.iv),additionalData:aad},await key(secret),bytes(b.body))))}catch{fail('Merchant connection must be restored by the owner.',503)}}
async function setting(env,name){return env.DB?.prepare('SELECT value FROM settings WHERE key=?').bind(name).first()}
async function save(env,name,value){return env.DB.prepare('INSERT INTO settings(key,value,updated) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated=excluded.updated').bind(name,value,new Date().toISOString()).run()}
export async function commercialEnv(env){if(!env.DB)return env;const [merchant,products,business]=await Promise.all([setting(env,'merchant_razorpay'),setting(env,'commercial_products'),setting(env,'commercial_business')]);let effective={...env};if(merchant){const m=await open(merchant.value,env.ACADEMY_SESSION_KEY);effective={...effective,RAZORPAY_KEY_ID:m.keyId,RAZORPAY_KEY_SECRET:m.keySecret,RAZORPAY_WEBHOOK_SECRET:m.webhookSecret,RAZORPAY_VERIFIED:m.verifiedAt}}if(products)effective.ACADEMY_LIVE_PRODUCTS=products.value;if(business)effective.ACADEMY_BUSINESS=business.value;return effective}
export async function merchantStatus(env){const e=await commercialEnv(env);let business={},products=[];try{business=JSON.parse(e.ACADEMY_BUSINESS||'{}');products=JSON.parse(e.ACADEMY_LIVE_PRODUCTS||'[]')}catch{}return {business,products,razorpay:{configured:!!(e.RAZORPAY_KEY_ID&&e.RAZORPAY_KEY_SECRET&&e.RAZORPAY_WEBHOOK_SECRET),mode:e.RAZORPAY_KEY_ID?.startsWith('rzp_live_')?'Live':e.RAZORPAY_KEY_ID?.startsWith('rzp_test_')?'Test':'Not connected',verifiedAt:e.RAZORPAY_VERIFIED||null},publicPaymentsReady:env.ACADEMY_PAYMENT_PUBLIC==='true',webhookPath:'/api/payments/razorpay',webhookEvents:['payment.captured','order.paid','refund.processed','payment.dispute.created','payment.dispute.under_review','payment.dispute.lost'],registrationRequired:true}}
export async function connectRazorpay(env,b){const old=await setting(env,'merchant_razorpay'),previous=old?await open(old.value,env.ACADEMY_SESSION_KEY):{},m={keyId:b.keyId?.trim()||previous.keyId,keySecret:b.keySecret?.trim()||previous.keySecret,webhookSecret:b.webhookSecret?.trim()||previous.webhookSecret};if(!/^rzp_(live|test)_[A-Za-z0-9]{8,80}$/.test(m.keyId||'')||typeof m.keySecret!=='string'||m.keySecret.length<12||m.keySecret.length>200||typeof m.webhookSecret!=='string'||m.webhookSecret.length<16||m.webhookSecret.length>200)fail('Enter the merchant key ID, key secret and a webhook secret of at least 16 characters.');let r;try{r=await fetch('https://api.razorpay.com/v1/orders?count=1',{headers:{Authorization:'Basic '+btoa(m.keyId+':'+m.keySecret)},signal:AbortSignal.timeout(15000)})}catch{fail('Razorpay could not be reached. Your previous connection has been kept.',502)}if(!r.ok)fail('Razorpay did not accept these merchant credentials. Check the merchant dashboard.',409);await r.body?.cancel();m.verifiedAt=new Date().toISOString();await save(env,'merchant_razorpay',await seal(m,env.ACADEMY_SESSION_KEY));return {saved:true,mode:m.keyId.startsWith('rzp_live_')?'Live':'Test',message:'Credentials verified. Add the webhook in Razorpay and publish approved offers before accepting students.'}}
export async function saveBusiness(env,b){const email=String(b.supportEmail||'').trim().toLowerCase(),name=String(b.name||'').trim(),url=String(b.termsUrl||'');if(name.length<2||name.length>120||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!/^https:\/\//.test(url)||url.length>1000)fail('Enter your business name, support email and HTTPS purchase terms URL.');let u;try{u=new URL(url)}catch{fail('Enter a valid HTTPS purchase terms URL.')}if(u.protocol!=='https:'||u.username||u.password)fail('Enter a valid HTTPS purchase terms URL.');await save(env,'commercial_business',JSON.stringify({name,supportEmail:email,termsUrl:u.href,country:'India',currency:'INR'}));return {saved:true}}
export async function saveProducts(env,b,tracks){if(!Array.isArray(b.products)||b.products.length>60)fail('Provide up to 60 course offers.');const seen=new Set();const products=b.products.map(p=>{if(!/^[a-z0-9-]{3,80}$/.test(p.id||'')||seen.has(p.id))fail('Use a unique offer ID with lowercase letters, numbers and hyphens.');seen.add(p.id);if(typeof p.title!=='string'||p.title.trim().length<3||p.title.length>160||!['Draft','Live'].includes(p.status)||!Number.isSafeInteger(p.amount)||p.amount<=0||p.amount>100000000||String(p.currency).toUpperCase()!=='INR'||!Array.isArray(p.courseIds)||!p.courseIds.length||p.courseIds.some(x=>!tracks[x])||new Set(p.courseIds).size!==p.courseIds.length||!Number.isInteger(p.durationDays)||p.durationDays<1||p.durationDays>3650)fail('Each offer needs a title, INR amount in paise, valid courses and access duration.');let u;try{u=new URL(p.termsUrl)}catch{fail('Each offer needs its HTTPS purchase terms.')}if(u.protocol!=='https:'||u.username||u.password||String(p.refundPolicy||'').trim().length<20||String(p.refundPolicy).length>4000)fail('Record the actual HTTPS terms and refund policy for each offer.');if(p.status==='Live'&&p.approved!==true)fail('Approve the actual price, included courses and terms before publishing an offer.');const plan=p.teacherCourseId?{courseId:p.teacherCourseId,weeks:8,classes:24,minutes:120,perWeek:3}:null;if(plan&&(!p.courseIds.includes(plan.courseId)||p.durationDays<56))fail('A teaching bundle needs its course and at least 56 days of course access.');return {id:p.id,title:p.title.trim(),status:p.status,amount:p.amount,currency:'inr',courseIds:p.courseIds,durationDays:p.durationDays,providers:['razorpay'],termsUrl:u.href,refundPolicy:p.refundPolicy.trim(),reviewApproval:p.approved===true?'Owner approved '+new Date().toISOString():'',...(plan?{teachingPlan:plan}:{})}});await save(env,'commercial_products',JSON.stringify(products));return {saved:true,count:products.length}}
