import {merchantStatus,connectRazorpay,saveBusiness,saveProducts} from './commercial.mjs';
import {professionalAccess} from './access.mjs';
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status})},now=()=>new Date().toISOString();
export function recordActivity(db,actor,action,record,details={}){return db.prepare('INSERT INTO audit(id,actor,action,record,details,created) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),actor,action,record,JSON.stringify(details),now())}
export async function claimLaunchAccount(env,id){if(!id?.verified||!id.profile?.consent_at||id.profile.status!=='Active')return;const db=env.DB,s=(q,...a)=>db.prepare(q).bind(...a),row=await s("SELECT * FROM launch_accounts WHERE email=? AND status='Awaiting registration' AND user_id IS NULL AND expires>=?",id.email.toLowerCase(),now().slice(0,10)).first();if(!row)return;const domains=JSON.parse(row.domains),time=now(),expiry=row.expires+'T23:59:59.999Z';await db.batch([s("UPDATE launch_accounts SET user_id=?,status='Active',updated=? WHERE id=? AND user_id IS NULL AND status='Awaiting registration'",id.id,time,row.id),...(row.kind==='Mentor'?[s("INSERT INTO staff(user_id,name,role,domains,qualification,expires,approved_by,created) SELECT ?,?,'Mentor',?,?,?,?,? WHERE EXISTS(SELECT 1 FROM launch_accounts WHERE id=? AND user_id=? AND status='Active') ON CONFLICT(user_id) DO UPDATE SET name=excluded.name,role=excluded.role,domains=excluded.domains,qualification=excluded.qualification,expires=excluded.expires,approved_by=excluded.approved_by",id.id,row.name,row.domains,row.qualification,row.expires,row.approved_by,time,row.id,id.id)]:[]),...domains.map(c=>s("INSERT INTO entitlements(id,user_id,course_id,source_id,status,expires,created) SELECT ?,?,?,?,'Active',?,? WHERE EXISTS(SELECT 1 FROM launch_accounts WHERE id=? AND user_id=? AND status='Active') ON CONFLICT(user_id,course_id,source_id) DO UPDATE SET status='Active',expires=excluded.expires",crypto.randomUUID(),id.id,c,'launch:'+row.id,expiry,time,row.id,id.id)),s("INSERT INTO audit(id,actor,action,record,details,created) SELECT ?,?,'account_access_activated',?,'{}',? WHERE EXISTS(SELECT 1 FROM launch_accounts WHERE id=? AND user_id=? AND status='Active')",crypto.randomUUID(),id.id,row.id,time,row.id,id.id)])}
export async function handleOperations(path,method,b,{env,db,id,owner,staff,atlas,tracks,curriculum}){
const s=(q,...a)=>db.prepare(q).bind(...a),one=(q,...a)=>s(q,...a).first(),all=async(q,...a)=>(await s(q,...a).all()).results||[],time=now(),mustOwn=()=>{if(!owner)fail('Only the Academy administrator can use launch settings.',403)};
if(path==='activity'&&method==='GET')return {items:await all('SELECT action,record,created FROM audit WHERE actor=? ORDER BY created DESC LIMIT 100',id.id),orders:await all('SELECT id,status,amount,currency,created FROM orders WHERE user_id=? ORDER BY created DESC LIMIT 50',id.id)};
if(path==='plan'&&method==='GET'){const ids=curriculum?await professionalAccess(env,id,curriculum,atlas):[];return {plan:await one('SELECT * FROM learning_plans WHERE user_id=?',id.id),programmes:(curriculum?.programmes||[]).filter(p=>ids.includes(p.id)).map(p=>({id:p.id,title:p.title,category:p.category})),teacherScope:staff?.role==='Mentor'?JSON.parse(staff.domains):[]}}
if(path==='plan'&&method==='PUT'){
 if(!['Guided','Professional'].includes(b.mode)||!Number.isInteger(b.hours)||b.hours<1||b.hours>40||!Array.isArray(b.days)||!b.days.length||b.days.length>7||b.days.some(n=>!Number.isInteger(n)||n<0||n>6)||new Set(b.days).size!==b.days.length||!Number.isInteger(b.expectedRevision)||b.expectedRevision<0||typeof b.timezone!=='string'||b.timezone.length>80||!b.timezone)fail('Choose your path, 1–40 weekly hours, practice days and the current plan version.');try{new Intl.DateTimeFormat('en',{timeZone:b.timezone}).format()}catch{fail('Choose a valid timezone.')}
 let course=null,programme=null;if(b.mode==='Guided'){course=tracks[b.courseId];if(!course)fail('Choose a guided course.');if(!owner&&!course.free&&!await one("SELECT id FROM entitlements WHERE user_id=? AND course_id=? AND status='Active' AND (expires IS NULL OR expires>?)",id.id,course.id,time))fail('Choose a free course or a course you have access to.',403)}else{const allowed=curriculum?await professionalAccess(env,id,curriculum,atlas):[];programme=curriculum?.programmes.find(p=>p.id===b.programmeId);if(!programme||!allowed.includes(programme.id))fail('Choose a professional programme you have access to.',403)}
 const old=await one('SELECT revision FROM learning_plans WHERE user_id=?',id.id);if((old?.revision||0)!==b.expectedRevision)fail('Your plan changed on another device. Reload before saving.',409);const out=await s('INSERT INTO learning_plans(user_id,mode,course_id,programme_id,hours,days,timezone,revision,updated) VALUES(?,?,?,?,?,?,?,1,?) ON CONFLICT(user_id) DO UPDATE SET mode=excluded.mode,course_id=excluded.course_id,programme_id=excluded.programme_id,hours=excluded.hours,days=excluded.days,timezone=excluded.timezone,revision=learning_plans.revision+1,updated=excluded.updated WHERE learning_plans.revision=?',id.id,b.mode,course?.id||null,programme?.id||null,b.hours,JSON.stringify(b.days),b.timezone,time,b.expectedRevision).run();if(!out.meta.changes)fail('Your plan changed. Reload it.',409);await recordActivity(db,id.id,'learning_plan_saved',id.id,{mode:b.mode}).run();return {saved:true,revision:b.expectedRevision+1};
}
if(!path.startsWith('operations'))return null;mustOwn();
if(path==='operations/initialize'&&method==='POST'){const rows=[['admin','Administrator'],['demo','Demo'],...Array.from({length:6},(_,i)=>['teacher-'+(i+1),'Mentor'])];await db.batch(rows.map(([slot,kind])=>s('INSERT OR IGNORE INTO launch_accounts(id,kind,name,email,user_id,domains,status,approved_by,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?)',slot,kind,slot==='admin'?'Academy administrator':'',slot==='admin'?id.email.toLowerCase():null,slot==='admin'?id.id:null,'[]',slot==='admin'?'Active':'Needs details',slot==='admin'?id.id:null,time,time)));return {initialized:true}}
if(path==='operations'&&method==='GET'){
 const count=async(q,...args)=>(await one(q,...args)).n;return {accounts:await all('SELECT id,kind,name,email,user_id,domains,status,qualification,expires,updated FROM launch_accounts ORDER BY id'),merchant:await merchantStatus(env),activity:await all('SELECT action,record,created FROM audit ORDER BY created DESC LIMIT 60'),counts:{registered:await count("SELECT count(*) n FROM profiles WHERE status='Active'"),paid:await count("SELECT count(*) n FROM orders WHERE status='Paid'"),teachers:await count("SELECT count(*) n FROM staff WHERE role='Mentor' AND expires>=?",time.slice(0,10)),waitingPackages:await count("SELECT count(*) n FROM teaching_enrolments WHERE status='Awaiting teacher'")},sharing:env.ACADEMY_PAYMENT_PUBLIC==='true'?'Registration is open. Each team member signs in with their own verified email and completes a profile to claim the appointment. No invitation email is sent by this form.':'Live purchases are paused. Your team can use public registration to claim their verified email appointments; this form does not send an email invitation.'};
}
if(path==='operations/account'&&method==='PUT'){
 const row=await one('SELECT * FROM launch_accounts WHERE id=?',b.slotId);if(!row||row.kind==='Administrator')fail('Choose the demo or one of the six teacher slots.');if(row.user_id)fail('Revoke the existing appointment before changing this account.',409);const email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email===id.email.toLowerCase()||name.length<2||name.length>120||!/^\d{4}-\d{2}-\d{2}$/.test(b.expires||'')||!Number.isFinite(Date.parse(b.expires))||b.expires<time.slice(0,10)||b.expires>new Date(Date.now()+366*86400000).toISOString().slice(0,10))fail('Enter a different verified-account email, name and access expiry within one year.');if(await one('SELECT id FROM launch_accounts WHERE email=? AND id<>?',email,row.id))fail('This email is already appointed to another slot.',409);const domains=row.kind==='Demo'?Object.keys(tracks):b.domains;if(!Array.isArray(domains)||!domains.length||domains.some(x=>!tracks[x])||new Set(domains).size!==domains.length)fail('Choose the courses this teacher can teach.');const qualification=row.kind==='Mentor'?String(b.qualification||'').trim():'Owner-approved full learning demonstration';if(row.kind==='Mentor'&&(qualification.length<100||qualification.length>10000||b.qualificationChecked!==true))fail('Record at least 100 characters of actual teacher qualifications and confirm you checked the evidence.');await db.batch([s("UPDATE launch_accounts SET name=?,email=?,domains=?,qualification=?,expires=?,status='Awaiting registration',approved_by=?,updated=? WHERE id=? AND user_id IS NULL",name,email,JSON.stringify(domains),qualification,b.expires,id.id,time,row.id),recordActivity(db,id.id,'account_appointment_saved',row.id)]);return {saved:true,message:'Access is reserved for this email. It activates when that person signs in and completes registration.'};
}
if(path==='operations/account/revoke'&&method==='POST'){
 const row=await one('SELECT * FROM launch_accounts WHERE id=?',b.slotId);if(!row||row.kind==='Administrator')fail('Choose a demo or teacher appointment.');if(String(b.reason||'').trim().length<20)fail('Record the reason for withdrawing this appointment.');await db.batch([s("UPDATE entitlements SET status='Revoked' WHERE source_id=?",'launch:'+row.id),...(row.kind==='Mentor'&&row.user_id?[s("DELETE FROM staff WHERE user_id=? AND role='Mentor' AND approved_by=?",row.user_id,row.approved_by)]:[]),s("UPDATE launch_accounts SET status='Revoked',user_id=NULL,updated=? WHERE id=?",time,row.id),recordActivity(db,id.id,'account_appointment_revoked',row.id)]);return {revoked:true};
}
if(path==='operations/merchant'&&method==='PUT'){const result=await connectRazorpay(env,b);await recordActivity(db,id.id,'merchant_connection_verified','razorpay').run();return result}
if(path==='operations/business'&&method==='PUT'){const result=await saveBusiness(env,b);await recordActivity(db,id.id,'business_details_saved','business').run();return result}
if(path==='operations/products'&&method==='PUT'){const result=await saveProducts(env,b,tracks);await recordActivity(db,id.id,'course_offers_saved','products',{count:result.count}).run();return result}
fail('Launch action not found.',404);
}
