const fail=(msg,status=400)=>{throw Object.assign(Error(msg),{status})};
const now=()=>new Date().toISOString();
export function teachingPlan(product,courseIds){const p=product.teachingPlan;if(!p)return {};if((product.durationDays||365)<56)fail('Course access must include the full eight-week teaching period.',409);if(p.weeks!==8||p.classes!==24||p.minutes!==120||p.perWeek!==3||!courseIds.includes(p.courseId))fail('The supported bundle must include its course and 24 two-hour classes across eight weeks.',409);return {courseId:p.courseId,weeks:8,classes:24,minutes:120,perWeek:3}}
export function teachingFulfilment(db,order,scope,stamp){let p;try{p=JSON.parse(scope.teaching_plan||'{}')}catch{return []}if(!p.courseId)return [];return [db.prepare("INSERT OR IGNORE INTO teaching_enrolments(id,order_id,user_id,course_id,status,created) SELECT ?,?,?,?,'Awaiting teacher',? WHERE EXISTS(SELECT 1 FROM orders WHERE id=? AND status='Paid')").bind('teaching-'+order.id,order.id,order.user_id,p.courseId,stamp,order.id)]}
export function teachingRevocation(db,orderId,stamp){const s=(q,...a)=>db.prepare(q).bind(...a);return [s("UPDATE teaching_enrolments SET status='Suspended' WHERE order_id=?",orderId),s("UPDATE class_bookings SET status='Cancelled',notes='Course purchase refunded or disputed. Contact the Academy about next steps.',updated=? WHERE package_id IN (SELECT id FROM teaching_enrolments WHERE order_id=?) AND status='Booked' AND slot_id IN (SELECT id FROM class_slots WHERE starts_at>?)",stamp,orderId,stamp),s("UPDATE class_slots SET status='Available' WHERE status='Booked' AND starts_at>? AND id IN (SELECT b.slot_id FROM class_bookings b JOIN teaching_enrolments p ON p.id=b.package_id WHERE p.order_id=?) AND NOT EXISTS(SELECT 1 FROM class_bookings active WHERE active.slot_id=class_slots.id AND active.status='Booked')",stamp,orderId)]}
export function safeMeeting(value){if(!value)return '';let u;try{u=new URL(value)}catch{fail('Enter a supported HTTPS class meeting link.')}if(u.protocol!=='https:'||u.username||u.password||!['meet.google.com','zoom.us','teams.microsoft.com','teams.live.com'].some(h=>u.hostname===h||u.hostname.endsWith('.'+h)))fail('Use an HTTPS Google Meet, Zoom or Teams meeting link.');return u.href}
export async function handleTeaching(path,method,payload,{db,id,owner,staff,tracks}){
const s=(q,...a)=>db.prepare(q).bind(...a),one=(q,...a)=>s(q,...a).first(),all=async(q,...a)=>(await s(q,...a).all()).results||[],stamp=now();
const qualifies=async(person,course)=>{const p=await one("SELECT * FROM staff WHERE user_id=? AND role='Mentor' AND expires>=?",person,stamp.slice(0,10));return p&&JSON.parse(p.domains).includes(course)};
const ownPackage=async pid=>{const p=await one('SELECT * FROM teaching_enrolments WHERE id=?',pid);if(!p||p.user_id!==id.id)fail('This teacher package is not available to you.',404);return p};
if(path==='teaching'&&method==='GET'){
 const packages=await all("SELECT p.*,st.name AS teacher_name,(SELECT count(*) FROM class_bookings b WHERE b.package_id=p.id AND b.status='Completed') AS completed_count FROM teaching_enrolments p LEFT JOIN staff st ON st.user_id=p.teacher_id WHERE p.user_id=? ORDER BY p.created DESC",id.id);
 const slots=await all("SELECT c.id,c.starts_at,c.minutes,st.name AS teacher_name,p.id AS package_id FROM class_slots c JOIN teaching_enrolments p ON p.teacher_id=c.teacher_id AND p.course_id=c.course_id JOIN staff st ON st.user_id=c.teacher_id WHERE p.user_id=? AND p.status='Active' AND st.role='Mentor' AND st.expires>=? AND c.status='Available' AND c.starts_at>=? AND c.starts_at>=p.starts_at AND c.starts_at<p.ends_at ORDER BY c.starts_at LIMIT 100",id.id,stamp.slice(0,10),stamp);
 const bookings=await all("SELECT b.id,b.status,b.notes,c.starts_at,c.minutes,CASE WHEN p.status='Active' AND st.role='Mentor' AND st.expires>=? THEN c.meeting_url ELSE '' END AS meeting_url,st.name AS teacher_name FROM class_bookings b JOIN class_slots c ON c.id=b.slot_id JOIN teaching_enrolments p ON p.id=b.package_id LEFT JOIN staff st ON st.user_id=c.teacher_id WHERE b.user_id=? ORDER BY c.starts_at DESC LIMIT 100",stamp.slice(0,10),id.id);return {packages,slots,bookings};
}
if(path==='teaching/preferences'&&method==='POST'){const p=await ownPackage(payload.packageId);if(!['Active','Awaiting teacher'].includes(p.status))fail('This package is inactive.',403);if(typeof payload.preferences!=='string'||payload.preferences.trim().length<10||payload.preferences.length>2000)fail('Describe preferred days, times and timezone in 10–2000 characters.');await s('UPDATE teaching_enrolments SET preferences=? WHERE id=?',payload.preferences.trim(),p.id).run();return {saved:true}}
if(path==='teaching/book'&&method==='POST'){
 const p=await ownPackage(payload.packageId),slot=await one('SELECT * FROM class_slots WHERE id=?',payload.slotId);if(p.status!=='Active'||!slot||slot.teacher_id!==p.teacher_id||slot.course_id!==p.course_id||!await qualifies(p.teacher_id,p.course_id))fail('This class is not available for your active package.',403);
 const start=Date.parse(p.starts_at),date=Date.parse(slot.starts_at);if(!Number.isFinite(start)||date<Date.now()||date<start||date>=Date.parse(p.ends_at))fail('Choose a future class inside your eight-week teaching period.');const week=Math.floor((date-start)/(7*86400000)),weekStart=new Date(start+week*7*86400000).toISOString(),weekEnd=new Date(start+(week+1)*7*86400000).toISOString(),bookingId=crypto.randomUUID();
 // The conditional INSERT and slot update share one D1 transaction. Overlapping classes, class quotas and weekly quotas are checked in that transaction.
 const out=await db.batch([s("INSERT INTO class_bookings(id,slot_id,package_id,user_id,status,created,updated) SELECT ?,c.id,p.id,p.user_id,'Booked',?,? FROM class_slots c JOIN teaching_enrolments p ON p.id=? WHERE c.id=? AND c.status='Available' AND p.status='Active' AND c.teacher_id=p.teacher_id AND c.course_id=p.course_id AND (SELECT count(*) FROM class_bookings WHERE package_id=p.id AND status IN ('Booked','Completed'))<24 AND (SELECT count(*) FROM class_bookings b JOIN class_slots sc ON sc.id=b.slot_id WHERE b.package_id=p.id AND b.status IN ('Booked','Completed') AND sc.starts_at>=? AND sc.starts_at<?)<3 AND NOT EXISTS(SELECT 1 FROM class_bookings b JOIN class_slots sc ON sc.id=b.slot_id WHERE b.user_id=p.user_id AND b.status='Booked' AND datetime(sc.starts_at)<datetime(c.starts_at,'+120 minutes') AND datetime(sc.starts_at,'+120 minutes')>datetime(c.starts_at))",bookingId,stamp,stamp,p.id,slot.id,weekStart,weekEnd),s("UPDATE class_slots SET status='Booked' WHERE id=? AND status='Available' AND EXISTS(SELECT 1 FROM class_bookings WHERE id=?)",slot.id,bookingId)]);if(!out[0].meta.changes)fail('This time was taken, overlaps another class, or your weekly/package class allowance is full.',409);return {booked:true,id:bookingId};
}
if(path==='teaching/cancel'&&method==='POST'){const b=await one('SELECT b.*,c.starts_at FROM class_bookings b JOIN class_slots c ON c.id=b.slot_id WHERE b.id=? AND b.user_id=?',payload.bookingId,id.id);if(!b||b.status!=='Booked')fail('This booking is not available to cancel.',404);if(Date.parse(b.starts_at)<=Date.now())fail('Contact your teacher about a class that has already started.',409);await db.batch([s("UPDATE class_bookings SET status='Cancelled',updated=? WHERE id=? AND status='Booked'",stamp,b.id),s("UPDATE class_slots SET status='Available' WHERE id=? AND NOT EXISTS(SELECT 1 FROM class_bookings WHERE slot_id=? AND status='Booked')",b.slot_id,b.slot_id)]);return {cancelled:true}}
if(path==='teaching/staff'&&method==='GET'){
 if(!owner&&staff?.role!=='Mentor')fail('Teaching staff access is required.',403);return {courseScope:owner?Object.keys(tracks):JSON.parse(staff.domains),packages:await all(owner?'SELECT p.*,pr.name AS learner_name,st.name AS teacher_name FROM teaching_enrolments p JOIN profiles pr ON pr.user_id=p.user_id LEFT JOIN staff st ON st.user_id=p.teacher_id ORDER BY p.created DESC LIMIT 100':'SELECT p.*,pr.name AS learner_name FROM teaching_enrolments p JOIN profiles pr ON pr.user_id=p.user_id WHERE p.teacher_id=? ORDER BY p.created DESC LIMIT 100',...(owner?[]:[id.id])),teachers:owner?await all("SELECT user_id,name,domains,expires FROM staff WHERE role='Mentor' AND expires>=?",stamp.slice(0,10)):[],slots:await all(owner?'SELECT * FROM class_slots ORDER BY starts_at DESC LIMIT 100':'SELECT * FROM class_slots WHERE teacher_id=? ORDER BY starts_at DESC LIMIT 100',...(owner?[]:[id.id])),bookings:await all(owner?'SELECT b.*,c.starts_at,c.teacher_id FROM class_bookings b JOIN class_slots c ON c.id=b.slot_id ORDER BY c.starts_at DESC LIMIT 100':'SELECT b.*,c.starts_at,c.teacher_id FROM class_bookings b JOIN class_slots c ON c.id=b.slot_id WHERE c.teacher_id=? ORDER BY c.starts_at DESC LIMIT 100',...(owner?[]:[id.id]))};
}
if(path==='teaching/assign'&&method==='POST'){if(!owner)fail('Only the owner can assign a teacher.',403);const p=await one('SELECT * FROM teaching_enrolments WHERE id=?',payload.packageId);if(!p||p.status!=='Awaiting teacher'||p.user_id===payload.teacherId||!await qualifies(payload.teacherId,p.course_id))fail('Assign a different, currently qualified course mentor to a paid waiting package.');const start=new Date(payload.startsAt);if(!Number.isFinite(+start)||+start<Date.now()-86400000)fail('Choose the agreed teaching start date.');const end=new Date(+start+56*86400000).toISOString();const access=await one("SELECT id FROM entitlements WHERE user_id=? AND course_id=? AND source_id=? AND status='Active' AND (expires IS NULL OR expires>=?)",p.user_id,p.course_id,p.order_id,end);if(!access)fail('The agreed teaching period must fit inside this order’s active course access.',409);const out=await s("UPDATE teaching_enrolments SET teacher_id=?,starts_at=?,ends_at=?,status='Active' WHERE id=? AND status='Awaiting teacher'",payload.teacherId,start.toISOString(),end,p.id).run();if(!out.meta.changes)fail('This package was already assigned.',409);return {assigned:true}}
if(path==='teaching/slot'&&method==='POST'){const teacher=owner?payload.teacherId:id.id;if(!tracks[payload.courseId]||!await qualifies(teacher,payload.courseId))fail('A currently qualified mentor for this course is required.',403);const date=new Date(payload.startsAt);if(!Number.isFinite(+date)||+date<Date.now()||+date>Date.now()+366*86400000)fail('Choose a future class time within the next year.');const start=date.toISOString(),meeting=safeMeeting(payload.meetingUrl);const row=await s("INSERT INTO class_slots(id,teacher_id,course_id,starts_at,minutes,status,meeting_url,created) SELECT ?,?,?,?,120,'Available',?,? WHERE NOT EXISTS(SELECT 1 FROM class_slots WHERE teacher_id=? AND status<>'Cancelled' AND datetime(starts_at)<datetime(?,'+120 minutes') AND datetime(starts_at,'+120 minutes')>datetime(?))",crypto.randomUUID(),teacher,payload.courseId,start,meeting,stamp,teacher,start,start).run();if(!row.meta.changes)fail('This teacher already has an overlapping class time.',409);return {created:true}}
if(path==='teaching/meeting'&&method==='POST'){const slot=await one('SELECT * FROM class_slots WHERE id=?',payload.slotId);if(!slot||(!owner&&slot.teacher_id!==id.id)||!await qualifies(slot.teacher_id,slot.course_id))fail('Assigned teaching access is required.',403);await s('UPDATE class_slots SET meeting_url=? WHERE id=?',safeMeeting(payload.meetingUrl),slot.id).run();return {saved:true}}
if(path==='teaching/slot/cancel'&&method==='POST'){const slot=await one('SELECT * FROM class_slots WHERE id=?',payload.slotId);if(!slot||(!owner&&slot.teacher_id!==id.id)||Date.parse(slot.starts_at)<=Date.now())fail('Only the assigned teacher or owner can cancel a future class.',403);if(typeof payload.reason!=='string'||payload.reason.trim().length<30||payload.reason.length>2000)fail('Explain the cancellation and next action in 30–2000 characters.');await db.batch([s("UPDATE class_slots SET status='Cancelled' WHERE id=?",slot.id),s("UPDATE class_bookings SET status='Cancelled',notes=?,updated=? WHERE slot_id=? AND status='Booked'",payload.reason.trim(),stamp,slot.id)]);return {cancelled:true}}
if(path==='teaching/complete'&&method==='POST'){const b=await one('SELECT b.*,c.starts_at,c.teacher_id FROM class_bookings b JOIN class_slots c ON c.id=b.slot_id WHERE b.id=?',payload.bookingId),p=b&&await one('SELECT * FROM teaching_enrolments WHERE id=?',b.package_id);if(!b||(!owner&&b.teacher_id!==id.id)||!p||p.status!=='Active'||!await qualifies(b.teacher_id,p.course_id))fail('Only the assigned qualified teacher or owner may record attendance.',403);if(b.status!=='Booked'||Date.parse(b.starts_at)+120*60000>Date.now())fail('Record completion only after the booked class has ended.',409);if(typeof payload.notes!=='string'||payload.notes.trim().length<30||payload.notes.length>5000)fail('Record actual attendance and learning notes in 30–5000 characters.');await db.batch([s("UPDATE class_bookings SET status='Completed',notes=?,updated=? WHERE id=? AND status='Booked'",payload.notes.trim(),stamp,b.id),s("UPDATE class_slots SET status='Completed' WHERE id=?",b.slot_id)]);return {recorded:true}}
fail('Teaching action not found.',404);
}
